### ISSUE TITLE
"LspCodeAction" is broken in diagnostics refactor

### ISSUE THREAD

**Issue by yaegassy** [prabirshrestha/vim-lsp#1000]
## Description

I'm having problems since this [commit](https://github.com/prabirshrestha/vim-lsp/commit/2eb8d16413b2da25d1e10cf5c57b183d6394c134)

## Error message

```
Error detected while processing function lsp#ui#vim#code_action[1]..lsp#ui#vim#code_action#do:
line   23:
E118: Too many arguments for function: lsp#internal#diagnostics#under_cursor#get_diagnostic
```

## Capture

![issue-vim-lsp-code-action-error](https://user-images.githubusercontent.com/188642/103460204-c48cfe00-4d57-11eb-8f55-983f71e89d77.gif)

**Comment by mattn** [comment]
Sorry, I pushed a commit to fix this but I noticed current implementation seems to be WIP. Please ignore my change.

**Comment by prabirshrestha** [comment]
Sorry my bad.

Meregd mattn's PR.
