### ISSUE TITLE
Initilization Status

### ISSUE THREAD

**Issue by adelarsq** [prabirshrestha/vim-lsp#101]
Is there any way to get server initialization status?
I want to show on status line the server status.

**Comment by prabirshrestha** [comment]
Do you mean something like this?

```vim
au User lsp_server_init call s:server_initialized()
au User lsp_server_exit call s:server_exited()
```

Refer to https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/175adcdc05090066e9fd00bbd5c4591b7d7c3bb5/plugin/asyncomplete-lsp.vim for an example.

**Comment by adelarsq** [comment]
Something like the ``LSCServerStatus()`` from https://github.com/natebosch/vim-lsc/blob/master/doc/lsc.txt#L124-L134.

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/134
