### ISSUE TITLE
lsp_float_opened is not hooked when a popup is opened for document preview

### ISSUE THREAD

**Issue by rhysd** [prabirshrestha/vim-lsp#1016]
### Repro

Add following config to your vimrc:

```vim
Autocmd User lsp_float_opened call popup_setoptions(lsp#ui#vim#output#getpreviewwinid(), {'borderchars': ['─', '│', '─', '│', '┌', '┐', '┘', '└']})
```

Then open a file which runs language server and trigger omni completion by `<C-x><C-o>`

### Expected behavior

Border characters are changed as set at `borderchars` option.

### Actual behavior

Border characters are not changed as follows:

<img width="716" alt="スクリーンショット 2021-01-04 13 43 02" src="https://user-images.githubusercontent.com/823277/103501844-cc04f200-4e92-11eb-9265-b4dd40c93321.png">

This is because `lsp_float_opened` event is not hooked when opening document preview popup. Note that the event is hooked when opening hover window.

### Environment

- Vim: 8.2.2164
- Neovim: 0.4.4
- vim-lsp: 7d15d0f5813f4af2f7efff3d6cf68092566da35b

**Comment by subnut** [comment]
Right... I am fixing this.

**Comment by subnut** [comment]
> `call popup_setoptions()`

```
E117: Unknown function: popup_setoptions
```

Neovim v0.4.4
