### ISSUE TITLE
Markdown documentation is not wrapped

### ISSUE THREAD

**Issue by pxl-th** [prabirshrestha/vim-lsp#1024]
Hi, I wonder if it is possible to wrap documentation for the methods to fit the popup window if it is in the markdown style?
Right now I have max width set to `79`, but it seems to have no effect, or am I missing something?

```vim
let g:lsp_preview_max_width = 79
```

Here's what it looks like:

![image](https://user-images.githubusercontent.com/17990405/103757886-1664ab00-501a-11eb-8e26-fcae02e7a2b7.png)

**Comment by subnut** [comment]
You have `set nowrap` in your `init.vim` ?

**Comment by pxl-th** [comment]
> 
> 
> You have `set nowrap` in your `init.vim` ?

Yeah, totally forgot about it. But after #1028 wrapping works now, thanks!
