### ISSUE TITLE
"E731: using Dictionary as a String" error in Neovim when getting diagnostics counts

### ISSUE THREAD

**Issue by brentyi** [prabirshrestha/vim-lsp#1026]
Hi,

I seem to get the error `E731: using Dictionary as a String` when I try to check the diagnostics counts, eg:
```
:echom lsp#get_buffer_diagnostics_counts()  
```

Notes:
- Happens in Neovim 0.4.3 but not Vim 8.2.
- Everything else seems to be working fine (looking at the diagnostics themselves, etc).

Thanks!!

**Comment by subnut** [comment]
```vim
:echom string(lsp#get_buffer_diagnostics_counts())
```

**Comment by mattn** [comment]
AFAIK, neovim does not support echom with non-scalar values. You should call `string()` or:
```
:echom lsp#get_buffer_diagnostics_counts().information
```

**Comment by subnut** [comment]
```vim
:echom {'a':0,'b':1,'c':2}
```
```
E731: using Dictionary as a String
```

<br>

```vim
echom string({'a':0,'b':1,'c':2})
```
```
{'a': 0, 'b': 1, 'c': 2}
```

**Comment by brentyi** [comment]
Oops, thanks for catching that @mattn @subnut !

Seems like my confusion here was because my script was calling `lsp#get_buffer_diagnostics_counts()->values()`, which works in Vim8 but throws the exact same E731 error as calling echom on a dictionary in Neovim. `values(lsp#get_buffer_diagnostics_counts())` works, however.

Appreciate the super quick help.

**Comment by Shougo** [comment]
Hi.

> Happens in Neovim 0.4.3 but not Vim 8.2.

Your neovim version is old.
neovim 0.5.0(HEAD) works for me.

**Comment by subnut** [comment]
@Shougo It doesn't work in `v0.4.4` either. We can't consider `v0.4.4` old, because it is the latest release. `v0.5.0` hasn't been released yet, right?

**Comment by Shougo** [comment]
Unfortunately, in neovim non HEAD version is old.

`v0.5.0` version is not released yet.
The `v0.5.0` changes are very huge(mainly LSP and Lua).

**Comment by Shougo** [comment]
In Vim8, version 8.2.0 is old today.  It is same with `neovim 0.4.5` in neovim.
