### ISSUE TITLE
Got error when try LspDocumentSymbolSearch

### ISSUE THREAD

**Issue by yuzu3886** [prabirshrestha/vim-lsp#1034]
When try `LspDocumentSymbolSearch` and input character, I got the error

```
Error detected while processing function <SNR>82_notify_onchange[4]..<SNR>82_update_items:
line   23:
E687: Less targets than List items
```

Seems like related to https://github.com/vim/vim/commit/9d19e4f4ba55f8bef18d4991abdf740ff6472dba

my vim version: 8.2.2320

**Comment by prabirshrestha** [comment]
I will try it out. in the mean time you can try disabling the fuzzy match but needs code changes. Can you set it to `0` in quickpick.vim and see if it works?

```vim
let s:has_matchfuzzy = 0
let s:has_matchfuzzypos = 0
```

**Comment by prabirshrestha** [comment]
I was able to repro. Seems like need update in quickfix. I can't use the destructing syntax now.

```
          let [l:fitems, l:highlights] = matchfuzzypos(s:state['items'], s:state['input'])
```

**Comment by prabirshrestha** [comment]
@yuzu3886 can you try this branch. https://github.com/prabirshrestha/vim-lsp/pull/1036

**Comment by prabirshrestha** [comment]
merged in master. Please try again.

**Comment by yuzu3886** [comment]
thanks for the quick fixes.
