### ISSUE TITLE
Vim intro message is erased automatically just after launching

### ISSUE THREAD

**Issue by ichizok** [prabirshrestha/vim-lsp#1043]
Since https://github.com/prabirshrestha/vim-lsp/commit/efd07d859e2d9812adad04684e2f0ab7a30f07ae, Vim intro message is erased automatically just after launching.

### Repro steps

test.vim
```vim
set rtp=/path/to/vim-lsp
```

`vim -Nu test.vim`

Expected: intro message is kept displaying until user gives some operations. 
Actual: intro message is erased after about 1 second.

**Comment by prabirshrestha** [comment]
fixed by https://github.com/prabirshrestha/vim-lsp/pull/1084

**Comment by prabirshrestha** [comment]
reopening due to https://github.com/prabirshrestha/vim-lsp/pull/1145.

will fix this in few days. need to add extra flag to avoid https://github.com/prabirshrestha/vim-lsp/issues/1142
