### ISSUE TITLE
`LspHover` is blank when `lsp_preview_float=0`

### ISSUE THREAD

**Issue by yatesco** [prabirshrestha/vim-lsp#1047]
Hi - thanks for this, it's great!

When I `let g:lsp_preview_float = 0` then `LspHover` appears in a split (yay) rather than a popup but it is empty (boo):

![image](https://user-images.githubusercontent.com/181469/104616996-d8ebc780-5682-11eb-98f5-ebcf7e7cc5fb.png)

With `let g:lsp_preview_float = 1`:

![image](https://user-images.githubusercontent.com/181469/104616658-772b5d80-5682-11eb-8e75-3bc557450cc0.png)

I've tried this in both NeoVim#HEAD and the latest release of vim.

I'm probably doing something wrong ;-) but I can't see it.

**Comment by prabirshrestha** [comment]
I can repro this. We are looking into refactor `:LspHover` https://github.com/prabirshrestha/vim-lsp/pull/1063 but it is going to take a bit more time. for now will have to use floating window.

**Comment by prabirshrestha** [comment]
Should be fixed in master. Please try again.
