### ISSUE TITLE
Completion menu is covered by other lower priority popup

### ISSUE THREAD

**Issue by obcat** [prabirshrestha/vim-lsp#1049]
**Describe the bug**

The `zindex` of insert mode completion menu is `100`, but it is covered by other popup with lower `zindex` value, such as `10`.

**To Reproduce**

1. Run `vim -N -u minimal_vimrc`.
    ```vim
    " minimal_vimrc
    call plug#begin()
    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/vim-lsp'
    call plug#end()
    ```

1. Create a popup with `zindex` of `10`.
    ```vim
    :call popup_create(['xxx', 'xxx'], {'zindex': 10})
    ```

1. Show completion menu around the popup.

1. Completion menu is covered by the popup.

**Screenshots**

<img width="500" alt="ss 2021-01-16 3 44 14" src="https://user-images.githubusercontent.com/64692680/104770842-932f1c00-57b4-11eb-8627-4c18df09eb32.png">

(Highlighted popup for clarity)

**Expected behavior**

Completion menu is not covered by lower priority popup.

**Environment**
 - Vim 8.2.2300
 - macOS Catalina (version 10.15.7)
 - iTerm2

**Additional context**

The fact that the `zindex` of completion menu is `100` is mentioned before `:h popup-props`.

```
Depending on the "zindex" the popup goes under or above other popups.  The
completion menu (|popup-menu|) has zindex 100.
```

**Comment by prabirshrestha** [comment]
completion menu is using default vim completion menu. so nothing we can do here. if you are manually creating a popup you can get the position and width/height of the complete menu and position it correctly.

not a bug in vim-lsp

**Comment by obcat** [comment]
I supposed this was a bug in either vim-lsp or asyncomplete.vim, since I couldn't reproduce it without them.
I wonder if this is caused by unknown bug in Vim.

Anyway, I understood that this cannot be fixed. Thank you.
