### ISSUE TITLE
:LspHover shouldn't move focus to the preview window

### ISSUE THREAD

**Issue by reidab** [prabirshrestha/vim-lsp#105]
Currently, triggering `:LspHover` switches focus to the newly-opened preview window, which doesn't seem ideal.

**Comment by prabirshrestha** [comment]
@reidab Curious at how you use this feature. I'm guessing you are reading the docs and need to type the code.
For me I usually use hover and then just close it so I prefer to focus on it. But I would be more than happy to learn how you use it so we can have configs to enable your suggestion.

**Comment by natebosch** [comment]
If the window is a 'preview' window it can be closed without focusing it with `<c-w><c-z>`

**Comment by reidab** [comment]
I'm using this primarily with [flowtype/flow-language-server](https://github.com/flowtype/flow-language-server), so `:LspHover` ends up displaying the type definition for the symbol under the cursor. Debugging type issues often involves inspecting types of several variables in a file and switching back and forth between then. When I'm doing this, I like to leave the preview window open to avoid it resizing my active window and moving where the cursor is sitting on the screen.

In general, I don't expect preview windows to be editable or to take focus. I either use `<c-w><c-z>` or a shorter keybinding for `:pclose` to close them.

**Comment by prabirshrestha** [comment]
@reidab This is fixed by https://github.com/prabirshrestha/vim-lsp/pull/109.
