### ISSUE TITLE
Cant jump to c++ standard library header

### ISSUE THREAD

**Issue by pdavydov108** [prabirshrestha/vim-lsp#106]
Hello @prabirshrestha , I've run into a small issue using this plugin with cquery server. My environment is linux, c++ project with cmake build system. It works well, except one case when I try to jump to some class or function that is defined in standard library, for example a std::string. libstdc++ headers are usually located somewhere in `/usr/include/c++/<compiler version>/`. Server replies to my request like this: 

```
2018 14:50:52:["<---",1,"cquery",{"response":{"id":16,"jsonrpc":"2.0",
"result":[{"uri":"file:///usr/include/c%2B%2B/7.2.0/bits/stringfwd.h",
"range":{"end":{"character":38,"line":73},"start":{"character":32,"line":73}}}]},
"request":{"method":"textDocument/definition","jsonrpc":"2.0","id":16,
"params":{"textDocument":{"uri":"file:///home/pablo/myproject/myfile.cpp"},
"position":{"character":26,"line":21}}}}]
```

As you can see, path to the header with string contains **c%2B%2B**, which is the root of this issue, as far as I can see. When vim opens a file, I see that '%' signs are substituted with a path to the original file, maybe it is treated like a mask somewhere in the plugin code. I've also seen cases when the path from cquery is just used as it is, with **c%2B%2B**. Anyway, vim is not able to find a file this way. I'm not sure if it is a bug in the plugin or in cquery, though. What do you think?

p.s. Thanks for your work on this plugin, it's so cool that now vim has a proper lsp support!

**Comment by prabirshrestha** [comment]
Seems like vim-lsp isn't encoding paths correctly. Should be an easy fix. Feel free to send a PR.
Need to modify `lsp#utils#path_to_uri` and `lsp#utils#uri_to_path` function. https://github.com/prabirshrestha/vim-lsp/blob/203d682e30ca30d995fdceaf53df8a7808409baa/autoload/lsp/utils.vim#L5-L31

**Comment by pdavydov108** [comment]
Okay, I've opened a pull request, please check it.

**Comment by prabirshrestha** [comment]
Thanks for the PR. Should be able to check by end of next week.

**Comment by Abbyyan** [comment]
> Thanks for the PR. Should be able to check by end of next week.

I want to ask whether the problem has been solved now ? Thanks for your reply.
