### ISSUE TITLE
Benchmark comparison of lsp for vim.

### ISSUE THREAD

**Issue by timsofteng** [prabirshrestha/vim-lsp#1062]
Hello.
Could you please make a comparison between lsp client for vim and neovim? It would be great to see some Benchmark of speed and cpu-usage.

I propose this clients:
1) vim-lsp :)
2) coc
3) vim-lsc
4) neovim built in lsp

I don't know how to do measurements but I suppose you know.
I hope many people would know which one is fastest and lightest.

Thanks

**Comment by prabirshrestha** [comment]
no plans to profile others.
