### ISSUE TITLE
$/cancelRequest should be a notification

### ISSUE THREAD

**Issue by zhu** [prabirshrestha/vim-lsp#1066]
https://github.com/prabirshrestha/vim-lsp/blob/21a29936ed74b2212e1904cca6c22bff4e27b637/autoload/lsp.vim#L1037-L1047

https://microsoft.github.io/language-server-protocol/specification#cancelRequest

**Comment by prabirshrestha** [comment]
@zhu what is the issue? could you elaborate?

**Comment by zhu** [comment]
vim-lsp send the `$/cancelRequest` as a request instead of a notification, and the server cannot handle it.

**Comment by prabirshrestha** [comment]
Fixed in master. Thanks for the bug report.
