### ISSUE TITLE
different diagnostics style between vim and neovim

### ISSUE THREAD

**Issue by dc25** [prabirshrestha/vim-lsp#1072]
This may or may not be a bug.   I get slightly different behavior between neovim and vim.   In vim, error diagnostics show at the bottom of the screen and in neovim they also show up on the same line.   It seems like it should be work one way or the other.      My working environment is ubuntu linux.  I'm working with rust currently but I've seen this problem with haskell as well.    My neovim is compiled from the latest source.   Vim is installed using apt (but I've tried building from source and it does not seem to make any difference).   Attaching screen shots, version information, vimrc config.  
![vim](https://user-images.githubusercontent.com/1620/108871889-76a1b300-75ae-11eb-9e86-ce42bfa2c1dd.jpg)
![nvim](https://user-images.githubusercontent.com/1620/108871911-7e615780-75ae-11eb-9ba8-82faa1be7e7f.jpg)
[rustVimrc.txt](https://github.com/prabirshrestha/vim-lsp/files/6030182/rustVimrc.txt)
[vim-version.txt](https://github.com/prabirshrestha/vim-lsp/files/6030183/vim-version.txt)
[nvim-version.txt](https://github.com/prabirshrestha/vim-lsp/files/6030185/nvim-version.txt)

**Comment by prabirshrestha** [comment]
This is expected. If you are in neovim we enable diagnostics virtual text by default which can be disabled by `let g:lsp_diagnostics_virtual_text_enabled = 0`. Vim doesn't have virtual text support so it doesn't show up even if you enable it.

**Comment by prabirshrestha** [comment]
There is a discussion about virtual text support in vim github repo at https://github.com/vim/vim/issues/7553

**Comment by dc25** [comment]
Thank you!
