### ISSUE TITLE
Feature request: plug mapping or command for diagnostics under cursor

### ISSUE THREAD

**Issue by paradigm** [prabirshrestha/vim-lsp#1074]
While I quite like the information readily provided by `g:lsp_diagnostics_float_cursor` and `g:lsp_diagnostics_echo_cursor`, their automatic nature doesn't fit my workflow.

Would it be difficult to add an avenue to trigger them on-demand, similar to `<plug>(lsp-hover)` / `:LspHover`?

Along similar lines, would it be difficult to add a `g:lsp...` setting to have `<plug>(lsp-next-diganostic)` and related items echo the diagnostic jumped to on the bottom line, similar to vim commands like `:lnext`?

Thanks!

**Comment by prabirshrestha** [comment]
great idea! should be simple if you want to give it a try.

you will need to slightly refactor this file so we expose an internal api that plugin.vim can call.

* https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/internal/diagnostics/echo.vim
* https://github.com/prabirshrestha/vim-lsp/blob/master/plugin/lsp.vim

**Comment by paradigm** [comment]
I don't understand how we went `good first issue` that I could give a try, [which I promptly did and have had an MR that's good to go](https://github.com/prabirshrestha/vim-lsp/pull/1075) and [have maintained against upstream to fix merge conflicts for two months](https://github.com/prabirshrestha/vim-lsp/pull/1075#issuecomment-817151354) to `wontfix` :(

**Comment by paradigm** [comment]
See you again in August, stale bot.
