### ISSUE TITLE
Error is occurred when delete the multiple text-prop line

### ISSUE THREAD

**Issue by ippachi** [prabirshrestha/vim-lsp#1076]
## Minimum vimrc
```vim
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()
```

## Reproduction
1. Create a file with a few lines that the language server will start line below
```vim
" test.vim
" this is test file
" this is test file
" this is test file
```

2. Open this.
3. `:call prop_type_add('x', {})` and `:call prop_add(1, 5, #{end_lnum: 3, end_col: 5, type: 'x'})`
4. delete a line by `dd`
5. `E685: Internal error: text property below deleted line not found` is displayed

This will also happen when delete all lines by `dG`

**Comment by prabirshrestha** [comment]
do u have a repro without using vim-lsp and vim-lsp-settings. wondering if it is a bug in vim or us which could be off by 1.

**Comment by ippachi** [comment]
## Empty vimrc
No Errors

## Only vim-lsp installed
```vim
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/vim-lsp'
call plug#end()
```

No Errors

## Install vim-lsp and register server
```vim
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/vim-lsp'
call plug#end()

if executable('vim-language-server')
  augroup LspVim
    autocmd!
    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'vim-language-server',
        \ 'cmd': {server_info->['vim-language-server', '--stdio']},
        \ 'whitelist': ['vim'],
        \ 'initialization_options': {
        \   'vimruntime': $VIMRUNTIME,
        \   'runtimepath': &rtp,
        \ }})
  augroup END
endif
```
Errors


So it seems to happen only when vim-lsp is installed and the language server is enabled.
