### ISSUE TITLE
lsp_float autocommands don't work as expected

### ISSUE THREAD

**Issue by duvall-eb** [prabirshrestha/vim-lsp#1080]
I put this into a function called when `lsp_buffer_enabled` is triggered:
```vim
autocmd User lsp_float_opened nnoremap <buffer> <expr><c-f> lsp#scroll(+20)
autocmd User lsp_float_opened nnoremap <buffer> <expr><down> lsp#scroll(+1)
autocmd User lsp_float_opened nnoremap <buffer> <expr><c-d> lsp#scroll(-20)
autocmd User lsp_float_opened nnoremap <buffer> <expr><up> lsp#scroll(-1)
autocmd User lsp_float_closed nunmap <c-f>
autocmd User lsp_float_closed nunmap <c-d>
autocmd User lsp_float_closed nunmap <down>
autocmd User lsp_float_closed nunmap <up>
```
but it doesn't work as expected, for a couple of reasons:

1. If I have both the mappings and the unmappings, then the popup (`:LspHover`) never shows up
2. If I have simply `echomsg OPEN` and `echomsg CLOSE` for the respective autocommands (and none of the mapping bits), then they're both triggered, but the `CLOSE` message comes first, and then the `OPEN`, and they both show up when the popup is displayed.

The scrolling itself works just fine.

This is on vim 8.2.2550 (on MacOS, via brew), with ca2b527 of vim-lsp.

**Comment by prabirshrestha** [comment]
//cc @hrsh7th

**Comment by hrsh7th** [comment]
I will tackle it.

**Comment by hrsh7th** [comment]
I've sent PR that fixes the issue that does not affect `LspHover`.

And I think your snippet of codes should be following.

```
autocmd User lsp_float_opened nnoremap <buffer> <expr><c-f> lsp#scroll(+20)
autocmd User lsp_float_opened nnoremap <buffer> <expr><down> lsp#scroll(+1)
autocmd User lsp_float_opened nnoremap <buffer> <expr><c-d> lsp#scroll(-20)
autocmd User lsp_float_opened nnoremap <buffer> <expr><up> lsp#scroll(-1)
autocmd User lsp_float_closed nunmap <buffer> <c-f>
autocmd User lsp_float_closed nunmap <buffer> <c-d>
autocmd User lsp_float_closed nunmap <buffer> <down>
autocmd User lsp_float_closed nunmap <buffer> <up>
```

**Comment by dhduvall** [comment]
Thanks for the note on the missing `<buffer>` tags. The autocommands now fire as expected. Unfortunately, the hover windows now seem to no longer scroll: the scrollbar doesn't show up and `lsp#scroll(+1)` doesn't do anything. Reverting either or both of `vim-lsp` and my configuration to where they were when this was working doesn't seem to fix it, so I've no idea what's going on.

**Comment by hrsh7th** [comment]
In my previous test, The hover floating window could be scrolled.

I will check it.

**Comment by dhduvall** [comment]
Thanks for double-checking, though I'm pretty sure it's got to be something on my end; I'm just not sure what.

**Comment by prabirshrestha** [comment]
If you have a minimal vimrc it is easier to repro on our end.

You can start with this https://github.com/prabirshrestha/vim-lsp/blob/master/minimal.vimrc

**Comment by dhduvall** [comment]
Apologies for the noise. I was using an older version of vim in the window where it wasn't working: I had installed the `vim` from `brew` since that shell started and hashed the command table; `rehash` made the problem go away. I discovered this when I found `Vim(let):E117: Unknown function: prop_find` in the `vim-lsp` logs. Glad that was there! :)

**Comment by dhduvall** [comment]
However, now I'm seeing that `lsp_float_closed` isn't getting triggered. With the following `.vimrc`, I see `HELLO THERE` after `:LspHover` but not `OK BYE` after moving the cursor and seeing the popup pop down (not even in the output of `:messages`):
```vim
set cpoptions-=C
call plug#begin('~/.vim/plugged')
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/vim-lsp'
call plug#end()

autocmd User lsp_float_opened echomsg "HELLO THERE"
autocmd User lsp_float_closed echomsg "OK BYE"
```

**Comment by dhduvall** [comment]
It looks like `lsp#ui#vim#output#closepreview()` isn't being called on the cursor being moved: `CLOSING PREVIEW` never shows up. It does with the second hunk added, but then the popup window disappears automatically after a second or less. Not sure where to go from here, but it does look like another bug to me.
```diff
--- a/autoload/lsp/ui/vim/output.vim
+++ b/autoload/lsp/ui/vim/output.vim
@@ -11,6 +11,8 @@ function! s:vim_popup_closed(...) abort
 endfunction

 function! lsp#ui#vim#output#closepreview() abort
+    echomsg "CLOSING PREVIEW"
+
     if win_getid() ==# s:winid
         " Don't close if window got focus
         return
@@ -382,6 +384,7 @@ function! lsp#ui#vim#output#preview(server, data, options) abort
       elseif s:use_vim_popup
         " Vim popups
         call s:set_cursor(l:current_window_id, a:options)
+        call s:add_float_closing_hooks()
       endif
       doautocmd <nomodeline> User lsp_float_opened
     endif
```
