### ISSUE TITLE
Document visual effects of options.

### ISSUE THREAD

**Issue by emiel** [prabirshrestha/vim-lsp#1091]
I just spent some time trying to figure out why "A> " was showing up in the column for the line my cursor was positioned. I had no idea how to figure out where this was coming from. Turns out this was related to "actions" and the `g:lsp_document_code_action_signs_enabled` option. I kind of now what what it means but it is still a bit puzzling.

In addition "H> " was showing up as well. Perhaps it would be beneficial to document what visual effects are triggered by certain options. If I can search for "H>" or "A>" I at least know where to look.

**Comment by prabirshrestha** [comment]
This is now documented in https://github.com/prabirshrestha/vim-lsp/pull/1099. Thanks for your suggestion.

**Comment by emiel** [comment]
Wow! Nice work @prabirshrestha. Looks great to me and clarifies things a lot. Thanks for your work on vim-lsp.
