### ISSUE TITLE
pyls related error

### ISSUE THREAD

**Issue by codemeleon** [prabirshrestha/vim-lsp#110]
Hi, 

For pyls server code 

```
if executable('pyls')
    " pip install python-language-server
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
endif
```

I am getting following error.

Error detected while processing User Auto commands for "lsp_setup":
E15: Invalid expression: >['pyls']}, 'whitelist': ['python'], })

Error detected while processing User Auto commands for "lsp_setup":
E116: Invalid arguments for function lsp#register_server

Any suggestion how to fix it???

Thanks

**Comment by prabirshrestha** [comment]
What version of vim are you using?

**Comment by codemeleon** [comment]
I am using version 7.4.1689.

**Comment by prabirshrestha** [comment]
Minimum vim version that is supported is vim8
