### ISSUE TITLE
too many 'workspace/didChangeConfiguration' may cause flood

### ISSUE THREAD

**Issue by zhu** [prabirshrestha/vim-lsp#1107]
Currently `ensure_conf` which send `workspace/didChangeConfiguration`  is called in every `request_create`.
Some language server will do some extra works when `workspace/didChangeConfiguration` request.
For example, `pyls` will lint *all* documents in the workspace and send bunch of diagnostic notifications.

**Comment by hrsh7th** [comment]
We should fix it. I will tackle it.
