### ISSUE TITLE
Cquery-specific lsp methods

### ISSUE THREAD

**Issue by pdavydov108** [prabirshrestha/vim-lsp#111]
Hello @prabirshrestha. I have a question related to cquery. This server has some methods/requests that are not as far as I know present in the LSP, but are nice to have for my daily workflow. For example '$cquery/derived' used on a virtual function shows all it's implementations (overrides) in a project. Please, see [this](https://github.com/cquery-project/cquery/wiki/FAQ#cqueryderived). Is it possible to support such extensional methods in this plugin somehow? Or maybe it is possible to make some other plugin that extends this one to support this?

**Comment by prabirshrestha** [comment]
It is possible to call custom LSP methods.  In fact I had designed lsp to be pluggable. 

Refer to this plugin on how an external plugin can call lsp methods. https://github.com/prabirshrestha/asyncomplete-lsp.vim
