### ISSUE TITLE
Rename not work with cquery

### ISSUE THREAD

**Issue by codeplayer2org** [prabirshrestha/vim-lsp#112]
Sample:
```
#include <iostream>

class Foo {
    public:
        int bar;
};

int main(int argc, char* argv[]) {
    Foo foo;
    foo;
    return 0;
}
```

Use :LspRename at `Foo`(line9), Rename `Foo` to `Bar`.The command returned `Renamed`, but nothing changed.

Here is part of vim-lsp's log:
```
Sun 04 Mar 2018 04:54:42 PM CST:[{"response":{"data":{"__data__":"vim-lsp","server_name":"cquery"},"message":"server already started"}}]
Sun 04 Mar 2018 04:54:42 PM CST:[{"response":{"data":{"__data__":"vim-lsp","init_result":{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":[]},"documentHighlightProvider":true,"hoverProvider":true,"definitionProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"codeActionProvider":true,"textDocumentSync":2,"codeLensProvider":{"resolveProvider":false},"documentLinkProvider":{"resolveProvider":true},"workspaceSymbolProvider":true,"documentRangeFormattingProvider":false,"documentFormattingProvider":false,"documentSymbolProvider":true,"renameProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",":",">","#","<","\"","/"]}}}},"server_name":"cquery"},"message":"lsp server already initialized"}}]
Sun 04 Mar 2018 04:54:42 PM CST:[{"response":{"data":{"path":"file:///home/petrus/sample-cpp/main.cpp","__data__":"vim-lsp","server_name":"cquery"},"message":"already opened"}}]
Sun 04 Mar 2018 04:54:42 PM CST:[{"response":{"data":{"path":"file:///home/petrus/sample-cpp/main.cpp","__data__":"vim-lsp","server_name":"cquery"},"message":"not dirty"}}]
Sun 04 Mar 2018 04:54:42 PM CST:["--->",1,"cquery",{"method":"textDocument/rename","on_notification":"---funcref---","params":{"newName":"Bar","textDocument":{"uri":"file:///home/petrus/sample-cpp/main.cpp"},"position":{"character":4,"line":8}}}]
Sun 04 Mar 2018 04:54:42 PM CST:["<---",1,"cquery",{"response":{"id":2,"jsonrpc":"2.0","result":{"documentChanges":[{"edits":[{"range":{"end":{"character":7,"line":8},"start":{"character":4,"line":8}},"newText":"Bar"},{"range":{"end":{"character":9,"line":2},"start":{"character":6,"line":2}},"newText":"Bar"}],"textDocument":{"uri":"file:///home/petrus/sample-cpp/main.cpp","version":0}}]}},"request":{"method":"textDocument/rename","jsonrpc":"2.0","id":2,"params":{"newName":"Bar","textDocument":{"uri":"file:///home/petrus/sample-cpp/main.cpp"},"position":{"character":4,"line":8}}}}]
Sun 04 Mar 2018 04:54:42 PM CST:["<---",1,"cquery",{"response":{"method":"$cquery/progress","jsonrpc":"2.0","params":{"indexRequestCount":0,"onIndexedCount":0,"doIdMapCount":0,"onIdMappedCount":0,"loadPreviousIndexCount":0,"activeThreads":0}}}]
Sun 04 Mar 2018 04:54:42 PM CST:["<---",1,"cquery",{"response":{"method":"$cquery/progress","jsonrpc":"2.0","params":{"indexRequestCount":0,"onIndexedCount":0,"doIdMapCount":0,"onIdMappedCount":0,"loadPreviousIndexCount":0,"activeThreads":0}}}]
```
Full log please see below link:
https://gist.githubusercontent.com/codeplayer2org/018fc7d273a218ff43865e962e93299a/raw/e8194a4871668a4e705ebdca15e72558524a780a/gistfile1.txt

BTW, LspDocumentFormat does't support cpp files?

**Comment by pdavydov108** [comment]
I have the same problem. LSP standard [states](https://microsoft.github.io/language-server-protocol/specification#workspaceedit) that 'the edit should either provide changes or documentChanges', but it looks like vim-lsp [doesn't support documentChanges](https://github.com/prabirshrestha/vim-lsp/blob/2e4954cc9e22dec52f025f581ff292c53bb4ae52/autoload/lsp/ui/vim.vim#L370) now and it is what cquery sends to it. I guess this is the reason.

**Comment by prabirshrestha** [comment]
Seems like should be an easy fix. I deliberately didn't support documentChanges because supporting other buffers require more work and depends on users preference. Lang servers I have used doesn't send documentChanges on the same file. Seems like I would need to loop through documentChanges and if the uri is the same as the current buffer uri apply changes else ignore. That would solve this issue.

Feel free to send a PR else I will have a look at it during the weekend.

**Comment by prabirshrestha** [comment]
@codeplayer2org @pdavydov108 Should be fixed by https://github.com/prabirshrestha/vim-lsp/pull/118. Please pull the latest vim-lsp and try again.

**Comment by codeplayer2org** [comment]
Works fine at first try, but if you rename twice, it won't change the same line, unless you save the file first.

**Comment by codeplayer2org** [comment]
Add a sample.

```
    1 #include <iostream>
    2
    3 class Bar {
    4     public:
    5     │   int bar;
    6 };
    7
    8 int main(int argc, char* argv[]) {
    9     Bar foo;
   10     bar;
   11     return 0;
   12 }

```

**Comment by prabirshrestha** [comment]
if in same line, renaming not working correctly is a known issue. Will use https://github.com/prabirshrestha/vim-lsp/issues/96 to track.

**Comment by prabirshrestha** [comment]
@codeplayer2org seems like I'm missing call to `s:ensure_flush()` after workspace edits. Filed a new bug to track this https://github.com/prabirshrestha/vim-lsp/issues/121.

**Comment by Abominas** [comment]
There's another issue:
If the renamed symbol appears more than twice on the same line, the added offset between each change isn't handled. Renaming f to 'foo' does this:
```c
for(int f = 0; f < 50; f++);
```
```c
for(int foo = 0; foo < 50foo f++);
```
