### ISSUE TITLE
clangd does not read user/project configuration

### ISSUE THREAD

**Issue by Chaz6** [prabirshrestha/vim-lsp#1138]
`clangd` has the option `--enable-config` to enable reading user and project configuration, but this does not appear to be set by default. Is there a simple way to configure vim-lsp to use this option when editing c/c++ files?

**Comment by E1k3** [comment]
vim-lsp has the option to provide command line arguments to the language server executable in the `register_server` call.

Excerpt from `:help vim-lsp-server_info`:
```
 * cmd:
    required
    Function or array which represents command line to start the language
    server.
    [...]
    When array, the first element is the language server executable and
    the rest are the appropriate arguments. It is useful when the command line
    can be determined statically and |vim-lsp-server_info| is not necessary.

    Example:
	'cmd': ['pyls']
```

So I expect `'cmd': {server_info->['clangd', '--enable-config']},` in your `lsp#register_server`call to do what you want.
