### ISSUE TITLE
Custom signs

### ISSUE THREAD

**Issue by pdavydov108** [prabirshrestha/vim-lsp#114]
Hello @prabirshrestha, what do you think about adding options to customize signs? I've noticed that you have [this todo](https://github.com/prabirshrestha/vim-lsp/blob/2e4954cc9e22dec52f025f581ff292c53bb4ae52/autoload/lsp/ui/vim/signs.vim#L23) in signs codebase. It would be nice to use some unicode signs instead of `E>` and `W>`. I thought about implementing it but decided to ask how you see it first. Is it ok to just provide a few variables such as `g:lsp_error_sign`, `g:lsp_warning_sign`, etc?

**Comment by prabirshrestha** [comment]
Feel free to send a PR.

**Comment by prabirshrestha** [comment]
merged #115
