### ISSUE TITLE
pyls: Hover on symbols without hover information results in empty preview-window

### ISSUE THREAD

**Issue by E1k3** [prabirshrestha/vim-lsp#1141]
When I use `lsp-hover` on a symbol that has no hover information with [python-language-server](https://github.com/palantir/python-language-server) active, a giant empty preview-window opens and I can only close it by focusing it (repeat `lsp-hover`) and pressing ESC.

Seems like the `lsp-hover` code cannot handle zero-length answers correctly - probably because a `null` response is expected whenever no information was found.

I am not familiar with the LSP specification on that matter. If this is a pyls bug, I will report it on their repo.\
I would still appreciate it if you could fix this at your end, because this is something that will probably happen again, even if the spec may not allow it.

log with pyls (`"result": {"contents": ""}` -> doesn't work):
```
["--->", 3, "pyls", {"method": "textDocument/hover", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///testfile.py"}, "position": {"character": 7, "line": 1}}}]
["<---", 3, "pyls", {"response": {"id": 8, "jsonrpc": "2.0", "result": {"contents": ""}}, "request": {"id": 8, "jsonrpc": "2.0", "method": "textDocument/hover", "params": {"textDocument": {"uri": "file:///testfile.py"}, "position": {"character": 7, "line": 1}}}}]
["s:on_stdout client request on_notification() error", "Vim(call):E5555: API call: 'width' key must be a positive Integer", "function <SNR>92_on_stdout[2]..<SNR>90_on_stdout[79]..<SNR>64_request_on_notification[3]..<SNR>65_createNext[1]..<SNR>65_flattenInnerSourceCallback[5]..<SNR>65_tapSourceCallback[1]..<lambda>126[1]..<SNR>101_show_hover[6]..lsp#ui#vim#output#preview[58]..lsp#ui#vim#output#adjust_float_placement, line 6"]

```

log with clangd (`"result": null` -> works):
```
["--->", 3, "clangd", {"method": "textDocument/hover", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///home/eike/Projects/masters/raspberrypi/util.cpp"}, "position": {"character": 1, "line": 0}}}]
["<---(stderr)", 3, "clangd", ["I[22:02:14.166] <-- textDocument/hover(7)", ""]]
["<---", 3, "clangd", {"response": {"id": 7, "jsonrpc": "2.0", "result": null}, "request": {"id": 7, "jsonrpc": "2.0", "method": "textDocument/hover", "params": {"textDocument": {"uri": "file:///home/eike/Projects/masters/raspberrypi/util.cpp"}, "position": {"character": 1, "line": 0}}}}]
```

**Comment by harshad1** [comment]
I can reproduce this

**Comment by rhysd** [comment]
Can you show Python code which can reproduce this?

**Comment by rhysd** [comment]
As per LSP v3.16, hover contents can be empty.

**Comment by rhysd** [comment]
I'm looking implementation of hover. This case seems already covered:

https://github.com/prabirshrestha/vim-lsp/blob/296fb98d198cbbb5c5c937c09b84c8c7a9605a16/autoload/lsp/internal/document_hover/under_cursor.vim#L46-L49

> log with pyls ("result": {"contents": ""} -> doesn't work):
>
> log with clangd ("result": null -> works):

When `contents` is `""`, `empty(a:response['result']['contents'])` returns `1` so `lsp#utils#error` should be called.

**Comment by rhysd** [comment]
In #1151 I modified not to open preview window on empty hover contents.
