### ISSUE TITLE
Error highlights not removed (typescript-language-server)

### ISSUE THREAD

**Issue by emiel** [prabirshrestha/vim-lsp#1142]
I need some help troubleshooting an issue I've been seeing lately. After performing some edits and resolving diagnostic issues pointed out by typescript-language-server the error highlights are not removed even though there are no issues reported by the language server.

I've enabled logging and many lines of the following nature are emitted:

```
Mon Apr 12 09:58:27 2021:["diagnostics","clear_all_highlights","prop_remove","Vim(let):E117: Unknown function: prop_find","function <SNR>70_debounceTimeTimerCallback[1]..<SNR>70_tapSourceCallback[1]..<lambda>21[1]..<SNR>77_clear_highlights[2]..<SNR>77_clear_all_highlights, line 11"]
```

Anyone else seeing this? Let me know what other info is needed to aid in troubleshooting.

vim-lsp: bba0f45c892b3c815c65ce44f93bcbe118a40377
typescript-language-server@0.5.1

**Comment by zoumi** [comment]
I got this too. I'm using clangd.

**Comment by TPLinux** [comment]
same issue with python

**Comment by ls4154** [comment]
I have same issue with clangd #1135

**Comment by prabirshrestha** [comment]
Reverted https://github.com/prabirshrestha/vim-lsp/pull/1084/files via https://github.com/prabirshrestha/vim-lsp/pull/1145.

Please update to latest master. I will send a proper fix for the welcome message bug later since this one is more annoying than welcome message disappearing. 

Sorry for the inconvenience.

**Comment by TPLinux** [comment]
> Reverted https://github.com/prabirshrestha/vim-lsp/pull/1084/files via #1145.
> 
> Please update to latest master. I will send a proper fix for the welcome message bug later since this one is more annoying than welcome message disappearing.
> 
> Sorry for the inconvenience.

Thank you! solved

**Comment by emiel** [comment]
> Reverted https://github.com/prabirshrestha/vim-lsp/pull/1084/files via #1145.
> 
> Please update to latest master. I will send a proper fix for the welcome message bug later since this one is more annoying than welcome message disappearing.
> 
> Sorry for the inconvenience.

Appears to be working for me as well. Thanks!
