### ISSUE TITLE
Inactive preprocessor regions (#ifdef) clangd 12

### ISSUE THREAD

**Issue by kting28** [prabirshrestha/vim-lsp#1147]
In clangd 12's release notes, there's a mention on Inactive preprocessor regions (#ifdef) can be highlighted as comments. I see the "meta.disabled" in LspSemanticScopes output and I linked it with Comment syntax highlight group but it doesn't seem to work in vim-lsp. I'm using neovim nightly release. Disabled regions are not colored any different from other code.

I tried vscode and it does seem to highlight disabled regions as comments. Is this something that's supposed to work in vim-lsp?

**Comment by kting28** [comment]
pinging again in case there is plan to fix/support this.

**Comment by prabirshrestha** [comment]
semantic highlighting is using the old spec, we need to update to newer spec and since it can be very slow we might even need to move to using lua only for it for perf reasons.
