### ISSUE TITLE
Disable diagnostics for one of the langservers

### ISSUE THREAD

**Issue by miuirussia** [prabirshrestha/vim-lsp#1163]
Is it possible to do this now or does it need a new feature?

**Comment by prabirshrestha** [comment]
You can define a custom function to get the capabilities. 

https://github.com/prabirshrestha/vim-lsp/blob/296fb98d198cbbb5c5c937c09b84c8c7a9605a16/doc/vim-lsp.txt#L760-L771

If you are registering a server you can also pass `capabilities`. Here is a similar one with code samples that you could use. https://github.com/prabirshrestha/vim-lsp/issues/1056
