### ISSUE TITLE
VIM LSP not working on windows

### ISSUE THREAD

**Issue by Bhavesh164** [prabirshrestha/vim-lsp#1166]
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
i have used these plugins to setup my PHP Project. But no auto suggestion works for me.
My GVIM version is 8.2.  
I want to to support the following languages
like PHP, JS, HTML, CSS thats it. Please suggest me. I am novice with LSP. If you can give me vimrc file that will be great or show me any video tutorial to how to setup for PHP language that would be great.

**Comment by prabirshrestha** [comment]
You can use the sample here. https://github.com/prabirshrestha/vim-lsp/blob/master/minimal.vimrc

make sure to set `/tmp/` to proper windows path.

You can also follow instructions at. https://github.com/prabirshrestha/vim-lsp#registering-servers
