### ISSUE TITLE
Providing configuration to language server

### ISSUE THREAD

**Issue by ldelossa** [prabirshrestha/vim-lsp#1169]
Hello,

Been reading around your docs for awhile but I do not see any explanation of providing configuration to a language server directly.

I'd like to toggle a few settings which can be found here: https://github.com/golang/tools/blob/v0.1.0/gopls/doc/settings.md#documentation

Is there a way to plumb settings directly to the language servers being initialized on buffer open?

**Comment by prabirshrestha** [comment]
I would suggest using vim-lsp-settings if possible. Else you can see how https://github.com/mattn/vim-lsp-settings/blob/master/settings/gopls.vim is setting values.

Feel free to send PR to docs to help improve it for the next perons.

**Comment by ldelossa** [comment]
Thanks @prabirshrestha 

Im sorry but im not exactly seeing where to pipe settings to gopls into. 

Would it be here: https://github.com/mattn/vim-lsp-settings/blob/master/settings/gopls.vim#L7

if so, those options dont look relevant to: https://github.com/golang/tools/blob/master/gopls/doc/settings.md

if you can confirm where in the config block the gopls settings go, i can update vim-lsp-settings with the up-to-date configs

**Comment by prabirshrestha** [comment]
Should look something like this.

```vim
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

let g:lsp_settings = {
\   'gopls'': {
\     'initialization_options': {
\       'hoverKind': 'SingleLine'
\     }
\   },
\}
```

Once you have the above in vimrc, open any go file and run `:LspInstallServer`. It should automatically download the language server and start the server with correct settings. Next time you close vim and open .go file it should use the same settings.

**Comment by prabirshrestha** [comment]
If you are using `lsp#register_server` you can also pass `initialization_options` or `capabilities`. https://github.com/prabirshrestha/vim-lsp/blob/1f98a0656620bfc03dcb8bad87aa76a6304b3b73/autoload/lsp.vim#L607-L609

Here is an example of capabilities but could be applied to `initialization_options` too. https://github.com/prabirshrestha/vim-lsp/issues/1056
