### ISSUE TITLE
Update diagnostic only when saving the file

### ISSUE THREAD

**Issue by joelostblom** [prabirshrestha/vim-lsp#1170]
Is it possible to update the vim-lsp diagnostics, highlights etc only when a file is saved? I saw that there are several options related to timeouts which would delay the update, but couldn't find an option to trigger the updates only when saving files. Would I need to use an autocmd command for this? The issue I am trying to fix is that I find it distracting when the diagnostic highlights are changing as I am editing the file.

**Comment by prabirshrestha** [comment]
Diagnostics is a push notification to the client so we don't control when we can subscribe or unsubscribe. We do hover have methods to disable/show diagnostics ui via `lsp#disable_diagnostics_for_buffer()` and `lsp#enable_diagnostics_for_buffer()`. You should be able to use those methods to do anything that would make sense.

For example:

```vim
augroup MyLspDiagnsotics
  autocmd!
  autocmd BufWritePost,InsertLeave call lsp#enable_diagnostics_for_buffer()<CR>
  autocmd InsertEnter,CursorMovedI,TextChangedI,TextChangedP call lsp#disable_diagnostics_for_buffer()<CR>
augroup END
```

**Comment by joelostblom** [comment]
Thank you for the quick reply and for writing out the autocommand @prabirshrestha, much appreciated! I modified it slightly, most notably adding `*` which was necessary for me to make it work:

```vim
augroup MyLspDiagnsotics
  autocmd!
  autocmd BufWritePost * call lsp#enable_diagnostics_for_buffer()
  autocmd InsertEnter,CursorMovedI,TextChangedI,TextChangedP * call lsp#disable_diagnostics_for_buffer()
augroup END
```
