### ISSUE TITLE
WriteAll necessary after LspRename

### ISSUE THREAD

**Issue by ldelossa** [prabirshrestha/vim-lsp#1172]
Hello,

Utilizing LspRename it appears that altered buffered are not saved afterwards. 

This seems to break code often when using the rename features.

I work around this by doing a "wall" in vim, but should it be the case that after Rename happens a "wall" happens implicitly ?

**Comment by prabirshrestha** [comment]
Are you asking to flush changes after editing buffers (we currently don't do this) or are you asking to save all edited files.

**Comment by ldelossa** [comment]
It appears from my testing that saving all buffers fixes the issue, however im not sure how user friendly that is. Maybe a flush of the buffers could work as well? If it triggers a "didChange" maybe that will work too. 

Is there a vim command to flush all buffs i can test to see if this fixes the issue as well?
