### ISSUE TITLE
lsp_diagnostics_echo_cursor and lsp_diagnostics_float_cursor conflict in Neovim

### ISSUE THREAD

**Issue by artkorsun** [prabirshrestha/vim-lsp#1173]
Hi,
I noticed that if both `lsp_diagnostics_echo_cursor` and `lsp_diagnostics_float_cursor` are enabled with the same delay (which by default) then text in status disappears and float window gets positioned on a wrong place, but if I set a delay for status echo a bit higher, for example like that:
```
let g:lsp_diagnostics_float_delay = 500
let g:lsp_diagnostics_echo_delay = 550
```
than everything works fine. 
Reproducible in nvim (0.4.3), doesn't happen in vim v8.1  

![image](https://user-images.githubusercontent.com/1114383/120116072-a8667f00-c186-11eb-9681-84090d98f1c3.png)

**Comment by prabirshrestha** [comment]
I'm not sure if we can do anything here. Can you send a PR to update the default values? 

I have noticed that the ui rendering mechanism of vim and neovim has diverged.

**Comment by artkorsun** [comment]
Hi @prabirshrestha, I did some more testing and default values don't really solve the issue (i.e. it solves, but echo delay should be always bigger than float delay, which is unreliable). Apparently there are two different problems:

- empty command bar when echo is enabled
- misplaced preview window in nvim

The first problem happens because 'preview' function which is used by float clears the command bar by some reason. I couldn't get roots of the second problem, somehow screencol/screenrow return wrong position, but it is getting solved by registering float diagnostics before echo.
 
Please see the PR
https://github.com/prabirshrestha/vim-lsp/pull/1189
