### ISSUE TITLE
Borders hides the left-most characters when ambiwidth=double

### ISSUE THREAD

**Issue by ichitera** [prabirshrestha/vim-lsp#1177]
## Current behavior
Borders hides the left-most characters when `ambiwidth=double`.

https://user-images.githubusercontent.com/31098747/120330804-231ad000-c328-11eb-8186-353ae20467d6.mp4

## Expected behavior
Borders does not hide the left-most characters even if `ambiwidth=double`.

## A vimrc to reproduce this behavior
```vim
language C
set encoding=utf-8
set ambiwidth=double

if !filereadable('plug.vim')
  silent !curl --insecure -fLo plug.vim
    \  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
source plug.vim

call plug#begin('./plug')
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()

set omnifunc=lsp#complete
```

## Environment

- OS: Windows 10 (21H1)
- Vim: 8.2.834
- vim-lsp: 541ed984b17bb603fbac6680be83451a98d4c025
- vim-lsp-settings: [33e3175](https://github.com/mattn/vim-lsp-settings/tree/33e31750a962974b63feef3b3ef1bdc6a321128d)

**Comment by hrsh7th** [comment]
Thank you for your reporting.

Hm... I don't know how to solve it.

Should we remove borders if ambiwidth is not single?

**Comment by hrsh7th** [comment]
or we should use `+`, `-` and `|` as borderchars?

**Comment by ichitera** [comment]
I found [a similar  issue in Vim](https://github.com/vim/vim/issues/4477). I think that your suggesting ASCII characters work expectedly.

**Comment by hrsh7th** [comment]
@ichitera Could you test with #1178 branch?

**Comment by ichitera** [comment]
Thank you, @hrsh7th. 
I tried #1178, and it seems to work expectedly.

https://user-images.githubusercontent.com/31098747/120396939-68fc8600-c372-11eb-85a9-86e27ae93f83.mp4

**Comment by hrsh7th** [comment]
Thank you for your checking. I've merged.
