### ISSUE TITLE
Long delay between buffer change and request to LSP server

### ISSUE THREAD

**Issue by floitsch** [prabirshrestha/vim-lsp#1192]
I'm working on a LSP server (for Toit), but run into the following issue:
in insert-mode, the client never sends document-changes (`textDocument/didChange`) to the server.
When I exit the insert-mode, the client enqueues the did-change event, but still waits another 4 seconds before actually sending the request to the server.

Here are the relevant lines of the log file:
```
Wed Jun  9 14:39:37 2021:["<---",1,"toit-language-server",{"response":{"method":"textDocument/publishDiagnostics","jsonrpc":"2.0","params":{"uri":"file:///home/flo/work/toit/build/debug/bin/lib/uuid.toit","diagnostics":[]}}}]
Wed Jun  9 14:39:50 2021:["s:on_text_document_did_change()",1]
Wed Jun  9 14:39:50 2021:["s:send_didchange_queue() will be triggered"]
Wed Jun  9 14:39:54 2021:["s:send_event_queue()"]
Wed Jun  9 14:39:54 2021:[{"response":{"data":{"__data__":"vim-lsp","server_name":"toit-language-server"},"message":"server already started"}}]
Wed Jun  9 14:39:54 2021:[{"response":{"data":{"__data__":"vim-lsp","init_result":{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"documentSymbolProvider":true,"experimental":{"ubjsonRpc":true},"semanticTokensProvider":{"legend":{"tokenTypes":["namespace","class","interface","parameter","variable"],"tokenModifiers":["definition","readonly","static","abstract","defaultLibrary"]},"range":false,"full":true},"definitionProvider":true,"textDocumentSync":{"save":{"includeText":false},"change":1,"openClose":true},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","-","$"]}}}},"server_name":"toit-language-server"},"message":"lsp server already initialized"}}]
Wed Jun  9 14:39:54 2021:[{"response":{"data":{"__data__":"vim-lsp","server_name":"toit-language-server"},"message":"configuration sent"}}]
Wed Jun  9 14:39:54 2021:[{"response":{"data":{"path":"file:///tmp/hello.toit","__data__":"vim-lsp","server_name":"toit-language-server"},"message":"already opened"}}]
Wed Jun  9 14:39:54 2021:["s:update_file_content()",1]
Wed Jun  9 14:39:54 2021:["--->",1,"toit-language-server",{"method":"textDocument/didChange","params":{"contentChanges":[{"text":"main:\n  print \"hello world\"\n  print \"foo\"\n  print \"bar\" 1 2\n"}],"textDocument":{"uri":"file:///tmp/hello.toit","version":2}}}]
```
In the time span 14:39:37-14:39:45 I modified the buffer. (There is no log-entry for me switching out of insert mode).
At 14:39:50 I left the insert mode, and then it takes another 4 seconds, before the queue is emptied and the server is notified about the changed file.
This makes the diagnostics way too slow.

Note that things feel better, when enabling completion. It seems that the client then sends document changes more frequently to the server.

**Comment by mattn** [comment]
You can set `let g:lsp_use_event_queue = 0` but you may have heavily behaviors.

**Comment by floitsch** [comment]
I think I'm ok with the queue waiting a few seconds.
I guess what I'm really looking for is to trigger the queue in insertion mode. At the moment the `did_change` trigger happens only when I exit the edit mode.

**Comment by prabirshrestha** [comment]
You can modify the `updatetime`. https://github.com/prabirshrestha/vim-lsp/blob/9ecbe24af95df983c74166108d2dd602443f69d0/autoload/lsp.vim#L1120

**Comment by prabirshrestha** [comment]
Please let us know if you are still having issues.
