### ISSUE TITLE
Add ability to (re)start LSP server

### ISSUE THREAD

**Issue by fedorenchik** [prabirshrestha/vim-lsp#1200]
**Please describe the problem.**
Please, add ability to restart LSP server or start it after `:LspStopServer`.

**Describe the solution you'd like**
Commands such as `LspStartServer` and `LspRestartServer`

**Additional context**
This is needed for running LSP in modified environment. For example, to use LSP to develop Blender plugins, need to add environment variable
```
PYTHONPATH=$(blender --background --python-expr 'print("PYTHONPATH="+":".join(__import__("sys").path))' 2>/dev/null | grep -F 'PYTHONPATH=')
```
before running LSP.

Currently I have to open terminal, export environment variable and run gvim from terminal.

It would be much more convenient to modify environment inside gvim and run LSP in modified environment directly.

**PS:**

When using `setenv()` LSP server doesn't update its config.

**Comment by fedorenchik** [comment]
ping?

**Comment by lukelbd** [comment]
It seems this can be done using `call lsp#activate()`.

**Comment by fedorenchik** [comment]
Can also be done with:
```viml
call lsp#disable()
call lsp#enable()
```
or
```viml
cd any_dir
cd -
```
