### ISSUE TITLE
What does lsp_document_code_action_signs_hint mean

### ISSUE THREAD

**Issue by laotoutou** [prabirshrestha/vim-lsp#1203]
Why do I have "A>" on the left side of my screen

**Comment by laotoutou** [comment]
let g:lsp_document_code_action_signs_enabled = 0

And then the "A>" disappears

**Comment by YusukeSuzuki** [comment]
I am introducing vim-lsp for the first time. This is my first time installing such a complicated plugin in vim. vim-lsp is not fully working yet (completion doesn't work and I don't know how to make it work). However, I'm concerned that "A>" keeps appearing. When I asked Claude 3, he answered that it was some kind of error. Even after searching all over the source, I still can't figure out what "A>" means. I don't know if it's a good idea to delete it. I don't think it should be deleted if it indicates a problem with the system.

**Comment by jmdevin** [comment]
It means there is a code action available on that line. If you open vim and do `:h g:lsp_document_code_action_signs_enabled` you can read about what it means and how to work with it/change it.
