### ISSUE TITLE
Strange popup layout on GVim

### ISSUE THREAD

**Issue by dubst3pp4** [prabirshrestha/vim-lsp#1208]
I'm using gVim 8.2 Patch 1-2815 with vim-lsp with commit 7ba553effb021293c9ff5176b91e76da71797825. On my system the popup with the completion preview (the one that shows additional infos like method signatures) looks strange. It seems that the content of the preview floats out of the popup window (see picture below). I don't have this issue with other popups like the one from `:LspHover` or `:LspPeekDefinition`, it is just this little popup that shows the signatures and documentation when completing a word that behaves like this.

Strange layout with autocompletion:
![Bildschirmfoto von 2021-08-06 13-43-33](https://user-images.githubusercontent.com/2373731/129691223-9aaba3fe-10ac-45c7-a500-e69949257d30.png)

Correct layout with `:LspHover`:
![Bildschirmfoto von 2021-08-17 10-30-08](https://user-images.githubusercontent.com/2373731/129691963-578e151c-0dfe-425b-8289-0d23ddb53982.png)

Correct layout with Vim in a terminal:
![Bildschirmfoto von 2021-08-17 10-31-13](https://user-images.githubusercontent.com/2373731/129692121-a5326bc1-2bdf-4163-9754-4221293f759f.png)

I have just some simple settings in my `gvimrc`:
```
set guifont=FantasqueSansMono\ Nerd\ Font\ 13
if &background =~# 'dark'
  set guioptions+=d "enable dark theme
endif
set guioptions-=T "remove toolbar
set guioptions-=m "remove menu bar
set guioptions-=L "disable scrollbars left
set guioptions-=l "disable scrollbars left
set guioptions-=R "disable scrollbars right
set guioptions-=r "disable scrollbars right

" shows a contextmenu when right-clicking
set mousemodel=popup
```
Thanks for any hints!

**Comment by prabirshrestha** [comment]
Can you verify you are having the same issue with `LspHover` in https://github.com/prabirshrestha/vim-lsp/pull/1078.

currently autocomplete uses vim-vital-vs and LspHover in master doesn't. LspHover in the above PR uses vim-vital-vs so would be interesting to see if the bug is in vim-vital-vs.

**Comment by dubst3pp4** [comment]
> Can you verify you are having the same issue with `LspHover` in #1078.
> 
Yes, the same issue occurs with #1078 when using `:LspHover` in gVim:
![Bildschirmfoto von 2021-08-18 08-44-56](https://user-images.githubusercontent.com/2373731/129851120-13175aea-eb85-49ac-8288-188e0f530087.png)
Whereas with normal Vim it looks as expected (except my colorscheme :upside_down_face:):
![Bildschirmfoto von 2021-08-18 08-45-28](https://user-images.githubusercontent.com/2373731/129851207-a63ed514-d901-4b8b-ac01-508c506acc6e.png)
Thanks for you help!

**Comment by prabirshrestha** [comment]
Then it would be a bug in vim-vitalvs. //cc @hrsh7th

**Comment by hrsh7th** [comment]
Thank you... Hm... It seems vim's bug to me. But the old implementation has no problem...
I will investigate workaround for it.

**Comment by dubst3pp4** [comment]
> Thank you... Hm... It seems vim's bug to me. But the old implementation has no problem...
> I will investigate workaround for it.

@hrsh7th thanks for having a look!

**Comment by hrsh7th** [comment]
@dubst3pp4 I'm the author of module of the popup window.

Sorry for the annoying but I have no reproducible environment.

https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/vital/_lsp/VS/Vim/Window/FloatingWindow.vim#L395

The above reference is to make vim's popup window options. Can you modify and test these options on your environment?

**Comment by dubst3pp4** [comment]
> The above reference is to make vim's popup window options. Can you modify and test these options on your environment?
@hrsh7th I'm sorry but can you give me a hint what I have to do exactly? I'm a little bit lost...

**Comment by hrsh7th** [comment]
@dubst3pp4 Sorry I was too short words.

I'm worried to `'wrap': v:false` or `'fixed': v:true` is the cause of this problem.
So it is helpful if you modify these argument and re-check the problem.

**Comment by dubst3pp4** [comment]
@hrsh7th okay, I checked the following combinations and none of them is working:
- `'wrap': v:true` and `'fixed': v:true`
- `'wrap': v:true` and `'fixed': v:false`
- `'wrap': v:false` and `'fixed': v:false`

The error remains the same... I can send you a DM on Twitter if this is the wrong place to discuss the error...

**Comment by vyouzhis** [comment]
![image](https://user-images.githubusercontent.com/5832145/181194031-8fc07f65-b541-4019-a6e1-b956c7456ae8.png)

.vimrc

`
set ambiwidth="double"
`


because the  code

`
./autoload/vital/_lsp/VS/Vim/Window/FloatingWindow.vim

line in  454  or 467 

vim default  ambiwidth == single
[https://yianwillis.github.io/vimcdoc/doc/options.html#'ambiwidth'](https://yianwillis.github.io/vimcdoc/doc/options.html#'ambiwidth')

`



![image](https://user-images.githubusercontent.com/5832145/181194331-1533dc05-dc67-4e17-bf0c-cdefb48cc558.png)
