### ISSUE TITLE
Display filenames in lsp-quickpick

### ISSUE THREAD

**Issue by nkaretnikov** [prabirshrestha/vim-lsp#1209]
Not sure whether it's an issue with vim-lsp or something else. I've tried this on Rust and C++ code -- the behavior is the same.

It would be nice to display filenames when searching for things (in live preview), when searching in a project/workspace.

For instance, if there are multiple functions having the same name, there's no way to see which one is the right one.

**Comment by nkaretnikov** [comment]
If it's not possible to implement for some reason, an okay-ish workaround would be a way to cycle thru quickpick matches (after jumping to one). Similar to how it can be done with `:cnext`, which doesn't work with the quickpick buffer.

**Comment by ArtAndreev** [comment]
Yes, it's really annoying when trying to search something, that has typical name

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/26388769/214023718-cd651b66-7be5-4253-8f0a-a9ad304f7f7f.png">

**Comment by ArtAndreev** [comment]
@prabirshrestha I am very sorry for tagging you, can I ask the maintainers to implement this? It'll improve workflow very much.
