### ISSUE TITLE
Could you hint me how to have higlight

### ISSUE THREAD

**Issue by aleiton** [prabirshrestha/vim-lsp#1217]
Hey guys, I decided to move to `vim-lsp` from `ale` as I wanted to have a full vimscript with autocompletion pluggin.

The thing is that I don't know how to set up the highlight / diagnostic here.

<img width="794" alt="Screen Shot 2021-08-29 at 2 18 27 PM" src="https://user-images.githubusercontent.com/20656001/131259755-6d12777d-94cb-4222-9a5f-190fab26ddc4.png">
<img width="794" alt="Screen Shot 2021-08-29 at 2 18 51 PM" src="https://user-images.githubusercontent.com/20656001/131259757-a7885ecf-87f0-42fc-a1b4-d2b91e6a58d6.png">

I tried with two coloscheme to see if there was a problem with that: onedark and gruvox, both of them doesn't highlight the errors.

I didn't find in the wiki how to set this.

This is my vim config up to day in case you could help me: https://github.com/aleiton/.config/tree/master/vim

Thanks !

**Comment by mirko1593** [comment]
<img width="235" alt="企业微信截图_b3f59909-6c00-4431-abd7-4956725ba815" src="https://user-images.githubusercontent.com/15713836/132199709-34d293df-d852-49db-bf98-922cb1a600d1.png">

what's the name of this column? lol

**Comment by mattn** [comment]
Could you provide output for `:LspStatus`.

**Comment by prabirshrestha** [comment]
This is the default.

```
let g:lsp_diagnostics_highlights_enabled = get(g:, 'lsp_diagnostics_highlights_enabled', lsp#utils#_has_highlights())
```

You are most likely using vim that doesn't support it.

https://github.com/prabirshrestha/vim-lsp/blob/ee38eb1bc6c898fee0e980276a2d9d2104f014e4/autoload/lsp/utils.vim#L27-L30

**Comment by dpo** [comment]
My vim is built with `+textprop`. In addition, both `:echo exists('*prop_add')` and `:echo has('patch-8.1.1035')` return `1`. Isn't that sufficient? Are there other requirements?

**Comment by dpo** [comment]
Actually, now that I opened a file from your plugin, I realized that it works for viml files. But it doesn't work for C/C++ or Julia.

**Comment by prabirshrestha** [comment]
Look at logs or `LspStatus`. your LSP serer could not be running or the features are disabled hence it is not working.

**Comment by prabirshrestha** [comment]
Please provide more context.
