### ISSUE TITLE
Force refresh repeats previous part of word instead of opening completion menu

### ISSUE THREAD

**Issue by ElArtista** [prabirshrestha/vim-lsp#1224]
Using the following mapping:
```
imap <c-space> <Plug>(asyncomplete_force_refresh)
```
and triggering it here:
![image](https://user-images.githubusercontent.com/4622346/134063165-abc2e2f3-95c2-4bb0-8eb8-1078a7aeda9b.png)

leads to this:
![image](https://user-images.githubusercontent.com/4622346/134063383-710dac36-2532-43e4-bc06-d8495a740dfe.png)

**Comment by ElArtista** [comment]
After checking out coc.nvim docs I just changed the mapping to <c-@> and ctrl-space works?
It must be the terminal emulator translating this into a different combination (I cross checked it with `cat -v`).
Maybe we should put it in vim-lsp docs too as a hint?

**Comment by prabirshrestha** [comment]
We should document it in asyncomplete.vim since `asyncomplete_force_refresh` is from asyncomplete. I have used `<c-@>` in the past so we should be good to add it to docs as well as readme.
