### ISSUE TITLE
Can't select workspace symbol

### ISSUE THREAD

**Issue by evergreen-trading-systems** [prabirshrestha/vim-lsp#1230]
When I search `:LspWorkspaceSymbolSearch`, I cannot select from the options but your video shows otherwise - https://github.com/prabirshrestha/quickpick-lsp.vim#plspworkspacesymbol

I press ⬇️ I see B

https://user-images.githubusercontent.com/4870868/135375444-9d28d19c-db0c-474b-b481-ea0a63863ff2.mp4

**Comment by prabirshrestha** [comment]
please provide logs.

**Comment by prabirshrestha** [comment]
You need to use `ctrl+j` or `ctrl+k`. You can view the default logs at https://github.com/prabirshrestha/vim-lsp/blob/10bbcb11428af1607009fcf76d79fee46d745955/autoload/lsp/internal/ui/quickpick.vim#L61-L103.

https://github.com/prabirshrestha/quickpick-lsp.vim is no longer required now as vim-lsp ships with quickpick ui by default. Use `:LspWorkspaceSymbolSearch` instead.
