### ISSUE TITLE
Disable inline diagnostics on warnings but keep them for errors?

### ISSUE THREAD

**Issue by adast9** [prabirshrestha/vim-lsp#1231]
Is this possible?
I don't want to see a warning for a line appended to the end of it but I still want to see it on errors.

**Comment by prabirshrestha** [comment]
Do you mean virtual text? It should be possible. We can add a small check here. https://github.com/prabirshrestha/vim-lsp/blob/a91419ea0ace6f791a43e0697946599fe7a9ae60/autoload/lsp/internal/diagnostics/virtual_text.vim#L131

**Comment by whonore** [comment]
As far as I can tell, this feature wasn't ever actually implemented, so could it be revisited? I would also find it very helpful to be able to selectively enable/disable virtual text and sign column markers for specific diagnostic severities. I'd be willing to open a PR if there's some agreement that it's a good idea.
