### ISSUE TITLE
Split resizing to 1 line after applying a codeaction

### ISSUE THREAD

**Issue by lazopm** [prabirshrestha/vim-lsp#1233]
This started happening a few weeks back, when I apply code actions my panes get resized to 1 or 2 lines.
Repro steps:
* :LspCodeAction
* ctrl+j to go down the list
* ctrl+k to go up the list (seems to repro consistently if I go down too far down the list then go up and select an action)
* select code action
* observe pane gets resized
<img width="1439" alt="Screen Shot 2021-10-14 at 2 10 01 AM" src="https://user-images.githubusercontent.com/5622067/137287319-1a1e8ce7-4445-409c-a08d-03888c6b5cac.png">

**Comment by blyoa** [comment]
I tried the repro steps with the following vimrc, but I cloud not reproduce the issue.

```viml
language C

if !filereadable('plug.vim')
  silent !curl --insecure -fLo plug.vim
    \  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
source plug.vim

call plug#begin('./plug')
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()

let g:lsp_settings = {
      \ 'efm-langserver': {'disabled': v:false},
      \ }
```

https://user-images.githubusercontent.com/9126033/139519239-cc62aaa3-7764-4510-b4e3-19bd800dadb1.mp4

@lazopm 
Could you add settings to the above vimrc to reproduce the issue?

**Comment by naotaka3** [comment]
I reproduce the same issue with the following setting.
`let g:lsp_diagnostics_float_cursor = 1`
The first LspCodeAction may succeed but the second time this issue definitely occurs in my case.

**Comment by prabirshrestha** [comment]
This should be fixed in the latest master. Please give it a try. Thanks to @blyoa for the fix.
