### ISSUE TITLE
Preview Window generate errors on popupclose

### ISSUE THREAD

**Issue by hotung1027** [prabirshrestha/vim-lsp#1238]
# Problems summary
Preview Window generate errors
Error message:
```
Error detected while processing BufUnload Autocommands for "<buffer=3>"..function <SNR>272_popMarkdown[3]..<SNR>272_popBuffer:
line    2:
E716: Key not present in Dictionary: "3"
```
https://user-images.githubusercontent.com/20833241/144276701-958dd5d0-670a-43ba-96bd-cde916de5540.mp4

## Expected
no error will disrupt

## Work Around
disable the popup preview window by
```
let g:lsp_preview_float=0
```

## Environment Information

- OS:
`Ubuntu-20.04`

```
- vim
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 28 2021 00:05:22)
Included patches: 1-3685
Compiled by randyt@randyt-MS-7C84
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sodium            -xfontset
+digraphs          +mouse             -sound             +xim
+dnd               +mouseshape        +spell             -xpm
-ebcdic            +mouse_dec         +startuptime       +xsmp_interact
+emacs_tags        -mouse_gpm         +statusline        +xterm_clipboard
+eval              -mouse_jsbterm     -sun_workshop      -xterm_save
+ex_extra          +mouse_netterm     +syntax            
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
```

```

                       
## minimal vimrc

```vim
" Your minimal init.vim/vimrc
call dein#begin('~/.vim/bundle')
" dein 管理的插件列表必须位于 dein#begin() 和 dein#end() 之间
"""""""""""""""""""""""
" Package Manager
""""""""""""""""""""""
call dein#add('Shougo/dein.vim')
call dein#add('wsdjeg/dein-ui.vim')


""""""""""""""""""""""""""
" Neovim 2 Vim Support
"""""""""""""""""
if !has('nvim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')
endif


""""""""""""""""""""""""""""""""
" COLORSCHEME
"""""""""""""""""""""""""""""
call dein#add( 'altercation/vim-colors-solarized')
call dein#add( 'rakr/vim-one')
call dein#add( 'vim-airline/vim-airline')
call dein#add( 'vim-airline/vim-airline-themes')
call dein#add( 'nathanaelkane/vim-indent-guides')


call dein#add( 'derekwyatt/vim-fswitch')
call dein#add( 'kshenoy/vim-signature')

""""""""""""""""""""""""""""""""""""""""""""
" NCM2
""""""""""""""""""""""""""""""""""""""""""""
call dein#add('ncm2/ncm2')

call dein#add( 'Shougo/pum.vim')


"""""""""""""""
" SOURCE
"""""""""""""""
call dein#add('ncm2/ncm2-vim-lsp')


"""""""""""""""""""""
" VIM LSP CONFIG
"""""""""""""""""""""
call dein#add( 'prabirshrestha/vim-lsp')
call dein#add( 'mattn/vim-lsp-settings')

""""""""""""""""""""
" Diagnostic
""""""""""""""""""""
call dein#add( 'dense-analysis/ale')
call dein#add( 'rhysd/vim-lsp-ale')


"""""""""""""""""""""""""""""""""""""""""""
" TMUX
""""""""""""""""""""""""""""""""""""""""""""
call dein#add( 'christoomey/vim-tmux-navigator')
call dein#add( 'wellle/tmux-complete.vim')

" 插件列表结束
call dein#end()

""""""""""""""""""""""""
" ALE
""""""""""""""""""""""
let g:ale_completion_enabled = 0
let g:ale_open_list = 1
let g:ale_keep_list_window_open = 0
let g:ale_hover_to_preview=0
let g:ale_cursor_detail=1
let g:ale_detail_to_floating_preview=0
let g:ale_floating_preview=0
let g:ale_lsp_suggestions=1


""""""""""""""""""""""""
" LSP
""""""""""""""""""""""
let g:lsp_semantic_enabled = 1
let g:lsp_preview_float=1

augroup lsp_install
    au!
    let g:lsp_signs_enabled = 1
    let g:lsp_diagnostics_echo_cursor = 1
    let g:lsp_signs_error = {'text': '✗'}
    let g:lsp_signs_warning = {'text': '‼'}
    let g:lsp_highlight_references_enabled = 1
    let g:lsp_diagnostics_enabled = 1
    let g:lsp_document_highlight_enabled=1
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END


```

## How to reproduce the problem from Vim startup 
1. find a function that lsp able to diagnostic
2. enter insert mode
3. jumping forth and back the function
4. error occur on popup closed

**Comment by mattn** [comment]
Could you please take a screenshot which can be look easily?
