### ISSUE TITLE
C/C++ Semantic highlighting seems to be broken for Clangd 13.0

### ISSUE THREAD

**Issue by kting28** [prabirshrestha/vim-lsp#1239]
Hello,

Semantic highlighting has been working for me for a while. I updated to clangd 13.0 from 12.0.1 and `:LspSemanticScopes` returns `Semantic highlighting not supported for cpp`. Switching to 12.0.1 restores the working behavior.

Hopefully this is easily reproducible. Here's my clangd configuration.  Let me know if you need any logs. I looked at log and don't see any obvious errors.

```
if executable('clangd')
  augroup lsp_clangd
    autocmd!
    autocmd User lsp_setup call lsp#register_server({
                \ 'name': 'clangd',
                \ 'cmd': {server_info->['clangd', '--header-insertion=never']},
                \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
                \ 'semantic_highlight': {
                \     'entity.name.function.cpp':'Function',
                \     'entity.name.function.method.cpp':'Function',
                \     'entity.name.type.enum.cpp':'Identifier',
                \     'entity.name.type.class.cpp':'Identifier',
                \     'meta.disabled':'Comment'
                \ }})
    autocmd FileType c setlocal omnifunc=lsp#complete
    autocmd FileType cpp setlocal omnifunc=lsp#complete
    autocmd FileType objc setlocal omnifunc=lsp#complete
    autocmd FileType objcpp setlocal omnifunc=lsp#complete
  augroup end
endif
```

**Comment by griwes** [comment]
This is easily reproducible. I _think_ what happened is that clangd adjusted its semantic token support to be up to spec (LSP 3.16 now includes semantic token information), but vim-lsp still uses the pre-standard protocol. 3.16 has been out for about a year. When can we hope for vim-lsp to implement the per-spec support for this?

**Comment by kting28** [comment]
yup.... ["Support for legacy semantic tokens extension is dropped."](https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#semantic-highlighting)

**Comment by prabirshrestha** [comment]
vim-lsp uses the old semantic highlighting. 

I haven't looked into porting to the new spec since with vimscript it can be very slow. This is one of the feature that we may want to be explicit lua. More than happy to look at the PR if folks are willing to send either in vimscript or in lua.

**Comment by kting28** [comment]
@prabirshrestha , what's your estimate of the scale of the work and how much slower with vimscript?

**Comment by prabirshrestha** [comment]
it shouldn't be much of a work but we have seen very bad performance in vimscript for large files since loops in vimscript is notoriously slow. We could also have a flag that says files that have greater than X number of lines or size will ignore syntax highlighting so one could get best of both worlds.

**Comment by prabirshrestha** [comment]
This is in PR. Please give it a try.

https://github.com/prabirshrestha/vim-lsp/pull/1275

**Comment by prabirshrestha** [comment]
PR has been merged. Please enable the new setting manually and let us know how it goes.
