### ISSUE TITLE
Support multiple filenames/directories in the lsp#utils#find_nearest_parent util functions

### ISSUE THREAD

**Issue by lithammer** [prabirshrestha/vim-lsp#124]
It would be nice to be able to define multiple filenames or directories to the various `lsp#utils#find_nearest_parent_*` functions. Most specifically useful when setting the `root_uri`, take for example `cquery` which supports both `compile_commands.json` and `.cquery`.

I imagine something like this:

```vim
lsp#utils#find_nearest_parent_file_directory(
  \  lsp#utils#get_buffer_path(), ['compile_commands.json', '.cquery'])
```

**Comment by prabirshrestha** [comment]
Feel free to send a PR. Should be simple by checking the type of args and handling array or string.

**Comment by renstrom** [comment]
I might take a stab at it. The only complicated part is that it isn't really enough to just return the first match, you have to check all provided filenames and return the one that's closest (i.e. has the longest path). Not sure if there's some builtin to calculate path depth or something.

**Comment by prabirshrestha** [comment]
This has already been implemented. https://github.com/prabirshrestha/vim-lsp/pull/373
