### ISSUE TITLE
How to open the definition/implementation in a tab

### ISSUE THREAD

**Issue by grisuthedragon** [prabirshrestha/vim-lsp#1241]
I recently found this plugin and after a few days of trying I find it better than ale or coc due to its better performance and not requiring that much external tools, like nodejs, and its better integration with old school vim stuff I am using. 

But after working a few days I got a bit annoyed since command like `lsp-definition` open the definition in a new buffer. I personally perfer using tabs. So is the a possible to let commands like: 

* `lsp-definition` 
* `lsp-implementation`

open the file in a new tab instead of a new buffer?

**Comment by prabirshrestha** [comment]
You can use mods. https://github.com/prabirshrestha/vim-lsp/pull/776

Currently don’t have first class support for plugs.
