### ISSUE TITLE
New API for hover breaking position of floating windows

### ISSUE THREAD

**Issue by xguerin** [prabirshrestha/vim-lsp#1245]
Hello,

It seems that commit 10bbcb11428af1607009fcf76d79fee46d745955 is breaking the positioning of floating windows, on both nvim (0.7.0-dev) and vim (8.2, with patches 1-2434, 3402-3403, 3409, 3428, 3487, 3564, 3581-3582).

Example 1: cursor is on the right pane, floating window appears on the left

![image](https://user-images.githubusercontent.com/73404/147272910-4a6fbc87-2346-4820-9150-83f1e90b18ae.png)

Example 2: floating window not closing after cursor moves

![image](https://user-images.githubusercontent.com/73404/147273191-e0c81736-56bb-4d9c-b652-170f5b1714db.png)

Example 3: floating window not aligned with cursor

![image](https://user-images.githubusercontent.com/73404/147273282-66b8f7f2-7c41-471d-a35d-e6c5f3ee11ce.png)

Thanks,

**Comment by basilgood** [comment]
Same here. I confirm this issue. Tested only on vim8.2 Included patches: 1-3848.

**Comment by rhysd** [comment]
I could reproduce this. The condition which is not described in this issue is that the same buffer is opened in two windows. vim-lsp only checks a buffer number. So, when the same buffer is opened in non-current window, it wrongly opens a popup there.

**Comment by prabirshrestha** [comment]
Sorry for the annoying  bug. We should be able to port previous logic from here. https://github.com/prabirshrestha/vim-lsp/blob/5270685e9b527b5848f4564b1ab103f08c5a9753/autoload/lsp/ui/vim/output.vim#L88-L115 to https://github.com/prabirshrestha/vim-lsp/blob/5270685e9b527b5848f4564b1ab103f08c5a9753/autoload/lsp/internal/document_hover/under_cursor.vim#L241-L264.

I will be a bit busy for next several days but if someone is willing to have a look at it and send a PR feel free to do so.

**Comment by prabirshrestha** [comment]
we should also most likely fix the size. https://github.com/prabirshrestha/vim-lsp/blob/5270685e9b527b5848f4564b1ab103f08c5a9753/autoload/lsp/internal/document_hover/under_cursor.vim#L140-L143

**Comment by hrsh7th** [comment]
@xguerin I've fixed it. Could you test with it?

**Comment by xguerin** [comment]
Sure ! Let me do that in a little bit and get back to you.

**Comment by xguerin** [comment]
The problem with the wrong window in screenshot 1 is fixed :+1:

However, the problem of the location of the hover highlighted in screenshot 3 is still here:
![image](https://user-images.githubusercontent.com/73404/147872526-b6e5f525-6a9a-48df-981e-a41fe418c7d4.png)

It seems to be linked with folding. The problem only appears when parts of the code is folded.

**Comment by hrsh7th** [comment]
@xguerin I've re-fixed it. If this don't solve it, I have no another solution... :pray:

**Comment by xguerin** [comment]
Confirmed, thanks for the quick fix !
