### ISSUE TITLE
Document lsp_log_verbose

### ISSUE THREAD

**Issue by emiel** [prabirshrestha/vim-lsp#1247]
I was not able to find an entry for `lsp_log_verbose` in the documentation. Would be great to have it!

Thanks again for your hard work on vim-lsp!

**Comment by prabirshrestha** [comment]
Added docs. Please let me know if you need more info.

https://github.com/prabirshrestha/vim-lsp/pull/1262

**Comment by emiel** [comment]
Look great! Thanks so much.
