### ISSUE TITLE
popup windows handle long lines poorly

### ISSUE THREAD

**Issue by numEricL** [prabirshrestha/vim-lsp#1249]
When a language server returns a single long line vim-lsp let's the window decide how it's displayed. When the wrap option is on the line may fill the popup window and then disallow scrolling.

![image](https://user-images.githubusercontent.com/13125969/147721742-9937c3b8-a654-463f-8b56-827c880ff6e9.png)

The scroll function in `vim-lsp/autoload/vital/_lsp/VS/Vim/Window.vim` doesn't know about wrapped lines. The problem is improved by removing the bottom of buffer check allows scrolling past the wrapped line.

```
function! s:scroll(winid, topline) abort
  let l:ctx = {}
  function! l:ctx.callback(winid, topline) abort
    let l:wininfo = s:info(a:winid)
    let l:topline = a:topline
    " let l:topline = min([l:topline, line('$') - l:wininfo.height + 1])
    let l:topline = max([l:topline, 1])

    if l:topline == l:wininfo.topline
      return
    endif
```

Now scrolling passed the wrapped line is possible, but if the wrapped line extends beyond the entirety of the window it is not possible to view it by scrolling. As far as I know this is a fundamental problem of vim as a window's top line cannot be partway through a wrapped line.

It may be better to explicitly add line breaks to the content returned by the language server.

**Comment by prabirshrestha** [comment]
Unfortunately we may never be able to properly handle all use cases for vim. Neovim support focusing popup which allows you to use all the vim movements. I had sent a PR for vim but don't think it will ever get merged. https://github.com/vim/vim/pull/7555

Would it instead be better to have a mapping that allows to convert the current hover popup to preview window?

**Comment by numEricL** [comment]
I don't think focus-able popups will help here, but I agree that the root of the problem is Vim itself. Smooth scrolling through wrapped lines has never worked, https://github.com/vim/vim/issues/3188. I think Neovim has the same issue, https://github.com/neovim/neovim/issues/8715. 

Being able to convert popup to preview is already possible without source code changes just by using the existing mappings and a little vimscript, but personally I have no interest in preview windows for this purpose.

It seems to me the workaround to fix popups is to populate them with properly formatted text. I implemented a newline hack and it's working well enough but it has its own quirks. I think VIm's `gq` motion is better suited but haven't looked into yet.
