### ISSUE TITLE
`s:on_text_document_did_change` isn't fired in normal mode

### ISSUE THREAD

**Issue by qnighy** [prabirshrestha/vim-lsp#125]
When I type `u` (undo) or `dd` (remove line) in normal mode, vim-lsp does not recompile the source. I expect that `s:on_text_document_did_change` is fired on `TextChange` in addition to `InsertLeave`.

**Comment by prabirshrestha** [comment]
This is a known issue. In order to reduce communication between client and server you need to manually save the file for now primarily because of https://github.com/vim/vim/issues/2548.

**Comment by prabirshrestha** [comment]
Dupe of https://github.com/prabirshrestha/vim-lsp/issues/186.
