### ISSUE TITLE
Key not present in Dictionary: 1

### ISSUE THREAD

**Issue by connojd** [prabirshrestha/vim-lsp#126]
While working in some part of a window that isn't code e.g. the command line, an error message repeatedly appears:

Error detected while processing function <SNR>74_out_cb[2]..<SNR>73_on_stdout:
line   79:
E716: Key not present in Dictionary: 1
E716: Key not present in Dictionary: 1
...

Is there a way to disable the error message, or perhaps my cquery backend isn't configured properly?

**Comment by prabirshrestha** [comment]
This seems like a bug that needs to be fixed. We shouldn't disable the error message. Can you enable logs and paste the log? It is either a bug in vim-lsp or in cquery.

**Comment by connojd** [comment]
1 Fri 30 Mar 2018 09:02:12 AM MDT:["lsp#register_server","server registered","cquery"]

2   Fri 30 Mar 2018 09:02:12 AM MDT:["s:on_text_document_did_open()",1,"cpp","/home/cjd/bareflank/eapis","file:///home/cjd/bareflank/ea    pis/bfvmm/tests/hve/arch/intel_x64/test_virt_x2apic.cpp"]

  1 Fri 30 Mar 2018 09:02:12 AM MDT:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"cquery"},"message":"started ls    p server successfully"}}]

  2 Fri 30 Mar 2018 09:02:12 AM MDT:["--->",1,"cquery",{"method":"initialize","params":{"rootUri":"file:///home/cjd/bareflank","initializationOptions":{"cacheDirectory":"/home/cjd/.cache/cquery"},"capabilities":{},"rootPath":"/home/cjd/bareflank","trace":"off"}}]

  3 Fri 30 Mar 2018 09:02:12 AM MDT:["<---",1,"cquery",{"response":{"method":"$cquery/progress","jsonrpc":"2.0","params":{"indexRequest    Count":0,"onIndexedCount":0,"doIdMapCount":0,"onIdMappedCount":0,"loadPreviousIndexCount":0,"activeThreads":0}}}]

  4 Fri 30 Mar 2018 09:02:12 AM MDT:["<---",1,"cquery",{"response":{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandPro    vider":{"commands":[]},"documentHighlightProvider":true,"hoverProvider":true,"definitionProvider":true,"referencesProvider":true,"s    ignatureHelpProvider":{"triggerCharacters":["(",","]},"codeActionProvider":true,"textDocumentSync":2,"codeLensProvider":{"resolvePr    ovider":false},"documentLinkProvider":{"resolveProvider":true},"workspaceSymbolProvider":true,"documentRangeFormattingProvider":fal    se,"documentFormattingProvider":false,"documentSymbolProvider":true,"renameProvider":true,"completionProvider":{"resolveProvider":f    alse,"triggerCharacters":[".",":",">","#","<","\"","/"]}}}},"request":{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"root    Uri":"file:///home/cjd/bareflank","initializationOptions":{"cacheDirectory":"/home/cjd/.cache/cquery"},"capabilities":{},"rootPath"    :"/home/cjd/bareflank","trace":"off"}}}]

**Comment by pdavydov108** [comment]
@connojd Does this happen when you work with cpp file or not? If yes, are you sure you have compile_commands.json in your root directory? I also use cquery, and I sometimes get similar messages either when auto completion is triggered or when some configuration issue with cquery occurs. Unfortunately, I haven't looked into it yet..

**Comment by connojd** [comment]
@pdavydov108  Yes it seems only with cpp..I have a root compile_commands.json that I merge from several sub-compile_commands.json. Every thing appears to work i.e. it's finding definitions etc, but it prints out the dictionary error on certain events like on_text_document_did_open and on_cursor_moved. 

Sometimes the error fires so much that I have to exit vim and disable the plugin. I'm using the vim and clang packages from Arch Linux fyi.

**Comment by prabirshrestha** [comment]
Language server has lot of optional properties or sometimes it expects it to be dict instead of primitive types. If you have an exact log that would be great.

Or if you have small sample repo I can try it out.

**Comment by connojd** [comment]
I think the source of the errors was due to cmake placing commands for .asm files in the compile_commands.json. Looking through the log, it *seems* that the errors displayed in vim correspond to messages of the form:
```bash
["<---",1,"cquery",{"response":{"id":1,"jsonrpc":"2.0","error":{"code":-32603,"message":"Failed to index /home/cjd/bareflank/hypervisor/bfintrinsics/src/arch/x64/tlb.asm"}}}]
```

Looking through the cquery [source](https://github.com/cquery-project/cquery/blob/master/src/lsp_diagnostic.h#L46), the error code indicates an internal error.  This is occuring while editing cpp files; I didn't open any asm files. I then tried adding ```'blacklist': ['asm']``` to the dictionary argument passed to lsp#register_server but that didn't seem to do anything. Only after I removed the asm entries from compile_commands.json did the errors stop.

I will leave logging enabled and make note if the errors start up again, but otherwise I think the asm-entry removal fixed it for now.

**Comment by prabirshrestha** [comment]
Usually vim-lsp checks for `lsp#client#is_error()` and ignore if there is an error. There could be a bug for a particular request. Can you share the request method name?

**Comment by pdavydov108** [comment]
Hi, I've found some new info regarding this issue. What I see is sometimes when I type fast and use completion with cquery I suddenly see "Key not present" errors. This error happens because vim-lsp receives a response with the id that was already removed [here](https://github.com/prabirshrestha/vim-lsp/blob/110454144572bb20fb09a898f361810bbe065739/autoload/lsp/client.vim#L112). This happens when cquery sends some kind of error to the plugin. In my case it's a bit weird:

```
["--->",1,"cquery",{"method":"textDocument/completion","on_notification":"---funcref---","params":{"textDocument":{"uri":"file
:///home/pablo/some_file.cpp"},"position":{"character":58,"line":398}}}]
["<---",1,"cquery",{"response":{"id":47,"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[{"label":"j0","insertTextFormat
":1,"insertText":"j0(","sortText":"...........","kind":3,"filterText":"j0","documentation":"","detail":"double j0(double)"},... <some text skipped here> ...
["<---",1,"cquery",{"response":{"id":47,"jsonrpc":"2.0","error":{"code":-32603,"message":"Dropping completion request; a newer request has come in that will be serviced instead."}}}]
```

As you can see, we send completion request, cquery replies with completions, we remove request `id`, but then cquery reports that completion request with this id was aborted, but this key is not in a dict any more. This issue is a bit different from the one reported by @connojd , but I think this two has the same source.

**Comment by connojd** [comment]
I've definitely seen the "Dropping completion ..." message before, and the behaviour you describe of when it pops up is similar to mine. It seems to happen when I backspace out of a completion e.g. 

foo::
*backspace*
*backspace*
*backspace*
fo

Maybe it tries to complete 'foo' after the second backspace, but then it had already aborted the completion from the first time?

Also @pdavydov108 your reasoning would explain why I received much fewer error messages after I removed the .asm files from the compile_commands

**Comment by prabirshrestha** [comment]
@pdavydov108 Seems like a bug in cquery that is it reusing the id. Can you file a bug there? `-32603` means internal server error according to the spec.

autocomplete engines like asyncomplete.vim caches the autocomplete results so it doesn't need to query the lang server all the time for optimizations. langservers can set `isIncomplete` to `true` to signify not to cache and the next character should call lang server again. So this shouldn't have any impact. An example where this can be used is if the server returns too many results it may only provide few results and tell the editors to call again - github username autocomplete is one of the example.

**Comment by prabirshrestha** [comment]
cquery dev has confirmed that is is a bug on their side. Will have to wait for it to be fixed. In the meantime I will keep the bug open here untile it gets closed there.

**Comment by pdavydov108** [comment]
@prabirshrestha @connojd Yay, this annoying bug was fixed. Works for me now.

**Comment by prabirshrestha** [comment]
Thanks for the update.

**Comment by connojd** [comment]
Thank you!
