### ISSUE TITLE
mapping to `<Esc>` is broken when call `:LspHover`

### ISSUE THREAD

**Issue by kuuote** [prabirshrestha/vim-lsp#1263]
Hi. I'm always use this plugin, thanks.

# Problem

When calling `:LspHover` after mapping to `<Esc>`, will overwrites `<Plug>(lsp-float-close)`.

# Wanted Behavior

Don't mapping by default or write this behavior to document.

**Comment by numEricL** [comment]
If I understand correctly, the problem is that `:LspHover`  is overwriting one of your `<esc>` maps? If that's the case then you can try adding `nmap <plug>() <Plug>(lsp-float-close)` to your vimrc.

**Comment by kuuote** [comment]
Thanks. It's fixed surely in this method.
but this behavior side effects wide range and undocumented correctly. I believe articulate this behavior is better.

**Comment by prabirshrestha** [comment]
This is a bug in vim-lsp. We should check if `Esc` is mapped before vim-lsp maps.

`mapcheck("\<ESC>", "n")`

Feel free to send a PR. Should be on this file. https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/internal/document_hover/under_cursor.vim

**Comment by kuuote** [comment]
Sorry I didn't notice. I'll make PR later.

**Comment by EgZvor** [comment]
Looks like you shouldn't map <esc> anyway https://github.com/vim/vim/issues/3080

**Comment by prabirshrestha** [comment]
PR is merged. Please try again.
