### ISSUE TITLE
using arrow keys breaks after using LspHover

### ISSUE THREAD

**Issue by hooloovooo** [prabirshrestha/vim-lsp#1267]
When i use LspHover something goes wrong. I'm not sure it's something with this plugin since i'm no vim guru, but after that vim inserts A, B, C or D depending on key on a new row above where my cursor is.

Sorry in advance if this is the wrong place to ask about this issue, but since it happens after LspHover it's my best guess. :)

**Comment by rsmmr** [comment]
I'm seeing that occasionally too (not always). I believe that `LspHover` can leave `Esc` remapped in insert mode. When it happens, I can fix it by executing `iunmap <buffer> <Esc>`.

**Comment by basilgood** [comment]
With minimal vimrc https://github.com/prabirshrestha/vim-lsp/blob/master/minimal.vimrc.
vim 8.2 Included patches: 1-3848

https://user-images.githubusercontent.com/16057481/149680213-88f418fa-f732-4a7c-972f-378935236afc.mp4

**Comment by rothn** [comment]
I am having this issue too!

**Comment by hooloovooo** [comment]
Seems this is the same as #1263 
Worked for me after i used @numEricL suggestion in that issue.

**Comment by tsung-ju** [comment]
Related: https://github.com/vim/vim/issues/3080

**Comment by prabirshrestha** [comment]
PR is merged. Please try again.
