### ISSUE TITLE
Spawning language server with cmd: `vscode-language-server.cmd` failed.

### ISSUE THREAD

**Issue by ArthurHydr** [prabirshrestha/vim-lsp#1270]
Good afternoon! When I start a.html file, nvim returns an error at the bottom: 
![2022-01-23_01-28](https://user-images.githubusercontent.com/61481946/150664851-fbe733f7-db3a-4a57-be5c-e55f08e37b77.png)

**Comment by prabirshrestha** [comment]
Please provide your vimrc on how you registered the server. You might want to use shell instead similar to this. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Bash

highly recommend using https://github.com/mattn/vim-lsp-settings

**Comment by ArthurHydr** [comment]
Thanks!!
