### ISSUE TITLE
Force lint on save only

### ISSUE THREAD

**Issue by brianjamesquinn1** [prabirshrestha/vim-lsp#1280]
Migrating from ALE because ALE does not implement all of the LSP spec. I prefer as little noise onscreen as possible when programming. I was able to limit this with the settings:
```
let g:asyncomplete_auto_popup = 0
let g:lsp_signature_help_enabled = 0
```
However, a nice feature of ALE was that even if a language server client provides real-time diagnostics, ALE had a setting `let g:ale_lint_on_save = 1` which allowed you to only see diagnostics on save. Is there a similar setting in vim-lsp that I am missing? Otherwise can this feature be supported in the future?

**Comment by stemoretti** [comment]
Functions `lsp#disable_diagnostics_for_buffer()` and `lsp#enable_diagnostics_for_buffer()` can be useful for doing what you want.

The following code added to function `s:on_lsp_buffer_enabled()` (see `README.md`) will enable the linter when saving the file only if the buffer contains diagnostic messages.

```
" disable linting for the current buffer
call lsp#disable_diagnostics_for_buffer()

" function for enabling linting only when there are diagnostic messages
function! s:enable_linting() abort
    call lsp#enable_diagnostics_for_buffer()

    let lint_count = lsp#get_buffer_diagnostics_counts()
    if !lint_count.error && !lint_count.warning && !lint_count.information
        call lsp#disable_diagnostics_for_buffer()
    endif
endfunction

autocmd! BufWritePre * call <SID>enable_linting()
```

**Comment by prabirshrestha** [comment]
`lsp#enable_diagnostics_for_buffer()` and `lsp#disable_diagnostics_for_buffer()` are the apis that should allow you to do this. And is a lot powerful. No plans to add api for `ale_lint_on_save`.

**Comment by brianjamesquinn1** [comment]
@stemoretti @prabirshrestha Apologies as I think my request was unclear, but the above does not actually accomplish what I am looking for. What I'm looking for is more similar to `g:lsp_diagnostics_highlights_delay`, `g:lsp_diagnostics_signs_delay`, and `g:lsp_diagnostics_virtual_text_delay`. Instead of a delay, I am looking for the signs/highlights to only be updated when the buffer is saved, not after the new diagnostics are received.

**Comment by prabirshrestha** [comment]
The problem with adding the flag is we don't know when the highlight should stop. Is it after a delay/when the cursor moves/when insert mode. It is impossible to satisfy this requirement as it is a personal preference. 

Looking at ale seems like there are several options to make it work properly.

```vim
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
" You can disable this option too
" if you don't want linters to run on opening a file
let g:ale_lint_on_enter = 0
```

But then we hit the same issue of adding too many custom options which can easily be represented by vimscript and is alsmost the same amount of code.

```vim
augroup AutoLspDiagnosticsShowHide
  autocmd!
  autocmd InsertEnter,CursorMovedI * call lsp#disable_diagnostics_for_buffer()<CR>
  autocmd BufWritePre,InsertLeave * call lsp#enable_diagnostics_for_buffer()<CR>
augroup END
```

The reason `delay` exists is for perf as we want to debounce it.

**Comment by brianjamesquinn1** [comment]
Okay, I'll try to see if I can get it working with autocommand groups. Although I don't think it becomes a question of when the highlight should stop. It's only a question of when highlight should should up, which is only on save. For ale the setting is actually none of the above, but instead `let g:ale_lint_on_save = 1`, albeit you do need to use it in conjunction with other settings.

https://github.com/dense-analysis/ale/blob/e2ef4d91ee88c49fbc5aa3ec9b670acb1d24b81f/doc/ale.txt#L1376

My concern with the vimscript you posted above is I'm unsure if the highlights will disappear once I do anything after I save, but let me give it a go and see what I come up with. Thanks!

**Comment by hydrasho** [comment]
@brianjamesquinn1 you've managed to do what you wanted to do? I'm looking for the same thing, I'm thinking of changing LspClient if that's impossible :/
Thank !
