### ISSUE TITLE
`lsp#ui#vim#output#getpreviewwinid()` returns `v:false` for :LspHover

### ISSUE THREAD

**Issue by noscript** [prabirshrestha/vim-lsp#1281]
To reproduce:
1. `autocmd User lsp_float_opened echom lsp#ui#vim#output#getpreviewwinid()`
2. `:LspHover`
3. `:messages`

I'm using Vim 8.

**Comment by noscript** [comment]
The bug was introduced in 10bbcb11428af1607009fcf76d79fee46d745955.

**Comment by prabirshrestha** [comment]
This is an internal api and isn't supposed to be used by others. Can you mention your use case?

**Comment by noscript** [comment]
What do you mean isn't supposed to be used by others? There is an example in the documentaion, saying that there is `lsp#ui#vim#output#getpreviewwinid()` to get the window id.

>Can you mention your use case?

I'm trying to customize the look of the lsp popups, hide the borders, change the background, just following the documentation:

```vim
autocmd User lsp_float_opened
		    \ call setwinvar(lsp#ui#vim#output#getpreviewwinid(),
		    \		       '&wincolor', 'PopupWindow')
```

**Comment by hillyu** [comment]
is this fixed? same use case.

**Comment by prabirshrestha** [comment]
Please try the latest master. There is a breaking change on the api.

https://github.com/prabirshrestha/vim-lsp/pull/1323
