### ISSUE TITLE
Does lsp not support C#?

### ISSUE THREAD

**Issue by SamL1n** [prabirshrestha/vim-lsp#1286]
I've read the wiki and searched issues.However,I don't see any configuration about C#.
Does anyone share about it?

I use OmniSharp as language server,but it seems doesn't work with lsp.

for example : 
run `:LspDefinition`,nothing happened but the `Retrieving definition not supported for file type cs` 
run `:OmniSharpGoToDefinition` works, it seems like that the OmniSharp server works.

OS: windows 11 
Vim version : 8.2
Here is my vimrc:
```
augroup omnisharp_commands
	autocmd!
	autocmd CursorHold *.cs OmniSharpTypeLookup
	autocmd FileType cs nmap <leader> gd <Plug>(omnisharp_go_to_definition)
augroup END

	au User lsp_setup call lsp#register_server({
						\ 'name': 'omnisharp-roslyn',
						\ 'cmd': {server_info->['OmniSharp']},
						\ 'whitelist': ['cs']
						\ })

function! s:on_lsp_buffer_enabled() abort
	setlocal omnifunc=lsp#complete
	setlocal signcolumn=yes
	nmap <leader> kk <plug>(lsp-definition)
	nmap <buffer> <f2> <plug>(lsp-rename)
endfunction

augroup lsp_install
	au!
	autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
```

**Comment by prabirshrestha** [comment]
You can enable logs to see if there are issues. https://github.com/prabirshrestha/vim-lsp#debugging

I would suggesting using https://github.com/mattn/vim-lsp-settings#supported-languages

**Comment by SamL1n** [comment]
> You can enable logs to see if there are issues. https://github.com/prabirshrestha/vim-lsp#debugging
> 
> I would suggesting using https://github.com/mattn/vim-lsp-settings#supported-languages

vim-lsp-settings solved my problem
