### ISSUE TITLE
Always leave space for the gutter?

### ISSUE THREAD

**Issue by evprkr** [prabirshrestha/vim-lsp#1288]
I like the gutter, but it bugs me how it moves my code left and right constantly as it appears and disappears. Is there a way to set it so there is always a space left for the gutter, even when it's empty?

Also, while I'm at it, how would I go about changing the colors of the gutter?

**Comment by prabirshrestha** [comment]
You need to set the signcolumn.

I personally using this setting. You can also set it up globally.

```vim
function! s:on_lsp_buffer_enabled() abort
  setlocal signcolumn=yes
  ....
endfunction

augroup configure_lsp
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
```
