### ISSUE TITLE
Now vim has direct handling on LSP messages, we can use it when available

### ISSUE THREAD

**Issue by CoelacanthusHex** [prabirshrestha/vim-lsp#1291]
Now vim has direct handling on LSP messages, we can use it when available
https://github.com/vim/vim/commit/9247a221ce7800c0ae1b3487112d314b8ab79f53
`has("patch-8.2.4648")` can determine this feature

**Comment by prabirshrestha** [comment]
Looking forward to this. I will probably play around a bit more.

We should be able to update [client.vim](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/client.vim) and use this directly without using async.vim behind a flag. 

If someone wants to go for this feel free to try it out in the meanwhile.

**Comment by prabirshrestha** [comment]
I have been working on native support at https://github.com/prabirshrestha/vim-lsp/pull/1362. Feel free to give it a try. Will continue to dogfood this for this next several days.
