### ISSUE TITLE
Why doesn't clangd work as advertised?

### ISSUE THREAD

**Issue by thejohnfreeman** [prabirshrestha/vim-lsp#1295]
I've installed these plugins:

```vim
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
```

with this configuration (taken from [here](https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Clangd)):

```vim
if executable('clangd')
  autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '--background-index']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif
```

with this version of clangd:

```
Ubuntu clangd version 13.0.0-2
Features: linux
Platform: x86_64-pc-linux-gnu
```

Here is an example interaction from my log:

```
Mon 11 Apr 2022 12:21:50 PM CDT:["--->", 4, "clangd", {"method": "textDocument/definition", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///home/jfreeman/code/rippled/src/ripple/app/consensus/RCLConsensus.cpp"}, "position": {"character": 4, "line": 162}}}]
Mon 11 Apr 2022 12:21:50 PM CDT:["<---", 4, "clangd", {"response": {"id": 6, "jsonrpc": "2.0", "result": [{"uri": "file:///home/jfreeman/code/rippled/src/ripple/basics/algorithm.h", "range": {"end": {"character": 16, "line": 24}, "start": {"character": 10, "line": 24}}}]}, "request": {"id": 6, "jsonrpc": "2.0", "method": "textDocument/definition", "params": {"textDocument": {"uri": "file:///home/jfreeman/code/rippled/src/ripple/app/consensus/RCLConsensus.cpp"}, "position": {"character": 4, "line": 162}}}}]
```

One request and one response. The request is me asking for the definition of the word `prop` at the start of [this line](https://github.com/thejohnfreeman/rippled/blob/6a04bb714153d1774e2b5fcbf497fd410fad1138/src/ripple/app/consensus/RCLConsensus.cpp#L163):

```cpp
    prop.set_currenttxhash(
```

I expect vim-lsp and clangd to take me to [this line in the same function](https://github.com/thejohnfreeman/rippled/blob/6a04bb714153d1774e2b5fcbf497fd410fad1138/src/ripple/app/consensus/RCLConsensus.cpp#L156):

```cpp
    protocol::TMProposeSet prop;
```

but instead they take me to [this line in another file](https://github.com/thejohnfreeman/rippled/blob/6a04bb714153d1774e2b5fcbf497fd410fad1138/src/ripple/basics/algorithm.h#L25):

```cpp
namespace ripple {
```

Every definition request for any symbol leads to that same line. I know clangd is "using" my `compile_commands.json`, because if I remove it, it takes me to [this line in the same file](https://github.com/thejohnfreeman/rippled/blob/6a04bb714153d1774e2b5fcbf497fd410fad1138/src/ripple/app/consensus/RCLConsensus.cpp#L50) instead. I'll note that this line is the first `namespace ripple` declaration in the current file, why the other line is the first `namespace ripple` declaration in the translation unit (after including all headers).

**Comment by prabirshrestha** [comment]
Can you also mention the clangd version? [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) makes it easy to setup the right configurations.

**Comment by thejohnfreeman** [comment]
`:LspInstallServer` failed with this message:

```
./clangd: error while loading shared libraries: libz3.so.4.8: cannot open shared object file: No such file or directory
```

which I'm guessing is the same problem as [mentioned](https://github.com/mattn/vim-lsp-settings#clangd-cc) in the README of vim-lsp-settings. libz3.so.4 is installed on my machine at /usr/lib/x86_64-linux-gnu/libz3.so.4; if only it were looking for a less specific version...

**Comment by prabirshrestha** [comment]
I couldn't get the repo to generate the compile_commands.json but when I tried with other cpp project I was able to correctly jump.

Few things I would suggest to try out. 

1. Try with a minimal vimrc. You can start with https://github.com/prabirshrestha/vim-lsp/blob/master/minimal.vimrc
2. Add logs in [handle_location](https://github.com/prabirshrestha/vim-lsp/blob/78e07f96840394ea49696f68fb6a156bba8dd154/autoload/lsp/ui/vim.vim#L223 ) function.
3. use `:LspDefinition` instead of key bindings.

Only thing I can currently think of is that some other plugin is taking over.

**Comment by thejohnfreeman** [comment]
I get the same behavior even with the minimal vimrc. One new data point: every `LspDefinition` invoked on a use of a member variable in [this constructor definition](https://github.com/ripple/rippled/blob/7c66747d27869f9f3c96617bd4227038f1fa92b8/src/ripple/app/consensus/RCLConsensus.cpp#L94-L115) correctly leads back to the corresponding member declaration in [this header file](https://github.com/ripple/rippled/blob/7c66747d27869f9f3c96617bd4227038f1fa92b8/src/ripple/app/consensus/RCLConsensus.h#L59-L88), both with my personal vimrc and the minimal one.

How can I log to the `lsp_log_file`?

**Comment by prabirshrestha** [comment]
you can use these functions.

https://github.com/prabirshrestha/vim-lsp/blob/79698651c84e68f9dc8ad00741967195ea4086ea/autoload/lsp.vim#L39-L49
