### ISSUE TITLE
Command Option about 'typescript-language-server'

### ISSUE THREAD

**Issue by mmktomato** [prabirshrestha/vim-lsp#130]
In 'README.md' and 'doc/vim-lsp.txt', `--stdio` option is a 4th element of array.

> in 'README.md'
> \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server', '--stdio']},
>
> in 'doc/vim-lsp.txt'
> 'cmd': {server_info->
>         \ [&shell, &shellcmdflag, 'typescript-language-server', '--stdio']}

These don't work on my environment. I found following expression in wiki.

> // https://github.com/prabirshrestha/vim-lsp/wiki/Servers-TypeScript
> \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},

`--stdio` is included in 3rd element. This works fine on my env.

Which one is correct ? Meaning, anyone doesn't have problems with former one ?

**Comment by mmktomato** [comment]
With former one, I got this error in verbose log.

> ["--->",1,"typescript-language-server",{"method":"initialize","params":{"rootUri":"file:///path/to/currentdir","initializationOptions":{},"capabilities":{},"rootPath":"/path/to/currentdir","trace":"off"}}]
> ["<---(stderr)",1,"typescript-language-server",["Connection type required (stdio, node-ipc, socket). Refer to --help for more details.",""]]

**Comment by prabirshrestha** [comment]
Studio in the third one. Feel free to send a PR for correction.

**Comment by mmktomato** [comment]
Thx. I sent a PR.
#131

**Comment by ryanolsonx** [comment]
Strange thing.. Reversing this change is what got typescript to work again for me.

**Comment by niklaas** [comment]
@ryanolsonx I had to register the server myself as described in the wiki here because your plugin didn't work for me.

**Comment by ryanolsonx** [comment]
Maybe it’s a windows vs others thing... I’ll dig into it sometime

**Comment by niklaas** [comment]
Yeah, just wanted to leave a note. 👍
