### ISSUE TITLE
Clangd index progress indicator

### ISSUE THREAD

**Issue by whenov** [prabirshrestha/vim-lsp#1314]
Since clangd supports the progress report in LSP 3.15 now, it would be nice to have an index progress indicator in the status bar.

Ref:
https://github.com/llvm/llvm-project/commit/7d20e80225b3e4f3f5a8c57929061bef55f3d855
https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/

**Comment by mattn** [comment]
You can do it.

https://github.com/micchy326/lightline-lsp-progress

**Comment by prabirshrestha** [comment]
This is already possible.
