### ISSUE TITLE
Can it surpport haskell?

### ISSUE THREAD

**Issue by hackingcat** [prabirshrestha/vim-lsp#132]
```
if executable('hie')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'hie',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'hie --lsp']},
        \ 'whitelist': ['haskell'],
        \ })
endif
```

**Comment by prabirshrestha** [comment]
It should be able to support any language servers. What is it that you are particularly asking for?

**Comment by liang-ting-chen** [comment]
I use the same configuration, and it (almost) works. However, as HIE responses typing information like

`Wed 25 Apr 17:57:34 2018:["<---",1,"hie",{"response":{"id":9,"result":[{"label":"fold","data":"fold module:Data.Map is:exact","kind":3,"detail":"forall a b k. (a -> b -> b) -> b -> Map k a -> b\nData.Map"},{"label":"foldWithKey","data":"foldWithKey module:Data.Map is:exact","kind":3,"detail":"forall k a b. (k -> a -> b -> b) -> b -> Map k a -> b\nData.Map"},`

the typing info does not show up when the auto completion pops up. 

I only use youcompleteme (YCM) through the built-in omnifunc, though.

**Comment by prabirshrestha** [comment]
Closing to cleanup. Please file new issue with details.
