### ISSUE TITLE
Command to show project errors

### ISSUE THREAD

**Issue by pdavydov108** [prabirshrestha/vim-lsp#133]
Hi @prabirshrestha! Some lsp servers (at least cquery) pushes diagnostics not only for the buffer that is now opened, but for all files in project. I often find myself recompiling the project to make sure that everything compiles, however cquery already provides all error messages, so instead of rebuilding the project I could just run a command that would show all of them as reported by cquery. What do you think about it? One good side effect from it would be that it would be possible to place error signs in buffers when they are opened, not waiting for language server to resend them again.

**Comment by mattn** [comment]
Some of language server does not send notification when errors are resolved. As far as I know, clangd does not send the notification. Language Server Specification seems not provide way to request send-back current diagnostics.

**Comment by tex** [comment]
Any progress on this? Would be good enough to supress diagnostic while in insert mode?

**Comment by ipkiss42** [comment]
> Some of language server does not send notification when errors are resolved. As far as I know, clangd does not send the notification. Language Server Specification seems not provide way to request send-back current diagnostics.

Even if not all language servers support this, when they do it is very useful because you can stay in the editor and fix everything, a bit as if you were calling `:make` (but with the usual advantages of LSP). This is one of the features I miss the most, particularly in statically-types languages like Rust.

I don't think this feature request should be auto-closed by a bot.

**Comment by prabirshrestha** [comment]
This is now possible via https://github.com/prabirshrestha/vim-lsp/pull/982. Please refer to the PR and docs on how to use it.
