### ISSUE TITLE
Something keeps setting shiftwidth=8, when I set it to 4

### ISSUE THREAD

**Issue by Hyperlynx2** [prabirshrestha/vim-lsp#1354]
After installing this plugin, seemingly at random when I work on a c++ file and I hit tab, I get \t\t instead of \t. Whenever this happens, I do `:shiftwidth` and it says `shiftwidth=8`.

My shiftwidth is 4, set in my vimrc. Something in this plugin is changing it, for whatever reason. The issue has only started happening since installing this plugin.

Very annoying!

**Comment by rhysd** [comment]
That's because your LSP server specifies indent size. Check format options of your C++ LSP server to modify the size to your favorite one.

https://github.com/prabirshrestha/vim-lsp/blob/296fb98d198cbbb5c5c937c09b84c8c7a9605a16/autoload/lsp/utils/buffer.vim#L68

**Comment by Hyperlynx2** [comment]
It seems to be getting set by various old syntax files I have that I haven't used or looked at in years, such as syntax/make.vim and syntax/vb.vim. However, I'm not editing a makefile or vb file. These files shouldn't have been sourced...
