### ISSUE TITLE
Buggy and glitchy inlay-hint when Vim's `set wrap` is enabled.

### ISSUE THREAD

**Issue by thingsiplay** [prabirshrestha/vim-lsp#1357]
When Vim has the `set wrap` mode enabled and linebreak occurs at end of window while an inlay-hint reaches that position, then the next lines are buggy. Vim no longer works correct until I make the window bigger so no linebreak happens anymore. Disabling wraps with `set nowrap` is obviously recommended and I just enabled it for a few days to test something else. So I noticed this bug.

Here some version and information about my system: In short I use standard Vim installed on Manjaro. I also have vim-lsp-settings installed and tested this with Rust source code using rust-analyzer. I updated the plugins and lsp-settings, so it is up to date.

```
# PLUGIN vim-lsp
# Enable LSP server during startup.
g:lsp_auto_enable = 1

# But disable diagnostics state for current buffer at default. This can be
# enabled later again, if needed. Reason to disable it is, if enabled initial
# loading is sometimes not correct. Otherwise I have to disable and enable with
# every new file to get correct syntax colors. I have created a function
# g:ToggleLSPDiagnostics() for that.
g:my_lsp_diagnostics_enabled = 1
call lsp#disable_diagnostics_for_buffer()
g:lsp_diagnostics_enabled = 1

# -1 to disable timout or use milliseconds
# Timout ms to abort FormatSync commands, as it could potentially slow down
# otherwise. Set to "-1" to disable timout.
# g:lsp_format_sync_timeout = 10
g:lsp_format_sync_timeout = 1000

# Enables additional semantic highlighting, where specific token are colored
# accordingly. Seems not to be working. More at ":h vim-lsp-semantic".
# Note: This option seems to make Vim very slow, especially on completion.
# So disable it. Note-note: It seems to be functioning normal now, so enabled
# it again.
# g:lsp_semantic_enabled = 1
# TODO: Disabled, because seems to be very slow, especially in Rust.
g:lsp_semantic_enabled = 0

# Inlay hints.
g:lsp_inlay_hints_enabled = 1
g:lsp_inlay_hints_mode = {
    'normal': ['always', '!curline'],
    'insert': ['always', '!curline'],
}
```

```
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28 kompiliert am Sep 01 2022 21:10:19)
Inklusive der Patches: 1-354
```

```
$ fetch
OS: Manjaro Linux x86_64
Kernel: 5.19.7-1-MANJARO
Uptime: 5 days, 10 hours, 25 mins
Packages: 2170 (pacman)[stable], 4 (flatpak)
Shell: zsh 5.9
Resolution: 2560x1440 @ 144Hz
DE: KDE Plasma 5.25.5
WM: Qtile 0.21.1.dev81+g67456def (X11)
Theme: breeze (GruvboxColors) [QT], Klaus [GTK2/3/4]
Icons: breeze [QT], Gruvbox [GTK2/3/4]
Font: Noto Sans (12pt) [QT], Noto Sans (12pt) [GTK2/3/4]
Cursor: default (24px)
Terminal: kitty
CPU: Intel Xeon E3-1230 v3 (8) @ 3.7GHz
GPU: NVIDIA GP104 [GeForce GTX 1070]
Memory: 4.67 GiB / 15.57 GiB (29%)
Disk: 134 GiB / 220 GiB (60%)
Locale: de_DE.UTF-8
```

**Comment by mattn** [comment]
Could you please take a screenshot? I'm guessing it's a bug of Vim (not vim-lsp)

**Comment by thingsiplay** [comment]
This isn't something I can show off with a screenshot. It looks normal on screenshot, but the behavior is buggy. But I try to explain what I mean. If the inlay-hint reaches the wrap point and a linebreak occurs, then going into insert mode in Vim will cause to insert into wrong line. And traversing on these lines (below the linebreak) will be buggy, like jumping up and down the lines as it cannot decide where it's correct. I hope this explains it a bit.

I will try to make a video screen capture and upload it to show it off. Will make a new reply here when it's done.

**Comment by thingsiplay** [comment]
Finally video screencast captured: https://odysee.com/@testing:ec5/vim-lsp-inlay-hints-problem-2022-09-18_18-27-17:6 (50 seconds long, problem begins after 40 seconds when I make window smaller).
