### ISSUE TITLE
Error E716: Key not present in Dictionary: linecount + 1

### ISSUE THREAD

**Issue by miyukic** [prabirshrestha/vim-lsp#1364]
OS Ubuntu22.04 on WSL2 on Windows11
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 19 2022 04:59:57)
Included patches: 1-2269, 3612, 3625, 3669, 3741

The following error occurs during the C ++ source editing using Clangd-12 using Vim.
```vim
match 1 of 53
Error detected while processing function <SNR>61_debounceTimeTimerCallback[1]..<SNR>61_tapSourceCallback[4]..<SNR>61_tapSourceCallback[1]..<lambda>46[1]..<SNR>89_set_signs[10]..<SNR>89_place_signs:
line    5:
E716: Key not present in Dictionary: linecount + 1
```

**Comment by csegarragonz** [comment]
I'm also running into this problem.
