### ISSUE TITLE
Rename broken for gopls

### ISSUE THREAD

**Issue by markuspeloquin** [prabirshrestha/vim-lsp#1384]
The error I'm seeing when I try to rename using :LspRename:

```
Thu 03 Nov 2022 12:55:51 PM PDT:["s:on_stdout client request on_notification() error", "Vim(let):E716: Key not present in Dictionary: \"start\"", "function <SNR>168_on_stdout_string[2]..<SNR>166_on_stdout[75]..<SNR>105_request_on_notification[3]..<SNR>106_createNext[1]..<SNR>106_subscribeSourceCallback[2]..<lambda>143[1]..<SNR>181_handle_rename_prepare, line 12"]
```

I tried tacking `['range']` onto the end of this line: https://github.com/prabirshrestha/vim-lsp/blob/0c8fda792177375ee90c03598adb1783c05bed83/autoload/lsp/ui/vim.vim#L283 and it worked. I've been told that a range may either be specified as `Range` or `{"range": Range}`. So I'm guessing that there's some normalization that happens to put it in both places.

I bisected commits and found that this commit was to blame:

https://github.com/prabirshrestha/vim-lsp/commit/a85b71bfc862753ee11ae5986d882bd9588b17a2

**Comment by studiome** [comment]
Thank you for this helpful comment, @markuspeloquin .  Dart LSP also works with this solution. I think it would  adapt all LSP.

**Comment by prabirshrestha** [comment]
could one of you help send a PR?

**Comment by studiome** [comment]
Thnak you for comment @prabirshrestha .  Could I create PR for this bug? Thank you   @markuspeloquin, too . This helped me so much.

**Comment by markuspeloquin** [comment]
@tsukkee

**Comment by tsukkee** [comment]
I found gopls rename works as expected when I set `prepareSupport` to `v:false`. 
https://github.com/prabirshrestha/vim-lsp/blob/0c8fda792177375ee90c03598adb1783c05bed83/autoload/lsp.vim#L589
I think this means gopls change the return value of prepare rename request according to `prepareSupport` capability.

So, possible workaround is modify `prepareSupport` by setting `g:lsp_get_supported_capabilities`.

And, vim-lsp code looks support prepare rename so I think vim-lsp should support both `Range` or `{"range": Range}` as @markuspeloquin said (also in [the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename)).

**Comment by tsukkee** [comment]
I tried to make PR #1386 to fix this.
Still in Draft PR since I don't care about tests right now.

**Comment by tsukkee** [comment]
I'm sorry but I missed #1385 .

**Comment by prabirshrestha** [comment]
fixed by https://github.com/prabirshrestha/vim-lsp/pull/1387
