### ISSUE TITLE
What's the best connector for php ?

### ISSUE THREAD

**Issue by pierreboissinot** [prabirshrestha/vim-lsp#139]
I read the wiki instructions to configure vim-lsp with [php-language-server](https://github.com/felixfbecker/php-language-server) and it seems working but I'm not satisfied because the process Php-language-server is eating 100% of my CPU at start when indexing and I suppose it crash after. So I tried to exclude some folder from indexing (like `node_modules` or even `vendor`) but actually it's not possible. There is an [issue](https://github.com/felixfbecker/php-language-server/issues/159) about that.
So I'm trying to use [vscode-intelephense](https://github.com/bmewburn/vscode-intelephense) but I don't know if it's possible to use it out of the box after a `npm install -g intelephense`.
Do you guys have any idea ?

At the moment I'm using [phpactor](https://github.com/phpactor/phpactor) and it works very well with async.vim since it uses omni completion. For me it's the best solution to bring IDE features to Vim.

Thank you for vim-lsp and have a nice day.

**Comment by prabirshrestha** [comment]
Based on the source code for vscode-intelephense, the language server is `https://github.com/bmewburn/intelephense-server`. You need to npm install that and point the lang server to that executable.

I don't use php so can't comment much on what is better.
