### ISSUE TITLE
Since patch 9.0.0993 vim-lsp causes frequent redraws

### ISSUE THREAD

**Issue by ilya-bobyr** [prabirshrestha/vim-lsp#1399]
Currently, vim-lsp calls `prop_type_delete()` on every update of a symbol reference.
Since Vim patch 9.0.0993 `prop_type_delete()` causes a full screen redraw (see https://github.com/vim/vim/issues/11666).

A PR to address this issue: https://github.com/prabirshrestha/vim-lsp/pull/1398

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/1397
