### ISSUE TITLE
vim-lsp with julia language server: KeyError: key "processId" not found

### ISSUE THREAD

**Issue by jbrea** [prabirshrestha/vim-lsp#140]
I am trying to get vim-lsp to talk to the [julia language server](https://github.com/JuliaEditorSupport/LanguageServer.jl). I filed an issue [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/262) already. But I tried now to manually add 'processId': 11111 [before this line](https://github.com/prabirshrestha/vim-lsp/blob/2f72235f1f508f8b72a4a3548a6e8bf310599241/autoload/lsp.vim#L334) (I didn't know what Id to take...) and get now the error
```
Tue 08 May 2018 10:31:15 PM CEST:["lsp#register_server","server registered","julia"]
Tue 08 May 2018 10:31:15 PM CEST:["s:on_text_document_did_open()",1,"julia","/home/j","file:///home/j/test.jl"]
Tue 08 May 2018 10:31:15 PM CEST:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"julia"},"message":"started lsp server successfully"}}]
Tue 08 May 2018 10:31:15 PM CEST:["--->",1,"julia",{"method":"initialize","params":{"rootUri":"file:///home/j","initializationOptions":{},"capabilities":{},"rootPath":"/home/j","processId":11111,"trace":"off"}}]
Tue 08 May 2018 10:31:22 PM CEST:["<---(stderr)",1,"julia",["INFO: RECEIVED: {\"method\":\"initialize\",\"jsonrpc\":\"2.0\",\"id\":1,\"params\":{\"rootUri\":\"file:///home/j\",\"initializationOptions\":{},\"capabilities\":{},\"rootPath\":\"/home/j\",\"processId\":11111,\"trace\":\"off\"}}",""]]
Tue 08 May 2018 10:31:22 PM CEST:["<---(stderr)",1,"julia",["INFO: ",""]]
Tue 08 May 2018 10:31:23 PM CEST:["on_stdout",1,"invalid content-length"]
Tue 08 May 2018 10:31:23 PM CEST:["<---(stderr)",1,"julia",["INFO: SENT: {\"id\":1,\"jsonrpc\":\"2.0\",\"result\":{\"capabilities\":{\"textDocumentSync\":1,\"hoverProvider\":true,\"completionProvider\":{\"resolveProvider\":false,\"triggerCharacters\":[\".\"]},\"signatureHelpProvider\":{\"triggerCharacters\":[\"(\"]},\"definitionProvider\":true,\"referencesProvider\":true,\"documentHighlightProvider\":false,\"documentSymbolProvider\":true,\"workspaceSymbolProvider\":true,\"codeActionProvider\":true,\"documentFormattingProvider\":true,\"documentRangeFormattingProvider\":false,\"renameProvider\":true,\"documentLinkProvider\":{\"resolveProvider\":false},\"executeCommandProvider\":{\"commands\":[]},\"experimental\":null,\"workspace\":{\"workspaceFolders\":{\"supported\":true,\"changeNotifications\":true}}}}}","INFO: ",""]]
Tue 08 May 2018 10:31:23 PM CEST:["s:on_exit",1,"julia","exited",-1]
```
Any ideas how to get vim-lsp talk with the julia language server?

**Comment by prabirshrestha** [comment]
Can you try adding `'processId': v:null` at the line number.

Based on the spec it says should be number or null. So could be a bug in vim-lsp. `processId: number | null;`

**Comment by jbrea** [comment]
Hi, thanks for response.

I tried your suggestion. Unfortunately it seems the julia language server expects currently a number (see [here](https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/559b3bbc7a9a8830cc49e91309154b435a18ed1a/src/protocol/configuration.jl#L137); I guess that has to be changed at some point on the side of the language server). For the moment I changed back the processId in vim-lsp to an arbitrary number (as above). Then, if I interpret the error log correctly, it is vim-lsp that throws the error "invalid content-length" on the returned message from the language server (see third row from bottom on previous comment in this issue).

**Comment by prabirshrestha** [comment]
Please provide logs. As for `processId` it is a bug in the server since it can be null.

**Comment by AtsushiSakai** [comment]
@jbrea Hi. Could you please share how did you setup vim-lsp and LanguageServer.jl? I want to try it based on latest version of it. Thanks.

**Comment by jbrea** [comment]
Sorry for that late response, it has been a while when I tried this, and I haven't tried it again now...

I think I used
```
autocmd User lsp_setup call lsp#register_server({
    \ 'name': 'pyls',
    \ 'cmd': {server_info->['pyls']},
    \ 'whitelist': ['python'],
    \ })
autocmd FileType python setlocal omnifunc=lsp#complete
autocmd User lsp_setup call lsp#register_server({
    \ 'name': 'julia',
    \ 'cmd': {server_info->['julialsp']},
    \ 'whitelist': ['julia'],
    \ })
autocmd FileType julia setlocal omnifunc=lsp#complete
let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')
```
with the content of `julialsp` (an executable in my search path)
```
#!/bin/bash
tee in.log | julia --startup-file=no --history-file=no -e 'println("starting"); import LanguageServer; server = LanguageServer.LanguageServerInstance(stdin, stdout, true); server.runlinter = true; run(server);' | tee out.log
```

**Comment by AtsushiSakai** [comment]
@jbrea I found the julialsp have to be this: (See: https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/327 )

```
#!/bin/bash
/Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia --startup-file=no --history-file=no -e 'println("starting"); using LanguageServer;using Pkg;import StaticLint;import SymbolServer;env_path = dirname(Pkg.Types.Context().env.project_file);debug = false;server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "", Dict()); server.runlinter = true; run(server);'
```

StaticLint and SymbolServer have to be installed before it.

However, It is not perfect. 
When I command LspStatus, Julia language server keep "starting" status, not become running status🤔.

**Comment by machakann** [comment]
@AtsushiSakai Probably, you need julia v1.0.3 aside the latest one. I could not get it work with v1.1.0 but succeeded with julia 1.0.3.

https://discourse.julialang.org/t/use-languageserver-jl-on-vim-8-1-with-vim-lsp-plugin/20601

**Comment by jbrea** [comment]
Awesome, thanks @machakann.
Most things seem to work on my Linux machine, except for `:LspRename` I get the error
`["s:on_stdout client request on_notification() error","Vim(for):E715: Dictionary required"]`.
Does renaming work for you?

**Comment by machakann** [comment]
@jbrea No. I tried but failed. This is the log corresponds to the rename action.

```
2019/02/09 22:55:56:["--->",1,"julia",{"method":"textDocument/rename","on_notification":"---funcref---","params":{"newName":"foo","textDocument":{"uri":"file:///C:/Users/username/test.jl"},"position":{"character":12,"line":1}}}]
2019/02/09 22:55:57:["<---(stderr)",1,"julia",["ERROR: LoadError: "]]
2019/02/09 22:55:58:["<---(stderr)",1,"julia",["KeyError: key LanguageServer.URI2(\"file:///C%3A/Users/username/test.jl\") not found","Stacktrace:"," [1] "]]
2019/02/09 22:55:58:["<---(stderr)",1,"julia",["getindex at .\\dict.jl:478 [inlined]"," [2] "]]
2019/02/09 22:55:58:["<---(stderr)",1,"julia",["find_references(::"]]
2019/02/09 22:55:58:["<---(stderr)",1,"julia",["LanguageServer.TextDocumentIdentifier, ::LanguageServer.Position, ::LanguageServer.LanguageServerInstance) at C:\\Users\\username\\.julia\\packages\\LanguageServer\\GNDpW\\src\\requests\\textDocument.jl:670"," [3] process(::LanguageServer.JSONRPC.Request{Val{"]]
2019/02/09 22:55:58:["<---(stderr)",1,"julia",["Symbol(\"textDocument/rename\")},LanguageServer.RenameParams}, ::LanguageServer.LanguageServerInstance) at C:\\Users\\username\\.julia\\packages\\LanguageServer\\GNDpW\\src\\requests\\textDocument.jl:704"," [4] run(::LanguageServer.LanguageServerInstance) at C:\\Users\\username\\.julia\\packages\\LanguageServer\\GNDpW\\src\\languageserverinstance.jl:46"," [5] top-level scope at none:0"," [6] include at .\\boot.jl:317 [inlined]"," [7] include_relative(::Module, ::String) at .\\loading.jl:1044"," [8] include(::Module, ::String) at .\\sysimg.jl:29"," [9] exec_options(::Base.JLOptions) at .\\client.jl:266"," [10] _start() at .\\client.jl:425","in expression starting at C:\\Users\\username\\Dropbox\\works\\julia\\startlanguageserver.jl:16",""]]
```

It seems that an error occurred internally. I will check in detail later. It should work because it is working in vscode, I think.

**Comment by prabirshrestha** [comment]
ProcessId is now sent to the server. https://github.com/prabirshrestha/vim-lsp/pull/325

**Comment by prabirshrestha** [comment]
processId is not sent. Please update to latest vim-lsp and the language server.
