### ISSUE TITLE
(Bug?) filetype cpp.doxygen not treated identically to cpp, even after registering provider

### ISSUE THREAD

**Issue by s-daveb** [prabirshrestha/vim-lsp#1413]
Hello, I've been encountering this bug for a while now, and wasn't sure under which repository to file this report.

I have a project that I've marked up and commented extensively with doxygen-style comments of the public API, and would like to use syntax highlighting to distinguish it from regular comments for internal development. 

The problem I encounter is that if I set my vim buffer's `ft` setting to `cpp.doxygen`, I get the following error when I call `:LspDefinition` or `:LspDeclaration`:

```
Retrieving definition not supported for filetype 'cpp.doxygen'
```

When I switch the buffer over to `ft=cpp`, it works as expected.  Since the difference between the two "filetypes" is just a syntax highlighting file, I suppose I could copy the cpp.doxygen syntax highlighting into my ~/.vim directory and try to replace the standard cpp highlighter

I'm not sure what I could be doing wrong. Please let me know if you can suggest anything. I've registered the provider and _included cpp.doxygen in its whitelist_, like so:
```
if executable(g:clangd_path)
	augroup lsp_clangd
		autocmd!
		autocmd User lsp_setup call lsp#register_server({
					\ 'name': 'clangd',
					\ 'cmd': {server_info->[g:clangd_path, '--background-index', '--suggest-missing-includes', '-j=2']},
					\ 'whitelist': ['c', 'cpp', 'cpp.doxygen', 'objc', 'objcpp'],
					\ })
		autocmd FileType c setlocal omnifunc=lsp#complete
		autocmd FileType cpp setlocal omnifunc=lsp#complete
		autocmd FileType cpp.doxygen setlocal omnifunc=lsp#complete
		autocmd FileType objc setlocal omnifunc=lsp#complete
		autocmd FileType objcpp setlocal omnifunc=lsp#complete
	augroup end
endif
```

**Comment by prabirshrestha** [comment]
Please provide logs. https://github.com/prabirshrestha/vim-lsp#debugging
