### ISSUE TITLE
Unexpected line break

### ISSUE THREAD

**Issue by ryicoh** [prabirshrestha/vim-lsp#1415]
There is an unexpected line wrap between lines 5 and 6 as show in the image below.

<img width="831" alt="Screen Shot 2023-01-12 at 11 05 54" src="https://user-images.githubusercontent.com/37844673/211958617-fc58bb14-becd-4f56-957d-0d2621e77cf5.png">

## Reproducing

Minimum vimrc:

```vim
" vimrc_lsp.vim
set number
packadd vim-lsp
packadd vim-lsp-settings

let g:lsp_diagnostics_virtual_text_enabled = 1
let g:lsp_diagnostics_virtual_text_align = 'after'
let g:lsp_diagnostics_virtual_text_wrap = 'truncate'
autocmd BufNewFile,BufRead *.tsx set filetype=typescriptreact
```

Target code:
```bash
export function Document() {
  return "hello"
}

 have a good idea that add option to disable lsp_diagnostics_float_cursor in insert mode.
```

```bash
% vim -N -u vimrc_lsp.vim
```

Environment: 

```bash
% vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 26 2022 13:51:26)
macOS version - arm64
Included patches: 1-1100
Compiled by Homebrew
```

**Comment by ryicoh** [comment]
I will try to resolve it.

**Comment by ryuichiroh** [comment]
I found that the cause is that both virtual text and diagnostic highlighting are enabled. So if disable highlighting, it will be able to be fixed.

```vim
" write to your vimrc
let g:lsp_diagnostics_highlights_enabled = 0
```

<img width="837" alt="Screen Shot 2023-01-13 at 0 36 38" src="https://user-images.githubusercontent.com/121105839/212110992-b6c39694-67b4-4b39-a020-f15ecb5c9d08.png">

**Comment by ryuichiroh** [comment]
Line 5 has only 88 lines, but the `col` of `prop_add()` is 89!

```vim
" log
prop_add(5, 89, {'bufnr': 1, 'end_lnum': 5, 'type': 'vim_lsp_diagnostics_highlights_LspError', 'end_col': 89})
```

https://github.com/prabirshrestha/vim-lsp/blob/500987604d356738068ee3bf320a82dfa9fbfc1f/autoload/lsp/internal/diagnostics/highlights.vim#L167-L175

https://github.com/prabirshrestha/vim-lsp/pull/721

> If someone wants to create lsp#utils#range#is_valid_for_buffer(range, buffer) before calling prop_add feel free to send a PR.

I have reached this point.
