### ISSUE TITLE
support for CompletionItem textEdit

### ISSUE THREAD

**Issue by CantGetRight82** [prabirshrestha/vim-lsp#142]
Very excited about your plugin, thanks a lot!

In my testing, CompletionItems with a textEdit property still use the label as the final completion.

`
{
	label:'some label",
	textEdit:{
		range: {
			start: { line:0, character:0 },
			end: { line:0, character:10 }
		},
		newText:'LSP is awesome'
	}
}
`

I would expect 'some label' to be completed as 'LSP is awesome' somewhere in the file.
Is this not supported? Any plans or ideas on how to implement it?

**Comment by mkwork** [comment]
I've done initial omni configuration in my [fork](https://github.com/mkwork/vim-lsp/tree/feature/complete-config), but I have no time to write the docs at least last month :(

**Comment by prabirshrestha** [comment]
Once codeaction PR https://github.com/prabirshrestha/vim-lsp/pull/162 gets merged we could try this

**Comment by MaskRay** [comment]
#162 has been merged. I'd like to remove `insertText` from ccls once vim-lsp supports `textEdit`... JSON serialization is slow and the server should not send too many `CompletionItem` properties to the client.

**Comment by prabirshrestha** [comment]
vim-lsp already supports this. Closing to cleanup stale issues.
