### ISSUE TITLE
Diagnostics in a split window can push text onto visibly unreachable lines

### ISSUE THREAD

**Issue by myobie** [prabirshrestha/vim-lsp#1424]
In a single window, I cannot reproduce this problem. In a split window, I can reproduce in a window showing more than one type of diagnostic. The issue is the text is rendered visibly different than where vim expects me to edit. If I move to a line, say `33G` the cursor will end up being visually on `32`, but edits to the line will will end up on `33` and will visually change on the screen in a different location than my cursor.

I recorded a screencast to help illustrate the issue.

https://user-images.githubusercontent.com/179/214160828-b57e94f6-94ab-4926-b125-c68275674c1a.mov

**Comment by wtsnjp** [comment]
I have the same problem with my local PC (Vim 9.0.1350, macOS 12.6).

It seems this happens after 3f6e23f.

**Comment by myobie** [comment]
Ah, thanks @wtsnjp I was looking for the name of of the setting. I do like the virtual text and hope it can work in vim9 soon.
