### ISSUE TITLE
Auto-run diagnostics / sort diagnostics

### ISSUE THREAD

**Issue by redcartel** [prabirshrestha/vim-lsp#144]
Is it possible to automatically run diagnostics on open & write?

Is it possible to sort the output by error severity or which checker generated the alert?

Looking to get behavior similar to syntastic.

**Comment by prabirshrestha** [comment]
Can you share how syntastic does it? Is it by flags to commands? Shortcut keys?

**Comment by yunusemrecan** [comment]
I don't know vimscript but I find that from ale(another linting plugin).
`
            if g:ale_lint_on_enter
                autocmd BufWinEnter * call ale#events#LintOnEnter(str2nr(expand('<abuf>')))
                " Track when the file is changed outside of Vim.
                autocmd FileChangedShellPost * call ale#events#FileChangedEvent(str2nr(expand('<abuf>')))
            endif`

**Comment by prabirshrestha** [comment]
closing to clean up stale issues.
