### ISSUE TITLE
Please enable scrollbar for popup windows 

### ISSUE THREAD

**Issue by lantw44** [prabirshrestha/vim-lsp#1457]
Reopen https://github.com/prabirshrestha/vim-lsp/issues/1368 by copy-pasting.
Related pull request: https://github.com/prabirshrestha/vim-lsp/pull/1406.

The popup window showed by `LspHover` can be scrolled with `lsp#scroll`, but it doesn't show a scrollbar. Can it be modified to show a scrollbar, so users can know the window can be scrolled? It seems it can be done by removing `'scrollbar': 0` from `autoload/vital/_lsp/VS/Vim/Window/FloatingWindow.vim`.

**Comment by prabirshrestha** [comment]
Please try the latest master.
