### ISSUE TITLE
How can I go to definition of a specific function not in cursor

### ISSUE THREAD

**Issue by littlecarpenter** [prabirshrestha/vim-lsp#1487]
Just like cscope,   :cs f g ***

**Comment by littlecarpenter** [comment]
And how to solve regex search issue?

**Comment by prabirshrestha** [comment]
You can try `LspDocumentSymbol`, `LspDocumentSymbolSearch` or `LspWorkspaceSymbolSearch` if the LSP server supports it. Usually it isn't regex but you can search and narrow it down.

**Comment by littlecarpenter** [comment]
> You can try `LspDocumentSymbol`, `LspDocumentSymbolSearch` or `LspWorkspaceSymbolSearch` if the LSP server supports it. Usually it isn't regex but you can search and narrow it down.


If I want to search a function like get_os， How can I input in command mode to pass a parameter to search?


:LspReferences get_os
CAN NOT be supportted

**Comment by littlecarpenter** [comment]
> > You can try `LspDocumentSymbol`, `LspDocumentSymbolSearch` or `LspWorkspaceSymbolSearch` if the LSP server supports it. Usually it isn't regex but you can search and narrow it down.
> 
> If I want to search a function like get_os， How can I input in command mode to pass a parameter to search?
> 
> :LspReferences get_os CAN NOT be supportted


@prabirshrestha How to pass a parameter to search in command mode?
