### ISSUE TITLE
Snippets in menu

### ISSUE THREAD

**Issue by damonmccain** [prabirshrestha/vim-lsp#1489]
I can't get snippets to show in autocomplete menu but the snippet executes with tab.
I know the snippet is there but it doesn't show up in the menu.
Forgot to mention I"am using plugin's for snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'thomasfaingnaert/vim-lsp-snippets'
Plug 'thomasfaingnaert/vim-lsp-ultisnips'

**Comment by prabirshrestha** [comment]
I don't own any of those plugins. I use https://github.com/prabirshrestha/asyncomplete.vim with https://github.com/hrsh7th/vim-vsnip.
