### ISSUE TITLE
How to change when the document is analyzed?

### ISSUE THREAD

**Issue by jackmott** [prabirshrestha/vim-lsp#151]
By default it appears every time I type, the language server fires  and analyzes the document.  Can I disable that and map it to a key instead?

**Comment by prabirshrestha** [comment]
By analyze do you mean diagnostics used for LspDiagnostics?

It shouldn't be fired when we type. are you sure this is true? It fires when textDocument/didChange occurs and this happens when asyncomplete needs to trigger completion or when you save the file.

**Comment by prabirshrestha** [comment]
There are no plans to expose this. It is currently debounced. you can instead disable the feature.
