### ISSUE TITLE
Can't get it to work with solargraph

### ISSUE THREAD

**Issue by bbtdev** [prabirshrestha/vim-lsp#152]
**vim-lsp.log**

> Sat Jul  7 18:10:05 2018:["lsp#register_server", "server registered", "solargraph"]
> Sat Jul  7 18:10:05 2018:["s:on_text_document_did_open()", 4, "ruby", "/Users/bogdan/Documents/Projects/zuppler/zuppler-accounts", "file:///Users/bogdan/Documents/Projects/my_prokect/models/account.rb"]
> Sat Jul  7 18:10:05 2018:[{"response": {"data": {"__data__": "vim-lsp", "lsp_id": 3, "server_name": "solargraph"}, "message": "started lsp server successfully"}}]
> Sat Jul  7 18:10:05 2018:["--->", 3, "solargraph", {"method": "initialize", "params": {"rootUri": "file:///Users/bogdan/Documents/Projects/", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/bogdan/Documents/Projects/", "trace": "off"}}]
> Sat Jul  7 18:10:07 2018:["<---(stderr)", 3, "solargraph", ["Could not find command \"stdio\".", ""]]
> Sat Jul  7 18:10:07 2018:["<---(stderr)", 3, "solargraph", [""]]
> Sat Jul  7 18:10:07 2018:["s:on_exit", 3, "solargraph", "exited", 0]
> Sat Jul  7 18:10:08 2018:["s:on_text_document_did_change()", 4]
> Sat Jul  7 18:10:08 2018:[{"response": {"data": {"__data__": "vim-lsp", "lsp_id": 4, "server_name": "solargraph"}, "message": "started lsp server successfully"}}]
> Sat Jul  7 18:10:08 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "waiting for lsp server to initialize"}}]
> Sat Jul  7 18:10:09 2018:["<---(stderr)", 4, "solargraph", ["Could not find command \"stdio\".", ""]]
> Sat Jul  7 18:10:09 2018:["<---(stderr)", 4, "solargraph", [""]]
> Sat Jul  7 18:10:09 2018:["s:on_exit", 4, "solargraph", "exited", 0]

**Minimal init.vim**

> call plug#begin('~/.vim/plugged')
> Plug 'prabirshrestha/async.vim'
> Plug 'prabirshrestha/vim-lsp', { 'branch': 'dev' }
> Plug 'prabirshrestha/asyncomplete.vim'    " optional only required for autocompletion
> Plug 'prabirshrestha/asyncomplete-lsp.vim' " when server is initialized and it supports completion, asyncomplete source is automatically registered. no need to call asyncomplete#register_source in .vimrc
> 
> call plug#end()
> 
> let g:lsp_log_verbose = 1
> let g:lsp_log_file = expand('~/vim-lsp.log')
> 
> " for asyncomplete.vim log
> let g:asyncomplete_log_file = expand('~/asyncomplete.log')
> 
> au User lsp_setup call lsp#register_server({
>      \ 'name': 'solargraph',
>      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
>      \ 'whitelist': ['ruby'],
>      \ })
> 
> inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
> inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
> inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
>

**Comment by bzf** [comment]
@bbtdev Did you manage to solve this? 😄

**Comment by megalithic** [comment]
@bbtdev / @prabirshrestha - PLEASE respond if you solved this, especially since you closed it.

I'm having issues as well, though not entirely identical to yours:

```
Fri Aug  3 15:01:00 2018:["lsp#register_server", "server registered", "solargraph"]
Fri Aug  3 15:01:00 2018:["vim-lsp signs enabled"]
Fri Aug  3 15:01:00 2018:["s:on_text_document_did_open()", 1, "ruby", "/Users/me/code/first/brainy", "file:///Users/me/code/thing/app/helpers/application_helper.rb"]
Fri Aug  3 15:01:00 2018:[{"response": {"data": {"__data__": "vim-lsp", "lsp_id": 4, "server_name": "solargraph"}, "message": "started lsp server successfully"}}]
Fri Aug  3 15:01:00 2018:["--->", 4, "solargraph", {"method": "initialize", "params": {"rootUri": "file:///Users/me/code/thing", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/me/code/thing", "trace": "off"}}]
Fri Aug  3 15:01:02 2018:["<---(stderr)", 4, "solargraph", ["Solargraph is listening on stdio PID=66636"]]
Fri Aug  3 15:01:02 2018:["<---(stderr)", 4, "solargraph", ["", ""]]
Fri Aug  3 15:01:12 2018:["on_stdout", 4, "invalid content-length"]
Fri Aug  3 15:02:02 2018:["s:on_text_document_did_change()", 1]
Fri Aug  3 15:02:02 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "server already started"}}]
Fri Aug  3 15:02:02 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "waiting for lsp server to initialize"}}]
Fri Aug  3 15:02:10 2018:["s:on_text_document_did_change()", 1]
Fri Aug  3 15:02:10 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "server already started"}}]
Fri Aug  3 15:02:10 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "waiting for lsp server to initialize"}}]
```

Any one else get solargraph via `stdio` working with vim-lsp? if so, PLEASE do tell how.
