### ISSUE TITLE
No semantic highlight with pylsp

### ISSUE THREAD

**Issue by kalium222** [prabirshrestha/vim-lsp#1530]
Hello, I got some problem when working with python environment. Here is how I config relative plugins:
```vimscript
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'  

" register clangd
if executable('clangd')
    au User lsp_setup call lsp#register_server({
    \ 'name': 'clangd',
    \ 'cmd': {server_info->['clangd', '-background-index']},
 	\ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
    \ })
endif

" register pylsp
if executable('pylsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pylsp',
        \ 'cmd': {server_info->['pylsp']},
        \ 'allowlist': ['python'],
        \ })
endif   

" enable sementic highlighting
let g:lsp_semantic_enabled = 1

```

And I get `pylsp` by running `pip install "python-lsp-server[all]"`, which should be OK from [here](https://github.com/python-lsp/python-lsp-server).

And here is a comparison with semantic highlight for cpp with clangd.

**Comment by kalium222** [comment]
![Screenshot from 2024-01-27 01-18-14](https://github.com/prabirshrestha/vim-lsp/assets/71812006/13f2b3b8-d929-4865-b912-0b11f735a4ec)

**Comment by kalium222** [comment]
How to solve this? Thanks.

**Comment by prabirshrestha** [comment]
You would want to look at the logs and see if it is enabled or not. Instructions in readme. Feel free to share the logs if you are still having issues.

**Comment by kalium222** [comment]
The non-verbose log of these two files were similar, so i will show you the verbose version. They are quite long. 
In the log for python, the researching result for "semantic" is two, which is much less than that in log for cpp.
[Uploading py_v.log…]()

**Comment by kalium222** [comment]
In comparison, it is log for cpp file: [cpp_v.log](https://github.com/prabirshrestha/vim-lsp/files/14137913/cpp_v.log)

**Comment by kalium222** [comment]
in fact i find that the output of `:LspSemanticTokenModifer` is `[]`. Doesn't `pylsp` support for semantic tokens?
