### ISSUE TITLE
Can vim-lsp display function name when calling LspReferences?

### ISSUE THREAD

**Issue by fiddleyuan** [prabirshrestha/vim-lsp#154]
Now when calling LspReferences, all occurrences are displayed in context format. Can vim-lsp display caller function name instead? Can we add more options to customize the display content such that we can choose to display the context, or caller function name, or both?

BTW, I'm using cquery for a C++ project, thanks

**Comment by prabirshrestha** [comment]
One option would be to provide an option to override such as call `format_lsp_references(references)` for the entire list and user can do what ever they want to do with it.

```vim
au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ 'format_lsp_references': function('s:Format_lsp_references')
        \ })
```

**Comment by fiddleyuan** [comment]
Thanks, Prabir, when can we expect this option to be available? :)

Also, I'll be very appreciated if you would consider including a option to turn true/false includeDeclaration vlaue. Now this value is by default set to false in LspReferences's implementation.

**Comment by mattn** [comment]
LspReferences add functions into quickfix on vim. So you can get them by getqflist().
