### ISSUE TITLE
Bug: Updating buffer (open, reload) creates duplicated server-side content when multiple LSP servers are enabled

### ISSUE THREAD

**Issue by rgoya** [prabirshrestha/vim-lsp#1547]
## Summary
When loading or updating the contents of a file (e.g. `:e`), `vim-lsp` correctly sends the full content to the file to the first LSP registered server, but erroneously tells subsequent servers that the file has had changes. This causes the subsequent LSP servers to have a warped view of what the file contents are.

In some cases the only effect will be an overloaded list of diagnostics, (e.g. when no code actions are requested).  In other cases, like requesting `:LspDocumentFormat`, the server will return its own warped version of the file, leaving the user with a buffer containing multiple copies of the actual content.

A suggested fix is provided in an accompanying PR (#1548)

## Setup
Tell `vim-lsp` to start both `ruff` and `pyright` servers:
```vim
let g:lsp_settings_filetype_python = ['pyright-langserver', 'ruff-lsp']
```
The formatting step in the reproduction below will work only when `ruff` is assigned the second slot int he server list; however, the duplication of diagnostics should also show up for `pyright` if that is the one assigned the second slot.

Create a test file that will trigger some diagnostics for both servers. The following has unused imports (`ruff fix`),  extra blank lines (`ruff format`) and unknown module (`pyright`):
```python
import pandas


import numpi
```

## Reproduce

The initial opening of the file correctly identifies the issues of the simple file:
![image](https://github.com/prabirshrestha/vim-lsp/assets/5192495/b7205a01-5853-44ae-a232-56b8f7c5abf8)

Executing `:e` on the file once causes `ruff` to start hallucinating, while `pyright` is doing well:
![image](https://github.com/prabirshrestha/vim-lsp/assets/5192495/7b6b6e9f-94c5-4e8b-8fe9-056c411f75ea)

And this continues as we reload the file:
![image](https://github.com/prabirshrestha/vim-lsp/assets/5192495/f18b4917-a3b4-4f2e-93b0-179c9acd8b1d)

Asking for `:LspDocumentFormat`, which is executed by `ruff`, results in a very different buffer, caused by `ruff` imposing its perceived reality onto the developer:
![image](https://github.com/prabirshrestha/vim-lsp/assets/5192495/cb479f74-3565-48e7-9b24-e7b97f0ee748)

## Debug
The offending line can be found in the function `s:text_changes(buf, server_name)` in the following line:
https://github.com/prabirshrestha/vim-lsp/blob/f7ccf006df1aefd327c0e2c55cc8632a2db577c1/autoload/lsp.vim#L752-L754

When the first LSP server is being sent the data `s:file_content` does not have an entry for the buffer yet, and is correctly sent the full content: https://github.com/prabirshrestha/vim-lsp/blob/f7ccf006df1aefd327c0e2c55cc8632a2db577c1/autoload/lsp.vim#L765-L768

When the second LSP server is being sent the data, the condition is met and the diff is sent. However, the check is not making the distinction of which LSP server is actually being updated, a distinction that should be meade given the expected content of `s:file_content`:
https://github.com/prabirshrestha/vim-lsp/blob/f7ccf006df1aefd327c0e2c55cc8632a2db577c1/autoload/lsp.vim#L9-L20

## Fix
The fix seems to be simple, just add a statement to the condition statement to ensure the right server is being evaluated and updated, change:
https://github.com/prabirshrestha/vim-lsp/blob/f7ccf006df1aefd327c0e2c55cc8632a2db577c1/autoload/lsp.vim#L752-L754
to:
```vim
   if l:sync_kind == 2 && has_key(s:file_content, a:buf) && has_key(s:file_content[a:buf], a:server_name)
```

**Comment by prabirshrestha** [comment]
This is now fixed. Thanks for the detailed issue as well as the PR fix.
