### ISSUE TITLE
Prettier & ESLint

### ISSUE THREAD

**Issue by EliphazBouye** [prabirshrestha/vim-lsp#1563]
I want to know if it's possible to use Prettier and ESLint with `vim-lsp` ? for code formating

**Comment by prabirshrestha** [comment]
you can use it via https://github.com/mattn/efm-langserver.

https://github.com/prabirshrestha/dotfiles/blob/f118c4c4e7c0cc3156ac88df698c5cee1715ef22/.vimrc#L326C1-L331C3

https://github.com/prabirshrestha/dotfiles/blob/main/.config/efm-langserver/config.yaml
