### ISSUE TITLE
vim-lsp not listed on https://langserver.org/

### ISSUE THREAD

**Issue by tim-seoss** [prabirshrestha/vim-lsp#159]
There are currently three vim plugins listed at https://langserver.org/#implementations-client , but not vim-lsp.

Perhaps consider submitting a PR via https://github.com/langserver/langserver.github.io/issues/5 ?

I'm not completely certain of the vim-lsp feature support, so I haven't done-so.

**Comment by prabirshrestha** [comment]
Feel free to submit it if you would like too. Else I can submit sometime in the future.

**Comment by tim-seoss** [comment]
Can I check you're happy with this?  https://github.com/tim-seoss/langserver.github.io  If-so, I'll submit a PR to that repo...

**Comment by prabirshrestha** [comment]
Looks good

**Comment by prabirshrestha** [comment]
Thanks.
