### ISSUE TITLE
Unable to get solargraph stdio working with vim-lsp

### ISSUE THREAD

**Issue by megalithic** [prabirshrestha/vim-lsp#163]
So, basically, I've added [`solargraph`](https://github.com/castwide/solargraph) to the LSP mix in my setup, since `solargraph` added support for `stdio` to be used with LSP implementations in editors (yay).

I see that in the `vim-lsp.log` file listed below that it is indeed starting solargraph and obtaining a pid, but looks like STDOUT is puking on itself and I'm just not sure where to look for this.

I haven't tried with LanguageClient-neovim yet, but may resort to trying that to see if it's an issue with solargraph specifically.

Any suggestions or other debugging tricks I can use?

Thanks!

#### environment info
- macos: 10.13.6
- neovim: 0.3.1
- vim-lsp: up-to-date with HEAD as of posting of this issue
- ncm2: up-to-date with HEAD as of posting of this issue
- kitty: 0.11.3
- tmux: 2.7
- zsh: 5.5.1
- neovim-ruby-host: 0.7.1
- ruby: 2.3.7
- solargraph: 0.26.3

#### vim-lsp config
```
  let g:lsp_auto_enable = 1
  let g:lsp_signs_enabled = 1         " enable diagnostic signs / we use ALE for now
  let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
  let g:lsp_signs_error = {'text': '✖'}
  let g:lsp_signs_warning = {'text': '~'}
  let g:lsp_signs_hint = {'text': '?'}
  let g:lsp_signs_information = {'text': '!!'}
  let g:lsp_log_verbose = 1
  let g:lsp_log_file = expand('~/.config/nvim/vim-lsp.log')
  if executable('solargraph')
    au User lsp_setup call lsp#register_server({
          \ 'name': 'solargraph',
          \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
          \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'Gemfile'))},
          \ 'whitelist': ['ruby', 'eruby'],
          \ })
  endif
```

#### vim-lsp.log output
```
Fri Aug  3 15:01:00 2018:["lsp#register_server", "server registered", "solargraph"]
Fri Aug  3 15:01:00 2018:["vim-lsp signs enabled"]
Fri Aug  3 15:01:00 2018:["s:on_text_document_did_open()", 1, "ruby", "/Users/me/code/first/brainy", "file:///Users/me/code/thing/app/helpers/application_helper.rb"]
Fri Aug  3 15:01:00 2018:[{"response": {"data": {"__data__": "vim-lsp", "lsp_id": 4, "server_name": "solargraph"}, "message": "started lsp server successfully"}}]
Fri Aug  3 15:01:00 2018:["--->", 4, "solargraph", {"method": "initialize", "params": {"rootUri": "file:///Users/me/code/thing", "initializationOptions": {}, "capabilities": {}, "rootPath": "/Users/me/code/thing", "trace": "off"}}]
Fri Aug  3 15:01:02 2018:["<---(stderr)", 4, "solargraph", ["Solargraph is listening on stdio PID=66636"]]
Fri Aug  3 15:01:02 2018:["<---(stderr)", 4, "solargraph", ["", ""]]
Fri Aug  3 15:01:12 2018:["on_stdout", 4, "invalid content-length"]
Fri Aug  3 15:02:02 2018:["s:on_text_document_did_change()", 1]
Fri Aug  3 15:02:02 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "server already started"}}]
Fri Aug  3 15:02:02 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "waiting for lsp server to initialize"}}]
Fri Aug  3 15:02:10 2018:["s:on_text_document_did_change()", 1]
Fri Aug  3 15:02:10 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "server already started"}}]
Fri Aug  3 15:02:10 2018:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "solargraph"}, "message": "waiting for lsp server to initialize"}}]
```

Any one else get solargraph via `stdio` working with vim-lsp? if so, PLEASE do tell how.

**Comment by megalithic** [comment]
UPDATE:  `solargraph stdio` looks to be working with as an LS for `LanguageClient-neovim`. :/

So, unfortunately, it appears to be an issue with `vim-lsp`; @prabirshrestha any chance you'd be able to give `solargraph` a try in your own `vim-lsp` config and see if things work as expected for you?

**Comment by prabirshrestha** [comment]
I dont have a ruby env. So if you have installation scripts or a docker dev env with dependencies installed I could try it out. Or could also be homebrew instructions for mac.

Please also include a sample ruby project.

**Comment by megalithic** [comment]
@prabirshrestha 

```rb
class Example
  # The example method
  #
  # @return [String]
  def give_me_things
    ["things"]
  end
end
```

The most useful action now would be to do something like `Example.new.` in a new file or in that existing file and this should result in a class method member in the autocomplete menu of `give_me_things` and it should show the return type of `[String]`.

To install ruby via homebrew can just be: `brew install ruby@2.3.7`

I hope this is sufficient, please let me know.

Thanks so much for your time, @prabirshrestha!

**Comment by megalithic** [comment]
@prabirshrestha or anyone else have any thoughts to the above? HUGE thanks.

**Comment by prabirshrestha** [comment]
@megalithic  Seems to work for me.

![image](https://user-images.githubusercontent.com/287744/43753827-7ef56126-99bc-11e8-8d9f-1adee7c74c01.png)

Are you using some sort of encoding for the file?

I used the same ruby version that came with mac. 

```sh
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
$ bundler --version
Bundler version 1.16.1
$ solargraph --version
0.23.6
$ nvim --version
NVIM v0.3.2-37-g5f15788dc
```

**Comment by megalithic** [comment]
@prabirshrestha might you share your vimrc/init.vim setup? i'd LOVE to get to the bottom of this. i'm using nvim 0.3.1 stable, but may switch to `HEAD` and see if something there changed. 

Thanks again for your time.

**Comment by castwide** [comment]
Solargraph gem v0.24.0 fixes a problem that caused malformed server messages in certain cases. See castwide/solargraph#79 for more information.
