### ISSUE TITLE
Option to open :LspDefinition in a split

### ISSUE THREAD

**Issue by ghost** [prabirshrestha/vim-lsp#169]
Hello,

Love your plugin especially the fact that it is written in vim script. However, one of the feature I'd like to use is jumping to a definition in a split. Language client provides this feature:
https://github.com/autozimu/LanguageClient-neovim/wiki/Goto-definition-in-a-split 

Note that this is not the same as doing: `:sp<CR> :LspDefinition<CR>` 
The above way would open up a split even if lsp was unable to find the definition which is not what I want. I only want to split if the definition exists.

This should be easy to do. Its the only feature I miss moving over from LanguageClient. I'd really appreciate it if you can put this option in  (pretty please).

**Comment by andyl** [comment]
Also: jump to a definition in a tab would be great.

**Comment by andyl** [comment]
Here's a workaround - put this in `.vimrc`

    nmap \gd :LspDefinition<cr>
    nmap \gt :tab split<cr>:LspDefinition<cr>
    nmap \gs :sp<cr>:LspDefinition<cr>
    nmap \gv :vsp<cr>:LspDefinition<cr>

**Comment by prabirshrestha** [comment]
This is now possible with `<mod>` which is the vim way. https://github.com/prabirshrestha/vim-lsp/pull/776

Examples:
usage:

`:leftabove LspDefinition` Splits horizontally and opens a window to the above.
`:rightbelow vertical LspDefinition` Splits vertically and opens a window to the right.
`:tab LspDefinition` Opens a window to the new tabpage.
