### ISSUE TITLE
[Question] Howto use lsp properly

### ISSUE THREAD

**Issue by tuyenpm9** [prabirshrestha/vim-lsp#172]
I still have some confusion about using lsp correctly. If I install for example `npm install -g flow-language-server` to install flow server globally, then do I need to install `flow` binary in local or global to enable all features of flow server: autocompletion, linter, go to definition ..etc?

I noticed that I can run `flow-language-server` in cmd

gvim 1-296 / windows10

**Comment by prabirshrestha** [comment]
You can refer to the wiki on how to use servers properly. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Flow

**Comment by prabirshrestha** [comment]
I believe flow language server auto download flow binaries if not installed.

**Comment by tuyenpm9** [comment]
If so, did it link `flow-language-server` to `flow` binary? I couldn't execute `flow` in cmd.

**Comment by prabirshrestha** [comment]
You will need to check the source. Last time I had checked it was smart enough to download. It did have bug on windows that they fixed.
