### ISSUE TITLE
LspNextError and LspPreviousError not working

### ISSUE THREAD

**Issue by phcerdan** [prabirshrestha/vim-lsp#173]
`LspNextError` and `LspPreviousError` does not work for me, either with errors or with warnings.

I use `:LspDocumentDiagnostics` and then navigate with `:cnext` `:cprevious` or `]q` `[q` if using vim-unimpaired

Related: #171

**Comment by phcerdan** [comment]
It might be worth exploring to populate the quickfix list automatically, instead of using LspNextError.

**Comment by ezyang** [comment]
Yes, I'd also appreciate if Quickfix were populated automatically. And I also report LspNextError and co do not work.

**Comment by casr** [comment]
> LspNextError and LspPreviousError does not work for me, either with errors or with warnings.

This appears to be working for me on the latest verion. @phcerdan Can you confirm?

> It might be worth exploring to populate the quickfix list automatically

This might be confusing to do out of the box as the quickfix can be used for a number of things. What about adding this to your `.vimrc`?
```vim
autocmd CursorHold call lsp#ui#vim#diagnostics#document_diagnostics()
```

**Comment by prabirshrestha** [comment]
Please try the latest master. It should be working now.
