### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by raz0r89** [prabirshrestha/vim-lsp#182]
I followed instructions on README to start use vim-lsp, and it worked before. After I did something, my vim gives me following error message, and it looks like it comes from the statements for registering cquery in .vimrc. Anyone knows what happened?

Error detected while processing function lsp#enable[12]..<SNR>57_register_events[9]..<SNR>57_on_text_document_did_open[4]..<SNR>57_ensure_flush[1]..lsp#utils#step#start[1]..<SNR>59_next[9]..<lambda>3[1]..
<SNR>57_ensure_start[39]..<SNR>59_callback[1]..<SNR>59_next[9]..<lambda>4[1]..<SNR>57_ensure_init[48]..<SNR>57_send_request[7]..lsp#client#send_request[1]..<SNR>60_lsp_send[24]..async#job#send[1]..<SNR>61
_job_send[6]..<SNR>61_flush_vim_sendraw:
line    5:
E631: ch_sendraw(): write failed
Press ENTER or type command to continue

**Comment by prabirshrestha** [comment]
Can you paste full logs. Feel free to tryin in a demo source code. Also mention vim version and os.

**Comment by raz0r89** [comment]
Hey @prabirshrestha , thanks for quick response. I enabled log. And here's the log content:
2018年09月20日 星期四 11时02分46秒:["lsp#register_server","server registered","cquery"]
2018年09月20日 星期四 11时02分46秒:["s:on_text_document_did_open()",1,"cpp","/home/shide/media_build","file:///home/shide/media_build/media_server_vos/udp1/outgoing_video_stream.h"]
2018年09月20日 星期四 11时02分46秒:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"cquery"},"message":"started lsp server successfully"}}]
2018年09月20日 星期四 11时02分46秒:["--->",1,"cquery",{"method":"initialize","params":{"rootUri":"file:///home/shide/media_build","initializationOptions":{"cacheDirectory":"/home/shide/.cquery-cache"},"capabilities":{},"rootPath":"/home/shide/media_build","trace":"off"}}]2018年09月20日 星期四 11时02分46秒:["<---(stderr)",1,"cquery",["executing job failed: No such file or directory",""]]
2018年09月20日 星期四 11时02分46秒:["s:on_exit",1,"cquery","exited",122]
2018年09月20日 星期四 11时02分53秒:["s:on_text_document_did_close()",1]
2018年09月20日 星期四 11时03分17秒:["lsp#register_server","server registered","cquery"]
2018年09月20日 星期四 11时03分17秒:["s:on_text_document_did_open()",1,"","/home/shide/media_build","file:///home/shide/vim-lsp.log"]
2018年09月20日 星期四 11时04分36秒:["s:on_text_document_did_close()",1]
2018年09月20日 星期四 11时04分44秒:["lsp#register_server","server registered","cquery"]
2018年09月20日 星期四 11时04分44秒:["s:on_text_document_did_open()",1,"","/home/shide/media_build","file:///home/shide/vim-lsp.log"]
2018年09月20日 星期四 11时04分50秒:["s:on_text_document_did_close()",1]

Please ignore the Chinese characters, they are just timestamps. Os version is Ubuntu 14.04, vim version is 8.1.1, which is built from source code distributed in official site.

**Comment by pdavydov108** [comment]
@raz0r89 Have you checked that compile_commands.json is generated and detected correctly? This is usually the root of all kinds of troubles that happen with cquery :). Does the directory "/home/shide/media_build" has compile_commands.json in it? This issue looks like some kind of cquery configuration error.

**Comment by prabirshrestha** [comment]
please try the lastest master and the language server.
