### ISSUE TITLE
Truncate  diagnostics cursor message while message is too long

### ISSUE THREAD

**Issue by bbchung** [prabirshrestha/vim-lsp#187]
It's annoying if diagnostics message too long to put in one line(if cmdheight==1) cause it always trigger "press enter to continue" in vim

**Comment by prabirshrestha** [comment]
@bbchung Even I wasn't a fan of this. This should now be fixed in the latest master

**Comment by bbchung** [comment]
I like this fix, it's very useful at some situation!
