### ISSUE TITLE
Sort completion results

### ISSUE THREAD

**Issue by theFroh** [prabirshrestha/vim-lsp#196]
Hi, I've been having great success with this in combination with `typescript-language-server`, and was just wondering if there was the possibility to customise how completion results are sorted?

It sounds like the LSP itself can provide hints for this information via `sortText` (ala [here](https://github.com/theia-ide/typescript-language-server/blob/101dae4f7b598e9bafcaa8c316f21e57341e6350/server/src/completion.ts#L23)). I only ask as in a project with many different completions (actually a Javascript project being scoured by the aforementioned LSP server), I get a whole lot of less relevant completions at the top (globals and such), with the more relevant fields such as properties and such buried further down.

This is at ends with, for example, VSCode, which'll neatly organise the Property completions near the top. As a bit of a counterpoint to `sortText`, apparently VSCode doesn't really listen to this and instead does its own magic, but that's akin to one solution I'm proposing.

I'd imagine one possible solution is the ability to post-rank completions (supply some kind of sorting function per LSP server config?) that'd then allow us to flag certain keywords like 'Property' so that they take priority over entries without any 'kind'. 

The other solution, and I'm not sure how prevalent this is in other LSP servers, is to use `sortText` to sort results.

Cheers for the great plugin!

**Comment by gbrlsnchs** [comment]
I also am using `typescript-language-server` and one thing that bothers me is that `field` variables don't appear first. They get mixed with `file` variables.

**Comment by prabirshrestha** [comment]
Will think about this. The problem with sorting is that vimscript is very slow at it 😢

**Comment by lithammer** [comment]
> Will think about this. The problem with sorting is that vimscript is very slow at it 😢

Could Lua be leveraged to speed up sorting? Also, is speed really a factor give that the number of completion items is fairly low... I think.

**Comment by lithammer** [comment]
If you're using asyncomplete and asyncomplete-lsp you can write a custom preprocessor to have the list sorted according to `sortText`:

```vim
" Sort according to sortText property.
" https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion
function! s:sort_by_sorttext_preprocessor(options, matches) abort
  let items = []
  for [source_name, matches] in items(a:matches)
    for item in matches['items']
      if stridx(item['word'], a:options['base']) == 0
        let user_data = lsp#omni#get_managed_user_data_from_completed_item(item)
        let completion_item = get(user_data, 'completion_item', {})
        let item['sort'] = get(completion_item, 'sortText',
              \ get(completion_item, 'label', ''))
        call add(items, item)
      endif
    endfor
  endfor

  let items = sort(items, {a, b ->
        \ a['sort'] == b['sort'] ? 0 : a['sort'] > b['sort'] ? 1 : -1})

  call asyncomplete#preprocess_complete(a:options, items)
endfunction

let g:asyncomplete_preprocessor = [function('s:sort_by_sorttext_preprocessor')]
```
