### ISSUE TITLE
Suggestion: Enable highlighting via LSP

### ISSUE THREAD

**Issue by E1k3** [prabirshrestha/vim-lsp#198]
As far as I understand, the LSP supports/will support [(semantic) code highlighting](https://github.com/Microsoft/vscode-languageserver-node/pull/367). Are there plans to integrate this into vim via this plugin or a separate one?

At least clangd already supports highlighting and there already is a [vim plugin](https://github.com/hukeyue/vim-clangd) that supports this interface.

**Comment by ryanolsonx** [comment]
Looks like it's still in a proposal state. Also, syntax highlighting works in a different sort of way in vim. I'm not sure if it's possible.

**Comment by smhc** [comment]
Not sure if this is the same issue, but LanguageClient-neovim supports symbol highlighting (at least in neovim). It is useful to see where symbols are used and how they are used (read or written etc).

I think it is the textDocument/documentHighlight command.

Any chance of vim-lsp supporting this?

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/375 Diagnostics highlighting is now supported in vim via text props. 
https://github.com/prabirshrestha/vim-lsp/pull/363 Highlight references under symbol has also been added.

Actual syntax highlight will be added later when textprop stabilizes and LSP officially supports it.

**Comment by prabirshrestha** [comment]
Please follow https://github.com/prabirshrestha/vim-lsp/pull/464 to support semantic highlight.
Not this feature is still in proposal so may only be supported by very few language servers.
