### ISSUE TITLE
lsp can't run

### ISSUE THREAD

**Issue by kdurant** [prabirshrestha/vim-lsp#199]
I has run `pip install python-language-server` and **executable('pyls') = 1**
```viml
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'ryanolsonx/vim-lsp-python'
if executable('pyls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
endif
```

![default](https://user-images.githubusercontent.com/2704364/47992087-ea41fc80-e126-11e8-84d6-a0f86b7cf32e.png)

**Comment by prabirshrestha** [comment]
@kdurant Could you try it again? There were some recent changes on text edits. I would also recommend to post logs which is document in README

**Comment by prabirshrestha** [comment]
Please try with latest master.
