### ISSUE TITLE
LspHover not working when RO buffer is present

### ISSUE THREAD

**Issue by noboruma** [prabirshrestha/vim-lsp#200]
If I open a writable file, LspHover works fine.
It stops working when I open a RO file.
The preview window opens but contains nothing. Other commands work fine.
It works again when I do `set noro` on the RO file.

vim-lsp.log shows:
`Thu 08 Nov 2018 11:25:42 AM GMT:["s:on_stdout client request on_notification() error","Vim(put):E21: Cannot make changes, 'modifiable' is off:         put ='```'.a:data.language"]`

**Comment by prabirshrestha** [comment]
Please update to latest master and try again.
