### ISSUE TITLE
TypeScript Not Supported?

### ISSUE THREAD

**Issue by Rybadour** [prabirshrestha/vim-lsp#204]
I've installed vim 8.0 and plugins: vim-lsp, async.vim, and vim-lsp-typescript.

I get an error when running any of the :Lsp* commands saying that they are not supported with typescript.

Is there some initial setup? Do I need to run some command to actually start the server or does it happen automatically?

I tried to set logging to verbose and set a log file but it only shows innocuous things like:

Tue Nov 27 18:05:38 2018:["s:on_text_document_did_close()",1]

**Comment by Rybadour** [comment]
So I dug a little deeper and found that the server wasn't running.

First off you should really list :LspStatus in your Readme so others can more easily discover the server isn't running.

There seems to be a bug either with ryanolsonx/vim-lsp-typescript or this repo. I had to comment out the second register_server in ryanolsonx/vim-lsp-typescript in order to get my typescript file to launch the server.

**Comment by prabirshrestha** [comment]
This is what I use.

```vim
let s:asyncomplete_blacklist = []

if executable('typescript-language-server')
  " npm i -g typescript-language-server
  let s:asyncomplete_blacklist += ['typescript']
  au User lsp_setup call lsp#register_server({
      \ 'name': 'typescript-language-server',
      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
      \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
      \ 'whitelist': ['typescript'],
      \ })
  autocmd FileType typescript nnoremap <buffer><silent> <c-]>  :LspDefinition<cr>
  autocmd FileType typescript nnoremap <buffer><silent> K :LspHover<cr>
  autocmd FileType typescript setlocal omnifunc=lsp#complete
endif
```

**Comment by Rybadour** [comment]
Okay thanks. Sounds like you should reconsider linking to that repo until it's fixed. Also you should add LspStatus to the Readme page.

**Comment by prabirshrestha** [comment]
@Rybadour Feel free to send a PR for readme. Wiki's are editable by anyone.

**Comment by Rybadour** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/217

**Comment by ryanolsonx** [comment]
The issue in ryanolsonx/vim-lsp-typescript has been resolved. So that repository should still provide a simple server registration with both typescript and javascript that should work.
