### ISSUE TITLE
Use virtual text to display diagnostics

### ISSUE THREAD

**Issue by pwntester** [prabirshrestha/vim-lsp#214]
Hi,

It would be great to offer an option to show the errors/warnings using new virtual text feature (nvim_buf_set_virtual_text) as, for example, ALE does (see https://github.com/w0rp/ale/pull/2056).

Thanks for the project!
A

**Comment by megalithic** [comment]
this would be fantastic.

**Comment by hauleth** [comment]
@prabirshrestha created PR.

**Comment by prabirshrestha** [comment]
This is now in master.
