### ISSUE TITLE
Autocomplete with cquery not working

### ISSUE THREAD

**Issue by Alexmac22347** [prabirshrestha/vim-lsp#228]
Hi, I have a simple cmake/c++ project to isolate the issue. Basically, I `#include <iostream>`, but vim-lsp cannot seem to find `std::cout`. However I can still go to the definition of `std::cout` using LspDefinition after typing out `std::cout` myself.

Here's main.cpp (~/Documents/test/main.cpp)
```cpp
#include <iostream>
int main() {
    std::cout << "hi";
}
```
compile_commands.json (~/Documents/test/build/compile_commands.json and symlink  ~/Documents/test/compile_commands.json)
```
[
{
  "directory": "/home/alex/Documents/test/build",
  "command": "/usr/bin/c++      -o CMakeFiles/test.dir/main.cpp.o -c /home/alex/Documents/test/main.cpp",
  "file": "/home/alex/Documents/test/main.cpp"
}
]
```
I've attached the [log](https://github.com/prabirshrestha/vim-lsp/files/2717723/vim-lsp.log)
 The completion request from vim-lsp looks ok, but then the server replies with isInComplete=True.
However, I do not think this is a cquery problem, since I tried the same thing in emacs using the emacs-cquery plugin, and was able to autocomplete std::cout.

Also, this problem happens with local includes as well. I tried adding file ~/Documents/test/foo.h:
```
int foo();
```
and modify ~/Documents/test/main.cpp:
```cpp
#include "foo.h"
int main() {
    int a = foo();
}
```
Again, like the std::cout example, lsp#complete cannot find the function foo. However, after I type in foo();, I can use LspDefinition just fine.

Thank you

**Comment by mattn** [comment]
As far as I can see your log, the `command` does not have `-I.` to include `"foo.h".

**Comment by mattn** [comment]
As far as I can see your log, vim-lsp does not send current edting text to cquery. Could you pleae try again with following step?

1. start vim
2. `let g:lsp_log_verbose=1`
3. `let g:lsp_log_file='/tmp/lsp.log'`
4. open the file
5. do code completion

**Comment by Alexmac22347** [comment]
Hi there, I just did it. I was trying to autocomple std::cou -> std::cout, but got no autocompletion results. Ive attached the log
[lsp.log](https://github.com/prabirshrestha/vim-lsp/files/2811993/lsp.log)

**Comment by Alexmac22347** [comment]
Weird, sometimes it works. Ive attached from when it worked, and autocompleted std::cout
[worked.txt](https://github.com/prabirshrestha/vim-lsp/files/2812045/worked.txt)
Most of the time though it doesnt work

**Comment by mattn** [comment]
Hmm, I could not figure out why cquery does not return candidate of completion from `std::`.


The first log file (https://github.com/prabirshrestha/vim-lsp/issues/228#issuecomment-458884363)

### initialize

```
2019年01月30日 18時59分33秒:["--->",1,"cquery",{"method":"initialize","params":{"rootUri":"file:///home/alex/Documents/test","initializationOptions":{"cacheDirectory":"/tmp/cquery/cache"},"capabilities":{"workspace":{"applyEdit ":true}},"rootPath":"/home/alex/Documents/test","trace":"off"}}]
```

### didOpen

```
2019年01月30日 18時59分33秒:["--->",1,"cquery",{"method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/alex/Documents/test/main.cpp","version":1,"languageId":"cpp","text":"#include <iostream>\n\nint main() {\n    std::\n}"}}}]
```

### didChange

```
2019年01月30日 18時59分40秒:["--->",1,"cquery",{"method":"textDocument/didChange","params":{"contentChanges":[{"text":"#include <iostream>\n\nint main() {\n    std::\n}"}],"textDocument":{"uri":"file:///home/alex/Documents/test/main.cpp","version":2}}}]
```

document still not have `cou`

### completion

```
2019年01月30日 18時59分40秒:["--->",1,"cquery",{"method":"textDocument/completion","on_notification":"---funcref---","params":{"textDocument":{"uri":"file:///home/alex/Documents/test/main.cpp"},"position":{"character":9,"line":3}}}]
```

### didChange

```
2019年01月30日 18時59分42秒:["--->",1,"cquery",{"method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":9,"line":3},"start":{"character":9,"line":3}},"text":"cou","rangeLength":0}],"textDocument":{"uri":"file:///home/alex/Documents/test/main.cpp","version":3}}}]
```

So completion was processed with text `std::` without `cou`. And `cou` was sent after completion.

**Comment by Alexmac22347** [comment]
I also found a way to make it autocomplete std::cout. basically, I type in std::co, then open the autocomplete menu and select the first choice. Then I started to delete characters, and once I delete enough characters so that its just std::co showing, then I will see the suggestion for cout showing!
Ill post more information and a gif when I get home

**Comment by mattn** [comment]
Thank your report. BTW, I tried to install cquery on Ubuntu 18.04 but cquery crash when cquery receives completion. (I always use clangd)

**Comment by Alexmac22347** [comment]
Im running Ubuntu 18.04 as well, cquery seems to run OK for me (no crash). I tried clangd as well, but it also could not complete std::cout. Ive attached a gif showing me using cquery, and how I can get the std::cout completion to show up by deleting characters.
![cquery](https://user-images.githubusercontent.com/14203288/52059380-0f6ecb80-25ad-11e9-9134-29713d456b17.gif)

Also heres what the clangd completion looked like. I couldnt get it to show std::cout at all
![clangd2](https://user-images.githubusercontent.com/14203288/52059403-1dbce780-25ad-11e9-8373-0d959e770b2f.gif)

**Comment by Alexmac22347** [comment]
Sorry just so you dont get confused, the logs and the gifs arent exactly the same. I forgot to turn on logging when I was making the gif, so the exact word I selected might be different. Also, I am using the omni complete function, ie in my vimrc I have set
```autocmd FileType cpp setlocal omnifunc=lsp#complete```
I will try your suggestions today

**Comment by Alexmac22347** [comment]
Hi, I tried waiting for clangd, but it didnt autocomplete std::cout. It must be finished initialization because I can see many other autocomplete suggestions showing, and I can also goto definition of std::cout.

Good news though, I tried using asyncomplete and asyncomplete-lsp.
That appears to find cout, and the function from my header file, so I will just use that from now on.
It works with both clangd and cquery.
When I have time, I will look more into why omnicomplete with just vim-lsp wasnt working. It works when I use the plugin vim-lsc, so I can compare how the two are sending the auto completion request to the server

**Comment by Alexmac22347** [comment]
btw, heres the log when it works with asyncomplete. Note that since it autocompletes as I type, theres probably a lot more completion requests
[lsp.log](https://github.com/prabirshrestha/vim-lsp/files/2821188/lsp.log)

**Comment by prabirshrestha** [comment]
If you are using asyncomplete please try the v2 branch. It has lot of improvements.

**Comment by mkwork** [comment]
Please be noticed that cquery is no more supported by its author and its community and current master branch is in mess a bit. Try with its latest release or `ccls` or even `clangd`.

**Comment by prabirshrestha** [comment]
@mkwork If itsn't supported we should remove it from the wiki. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-cquery

**Comment by mkwork** [comment]
I guess it's better to make remark about stable version and possibly broken master. Also link to this [issue](https://github.com/cquery-project/cquery/issues/867) could be provided.

I can propose such form:

**ATTENTION**: looks like `cquery` is no more supported by its author and master could be unstable. Please check this [issues](https://github.com/cquery-project/cquery/issues/867) status. Anyway try to use [latest stable version](https://github.com/cquery-project/cquery/releases/latest) or other clang based language server like `ccls` or `clangd`, before reporting issues related to `cquery`.

**Comment by Alexmac22347** [comment]
Yeah, I just did a fresh install of vim-lsp and clangd, and everything seems to work now, so I think it was a cquery problem. Thanks for the help!

**Comment by Abbyyan** [comment]
> Thank your report. BTW, I tried to install cquery on Ubuntu 18.04 but cquery crash when cquery receives completion. (I always use clangd)

Sorry to bother you . Could you give an config of vim-lsp on clangd? I have installed clangd and vim-lsp , but it seems can't work just for autocomplete. Will it come out the selection bar automatically when I input some words ? Or should i type Ctl+N when i  want to use complete features? It seems like i still use original vim-autocomplete even after i config the vim-lsp. Hope for your reply . Thanks  a lot.

**Comment by thomasfaingnaert** [comment]
@Abbyyan I'm using the following config for clangd:
```vim
if executable('clangd')
    augroup vim_lsp_cpp
        autocmd!
        autocmd User lsp_setup call lsp#register_server({
                    \ 'name': 'clangd',
                    \ 'cmd': {server_info->['clangd']},
                    \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
                    \ })
        autocmd FileType c,cpp,objc,objcpp,cc setlocal omnifunc=lsp#complete
        autocmd FileType c,cpp,objc,objcpp,cc setlocal keywordprg=:LspHover
        autocmd FileType c,cpp,objc,objcpp,cc nnoremap <buffer> <C-]> :LspDefinition<CR>
        autocmd FileType c,cpp,objc,objcpp,cc nnoremap <buffer> <F2> :LspRename<CR>
    augroup end
endif
```
You can start completion manually by pressing `CTRL-X CTRL-O` in insert mode.
If you want the completion menu to pop up automatically, you may want to check out https://github.com/prabirshrestha/asyncomplete.vim.
