### ISSUE TITLE
LspDocumentFormatSync is not executed synchronously

### ISSUE THREAD

**Issue by bmtsstl** [prabirshrestha/vim-lsp#230]
Probably due to the code below.

https://github.com/prabirshrestha/vim-lsp/blob/d4c8e001e6abb3f229f23da83ba02a8b59d49cba/autoload/lsp/client.vim#L228-L234

The expected behavior is to wait for the response of the Language Server, but this code is trying to wait for the process to finish.

Actually, it does not wait for the process because the arguement for `async#job#wait` is incorrect.

**Comment by OneOfOne** [comment]
Not sure if this is the same issue, but writing a format-on-save func for vim sometimes freezes neovim.

```
func! FormatOnSave(...)
	silent doautocmd BufWritePre
	let winview = winsaveview()
	:LspDocumentFormatSync
	set nomod
	call winrestview(winview)
	execute 'write %'
	silent doautocmd BufWritePost
endfun

augroup lsp.format
		autocmd!
		autocmd BufWriteCmd *.go call FormatOnSave()
augroup END
```

**Comment by mattn** [comment]
Could you please try this?
https://github.com/prabirshrestha/vim-lsp/pull/232
