### ISSUE TITLE
intelephense-server only matches one filetype (php)

### ISSUE THREAD

**Issue by losnappas** [prabirshrestha/vim-lsp#231]
I wrote a segment here https://github.com/prabirshrestha/vim-lsp/wiki/Servers-PHP .
Now, the problem is that it matches `filetype=php`, but it doesn't match anything other than that. Tried `['*']` as whitelist too - no difference. Is the bug on that side(langserver) or this side?

Doing `au filetype php setl ft=php.test` will just flat out break the thing. But `lsp#get_server_status()` says it's "running".

**Comment by mattn** [comment]
Try this.

```
au User lsp_setup call lsp#register_server({                                    
     \ 'name': 'php-language-server',                                            
     \ 'cmd': {server_info->['php', expand('~/.vim/plugged/php-language-server/bin/php-language-server.php')]},
     \ 'whitelist': ['php', 'php.test'],
     \ })
```

**Comment by losnappas** [comment]
Seems to work, so I guess it's on the intelephense LSP side.

And then there's [this](https://github.com/prabirshrestha/asyncomplete.vim/issues/87) bug which doesn't exist in intelephense. It's always something, eh?
