### ISSUE TITLE
hung with frequent modifying.

### ISSUE THREAD

**Issue by mattn** [prabirshrestha/vim-lsp#235]
1. find text with `/foobar`
2. change word with `cwbarfoo`
3. type `n.n.n.n.n.`

Seems to be blocking with ch_sendraw.

**Comment by prabirshrestha** [comment]
I think it is a bug in vim which is discussed in length at https://github.com/vim/vim/issues/2548 since doesn't occur in neovim.

I did try this in async.vim with `no-block` but it didn't help much although it is better. https://github.com/prabirshrestha/async.vim/pull/18.

Either way also supporting incremental change in vim-lsp would help avoid sending large number of data to server.

**Comment by mattn** [comment]
I could fix this problem with this patch.

```diff
diff --git a/autoload/async/job.vim b/autoload/async/job.vim
index dcdaaf3..a9c4e96 100644
--- a/autoload/async/job.vim
+++ b/autoload/async/job.vim
@@ -193,6 +193,7 @@ function! s:flush_vim_sendraw(jobid, timer) abort
     " https://github.com/vim/vim/issues/2548
     " https://github.com/natebosch/vim-lsc/issues/67#issuecomment-357469091
     let l:jobinfo = s:jobs[a:jobid]
+    sleep 1m
     if len(l:jobinfo.buffer) <= 1024
         call ch_sendraw(l:jobinfo.channel, l:jobinfo.buffer)
         let l:jobinfo.buffer = ''
```

**Comment by mattn** [comment]
Vim does not check that channel is readable if state is not indle.

**Comment by mattn** [comment]
Also, even if you start timer, Vim does not check whether the timer arrival if state is not idle.

**Comment by prabirshrestha** [comment]
I'm ok for putting `sleep 1m` hack if that solves the issue.
Hang is the main reason why I set `let g:asyncomplete_auto_popup = 0`.

Do we still need this `noblock` after `sleep 1m`?

```
let l:jobopt['noblock'] = 1
```

Before I used to think it was a bug in vim-lsp because of the while loop but I have rewriteen the lsp client and looked at it several times and couldn't see a bug. One thing I do know is I don't calculate the length of strings correctly for mutli byte chars since currently I use only English it hasn't been an issue, but this is something I would like to fix it properly.

Another bug that I had thought that could impact was this but this only happens on exit. Vim does document this in help which seems a bit weird. This isn't implemented in async.vim
https://github.com/prabirshrestha/asyncomplete-tags.vim/blob/c3c575a62a34661134e9e9427fdcc46dc50a5069/autoload/asyncomplete/sources/tags.vim#L160-L171

**Comment by mattn** [comment]
Also I noticed that sending data with small steps does not fix this issue. I checked this working well. (but bit's slowly)

```
diff --git a/autoload/async/job.vim b/autoload/async/job.vim
index dcdaaf3..a0a9849 100644
--- a/autoload/async/job.vim
+++ b/autoload/async/job.vim
@@ -190,18 +190,10 @@ function! s:job_send(jobid, data) abort
 endfunction
 
 function! s:flush_vim_sendraw(jobid, timer) abort
-    " https://github.com/vim/vim/issues/2548
-    " https://github.com/natebosch/vim-lsc/issues/67#issuecomment-357469091
     let l:jobinfo = s:jobs[a:jobid]
-    if len(l:jobinfo.buffer) <= 1024
-        call ch_sendraw(l:jobinfo.channel, l:jobinfo.buffer)
-        let l:jobinfo.buffer = ''
-    else
-        let l:to_send = l:jobinfo.buffer[:1023]
-        let l:jobinfo.buffer = l:jobinfo.buffer[1024:]
-        call ch_sendraw(l:jobinfo.channel, l:to_send)
-        call timer_start(1, function('s:flush_vim_sendraw', [a:jobid]))
-    endif
+    sleep 1m
+    call ch_sendraw(l:jobinfo.channel, l:jobinfo.buffer)
+    let l:jobinfo.buffer = ''
 endfunction
 
 function! s:job_wait_single(jobid, timeout, start) abort
```

**Comment by natebosch** [comment]
Have you tried keeping the chunking but replacing the `timer_start` with `sleep 1m`?

**Comment by mattn** [comment]
Using timer_start have no mean since Vim does not read data from channel until the Vim get idle. 

https://github.com/vim/vim/blob/663bc89bbb8158bd0888f7d7228b2dbc6bbd4802/src/os_win32.c#L1556-L1566

Timer event will not triggered until the Vim get idle.

https://github.com/vim/vim/blob/663bc89bbb8158bd0888f7d7228b2dbc6bbd4802/src/os_win32.c#L1578-L1597

**Comment by mattn** [comment]
LSP server reply response to vim-lsp but vim-lsp does not read. So this make blocking.

**Comment by mattn** [comment]
FYI, sleep command check channel readable. Thus, async.vim must do `sleep 1m` to read channel to avoid busy loop.

https://github.com/vim/vim/blob/663bc89bbb8158bd0888f7d7228b2dbc6bbd4802/src/ex_docmd.c#L9270-L9311

**Comment by mattn** [comment]
> Have you tried keeping the chunking but replacing the timer_start with sleep 1m?

Ah, you worries the huge data. Okay will check soon.

**Comment by prabirshrestha** [comment]
I would also be curious with big files. If we have both chunking and sleep would that cause some other race conditions?

**Comment by mattn** [comment]
```diff
diff --git a/autoload/async/job.vim b/autoload/async/job.vim
index dcdaaf3..a9c4e96 100644
--- a/autoload/async/job.vim
+++ b/autoload/async/job.vim
@@ -193,6 +193,7 @@ function! s:flush_vim_sendraw(jobid, timer) abort
     " https://github.com/vim/vim/issues/2548
     " https://github.com/natebosch/vim-lsc/issues/67#issuecomment-357469091
     let l:jobinfo = s:jobs[a:jobid]
+    sleep 1m
     if len(l:jobinfo.buffer) <= 1024
         call ch_sendraw(l:jobinfo.channel, l:jobinfo.buffer)
         let l:jobinfo.buffer = ''
```
This works fine for me. For making retry it must keep timer_start. The lsp server will not return the response unless it reads non-fragment JSON. So race condition will not occured while vim-lsp expect sending requests and receiving replies.

**Comment by mattn** [comment]
If you want to remove timer_start:

```vim
function! s:flush_vim_sendraw(jobid, timer) abort
    " https://github.com/vim/vim/issues/2548
    " https://github.com/natebosch/vim-lsc/issues/67#issuecomment-357469091
    let l:jobinfo = s:jobs[a:jobid]
    while 1
        sleep 1m
        if len(l:jobinfo.buffer) <= 1024
            call ch_sendraw(l:jobinfo.channel, l:jobinfo.buffer)
            let l:jobinfo.buffer = ''
            break
		endif
        let l:to_send = l:jobinfo.buffer[:1023]
        let l:jobinfo.buffer = l:jobinfo.buffer[1024:]
        call ch_sendraw(l:jobinfo.channel, l:to_send)
    endwhile
endfunction
```

**Comment by prabirshrestha** [comment]
@mattn Any idea how to fix this upstream in vim without the hack. Either way we would still most likely need the hack for those who doesn't have the patch.

Also did you see any improvement with setting `noblock = 1`?
```
						*job-noblock*
"noblock": 1		When writing use a non-blocking write call.  This
			avoids getting stuck if Vim should handle other
			messages in between, e.g. when a job sends back data
			to Vim.  It implies that when `ch_sendraw()` returns
			not all data may have been written yet.
			This option was added in patch 8.1.0350, test with: >
				if has("patch-8.1.350")
				  let options['noblock'] = 1
				endif
```

**Comment by mattn** [comment]
I tried this but unfortunately don't get any fixes.

```diff
diff --git a/autoload/lsp/client.vim b/autoload/lsp/client.vim
index 07795ed..95aaa5b 100644
--- a/autoload/lsp/client.vim
+++ b/autoload/lsp/client.vim
@@ -185,6 +185,7 @@ function! s:lsp_start(opts) abort
         \ 'on_stdout': function('s:on_stdout'),
         \ 'on_stderr': function('s:on_stderr'),
         \ 'on_exit': function('s:on_exit'),
+        \ 'noblock': 1,
         \ })
 
     let l:ctx = s:create_context(l:client_id, a:opts)
```

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/async.vim/pull/22 This didn't work for me for typescript emitter.ts file.

@mattn Does golang server use async stdin? Does it buffer writes? Can you also name the lang server you are trying. I can try a big file and see if it work there.

@natebosch Does vim-lsc work with this file? https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts would be curious if you have files over 100k that doesn't buffer on server.

**Comment by prabirshrestha** [comment]
This seems like a big go file. https://github.com/golang/go/blob/master/src/html/entity.go

**Comment by mattn** [comment]
I'm using golsp for Go. typescript-language-server for ts.

**Comment by mattn** [comment]
entity.go works fine for me.
![terminal6](https://user-images.githubusercontent.com/10111/50883807-7b399a80-142c-11e9-90ec-3be5ab192acf.gif)

**Comment by prabirshrestha** [comment]
So I tried the emitter.ts from TS source code and here is what I get.

If I use just omnicomplete i.e. with Ctrl+X, Ctrl+O it doesn't hang. Based on your gif you seem to be doing the same. As soon I use asyncomplete.vim it starts to hang. I also tried mucomplete and it has the same impact.

**Comment by mattn** [comment]
emitter.ts also work fine.
![terminal6](https://user-images.githubusercontent.com/10111/50884975-c1dcc400-142f-11e9-9e1b-d225b8512eca.gif)

**Comment by prabirshrestha** [comment]
If I disable asyncomplete.vim's auto_popup and use just omnicomplete with `<c-x><c-o>` it works for me to in emitter. So I'm good with this changes.

It is midnight here so feel free to merge the changes in async.vim and here. You should have permission for both repos.

**Comment by mattn** [comment]
Closed by https://github.com/prabirshrestha/async.vim/pull/22

**Comment by prabirshrestha** [comment]
@mattn Can you try to add this in your vimrc. This will autopopup omni complete.

This will make emitter.ts hang. So bug could be in omnicomplete in vim.

```
function! OpenCompletion()
    if !pumvisible() && ((v:char >= 'a' && v:char <= 'z') || (v:char >= 'A' && v:char <= 'Z'))
        call feedkeys("\<C-x>\<C-o>", "n")
    endif
endfunction

autocmd InsertCharPre * call OpenCompletion()
```

**Comment by mattn** [comment]
On my environment, seems to be just heavy slowly.

![terminal6](https://user-images.githubusercontent.com/10111/50887376-59ddac00-1436-11e9-9b12-c0fa38e4653c.gif)

I'm on Windows7 64bit Intel Core i5 16GB mem.

**Comment by mattn** [comment]
Seems to be size of stepping.

```diff
diff --git a/autoload/async/job.vim b/autoload/async/job.vim
index 109719e..044c112 100644
--- a/autoload/async/job.vim
+++ b/autoload/async/job.vim
@@ -199,13 +199,13 @@ function! s:flush_vim_sendraw(jobid, timer) abort
             call timer_start(1, function('s:flush_vim_sendraw', [a:jobid]))
             return
         endif
-        if len(l:jobinfo.buffer) <= 1024
+        if len(l:jobinfo.buffer) <= 4096
             call ch_sendraw(l:jobinfo.channel, l:jobinfo.buffer)
             let l:jobinfo.buffer = ''
             break
         endif
-        let l:to_send = l:jobinfo.buffer[:1023]
-        let l:jobinfo.buffer = l:jobinfo.buffer[1024:]
+        let l:to_send = l:jobinfo.buffer[:4095]
+        let l:jobinfo.buffer = l:jobinfo.buffer[4096:]
         call ch_sendraw(l:jobinfo.channel, l:to_send)
     endwhile
 endfunction
```
![terminal6](https://user-images.githubusercontent.com/10111/50888044-0e2c0200-1438-11e9-95c1-3bed8e311c1f.gif)

**Comment by mattn** [comment]
https://github.com/prabirshrestha/async.vim/pull/22 does not fix collectly.

**Comment by mattn** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/237
