### ISSUE TITLE
Add omni completion support

### ISSUE THREAD

**Issue by keremc** [prabirshrestha/vim-lsp#25]
It would be much appreciated if you could add support for Vim's built-in omni completion. This way, those who prefer not to use any third-party completion plugins can also enjoy LSP goodness.

I've tried to do it myself but my VimL knowledge isn't up to par ☹️.

**Comment by prabirshrestha** [comment]
This is more of [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim) issue. Vim's built-in omnicompletion support for asyncomplete can be found at https://github.com/yami-beta/asyncomplete-omni.vim. You can find list of all asyncomplete sources at https://github.com/prabirshrestha/asyncomplete.vim#sources.

Out of curiosity which language do you need omni complete?

**Comment by keremc** [comment]
Sorry, I should have worded things better. I want vim-lsp to act as a source for omni completion so that I can use the `<C-X><C-O>` key sequence for Language Server-assisted completion. To enable this, vim-lsp must expose a "complete function" (documented in `:help complete-functions`). I would do it myself but my VimL knowledge isn't up to par and the asynchronous nature of the vim-lsp API doesn't help either.

**Comment by prabirshrestha** [comment]
If you want to use key to trigger autocomplete you can try adding a mapping instead. 

```vim
let g:asyncomplete_auto_popup = 0
imap <c-space> <Plug>(asyncomplete_force_refresh)
```

If you would really like to have the feature file an issue in asyncomplete.vim, but I want be able to have a look at it any time soon.

**Comment by xtal8** [comment]
I think @keremc  would like to use LSP provided completion without having to install *asyncomplete*. I also like to use manual completion and Vim's built-in features. 

Is there any way to use vim-LSP provided completion manually without having to install other completion plugins?

**Comment by keremc** [comment]
The thing is I would rather not use asyncomplete. With [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim), for example, I can just add `autocmd FileType python setlocal omnifunc=LanguageClient#complete` to my `init.vim` to enable intelligent completion for Python files. I don't need to install more complex plugins like [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) or [deoplete.nvim](https://github.com/Shougo/deoplete.nvim). IMHO, vim-lsp should be able to provide this feature without depending on other plugins too.

**Comment by prabirshrestha** [comment]
That totally makes sense. Reopening the issue.

If anyone wants to pick this up and send a PR, feel free to give a shot. Here is an example on how to get async omni working without any plugins. https://gist.github.com/prabirshrestha/0b3b7b4e2112c662979bfeeec4e1edb7. This was what I had before `asyncomplete.vim`.

Here is the code from `asyncomplete-lsp.vim` that needs to be ported. https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/cc168c5a0873dc902d9e1f55032e776a2fcd8d69/plugin/asyncomplete.vim#L82-L114

**Comment by prabirshrestha** [comment]
Just pushed the basic support for `omnifunc`. Please give it a try and let me know how it goes.

```vim
autocmd FileType python setlocal omnifunc=lsp#complete
```

Here are some know issues:

* If this works I will port the symbol kind features from `asyncomplete-lsp.vim` to `vim-lsp`. Currently omnifunc menu is empty string.
* I will not be supporting the `isIncomplete` feature so you would need to manually press `<c-x c-o>` again. This one isn't possible to implement in raw omnifunc without implementing lot of logic from asyncomplete.vim which would defeat the purpose.
* Currently I don't filter out the prefix. This might be something some would want and some wouldn't want. I can add an option if there is a request.

**Comment by prabirshrestha** [comment]
Another known issue: `lsp#complete` only supports one completion provider for now. This should be enough for most of the use cases.

**Comment by keremc** [comment]
It doesn't play nicely with [MUcomplete](https://github.com/lifepillar/vim-mucomplete).

**Comment by keremc** [comment]
> MUcomplete is an implementation of chained (fallback) completion, whereby several completion methods are attempted one after another until a result is returned. MUcomplete brings Vim completion down to earth again.
>
> Under the hood, µcomplete does nothing more than typing some completion mappings for you, either when you press <tab>/<s-tab> or automatically while you are typing. You choose which completion methods to use and in which order, and µcomplete does the rest. It does no caching, no asynchronous computation, no intelligent guessing.

The problem is that since `lsp#complete()` does not return anything, MUcomplete considers omni-completion to have failed and tries the next configured method (which is keyword completion in my case). This process is interrupted when `s:handle_omnicompletion()` is finally triggered, breaking the chained completion.
The solution is to make omni-completion completely synchronous.

Here is a patch that "works" (or at least shows that it can work):
```diff
diff --git a/autoload/lsp.vim b/autoload/lsp.vim
index 95d6b09..c48b552 100644
--- a/autoload/lsp.vim
+++ b/autoload/lsp.vim
@@ -525,6 +525,9 @@ function! lsp#send_request(server_name, request) abort
 endfunction
 
 " omnicompletion
+
+let s:completions = []
+
 function! lsp#complete(findstart, base) abort
     if a:findstart
         let l:info = s:find_complete_servers_and_start_pos()
@@ -533,7 +536,7 @@ function! lsp#complete(findstart, base) abort
             return -1
         endif
 
-        return l:info['findstart']
+        return l:info['findstart'] - 1
     else
         let l:info = s:find_complete_servers_and_start_pos()
 
@@ -550,9 +553,10 @@ function! lsp#complete(findstart, base) abort
             \   'textDocument': lsp#get_text_document_identifier(),
             \   'position': lsp#get_position(),
             \ },
-            \ 'on_notification': function('s:handle_omnicompletion', [l:server_name, l:info['findstart'], s:complete_counter]),
+            \ 'on_notification': function('s:handle_omnicompletion', [l:server_name, s:complete_counter]),
             \ })
-        return []
+        sleep 1 " temporary hack
+        return filter(s:completions, {_, dict -> dict['word'] =~ '^' . a:base})
     endif
 endfunction
 
@@ -578,7 +582,7 @@ function! s:find_complete_servers_and_start_pos() abort
     return { 'findstart': l:findstart, 'server_names': l:server_names }
 endfunction
 
-function! s:handle_omnicompletion(server_name, startcol, complete_counter, data) abort
+function! s:handle_omnicompletion(server_name, complete_counter, data) abort
     if s:complete_counter != a:complete_counter
         " ignore old completion results
         return
@@ -600,5 +604,5 @@ function! s:handle_omnicompletion(server_name, startcol, complete_counter, data)
 
     let l:matches = []
     let l:matches = map(l:items,'{"word":v:val["label"],"dup":1,"icase":1,"menu": ""}')
-    call complete(a:startcol, l:matches)
+    let s:completions = l:matches
 endfunction
```
Ideally, there would be a blocking version of `lsp#send_request()`, so that `sleep 1` can be removed.

**Comment by prabirshrestha** [comment]
Making it completely sync wouldn't be a good idea since it would block vim and that is something I really don't want to support. `sleep 1` isn't reliable if the language servers are slow can you do something like this.

```vim
let s:completions = { 'status': '' } " It may contain optional items whens status is success

function! lsp#complete()
    ...

    let s:completions['status'] = 'pending'

    call lsp#send_request(....)

    while s:completions['status'] == 'success' || s:completions['status'] == 'failed'
        sleep 10m
    endwhile

    let l:items

    if s:completions['status'] == 'success'
        let l:items = s:completions['items']
        unlet s:completions['items']
        let s:completions['status'] = ''
    elseif s:completions['status'] == 'failed'
        l:items = []
        let s:completions['status'] = ''
    endif

    return l:items
endfunction

function! s:handle_completion()
    if success
        let s:completions['status'] = 'success'
        let s:completions['items'] = items
    else
        let s:completions['status'] = 'failed'
    end
endfunction
```

Please do create variables for status. 

```vim
let s:completion_status_success = 'success'
let s:completion_status_failed = 'failed'
let s:completion_status_pending = 'pending'
```

We could increase the `sleep` to higher number or make it a variable that user can customize.

If this blocks vim but you really need to have this, I would have a flag that allows users to use sleep or my previous method of calling `complete()` that is purely async.

If possible would can you send PRs so it is easier to code review. If not feel free to send patches here.

**Comment by prabirshrestha** [comment]
@keremc I have merged your PR. Let me know how it goes.

You might also want to port this part to `vim-lsp`. I would have this method. `lsp#utils#lsp_complete_item_to_vim(completeItem)`

https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/2845beeced147bb923189deb62df4e1f9d4c0973/plugin/asyncomplete.vim#L11-L34

https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/2845beeced147bb923189deb62df4e1f9d4c0973/plugin/asyncomplete.vim#L108

**Comment by keremc** [comment]
@prabirshrestha Thanks! 
I'll look into it tomorrow. Would you mind if I move the completion code to a separate file (perhaps `autoload/lsp/omni.vim`)?

**Comment by prabirshrestha** [comment]
Sure, feel free to do that. Even I was thinking the same. That file is getting huge. The only reason I had it there was because I wanted the complete func to be simple as `lsp#complete()`, if we move it would be `lsp#omni#complete()`.

**Comment by prabirshrestha** [comment]
Closing this since omnicomplete has been implemented. Please file new bugs/feature requests as needed.
