### ISSUE TITLE
FYI golsp has been renamed to gopls

### ISSUE THREAD

**Issue by DGollings** [prabirshrestha/vim-lsp#255]
fyi: cmd/gopls: rename "golsp" to "gopls", as in "Go Please" https://github.com/golang/tools/commit/b258f6da23835bf37e95cc50af792447c7c67fe4

**Comment by prabirshrestha** [comment]
Feel free to update the wiki. It is editable by anyone.

**Comment by DGollings** [comment]
I was trying to, but it refused to let me save for some reason :)

**Comment by DGollings** [comment]
wth, "DGollings edited this page 14 minutes ago"

anyway, nevermind.
