### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#256]
@mattn Got this error today when was playing with latest vim-lsp. Most likely some race condition. I was using splits `<c-w><c-v>`. Haven't had a chance to play with latest vim-lsp much and debug this further.

![image](https://user-images.githubusercontent.com/287744/51366632-72377180-1a9b-11e9-96ba-243bc1198bb7.png)

**Comment by mattn** [comment]
Thought possibility of this error message, probably, `a:old` is empty `[]`. Did you add some lines from the empty buffer?

**Comment by prabirshrestha** [comment]
Here is another one I got. I have asyncomplete.vim auto_popup set to 1 and I just type normal. This time no splits.

![image](https://user-images.githubusercontent.com/287744/51412758-87ef7a00-1b21-11e9-8210-9d450adcc102.png)

**Comment by mvattuone** [comment]
I'm actually seeing errors similar to these pop up in my editor, though I'm not really sure I can say with confidence they are exactly the same.

![image](https://user-images.githubusercontent.com/1200102/52294968-a4284f00-2948-11e9-895c-46a7ac22edeb.png)

Seems like it happens whenever there aren't any characters to diff... makes me wonder if there is some sort of workaround.

**Comment by prabirshrestha** [comment]
I don’t see this issue anymore.

**Comment by lkebin** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/1335935/76976000-45683e00-696e-11ea-8657-7bc55397265d.png">

Same issue ?

**Comment by mattn** [comment]
Probably No. But win_findbuf possibly return empty.

https://github.com/prabirshrestha/vim-lsp/blob/f759e4dd0d4700e9b1fad48ab5d1e26c57bc3a3b/autoload/lsp/ui/vim/folding.vim#L50

**Comment by lkebin** [comment]
In my case, I just switch between changed buffers (without save). After several times will get this error.

**Comment by gbishop** [comment]
I'm seeing this (or something very similar) on buffer switch.
