### ISSUE TITLE
Can I use link path instead of target path when I work in a symbolic link dir?

### ISSUE THREAD

**Issue by fcying** [prabirshrestha/vim-lsp#258]
my work dir is `~/go`(GOPATH), it is a symbolic link for `/mnt/d/workspace/go`

when I use `vim-lsp` with `bingo`, it will jump a error
```
Failed to initialize bingo with error 0: /mnt/d/workspace/go/src/test is out of GOPATH workspace [/home/fcying/go], 
```

This looks like it was passed to the bingo target path, not symbolic  link path

**Comment by prabirshrestha** [comment]
This is most likely an issue with the server.
