### ISSUE TITLE
Not show autocompletion popup when language server return insertText field

### ISSUE THREAD

**Issue by yami-beta** [prabirshrestha/vim-lsp#261]
vim-lsp with asyncomplete.vim cannot show popup when language server return completion items with `insertText` field.
Example repo (gopls + vim-lsp + asyncomplete-lsp + asyncomplete)
https://github.com/yami-beta/vim-lsp-asyncomplete-insert-text-bug

When input `f`,  language server complete `fmt` with insertText field it is `mt`.
vim-lsp set `insertText` value to `word`.
https://github.com/prabirshrestha/vim-lsp/blob/1aba95603c1f4d7c7808e52deda993fbeb4b1620/autoload/lsp/omni.vim#L157-L167

asyncomplete.vim receive completion item but popup is not shown. 
A completion item `fmt` is filtered because `s:filter_completion_items` function use forward match.
https://github.com/prabirshrestha/asyncomplete.vim/blob/c4d93a8dd1efda3ca1ffb3c6535ac9c080f245b0/autoload/asyncomplete.vim#L452-L460

| Current (Not show popup `fmt`) | Expected |
| --- | --- |
| ![vim-lsp-bug-current](https://user-images.githubusercontent.com/5106704/51435973-dc802a00-1cc6-11e9-8887-e082e5728ab4.gif) | ![vim-lsp-bug-changed](https://user-images.githubusercontent.com/5106704/51435974-e570fb80-1cc6-11e9-9ffe-3f92138f21f1.gif) |

**Comment by prabirshrestha** [comment]
Thanks for the detailed repro step. 

We do need to be careful about this. https://github.com/prabirshrestha/vim-lsp/pull/45

I re-read the spec and seems like insertText is deprecated and is up for clients to interpret. Which means the behavior can not be guaranteed. It seems to have been replaced by TextEdit which makes more sense to me now.

I’m ok removing insertText support but we should try to allow other language servers to opt in or out if needed.

I’m out of town for several days so won’t be able to have a look into this yet. Feel free to send a PR if you would like.

**Comment by prabirshrestha** [comment]
Also would be good to compare with other language servers and see if it is a bug in gopls instead because most editors will cache the value so seems like insertText should most likely be replace instead of append although it contradicts with the naming.

**Comment by yami-beta** [comment]
Thanks for your reply.
I try to compare with other language server that uses insertText.

**Comment by yami-beta** [comment]
I try some language servers, but I don't find language server that uses correct insertText.
So, I will create PR that adding option to opt in or opt out insertText.

---

I try to use [python-language-server](https://github.com/palantir/python-language-server) that return insertText but insertText is incorrect (insertText and label have same value).

```python
import sys

# Input 's' at here
```

```python
{"label":"sys","insertText":"sys","sortText":"asys","kind":9,"documentation":"This module provides access to some objects used or maintained by the\ninterpreter and to functions that interact strongly with the interpreter.\n\nDynamic objects:\n\nargv -- command line arguments; argv[0] is the script pathname if known\npath -- module search path; path[0] is the script directory, else ''\nmodules -- dictionary of loaded modules\n\ndisplayhook -- called to show results in an interactive session\nexcepthook -- called to handle any uncaught exception other than SystemExit\n  To customize printing in an interactive session or to install a custom\n  top-level exception handler, assign other functions to replace these.\n\nstdin -- standard input file object; used by input()\nstdout -- standard output file object; used by print()\nstderr -- standard error object; used for error messages\n  By assigning other file objects (or objects that behave like files)\n  to these, it is possible to redirect all of the interpreter's I/O.\n\nlast_type -- type of last uncaught exception\nlast_value -- value of last uncaught exception\nlast_traceback -- traceback of last uncaught exception\n  These three are only available in an interactive session after a\n  traceback has been printed.\n\nStatic objects:\n\nbuiltin_module_names -- tuple of module names built into this interpreter\ncopyright -- copyright notice pertaining to this interpreter\nexec_prefix -- prefix used to find the machine-specific Python library\nexecutable -- absolute path of the executable binary of the Python interpreter\nfloat_info -- a struct sequence with information about the float implementation.\nfloat_repr_style -- string indicating the style of repr() output for floats\nhash_info -- a struct sequence with information about the hash algorithm.\nhexversion -- version information encoded as a single integer\nimplementation -- Python implementation information.\nint_info -- a struct sequence with information about the int implementation.\nmaxsize -- the largest supported length of containers.\nmaxunicode -- the value of the largest Unicode code point\nplatform -- platform identifier\nprefix -- prefix used to find the Python library\nthread_info -- a struct sequence with information about the thread implementation.\nversion -- the version of this interpreter as a string\nversion_info -- version information as a named tuple\n__stdin__ -- the original stdin; don't touch!\n__stdout__ -- the original stdout; don't touch!\n__stderr__ -- the original stderr; don't touch!\n__displayhook__ -- the original displayhook; don't touch!\n__excepthook__ -- the original excepthook; don't touch!\n\nFunctions:\n\ndisplayhook() -- print an object to the screen, and save it in builtins._\nexcepthook() -- print an exception and its traceback to sys.stderr\nexc_info() -- return thread-safe information about the current exception\nexit() -- exit the interpreter by raising SystemExit\ngetdlopenflags() -- returns flags to be used for dlopen() calls\ngetprofile() -- get the global profiling function\ngetrefcount() -- return the reference count for an object (plus one :-)\ngetrecursionlimit() -- return the max recursion depth for the interpreter\ngetsizeof() -- return the size of an object in bytes\ngettrace() -- get the global debug tracing function\nsetcheckinterval() -- control how often the interpreter checks for events\nsetdlopenflags() -- set the flags to be used for dlopen() calls\nsetprofile() -- set the global profiling function\nsetrecursionlimit() -- set the max recursion depth for the interpreter\nsettrace() -- set the global debug tracing function","detail":"__main__"}
```

**Comment by yami-beta** [comment]
Thanks for merge my PR!
