### ISSUE TITLE
Call settagstack to allow C-t after lsp-definition

### ISSUE THREAD

**Issue by idbrii** [prabirshrestha/vim-lsp#262]
Add support for C-t (jump back after "tag" jumping with lsp-definition) by using settagstack.

Copy pasting [the implementation from vim-lsc](https://github.com/natebosch/vim-lsc/blob/b8a04ab0721c7383290ee997dd3bd491b8f5f93c/autoload/lsc/reference.vim#L22-L28) into s:handle_location (lsp/ui/vim.vim) seems to work, but since that's a callback I assume the cursor could have moved and it should be done earlier.

**Comment by prabirshrestha** [comment]
tagstack is already supported. please try latest master.
