### ISSUE TITLE
How to debug an lsp server that won't run?

### ISSUE THREAD

**Issue by idbrii** [prabirshrestha/vim-lsp#263]
I configured vim-lsp with verbose output to a log file:
	
    let g:lsp_log_verbose = 1
    let g:lsp_log_file = expand('c:/code/lsp.log')

But the log has some not very helpful output:

    2019-01-22 4:41:51 PM:["lsp#register_server","server registered","lua-lsp"]
    2019-01-22 4:41:51 PM:["s:on_text_document_did_open()",1,"lua","C:/code/project","file:///C:/code/project/main.lua"]
    2019-01-22 4:41:51 PM:[{"response":{"error":{"data":{"cmd":["lua-lsp"],"__error__":"vim-lsp","server_name":"lua-lsp"},"code":0,"message":"failed to start server"}}}]

Is there more I can do from vim-lsp to debug why it "failed to start server"?

* The log isn't clear whether the server started and issued a "failed to start server" error or if vim-lsp couldn't run the server executable.
* While the message looks like an error rpc from the server, [that error message appears in vim-lsp](https://github.com/prabirshrestha/vim-lsp/blob/c39e2633b9c0e7f9fcd683fba3804654e5c845f0/autoload/lsp.vim#L354). It couldn't start the server, but I don't know what to do to fix it. Is my vim-lsp configuration wrong? Does the path to the server not exist? Is there a failure in async.vim? etc.

Reading the code, it looks like there's no additional information, so I guess this is a feature request to add helpful debug info.

**Comment by prabirshrestha** [comment]
Language servers should either write to stderr or should have an option to pass custom logfile.

A good example of this is https://github.com/theia-ide/typescript-language-server/blob/master/README.md

**Comment by prabirshrestha** [comment]
@idbrii any update on this?

**Comment by idbrii** [comment]
Not yet. I gave up on using lua-lsp for the duration of my gamejam.

I debugged a bit in the code and it looks like there's not much vim-lsp can do to provide more information (aside from my above commit). Looks like async.vim would have to support `verbose`.

(I'm not looking for you to help me get my server working. I'd just like vim-lsp to have better support for debugging these issues.)

**Comment by prabirshrestha** [comment]
Based on lua-lsp seems like it is actually a shell command. Can you try this instead?

```vim
 'cmd': {server_info->[&shell, &shellcmdflag, 'lua-lsp']},
```

**Comment by prabirshrestha** [comment]
Actually noticed that you are using windows due to the `c:/path`. `lua-lsp` needs to ship `lua-lsp.cmd` along with `lua-lsp` bash file similar how node npm packages are shipped. On windows it will use `lua-lsp.cmd` and on unix it will use `lua-lsp` bash file. Shebangs are not supported in windows. Unlike neovim, vim starts without shell, so it doesn't know how to run 'lua-lsp.cmd'. Using `[&shell, &shellcmdflag]` helps in this case.

**Comment by prabirshrestha** [comment]
@idbrii any updates on this?

**Comment by idbrii** [comment]
lua-lsp ships a lua-lsp.bat that runs lua.exe with arguments to load the server script.

Looks like your shell argument recommendation is documented in `:help vim-lsp-server_info`. I didn't see that because I dove in based on the readme. Using those shell arguments gives me more useful log information to debug some issues with lua-lsp.

Now it's stuck on 'lua-lsp: starting', but I need to read through vim-lsp's docs to see what else I'm missing. 

I don't suppose there's anyway for vim-lsp to determine when `[&shell, &shellcmdflag]` would be needed and complain?

**Comment by prabirshrestha** [comment]
By the way there is also a way to enable logs on job api for vim. You will need to read the docs though.

**Comment by prabirshrestha** [comment]
@idbrii Did you make any progress on this?

**Comment by idbrii** [comment]
In the end, I gave up on lua-lsp and use either emmylua-ls (java, but works really well) and sumneko-lua-language-server (lua, but has issues with asyncomplete).
