### ISSUE TITLE
Fix from #158 and #160 reverted by 34c2a1e 

### ISSUE THREAD

**Issue by greghensley** [prabirshrestha/vim-lsp#264]
Commit 34c2a1e appears to have reverted bugfixes to EOL handling in [s:get_text_document_text](https://github.com/prabirshrestha/vim-lsp/blob/34c2a1e851aab701e4241d65dbc581546800551e/autoload/lsp.vim#L621), introduced in PRs #158 and #160.

**Comment by prabirshrestha** [comment]
@greghensley would you like to send a PR for this.

**Comment by greghensley** [comment]
Duplicate of #301
