### ISSUE TITLE
[Bug] LspDefinition can't open the file when `+` included in the file path.

### ISSUE THREAD

**Issue by skanehira** [prabirshrestha/vim-lsp#268]
**Bug:** 
LspDefinition can't open the file when `+` included in the file path.

 **relate:**
https://github.com/prabirshrestha/vim-lsp/issues/167

 **vim-lsp.log:**
```
月  1/28 15:12:14 2019:["s:on_stdout client request on_notification() error","Vim(let):E484: ファイル \"/Users/skanehira/dev/go/pkg/mod/github.com/labstack/echo@v3.3.5 incompatible/echo.go\" を開けません"] 
```

**Comment by mattn** [comment]
This is fixed by https://github.com/prabirshrestha/vim-lsp/pull/269
