### ISSUE TITLE
Line removal sends empty contentChanges in textDocument/didChage

### ISSUE THREAD

**Issue by Tert0z** [prabirshrestha/vim-lsp#270]
When line is removed from file then `textDocument/didChage` sent to server contain empty `contentChanges`. 
I believe that problem lies in following part of code:
https://github.com/prabirshrestha/vim-lsp/blob/daaec92efed3fcc06aa3c61990718f0e773ca932/autoload/lsp.vim#L454-L457

Line removal causes that `l:changes.text` is empty but `line` in range start and end is different.
`:echo lsp#utils#diff#compute(['a','b','c'],['a','b'])`
`{'range': {'end': {'character': 1, 'line': 2}, 'start': {'character': 1, 'line': 1}}, 'text': '', 'rangeLength': 2}  
`

`:echo lsp#utils#diff#compute(['a','b','c'],['a','b','c'])`
`{'range': {'end': {'character': 1, 'line': 2}, 'start': {'character': 1, 'line': 2}}, 'text': '', 'rangeLength': 0}  
`

**Comment by mattn** [comment]
This seems to be fixed by https://github.com/prabirshrestha/vim-lsp/pull/272

Could you please try this again?

**Comment by Tert0z** [comment]
Yes I can confirm that with fixes from #272 now removing lines works correctly.
