### ISSUE TITLE
default rootUri

### ISSUE THREAD

**Issue by mattn** [prabirshrestha/vim-lsp#274]
https://github.com/castwide/solargraph/pull/151

rootUr should be able to set null for default behavior.

**Comment by prabirshrestha** [comment]
Read the spec seems like all version v1,v2 and v3 supports null. We should fix it.

**Comment by prabirshrestha** [comment]
Now that I think of it this case was already supported when I implemented it.

https://github.com/prabirshrestha/vim-lsp/blob/e090d84150f65a05914865a1f0dc55518ad70b10/autoload/lsp.vim#L380-L392

If you provide `root_uri` as function.

```
function! s:find_root_uri(server_name) abort
    " add your custom logic here
    " return empty string if you want to vim-lsp to ignore initialization
endfunction

 au User lsp_setup call lsp#register_server({
        \ 'name': 'solargraph',
        \ 'cmd': {server_info->['solargraph']},
        \ 'root_uri': function('s:find_root_uri'),
        \ 'whitelist': ['python'],
        \ })
```

Does it mean `let l:root_uri = lsp#utils#get_default_root_uri() ` is not a good default instead?

If there was a plugin specific to solargraph, then it is easier for the users then users don't need to do to much. I actually have created org for these sort of plugins. https://github.com/vimlsp. Unforutnately vim-lsp was taken already.

```vim
Plug 'vimlsp/solargraph'
```

**Comment by mattn** [comment]
Cool. Now I sent e-mail to GitHub to ask that we can use vim-lsp if they are not active.

**Comment by prabirshrestha** [comment]
That would be great.

**Comment by mattn** [comment]
Unfortunately, vim-lsp seems to be active on private repos.

**Comment by prabirshrestha** [comment]
@mattn Did `'root_uri': function('s:find_root_uri'),` solve the issue?

**Comment by mattn** [comment]
I am convinced that it will work, but solargraph still does not go well. Hmm. I tried `{x->0}`. But don't try other yet.

**Comment by prabirshrestha** [comment]
Closing for now. I think it should be possible.
