### ISSUE TITLE
Automatically displaying function documentation (i.e. LspHover) while typing?

### ISSUE THREAD

**Issue by fgimian** [prabirshrestha/vim-lsp#275]
Hey there, thanks so much for your amazing work on this plugin for vim 😄 

When using LSP in Sublime Text, I can easily see function documentation in a little tooltip as I type:

![screen shot 2019-02-02 at 11 24 45 pm](https://user-images.githubusercontent.com/1811813/52169256-747f1880-2789-11e9-8871-42f1412a465d.png)

When using vim-lsp and vim, I can see the suggestions as I type:

![screen shot 2019-02-02 at 11 29 07 pm](https://user-images.githubusercontent.com/1811813/52169258-777a0900-2789-11e9-86c7-7717aa64f1f7.png)

However, this popup disappears when I open my brackets to type the parameters. Is there a way to keep this displayed and highlight which parameter I'm currently entering like Sublime Text does above?

Further to this, it seems the only way to see documentation once I type the opening bracket is to use the `:LspHover` command, which gives me this:

![screen shot 2019-02-02 at 11 29 27 pm](https://user-images.githubusercontent.com/1811813/52169269-9082ba00-2789-11e9-99f5-38b594c6b690.png)

Is there a way to display this information automatically as you are typing?
I also noticed that this documentation would disappear after I started typing my parameter names in the brackets too. Not sure if there's a way to avoid that happening.

I attempted to explicitly set `completeopt` to include `preview` but that didn't seem to help.

Any help is greatly appreciated
Fotis

**Comment by fgimian** [comment]
So I've managed to get one step closer.  I had to do the following to see automatic previews of functions:

```
let asyncomplete_auto_completeopt = 0
set completeopt=menuone,noinsert,noselect,preview
```

It seems that `set completeopt+=preview` simply won't work because `completeopt` is entire overridden by asyncomplete.vim.  I'm not sure if this is a bug?

So I guess the main questioning remaining is, is there a way to see the function signature or preview window while typing function arguments?

vim-go [seems to have attempted this](https://github.com/fatih/vim-go/pull/685) 😄 

Cheers
Fotis

**Comment by mikew** [comment]
Looks like `textDocument/signatureHelp` exists in LSP. There was even an issue created here for it, but the author closed it. https://github.com/prabirshrestha/vim-lsp/issues/53

vim-lsc seems to have support for it: https://github.com/natebosch/vim-lsc/blob/c6d088d86cf485567cdafcf451c8b265b1620efe/autoload/lsc/signaturehelp.vim#L17-L54

**Comment by fgimian** [comment]
> Looks like `textDocument/signatureHelp` exists in LSP. There was even an issue created here for it, but the author closed it. #53
> 
> vim-lsc seems to have support for it: https://github.com/natebosch/vim-lsc/blob/c6d088d86cf485567cdafcf451c8b265b1620efe/autoload/lsc/signaturehelp.vim#L17-L54

Thanks a lot for the reply.  I also found deoplete does it well, so I may try that again too.

So far vim-lsp has been my favourite LSP plugin so would be lovely if it supported this functionality in future.

Kindest Regards
Fotis

**Comment by prabirshrestha** [comment]
MenuPopupChanged https://github.com/neovim/neovim/pull/9616 and floating windows should allow this in the future. Will wait for it to stabilize first.

**Comment by mkwork** [comment]
@prabirshrestha, did you know that `jedi-vim` has this feature implementation? It's quite tricky and my vim coding skills are too low for this implementation generalization. But, may be you would like to have a look.

**Comment by prabirshrestha** [comment]
There is a discussion going on floating window. Will take time for vim to support it. Neovim support was merged this week. https://github.com/vim/vim/issues/4063

I would rather wait for a proper floating window support and have something like this instead instead of hacks. I'm not a fan of the preview window as it flickers the buffer too much.

![image](https://user-images.githubusercontent.com/287744/53836047-d3c87800-3f43-11e9-95e4-caead82db8e8.png)

**Comment by mkwork** [comment]
It's implemented within conceal instead of preview windows or other echodoc style distractive workrarounds :) Yep it's dirty hack. But it works like a charm, just try it on any python helloworld.

**Comment by zorgick** [comment]
@prabirshrestha any news? Is it implemented already? Man, I am fascinated by your plugin and I don't want to move again to another autocompletion plugin, but I'm really in lack of this feature.

**Comment by paltom** [comment]
@prabirshrestha are you going to support this? Now that Vim has `popup_create` and `CompleteChanged` it should be possible to implement this. This feature works in coc.nvim but it lefts artifacts when changing completion items and I prefer your LSP plugin anyway.

**Comment by dezza** [comment]
I see that the popup triggers on the latter arguments as well

__________________popup_happens
```function (arg1, <cursor>)```

The only issue I see with this is the closing/reopening of the popup and the lack of highlight on the "current" argument.

I guess the highlighting of current argument will take a little effort to implement.

If you want the signature always displayed you can do "echodoc.vim" similar behaviour by doing:
```vim
        echo get(l:contents, 0, '')
```
after line 80
https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim/signature_help.vim#L80
