### ISSUE TITLE
"textDocumentSync":{"change": xx} not recognized

### ISSUE THREAD

**Issue by soci64** [prabirshrestha/vim-lsp#285]
It's missing a ['change'] subscription before type(1) so that path handling this never executes. See below.

    --- capabilities.vim-old        2019-01-29 06:14:57.000000000 +0000
    +++ capabilities.vim    2019-02-07 19:04:16.635558625 +0000
    @@ -81,7 +81,7 @@
         let l:capabilities = lsp#get_server_capabilities(a:server_name)
         if !empty(l:capabilities) && has_key(l:capabilities, 'textDocumentSync')
             if type(l:capabilities['textDocumentSync']) == type({})
    -            if  has_key(l:capabilities['textDocumentSync'], 'change') && type(l:capabilities['textDocumentSync']) == type(1)
    +            if  has_key(l:capabilities['textDocumentSync'], 'change') && type(l:capabilities['textDocumentSync']['change']) == type(1)
                     let l:val = l:capabilities['textDocumentSync']['change']
                     return l:val >= 0 && l:val <= 2 ? l:val : 1
                 else

**Comment by mattn** [comment]
You're right. Will fix.
