### ISSUE TITLE
:LspDefinition will display an empty quickfix

### ISSUE THREAD

**Issue by lighttiger2505** [prabirshrestha/vim-lsp#293]
Hello.
vim-lsp is a great plugin. thank you.

I have points that I want you to correct about quickfix set by `:LspDefinition`.
I often display the result of the grep command in quickfix, but when I run `:LspDefinition`, an empty quickfix is displayed.
In this case need to run `:colder` to display the previous quickfix. I think this is undesirable.

I guess that the reason is that you have set an empty quickfix in the following places
https://github.com/prabirshrestha/vim-lsp/blob/043340455683463a3c8f854b7ac4bdfed70089d9/autoload/lsp/ui/vim.vim#L34

**Comment by prabirshrestha** [comment]
Seems like we need to fix these.

* Reset quick-list just before filling it again, not before sending request - https://github.com/prabirshrestha/vim-lsp/issues/76
* If there is only one `LspDefinition` don't even bother clearing quickfix.

The reason currently it clears quickfix is vim-lsp actually supports multiple langservers for the same filetype.

**Comment by lighttiger2505** [comment]
> * If there is only one `LspDefinition` don't even bother clearing quickfix.

I thought that correspondence was already done about the that case.

https://github.com/prabirshrestha/vim-lsp/blob/043340455683463a3c8f854b7ac4bdfed70089d9/autoload/lsp/ui/vim.vim#L368

**Comment by prabirshrestha** [comment]
That is for opening quickfix not for clearning quickfix. We always clear quickfix.

**Comment by lighttiger2505** [comment]
I see. I was wrong.

> The reason currently it clears quickfix is vim-lsp actually supports multiple langservers for the same filetype.

Why were you speaking like this?
I thought that it was not necessary to clear quickfix allways.

**Comment by adaszko** [comment]
> That is for opening quickfix not for clearning quickfix. We always clear quickfix.

I just got bitten by this.  This interferes with [asyncrun](https://github.com/skywind3000/asyncrun.vim) populating quickfix with compilation errors.  Shouldn't `LspDefinition` use location list instead?

**Comment by nickspoons** [comment]
In a branch of my fork I have removed all of the `call setqf([])` lines, as I also find this behaviour problematic. I have also made some other changes (currently specific to my usage), including calling a user-specified function to open the quickfix, e.g. [qf#OpenQuickFix()](https://github.com/romainl/vim-qf/blob/master/autoload/qf.vim#L115).

I would like to refactor some of this to a PR but I can't work out how vim-lsp uses multiple language servers for a filetype - are there tests for this? Or a good suggestion of a filetype with multiple language servers which work together, that I can test with?

**Comment by hoopchen** [comment]
same issue here..

**Comment by mattn** [comment]
Did you try latest?

**Comment by prabirshrestha** [comment]
please try latest master. also it is now using loclist.

**Comment by adaszko** [comment]
Just tried latest master.  The `call setqflist([])` call [is still there](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim.vim#L83).

**Comment by nickspoons** [comment]
I don't think this issue should be auto-closed. The discussed line is [still present](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim.vim#L318) so if the issue is to be closed, it should be "on purpose", not by a bot.

**Comment by nickspoons** [comment]
Ugh. Bots.
