### ISSUE TITLE
Add option to disable split when going to definition

### ISSUE THREAD

**Issue by jason0x43** [prabirshrestha/vim-lsp#307]
A change was recently merged (#277) that causes "go to definition" to open a split when the current buffer has been edited. I, at least, much preferred the previous behavior. The change seems to have been made to deal with E37 errors, but that should only come up if `hidden` is disabled. A better solution would be to only use the new behavior if `hidden` is disabled, or to make the new behavior a configurable option.

**Comment by jason0x43** [comment]
Also, the new behavior will continually create new splits as further definitions are followed, which can quickly get messy.

**Comment by mattn** [comment]
This change looks good?
```
if &modified && !&hidden
```

>Also, the new behavior will continually create new splits as further definitions are followed, which can quickly get messy.

When the buffer jumped to is not modified, the next jump does not split buffer, I think.

**Comment by jason0x43** [comment]
```
if &modified && !&hidden
```

Yes, that should fix the issue.

> When the buffer jumped to is not modified, the next jump does not split buffer, I think.

That's true, additional splits are only opened if the jumped-to buffer is also modified. However, that's not an uncommon situation when a user has `hidden` enabled.

**Comment by mattn** [comment]
Thanks for your explain. I'll fix this bug soon. If you have an idea for split window, please file new issue or create PR. :)
