### ISSUE TITLE
Show completion without typing a first character

### ISSUE THREAD

**Issue by timbedard** [prabirshrestha/vim-lsp#308]
So something I've noticed with python completion from pyls is that no contextual completion is offered without the first character of a symbol. With vim-jedi and deoplete-jedi, I can type `from requests import ` and I will receive completion suggestions from within the requests package. Is this a limitation of vim-lsp, asyncomplete, or pyls? I haven't had the chance to try out other language servers yet, so apologies if this is just a pyls thing.

**Comment by thomasfaingnaert** [comment]
I'm using vim-lsp and pyls with omnifunc and I do get suggestions if I only type `from requests import<space><C-x><C-o>`. So this most likely is not an issue in vim-lsp. Could you provide logs to check what completion items pyls sends to vim-lsp? You may also want to try if omnifunc gives the same issue, to check if asyncomplete is the problem or not.

**Comment by prabirshrestha** [comment]
Please provide logs. Also do give asyncomolete v2 a try.
