### ISSUE TITLE
Support LSP 3.0

### ISSUE THREAD

**Issue by laktak** [prabirshrestha/vim-lsp#311]
The readme does not mention which version of LSP this plugin supports but according to https://github.com/georgewfraser/java-language-server/issues/51#issuecomment-465459314 it's 2.0:

> `vim-lsp` only sends v2.0 messages from best I can tell. Notably it doesn't send the `initialized` message to language servers, so language servers like this one that are coded to v3.0 may not work.

Are there plans to make vim-lsp compatible with v3 of the protocol?

**Comment by doriath** [comment]
Duplicate of #166?

**Comment by prabirshrestha** [comment]
Please try https://github.com/prabirshrestha/vim-lsp/pull/317

**Comment by laktak** [comment]
Works with java-language-server. Thank you!
