### ISSUE TITLE
Length of list for `cmd` restricted to 3?

### ISSUE THREAD

**Issue by niklaas** [prabirshrestha/vim-lsp#312]
Most probably I overlooked something here. How long can be the list provided to `cmd` when registering a server with `lsp#register_server()`? As I understand `job_start()`, which is eventually called through `async.vim`, it can be "endless" and all items are concatenated to a string separated by spaces.

For example I use the following to register the language server for TypeScript:

```
  autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
        \ 'whitelist': ['typescript'],
        \ 'priority': 10,
        \ })
```

where it says

```
'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
```

This works perfectly. But as soon as I change this to

```
'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server ', '--stdio']},
```

the server does not start.

I did some debugging and it seems only `typescript-language-server` is executed i.e., without the argument provided as last item in the list.

I come up with this because I'm figuring out how to run Eclipse's language server for Java with `vim-lsp`. There it would be quite handy to provide all the arguments as items in the list. At this stage, the way I register the server looks like the following but this does not work. And debugging gives me the output of `java` without any arguments given, telling me that I need to provide arguments.

```
if executable('java')
  autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'java-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag,
        \   'java',
        \     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        \     '-Dosgi.bundles.defaultStartLevel=4',
        \     '-Declipse.product=org.eclipse.jdt.ls.core.product',
        \     '-Dlog.level=ALL',
        \     '-noverify',
        \     '-Xmx1G',
        \     '-jar /home/niklaas/dev/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar',
        \     '-configuration /home/niklaas/dev/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux',
        \     '-data /home/niklaas/git/some/path'
        \   ]},
        \ 'whitelist': ['java'],
        \ 'priority': 10,
        \ })
endif
```

A solution is to provide the arguments in the final item as a single string. But maybe someone can tell me why this does not work. I'm not very much into VimL but from what I see, it actually should work. :-)

**Comment by mattn** [comment]
This is related to the behavior of your shell.

```
[&shell, &shellcmdflag, 'typescript-language-server --stdio']
```

Vim start process &shell with flag &shellcmdflag. 1 more argument `typescript-language-server --stdio`.

```
[&shell, &shellcmdflag, 'typescript-language-server ', '--stdio']
```

Vim start process &shell with flag &shellcmdflag. 2 mroe arguments `typescript-language-server` and `--stdio`.

```
$ bash -c 'echo 1' 'echo 2'
1
```

bash does not handle second argument for `-c` flag. So the arguments to jdtls must be a string.

```vim
if executable('java')
  autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'java-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag,
        \   join(['java',
        \     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        \     '-Dosgi.bundles.defaultStartLevel=4',
        \     '-Declipse.product=org.eclipse.jdt.ls.core.product',
        \     '-Dlog.level=ALL',
        \     '-noverify',
        \     '-Xmx1G',
        \     '-jar /home/niklaas/dev/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar',
        \     '-configuration /home/niklaas/dev/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux',
        \     '-data /home/niklaas/git/some/path'], ' '),
        \   ]},
        \ 'whitelist': ['java'],
        \ 'priority': 10,
        \ })
endif
```

**Comment by niklaas** [comment]
> This is related to the behavior of your shell.

Uff, that's it! Totally makes sense. I had been digging around in VimL code trying to figure out what I'm misunderstanding and did not realize it's a "simple" shell issue.

Thanks a lot for taking the time pointing that out and providing a solution. I'll adapt this soon and post my solution (because some paths I want to generate dynamically). I had been thinking about concatenating the actual command like you did too, so thanks for providing a working example. :)

**Comment by niklaas** [comment]
As promised. Probably the following can be improved. Especially finding out the `-data` path automatically with something like

```
lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'pom.xml')
```

That said, for me this isn't a solution because the structure of the Java project I work on is quite complex, consisting of several sub-projects etc. The following should give enough flexibility.

```
" This requires g:eclipse_jdt_ls_data_path, g:eclipse_jdt_ls_jar and
" g:eclipse_jdt_ls_path to be set. The last is the path where you checked out
" Eclipse's language server (see references below); the second is the
" *filename* of the JAR generated by the project; and the first is the
" workspace of your project. For example:
"
"   let g:eclipse_jdt_ls_data_path = '/absolute/path/to/workspace'
"   let g:eclipse_jdt_ls_jar = 'org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar'
"   let g:eclipse_jdt_ls_path = expand($HOME . '/dev/eclipse.jdt.ls')
"
" References:
"
" - https://github.com/eclipse/eclipse.jdt.ls
" - https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line
"
if executable('java')
  autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'java-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag,
        \   join(['java',
        \     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        \     '-Dosgi.bundles.defaultStartLevel=4',
        \     '-Declipse.product=org.eclipse.jdt.ls.core.product',
        \     '-Dlog.level=ALL',
        \     '-noverify',
        \     '-Xmx1G',
        \     '-jar ' . g:eclipse_jdt_ls_path . '/org.eclipse.jdt.ls.product/target/repository/plugins/' . g:eclipse_jdt_ls_jar,
        \     '-configuration ' . g:eclipse_jdt_ls_path . '/org.eclipse.jdt.ls.product/target/repository/config_linux',
        \     '-data ' . g:eclipse_jdt_ls_data_path
        \   ], ' ')]},
        \ 'whitelist': ['java'],
        \ 'priority': 10,
        \ })
endif
```

The three variables I set in a project-specifix `.exrc`.
