### ISSUE TITLE
<Plug>(lsp-next-error) problem

### ISSUE THREAD

**Issue by nickspoons** [prabirshrestha/vim-lsp#314]
Mapping to `<Plug>(lsp-next-error)` and `<Plug>(lsp-previous-error)` does not work for me. I am not quite sure what's happening - the cursor _sometimes_ navigates to the error, then moves back.

```vim
nmap <buffer> ,n <Plug>(lsp-next-error)
nmap <buffer> ,p <Plug>(lsp-previous-error)
```

If I map to the `:LspNextError` and `:LspPreviousError` commands directly things work correctly:

```vim
nnoremap <buffer> ,n :LspNextError<CR>
nnoremap <buffer> ,p :LspPreviousError<CR>
```

However, if I modify the `<Plug>` mappings from their current format to what I consider a more "traditional" mapping, my `nmap <buffer> ,n <Plug>(lsp-next-error)` mapping works again:

```vim
nnoremap <silent> <plug>(lsp-next-error) :call lsp#ui#vim#signs#next_error()<CR>
nnoremap <silent> <plug>(lsp-previous-error) :call lsp#ui#vim#signs#previous_error()<CR>
```

What is the rationale behind the current `<Plug>` mappings, using an `<expr>` and array instead of just calling a function? Do they solve a problem?

[Current mappings:](https://github.com/prabirshrestha/vim-lsp/blob/master/plugin/lsp.vim#L57:L58):

```vim
nnoremap <expr> <plug>(lsp-next-error) [lsp#ui#vim#signs#next_error(),''][1]
nnoremap <expr> <plug>(lsp-previous-error) [lsp#ui#vim#signs#previous_error(),''][1]
```

**Comment by mattn** [comment]
Thanks. `<expr>` does not allow to call `winrestview`. Will fix.

**Comment by nickspoons** [comment]
Thanks @mattn!
