### ISSUE TITLE
Error when init with vscode-html-language-server

### ISSUE THREAD

**Issue by banminkyoz** [prabirshrestha/vim-lsp#319]
When open html file lsp crash and show this error:

```
Failed to initialize lsp-html with error -32603: Request initialize failed with message: Can not read property 'css' of undefined
```

This is my config (installed `vscode-html-languageserver-bin` globally):

```
if executable('html-languageserver')
  au User lsp_setup call lsp#register_server({
      \ 'name': 'html-languageserver',
      \ 'cmd': {server_info->[&shell, &shellcmdflag, 'html-languageserver --stdio']},
      \ 'whitelist': ['html', 'javascript', 'typescript'],
      \ })
endif
```

I'v found that someone have this problem too:

[vscode-html-languageserver-bin issue](https://github.com/vscode-langservers/vscode-html-languageserver-bin/issues/4)
[LanguageClient-neovim issue](https://github.com/autozimu/LanguageClient-neovim/issues/494)

First i think that this is the problem of `html-languageserver-bin`, but somehow they'v fixed it in [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/issues/494)

Do we have any workaround or fix for this ?. Thank you very much.

**Comment by mattn** [comment]
fixed by https://github.com/prabirshrestha/vim-lsp/pull/323

**Comment by banminkyoz** [comment]
Thank you all for your hard work :heart:

**Comment by carlevison** [comment]
@banminkyoz Any chance you could push up your updated ```autocomplete.vim``` settings, i'm having an issue with autocomplete working even though the server is running.

I'm wondering if i'm missing anything out.

**Comment by banminkyoz** [comment]
Hi @carlevison 

This's my current config for vim-lsp: [lsp.vim](https://github.com/banminkyoz/neovim/blob/master/configs/lsp.vim)

I'v confirmed that #323 fixed the initialize error. But it seem missing something, error signs is never show when there's error (There's an issue about that https://github.com/prabirshrestha/vim-lsp/issues/322)

Like you'v said, the autocomplete seem have problem, there's no autocomplete anymore

I'll look in to it when i'v time. There's an issue of `html_autocomplete` when i use `ncm2_html_subscope`. There's an issue, check it out: https://github.com/ncm2/ncm2-html-subscope/issues/1

I'm a front end developer. With out autocomplete and subscope attribute complete it's painful. Currently i'm back to use vscode. But i'll pay time to reconfig my [nvim config](https://github.com/banminkyoz/neovim). :)

**Comment by mattn** [comment]
FYI, html-language-server is NOT provide completionProvider.

**Comment by banminkyoz** [comment]
@mattn yep. Definitely. I forgot to say that it not error of `html-language-server` or `vim-lsp` :)

Btw, is default html_complete is one of neovim ? Sorry i'm not know much about thoses.

If you have time, please view the gif inside this [issue](https://github.com/ncm2/ncm2-html-subscope/issues/1)

If it's actually an error of html_autocomplete, then i sound raise an issue in neovim repo right ?

Thanks @mattn  :)

**Comment by mattn** [comment]
The completion feature is provided from client-side snippet feature. When https://github.com/prabirshrestha/vim-lsp/pull/306 will be merged, we will be able to use completion feature with html-languageserver.

**Comment by carlevison** [comment]
Thanks for the info guys, I didn't realise when switching from Sublime around a week a go that I would need to pull in so many different plugins to achieve autocompletion.

Are they any guides on how all these pieces fit together? because when I used Sublime I only needed the `LSP` package.

@banminkyoz Have you had any time to check if the branch waiting to be merged on `vim-lsp` solves our problem?

**Comment by prabirshrestha** [comment]
If you are using asyncomplete-omni, cursor move is fixed. @roxma you might want this patch in ncm2 omni - https://github.com/yami-beta/asyncomplete-omni.vim/pull/11

https://github.com/prabirshrestha/asyncomplete.vim/issues/70

Discussion in vim dev https://groups.google.com/forum/m/#!searchin/vim_dev/Html$20Omni/vim_dev/daDSGpggjqY

**Comment by banminkyoz** [comment]
@carlevison i'll test it tomorrow
Omg thanks @prabirshrestha so much. That's definitely the issue i have. Hope it'll be fixed soon. :heart:

**Comment by carlevison** [comment]
@banminkyoz thank you :) fingers crossed. I'd love to have autocomplete for html.

**Comment by banminkyoz** [comment]
Hi @carlevison,  i'v looked in your configuration. To enable html autocomplete you must remove this line:

```
au User Ncm2Plugin call ncm2#register_source({
  \ 'name' : 'html',
  \ 'priority': 9,
  \ 'subscope_enable': 1,
  \ 'scope': ['html'],
  \ 'mark': 'html',
  \ 'complete_length': -1,            <------------------------- This line
  \ 'complete_pattern': ['\<'],
  \ 'word_pattern': '[\w-]+',
  \ 'on_complete': ['ncm2#on_complete#omni', 'htmlcomplete#CompleteTags'],
  \ })
```
You may want to disable `ncm2-html-subscope` temporary. Cause there is an issue of cursor move just like @prabirshrestha has mentioned. Hope it'll be fixed soon :smile_cat:

**Comment by carlevison** [comment]
Just followed your instructions and it's working :) 

For some reason though it's completing like this `href="`without adding the closing `"` any ideas? I do have a plugin for auto closing.

**Comment by banminkyoz** [comment]
That's the normally behavior :)).Your idea is cool. Maybe you should open an issue about that option.
The problem is i don't know exactly where we should raise an issue :)))

**Comment by prabirshrestha** [comment]
about closing `href="` you need to find the owner of html omnifunc and get it approved by the author, once that is done the patch can be submitted to vim.
