### ISSUE TITLE
lsp_signs_enabled  broken

### ISSUE THREAD

**Issue by dc25** [prabirshrestha/vim-lsp#320]
Signs (error and info on lefthand side of vim window) don't appear.  Binary searching/testing shows that this started happening on the master branch with the latest merge : "Merge pull request #294 from prabirshrestha/redo-diagnostics" .  Testing on the merged branch shows that it started happening at revision "98f7abac7d0894889c2ea4a8cac55b7e44210866" : "cleanup" .

I'm running ubuntu 18.04, editing rust with rls as my language server.  This happens both with nvim and vim. 

Let me know if you need more info.

**Comment by mattn** [comment]
Please try

```
:echo has('signs') && has('patch-8.1.0772') && exists('*sign_define')
```

If you will see 0, you have to install newer version of Vim.

**Comment by prabirshrestha** [comment]
Also neovim currently doesn’t support the api yet. There is a Issue tracking it on neovim side.

**Comment by dc25** [comment]
@mattn,  I tried your test and got the result "0".   Then I installed the latest version of vim, ran your test again, and got the result "1" .   This had no effect on the behavior that I am seeing though.

Just to make it clear:   This was working in vim *and* neovim until it was, I believe, broken by the merge  to vim-lsp master branch on 2019-02-22 .  I can still get it to work if I jump through some hoops to work with a version of vim-lsp that does not have that merge.

**Comment by prabirshrestha** [comment]
@dc25 Are you telling with latest vim it is still broken?

**Comment by dc25** [comment]
yes

**Comment by mattn** [comment]
Could you please provide log file?

**Comment by dc25** [comment]
Sorry, my testing error.  With the latest vim (version 8.1.978), the problem goes away.    

The other results that I mentioned still are valid.  With the default vim and neovim installed by apt-get in Ubuntu 18.10 ( and 18.04 ), the signs (error and info on lefthand side of vim window) don't appear.  However, if you use an earlier vim-lsp as described in the original report, the signs appear in both vim and neovim.

**Comment by prabirshrestha** [comment]
That makes sense. There are no plans to support signs on older version since the new apis are cleaner and lot easier for us to maintain. Since this plugin will most likely only be used in dev machine we also assume that updating vim on dev machine is easy.
