### ISSUE TITLE
Any example for clang_complete like example?

### ISSUE THREAD

**Issue by adam900710** [prabirshrestha/vim-lsp#321]
Hi,

I'm converted from clang_complete (https://github.com/Rip-Rip/clang_complete), as it no longer works well for kernel.

After setting up `clangd` with `bear` for btrfs module, Lsp works pretty well, but I struggled with the key mapping.
Currently I'm using something copied from clang_complete (https://gist.github.com/adam900710/5c8b371ca68b8ed1104f75ea7d79c8f6) , but still can't handle the tag stack nor the snippet.

Any idea/example for tag stack/snippet?

**Comment by thomasfaingnaert** [comment]
I believe `:LspDefinition` does not alter the tag stack, though you can jump back and forth using the jump list mappings `CTRL-O` and `CTRL-I`.
Regarding snippet support: I'm currently working on integrating [UltiSnips](https://github.com/SirVer/ultisnips) and [neosnippet](https://github.com/SirVer/ultisnips) in vim-lsp. You may want to check if https://github.com/prabirshrestha/vim-lsp/pull/306 and either https://github.com/thomasfaingnaert/vim-lsp-ultisnips or https://github.com/thomasfaingnaert/vim-lsp-neosnippet works for you.

**Comment by prabirshrestha** [comment]
Unfortunatly neovim doesn't support the new signs api. You can follow the issue at https://github.com/neovim/neovim/issues/8668

Tagstack is something I do want to support soon. There were some active discussions going in vim mailing list so haven't looked at it yet. https://groups.google.com/forum/#!searchin/vim_dev/tagstack%7Csort:date/vim_dev/V4vfRwKilcU/g7xDmOlxBQAJ

For snippets do try @thomasfaingnaert PR first.

**Comment by prabirshrestha** [comment]
Waiting for https://github.com/vim/vim/pull/4010 to be merged upstream.

**Comment by andymass** [comment]
@prabirshrestha, would that patch cover your (or other LSP) plugin's needs?  Some feedback or proof of the concept might help get the PR moved forward.  Note that it's not necessary to add an "asynchronous" API to the tagfunc since vim processes job callbacks during sleep, and the expectation is that if the language server takes too long to respond, the tag operation will simply fail.

```vim
set tagfunc=TagFunc
let s:tags_ready = 0
let s:tag_wait_time = 200
let s:tags = []

function! TagFunc(pat, flag, info) abort
  let s:tags = []
  let s:tags_ready = 0

  " make LSP request which sets s:tags_ready on response

  " wait for response from LSP
  let tic = reltime()
  while 1000*reltimefloat(reltime(tic)) < s:tag_wait_time && !s:tags_ready
    sleep 20m
  endwhile
  return s:tags
endfunction
```

Of course, this can be made nicer by using a local dict instead of the globals which is passed in the request and then resolved in the response callback.

**Comment by ward** [comment]
> Waiting for [vim/vim#4010](https://github.com/vim/vim/pull/4010) to be merged upstream.

Just wanted to add that it seems to have been merged in https://github.com/vim/vim/commit/45e18cbdc40afd8144d20dcc07ad2d981636f4c9

**Comment by prabirshrestha** [comment]
tagstack is already supported. also please try https://github.com/hrsh7th/vim-vsnip for snippets.
