### ISSUE TITLE
Initialization options is not correctly passed to the server

### ISSUE THREAD

**Issue by ElArtista** [prabirshrestha/vim-lsp#326]
Since this commit: https://github.com/prabirshrestha/vim-lsp/commit/8a8f2131295a8fa26e0cec0c74a7dae54a0bfaf1 initializationOptions is not passed correctly in the initialize request.

This line:

```
let l:request['initialization_options'] = l:server_info['initialization_options']
```

Should be something like this:
```
let l:request.params['initializationOptions'] = l:server_info['initialization_options']
```
for the initialization options to be passed correctly into the language servers.
The above fix has been tested with latest vim-lsp and ccls language server.

**Comment by mattn** [comment]
Oops. Sorry. Will fix soon.

**Comment by ElArtista** [comment]
Initialization options key should be 'initializationOptions' not 'initialization_options' as it is on the pull request.

**Comment by mattn** [comment]
Hmm, I seems to be slept.
