### ISSUE TITLE
LspDeclaration error:"Retrieving declaration not supported for cpp"

### ISSUE THREAD

**Issue by Tom8C** [prabirshrestha/vim-lsp#333]
I just installed cquery and vim-lsp and i am trying to use LspDefinition and LspDeclaration.

When in the header file :LspDefinition works as expected and jump to the method definition in the source file. However i cannot jump back to the declaration with :LspDeclaration i got the following error: `Retrieving declaration not supported for cpp`

I am using gvim on windows 10.
- C:\Users\username\ _vimrc
```
" register lsp server
let g:lsp_log_verbose = 1
let g:lsp_log_file = 'vim-lsp.log'

if executable('cquery')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'cquery',
      \ 'cmd': {server_info->['cquery']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
      \ 'initialization_options': { 'cacheDirectory': 'cquery_cache' },
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
      \ })
endif
```
- test_project\include\dummy\dummy.hpp
```
class MyDummyClass
{
public:
  MyDummyClass();
public:
  void my_dummy_method();
};
```
- test_project\source\dummy.cpp
```
#include "dummy/dummy.hpp"

MyDummyClass::MyDummyClass(){
}
void MyDummyClass::my_dummy_method(){
}
```

**Comment by prabirshrestha** [comment]
Please attach logs.

**Comment by Tom8C** [comment]
[vim-lsp.log](https://gist.github.com/Tom8C/cc2c0af3098b45fa8168a23c83742005)

**Comment by JankoDedic** [comment]
I'm using clangd (Windows 8.1 | gVim) and I'm having the same problem. `declarationProvider` is nowhere to be found in the logs.

**Comment by mattn** [comment]
As I can see the log, you specify unsupported option `-Wunknown-argument`.

**Comment by prabirshrestha** [comment]
closing stale issue,
