### ISSUE TITLE
Customize Neovim virtual text highlight group?

### ISSUE THREAD

**Issue by vshl** [prabirshrestha/vim-lsp#338]
I can't find my way around customizing it. I tried customizing the signs highlight group but that didn't do anything. The virtual text is currently the same color as the Normal highlight group, so it's hard to distinguish it.

**Comment by kadrach** [comment]
The README:
> Virtual text will use the same highlight groups as signs feature.

From my config files:

```viml
" Hook up vim-lsp's virtual text feature with gruvbox
highlight link LspError GruvboxGray                  
highlight link LspWarning GruvboxGray                
highlight link LspInformation GruvboxGray            
highlight link LspHint GruvboxGray                   
```

**Comment by kadrach** [comment]
Note that you need `LspErrorText`, `LspWarningText`, ... as of https://github.com/prabirshrestha/vim-lsp/pull/343.
