### ISSUE TITLE
Virtual Text and Signs highlight defaults don't work

### ISSUE THREAD

**Issue by aktau** [prabirshrestha/vim-lsp#340]
Sorry for not sending a PR but it's been a long time since I properly used GitHub and moreover I wasn't sure if what I'm seeing is intentional. From `signs.vim` and `virtual.vim`:

```vim
let s:severity_sign_names_mapping = {
    \ 1: 'LspError',
    \ 2: 'LspWarning',
    \ 3: 'LspInformation',
    \ 4: 'LspHint',
    \ }

if !hlexists('LspErrorText')
    highlight link LspErrorText Error
endif

" ...
```

Basically the mapping says `LspWarning` but the highlight linking is for LspError**Text**, which is not the same thing. As a result, the virtual text in my editor for diagnostic warnings is "normal", making it look very strange as it's not spaced apart far from EOL. Was it the intention to do:

```vim
if !hlexists('LspError')
    highlight link LspError Error
endif
```

Instead?

**Comment by prabirshrestha** [comment]
Seems like a bug. Feel free to send a PR. 

I have also been wondering if we should actually use a different name virtual text. @hauleth

**Comment by grainrigi** [comment]
Made a PR(#343).
signs.vim seems to handle the highlight group name appropriately(signs.vim:47)

**Comment by prabirshrestha** [comment]
Merged. Thanks.
