### ISSUE TITLE
no diagnostics results with bingo

### ISSUE THREAD

**Issue by Cosson2017** [prabirshrestha/vim-lsp#341]
There is no diagnostics results by bingo.

**Comment by mattn** [comment]
Can you provide log?

```
let g:lsp_log_verbose= 1
let g:lsp_log_file = '/tmp/lsp.log'
```

**Comment by Cosson2017** [comment]
@mattn 
I already enable log verbose and execute :LspDocumentDiagnostics, but no log output and cmd line show: 
![image](https://user-images.githubusercontent.com/20379044/54510379-fddc5a00-4987-11e9-8fd9-719f30540007.png)

**Comment by Cosson2017** [comment]
@mattn
I already enable log verbose and execute :LspDocumentDiagnostics, but no log output and cmd line show:
![image](https://user-images.githubusercontent.com/20379044/54510457-46941300-4988-11e9-8b7f-8db681d1d662.png)

**Comment by mattn** [comment]
Nothing should be displayed. Could you please paste the log file here?

**Comment by Cosson2017** [comment]
When I typed LspDocumentDiagnostics, there is no log.

**Comment by Cosson2017** [comment]
Tue 19 Mar 2019 12:42:07 PM CST:["lsp#register_server", "server registered", "bingo"]
Tue 19 Mar 2019 12:42:07 PM CST:["lsp#register_server", "server registered", "rls"]
Tue 19 Mar 2019 12:42:07 PM CST:["lsp#register_server", "server registered", "ccls"]
Tue 19 Mar 2019 12:42:07 PM CST:["lsp#register_server", "server registered", "lua-lsp"]
Tue 19 Mar 2019 12:42:07 PM CST:["lsp#register_server", "server registered", "javascript-typescript-stdio"]
Tue 19 Mar 2019 12:42:07 PM CST:["lsp#register_server", "server registered", "php-lsp"]
Tue 19 Mar 2019 12:42:07 PM CST:["vim-lsp virtual text enabled"]
Tue 19 Mar 2019 12:42:07 PM CST:["s:on_text_document_did_open()", 1, "go", "/home/lks/Projects/go/module/test", "file:///home/lks/Projects/go/module/test/main.go"]
Tue 19 Mar 2019 12:42:07 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "lsp_id": 3, "server_name": "bingo"}, "message": "started lsp server successfully"}}]
Tue 19 Mar 2019 12:42:07 PM CST:["--->", 3, "bingo", {"method": "initialize", "params": {"rootUri": "file:///home/lks/Projects/go/module/test", "capabilities": {"workspace": {"applyEdit ": true}}, "rootPath": "/home/lks/Projects/go/module/test", "processId": 29533, "trace": "off"}}]
Tue 19 Mar 2019 12:42:07 PM CST:["<---(stderr)", 3, "bingo", ["langserver-go: reading on stdin, writing on stdout", ""]]
Tue 19 Mar 2019 12:42:07 PM CST:["<---(stderr)", 3, "bingo", ["Passing an initialize rootPath URI (\"file:///home/lks/Projects/go/module/test\") is deprecated. Use rootUri instead.", ""]]
Tue 19 Mar 2019 12:42:07 PM CST:["<---", 3, "bingo", {"response": {"method": "window/showMessage", "jsonrpc": "2.0", "params": {"message": "load /home/lks/Projects/go/module/test successfully! elapsed time: 0 seconds, cache: false, go module: false.", "type": 3}}}]
Tue 19 Mar 2019 12:42:07 PM CST:["<---", 3, "bingo", {"response": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "xdefinitionProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentRangeFormattingProvider": true, "xworkspaceReferencesProvider": true, "documentFormattingProvider": true, "xworkspaceSymbolByProperties": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "request": {"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///home/lks/Projects/go/module/test", "capabilities": {"workspace": {"applyEdit ": true}}, "rootPath": "/home/lks/Projects/go/module/test", "processId": 29533, "trace": "off"}}}]
Tue 19 Mar 2019 12:42:07 PM CST:["--->", 3, "bingo", {"method": "initialized", "params": {}}]
Tue 19 Mar 2019 12:42:07 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "configuration sent"}}]
Tue 19 Mar 2019 12:42:07 PM CST:["s:update_file_content()", 1]
Tue 19 Mar 2019 12:42:07 PM CST:["--->", 3, "bingo", {"method": "textDocument/didOpen", "params": {"textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go", "version": 1, "languageId": "go", "text": "package main\n\nimport (\n\t\"fmt\"\n)\n\nfunc main() {\n\tfmt.Printf(\"hello world\")\n\tfmt.Println(\"hello word\")\n\n}\n"}}}]
Tue 19 Mar 2019 12:42:07 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "filetype": "go", "server_name": "bingo"}, "message": "textDocument/open sent"}}]
Tue 19 Mar 2019 12:42:07 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "not dirty"}}]
Tue 19 Mar 2019 12:42:08 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "server already started"}}]
Tue 19 Mar 2019 12:42:08 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "xdefinitionProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentRangeFormattingProvider": true, "xworkspaceReferencesProvider": true, "documentFormattingProvider": true, "xworkspaceSymbolByProperties": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "bingo"}, "message": "lsp server already initialized"}}]
Tue 19 Mar 2019 12:42:08 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "configuration sent"}}]
Tue 19 Mar 2019 12:42:08 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "already opened"}}]
Tue 19 Mar 2019 12:42:09 PM CST:["s:update_file_content()", 1]
Tue 19 Mar 2019 12:42:09 PM CST:["--->", 3, "bingo", {"method": "textDocument/didChange", "params": {"contentChanges": [{"range": {"end": {"character": 0, "line": 9}, "start": {"character": 0, "line": 9}}, "text": "\txx\n", "rangeLength": 0}], "textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go", "version": 2}}}]
Tue 19 Mar 2019 12:42:09 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "textDocument/didChange sent"}}]
Tue 19 Mar 2019 12:42:09 PM CST:["--->", 3, "bingo", {"method": "textDocument/completion", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go"}, "position": {"character": 3, "line": 9}}}]
Tue 19 Mar 2019 12:42:09 PM CST:["<---", 3, "bingo", {"response": {"id": 2, "result": {"isIncomplete": false, "items": []}, "jsonrpc": "2.0"}, "request": {"method": "textDocument/completion", "jsonrpc": "2.0", "id": 2, "params": {"textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go"}, "position": {"character": 3, "line": 9}}}}]
Tue 19 Mar 2019 12:42:10 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "server already started"}}]
Tue 19 Mar 2019 12:42:10 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "xdefinitionProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentRangeFormattingProvider": true, "xworkspaceReferencesProvider": true, "documentFormattingProvider": true, "xworkspaceSymbolByProperties": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "bingo"}, "message": "lsp server already initialized"}}]
Tue 19 Mar 2019 12:42:10 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "configuration sent"}}]
Tue 19 Mar 2019 12:42:10 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "already opened"}}]
Tue 19 Mar 2019 12:42:10 PM CST:["s:update_file_content()", 1]
Tue 19 Mar 2019 12:42:10 PM CST:["--->", 3, "bingo", {"method": "textDocument/didChange", "params": {"contentChanges": [{"range": {"end": {"character": 3, "line": 9}, "start": {"character": 3, "line": 9}}, "text": "x\n\txx", "rangeLength": 0}], "textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go", "version": 3}}}]
Tue 19 Mar 2019 12:42:10 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "textDocument/didChange sent"}}]
Tue 19 Mar 2019 12:42:10 PM CST:["--->", 3, "bingo", {"method": "textDocument/completion", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go"}, "position": {"character": 3, "line": 10}}}]
Tue 19 Mar 2019 12:42:10 PM CST:["<---", 3, "bingo", {"response": {"id": 3, "result": {"isIncomplete": false, "items": []}, "jsonrpc": "2.0"}, "request": {"method": "textDocument/completion", "jsonrpc": "2.0", "id": 3, "params": {"textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go"}, "position": {"character": 3, "line": 10}}}}]
Tue 19 Mar 2019 12:42:11 PM CST:["s:on_text_document_did_change()", 1]
Tue 19 Mar 2019 12:42:11 PM CST:["s:send_didchange_queue() will be triggered"]
Tue 19 Mar 2019 12:42:12 PM CST:["s:on_text_document_did_save()", 1]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "server already started"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "xdefinitionProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentRangeFormattingProvider": true, "xworkspaceReferencesProvider": true, "documentFormattingProvider": true, "xworkspaceSymbolByProperties": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "bingo"}, "message": "lsp server already initialized"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "configuration sent"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "already opened"}}]
Tue 19 Mar 2019 12:42:12 PM CST:["s:update_file_content()", 1]
Tue 19 Mar 2019 12:42:12 PM CST:["--->", 3, "bingo", {"method": "textDocument/didChange", "params": {"contentChanges": [{"range": {"end": {"character": 3, "line": 10}, "start": {"character": 3, "line": 10}}, "text": "x", "rangeLength": 0}], "textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go", "version": 4}}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "textDocument/didChange sent"}}]
Tue 19 Mar 2019 12:42:12 PM CST:["s:update_file_content()", 1]
Tue 19 Mar 2019 12:42:12 PM CST:["--->", 3, "bingo", {"method": "textDocument/didSave", "params": {"textDocument": {"uri": "file:///home/lks/Projects/go/module/test/main.go", "version": 4}}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "textDocument/didSave sent"}}]
Tue 19 Mar 2019 12:42:12 PM CST:["s:send_event_queue()"]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "server already started"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "result": {"capabilities": {"hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "xdefinitionProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentRangeFormattingProvider": true, "xworkspaceReferencesProvider": true, "documentFormattingProvider": true, "xworkspaceSymbolByProperties": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"triggerCharacters": ["."]}}}, "jsonrpc": "2.0"}, "server_name": "bingo"}, "message": "lsp server already initialized"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "bingo"}, "message": "configuration sent"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "already opened"}}]
Tue 19 Mar 2019 12:42:12 PM CST:[{"response": {"data": {"path": "file:///home/lks/Projects/go/module/test/main.go", "__data__": "vim-lsp", "server_name": "bingo"}, "message": "not dirty"}}]
Tue 19 Mar 2019 12:42:13 PM CST:["s:on_text_document_did_close()", 1]
T

**Comment by Cosson2017** [comment]
@mattn Seem bingo's mistake.
