### ISSUE TITLE
Statusline Support

### ISSUE THREAD

**Issue by Camotubi** [prabirshrestha/vim-lsp#346]
I'm not sure if vim-lsp has this but other lsp like ale or coc has a way of showing in the statusline (airline, lightline, etc) at what line an error was encountered. I have read the help file from vim.lsp but i wasn't able to find anything about statuslines. Is there a way to get a similar behavior?.

Thanks for this awesome plugin btw.

**Comment by mattn** [comment]
airline/lightline use segments that is separated informations. So what do you want to do? error information?

**Comment by Camotubi** [comment]
I wanted to display how many errors / warnings were detected. Also, line number of the first error of the current buffer.

**Comment by prabirshrestha** [comment]
@Camotubi can you verify if this solves your needs. https://github.com/prabirshrestha/vim-lsp/pull/376

**Comment by Camotubi** [comment]
Almost. The only thing left is the line number of the first error in the current buffer, but I think I can live without that. Should I close this issue?

**Comment by prabirshrestha** [comment]
It is ok to leave it open. Let us continue the discussion in the PR instead.

**Comment by prabirshrestha** [comment]
PR is merged. Please try the latest master.
