### ISSUE TITLE
Is there a way to show the error message below the statusline?

### ISSUE THREAD

**Issue by sbromberger** [prabirshrestha/vim-lsp#349]
Using vim-lsp with gopls. Errors are showing up in the gutter (which is awesome) but I can't figure out how to display the error message itself. My preference would be to have the error message displayed under the statusline when I hover on the line (or even on the offending string, but right now the position within the line that's causing the error isn't shown).

Is there a configuration option I'm missing to do this?

Edited: see attached screenshot. It would be great to see the error message where the "vim-go" info currently is.

![IMG_0054](https://user-images.githubusercontent.com/941359/54630006-1acf6680-4a36-11e9-8ae5-1702ba094396.png)

**Comment by caksoylar** [comment]
You are possibly looking for `let g:lsp_diagnostics_echo_cursor = 1` option, which doesn't seem to be documented in `:help vim-lsp` but is noted in the README.

**Comment by sbromberger** [comment]
Thanks. I'll give this a try and reopen if I run into further issues.

**Comment by georgettica** [comment]
for me I did `LspDocumentDiagnostics`
