### ISSUE TITLE
Error in s:on_text_document_did_save when file saving

### ISSUE THREAD

**Issue by mikoto2000** [prabirshrestha/vim-lsp#354]
I got error when save.

![image](https://user-images.githubusercontent.com/345832/54945365-f6651400-4f78-11e9-9ddf-8bc6f4d4b1a1.png)

# Cause

In #345, fixed called function `s:get_text_document_text(a:buf, a:server_name)` to `s:get_text_document_text(a:buf)`[(autoload/lsp.vim#L222)](https://github.com/prabirshrestha/vim-lsp/pull/345/files#diff-d894fdd20596308dd9b1c8ac8a9197c8R222). but not fix `function s:get_text_document_text(buf, server_name)`[(autoload/lsp.vim#L670)](https://github.com/prabirshrestha/vim-lsp/pull/345/files#diff-d894fdd20596308dd9b1c8ac8a9197c8R670).

# Solution proposal

Revert [autoload/lsp.vim#L227(at master branch)](https://github.com/prabirshrestha/vim-lsp/blob/c5c7bf0abcd5540fe1c562bdbe2800e914069bb7/autoload/lsp.vim#L227) to  `s:get_text_document_text(a:buf, a:server_name)`.

- s:file_content is managing text, using buffer numbrt and server name.
- so, s:get_text_document_text can not provide text data if no server name.

# Environment

* vim: version 8.1.1006
* server: [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls)
* server regster setting: See 'Server regster setting' section

# Server register setting

<details>
<summary>.vimrc</summary>

```vim
function! StartJavaDevelopment()
    packadd async.vim
    packadd vim-lsp

    let g:lsp_log_verbose = 1
    let g:lsp_log_file = expand('~/vim-lsp.log')

    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'eclipse.jdt.ls',
        \ 'cmd': {server_info->[
        \     'java',
        \     '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        \     '-Dosgi.bundles.defaultStartLevel=4',
        \     '-Declipse.product=org.eclipse.jdt.ls.core.product',
        \     '-Dlog.level=ALL',
        \     '-noverify',
        \     '-Dfile.encoding=UTF-8',
        \     '-Xmx1G',
        \     '-jar',
        \     '/PATH/TO/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar',
        \     '-configuration',
        \     '/PATH/TO/eclipse.jdt.ls/config_win',
        \     '-data',
        \     '/PATH/TO/eclipse.jdt.ls/workspace'
        \ ]},
        \ 'root_uri':{server_info->SearchProjectRoot('settings.gradle')},
        \ 'whitelist': ['java'],
        \ })

    call lsp#enable()
    autocmd FileType java setlocal omnifunc=lsp#complete
endfunction
```

<details>

**Comment by prabirshrestha** [comment]
Can you tryin latest master. Added `a:server_name`

**Comment by mikoto2000** [comment]
Thank you for fixing!
