### ISSUE TITLE
Error detected while processing function <SNR>159_apply_text_edit[32]..<SNR>159_expand_range:

### ISSUE THREAD

**Issue by yaegassy** [prabirshrestha/vim-lsp#355]
If one character is entered after selecting a completion candidate, an error will be output.

It seems that it has occurred since [PR:318](https://github.com/prabirshrestha/vim-lsp/pull/318) was merged.

It occurs in the configuration using `asyncomplete related` and `php-language-server`.

## Error message

```
Error detected while processing function <SNR>159_apply_text_edit[32]..<SNR>159_expand_range:
line    2:
E689: Can only index a List, Dictionary or Blob
```

## Animation GIF

![ng](https://user-images.githubusercontent.com/188642/54964890-83c45a80-4fb1-11e9-898a-553d5b4ef70d.gif)

## minimum.vimrc

```vim
call plug#begin('~/.vim/cache')

Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

call plug#end()

augroup LspPHP
  au!
  au User lsp_setup call lsp#register_server({
       \ 'name': 'php-language-server',
       \ 'cmd': {server_info->['php', expand('~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php')]},
       \ 'whitelist': ['php'],
       \ })
augroup end
```

## commit 3e28b8fb1ed670a19f1cb178f5363739c8732a39

The commit `3e28b8fb1ed670a19f1cb178f5363739c8732a39` has no problem.

```vim
"... snip
"Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/vim-lsp', { 'commit': '3e28b8fb1ed670a19f1cb178f5363739c8732a39' }
"... snip
```

![ok](https://user-images.githubusercontent.com/188642/54964904-8f178600-4fb1-11e9-8f7a-bc2bf6db52e1.gif)

**Comment by prabirshrestha** [comment]
//cc @mikoto2000

**Comment by mikoto2000** [comment]
php-language-server was provided textEdit property and textEdit value is null.

![image](https://user-images.githubusercontent.com/345832/55022742-9afd5980-503e-11e9-97a5-606fe5b9f0bc.png)

I think these pattern is same.

- Not provide property
- Provide property and property value is null

I will fix to allow "textEdit property provide and null value".
(Not add user_data, when textEdit not provide or null)

references: 

- [VS Code tries to read 'range' field from TextEdit which is null](https://github.com/Microsoft/vscode-languageserver-node/issues/95)
    - [Fixed commit](https://github.com/Microsoft/vscode-languageserver-node/commit/203d42fbeae8ecc902852c4ceef8b32278f38fc6)
- [Simplify protocol with regards to optional fields vs nullable fields.](https://github.com/Microsoft/language-server-protocol/issues/87)

**Comment by prabirshrestha** [comment]
This has been fixed by @mikoto2000. Please try latest master.
