### ISSUE TITLE
apply_text_edit error on completion with asyncomplete

### ISSUE THREAD

**Issue by squareduck** [prabirshrestha/vim-lsp#357]
With `asyncomplete` and `asyncomplete-lsp`, and typescript
I'm getting the error as soon as autocomplete is done:
```
Error detected while processing function <SNR>162_apply_text_edit:
line   25:
E474: Attempt to decode a blank string
```

There are a bunch of other sources enabled:
```
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'

Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'

```

Could this be related to recent changes in https://github.com/prabirshrestha/vim-lsp/pull/344 ?

**Comment by prabirshrestha** [comment]
Can you provide logs?

**Comment by squareduck** [comment]
vim-lsp.log: https://pastebin.com/4F08J66X
asyncomplete.log: https://pastebin.com/FEyTWvZn

I can only reproduce it with:
```
let g:asyncomplete_smart_completion = 1
let g:asyncomplete_auto_popup = 1
set completeopt+=preview
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
```

So not sure if this is asyncomplete issue.

Full init.vim:
https://github.com/squareduck/config-nvim/blob/master/init.vim

**Comment by mikoto2000** [comment]
I tried NeoVim v0.3.4.

nvim provided empty string user_data, if no user_data.
nvim, or third party plugin may provide not json type user_data.

We need add check whether user_data is json type.

https://github.com/prabirshrestha/vim-lsp/blob/5c3dcc952bcd50987526ae58694afea8a9052f35/autoload/lsp/omni.vim#L267

**Comment by prabirshrestha** [comment]
Make sense. Also might be simple to just add a try catch on `json_decode` too.

**Comment by mikoto2000** [comment]
> Also might be simple to just add a try catch on json_decode too.

I will implement this and PR.

**Comment by prabirshrestha** [comment]
This is now fixed.
