### ISSUE TITLE
Question: RLS config

### ISSUE THREAD

**Issue by paulhauner** [prabirshrestha/vim-lsp#360]
Hi,
  Thanks for this plugin it's great.

I'm using `vim` with RLS. I'm passing some `workspace_configuration` params to attempt to change the [RLS configuration](https://github.com/rust-lang/rls#configuration).

This is my .vimrc:

```
" vim-lsp
let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')
if executable('rls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rls',
        \ 'cmd': {server_info->['rustup', 'run', 'stable', 'rls']},
        \ 'workspace_config': {'param': {'clippy_preference': 'on'}},
        \ 'whitelist': ['rust'],
        \ })
endif
let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
```

Examining the logs, I can see the following 

```
Wed 03 Apr 2019 13:56:30 AEDT:["--->",1,"rls",{"method":"workspace/didChangeConfiguration","params":{"settings":{"param":{"clippy_preference":"on"}}}}]
```

However, I don't seem to be seeing changes in RLS. Is there anything you can see that I'm doing wrong please? From looking around the RLS repo, it seems this functionality is working for Atom users.

EDIT: just a single line/word answer is fine. I'm not looking for a whole lot of effort, I just thought it might be obvious to someone.

**Comment by cithiLoe** [comment]
Replacing `param` with `rust` in workspace_config did the trick for me:
```
au User lsp_setup call lsp#register_server({
     \ 'name': 'rls',
     \ 'cmd': {server_info->['rustup', 'run', 'stable', 'rls']},
     \ 'workspace_config': {'rust': {'clippy_preference': 'on'}},
     \ 'whitelist': ['rust'],
     \ })
```

**Comment by prabirshrestha** [comment]
Could one of you update the docs here. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Rust

**Comment by prabirshrestha** [comment]
I update the docs.
