### ISSUE TITLE
User definition cursor position mechanism of textEdit

### ISSUE THREAD

**Issue by mikoto2000** [prabirshrestha/vim-lsp#361]
I want user definition cursor position mechanism in omni complete.

https://github.com/prabirshrestha/vim-lsp/blob/ee1dd1638a69930fb49be7f7e4e17c9bdb16de63/autoload/lsp/omni.vim#L285-L291

ex: I want move cursor to inner tag when use [lsp4xml](https://github.com/angelozerr/lsp4xml).

```xml
<completed_tag><!-- I want move cursor here. --></completed_tag>
```

# Proposal

1. Add global variable `g:lsp_text_edit_cursor_move_func`
    - Type is Dictionary
    - key is server name
    - value is user defined function
2. Add user defined function in last of [`s:apply_text_edit()`](https://github.com/prabirshrestha/vim-lsp/blob/ee1dd1638a69930fb49be7f7e4e17c9bdb16de63/autoload/lsp/omni.vim#L242)

user defined vimrc example:

```vim
" g:lsp_text_edit_cursor_move_func = {
"   'SERVER_NAME': 'CURSOR_MOVE_FUNC_NAME',
"   'SERVER_NAME': 'CURSOR_MOVE_FUNC_NAME',
"   ...
" }
let g:lsp_text_edit_cursor_move_func = {
        \ 'lsp4xml': 'Cursor_move_func_for_lsp4xml'
        \ }

function! Cursor_move_func_for_lsp4xml(text_edit)
    " calculate cursor position
    call cursor(l:line, l:col)
endfunction
```

I will implement this and create PR.

If there are any indication or advice, please.

**Comment by mikoto2000** [comment]
This function prototpe is better than previous function prototpe.

```vim
function! Cursor_move_func_for_lsp4xml(new_text)
    " calculate cursor position index
    return l:cursor_index_of_new_text
endfunction
```

**Comment by prabirshrestha** [comment]
Why not use snippet?  https://github.com/prabirshrestha/vim-lsp/pull/306

**Comment by mikoto2000** [comment]
lsp4xmlis complementing from xsd definition.
I think it is can not in snippets.

Can UltiSnips do it?
Or, does that mean there is a way to add a snippet or tabstop to a CompletionItem?

**Comment by mikoto2000** [comment]
I understood maybe.

1. Get `thomasfaingnaert:ultisnips-integration` branch.
2. Implement `Custom_get_supported_capabilities(server_info)`.
    - Add `capabilities['textDocument']['completion']['completionItem']['snippetSupport'] = v:true`.
3. Set '2.' to `g:Lsp_get_vim_completion_item`.
4. Install UltiSnips, or implement the function to move to the tab stop.

I will try this.

**Comment by thomasfaingnaert** [comment]
@mikoto2000 At the moment, snippets do not work anymore against the latest master. I've been a little busy lately, but I'm planning to look into it this weekend.

**Comment by thomasfaingnaert** [comment]
@mikoto2000 `vim-lsp-ultisnips` should be able to support textEdit now. I tested with your example at https://github.com/prabirshrestha/vim-lsp/pull/318#issuecomment-475856672, and it seems to work:
![xml](https://user-images.githubusercontent.com/10748726/55692192-e18b7600-59a5-11e9-9de9-9e321f556c85.gif)
Can you test if it works on your machine as well?

Minimal vimrc to reproduce:
```vim
call plug#begin()

Plug 'SirVer/ultisnips'
Plug 'prabirshrestha/async.vim'
Plug 'thomasfaingnaert/vim-lsp', {'branch': 'ultisnips-integration'}
Plug 'thomasfaingnaert/vim-lsp-ultisnips'

call plug#end()

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

autocmd User lsp_setup call lsp#register_server({
\ 'name': 'lsp4xml',
\ 'cmd': {server_info->[
\     'java',
\     '-noverify',
\     '-Xmx1G',
\     '-XX:+UseStringDeduplication',
\     '-Dfile.encoding=UTF-8',
\     '-jar',
\     '/path/to/lsp4xml/org.eclipse.lsp4xml/target/org.eclipse.lsp4xml-uber.jar'
\ ]},
\ 'whitelist': ['xml', 'arxml'],
\ })

autocmd FileType xml setlocal omnifunc=lsp#complete

set completeopt+=menuone
```

**Comment by mikoto2000** [comment]
I tried it, and almost worked.
But I got some problem, so I deconstruct problem and create new issue(maybe to vim-lsp-ultisnips). 

This issue(#361) will resolve when merge `integration-ultisnips` branch and use snippet mechanism.
I will delete TODO and close this issue.
https://github.com/prabirshrestha/vim-lsp/blob/a79fb04d36e89261e356c16e638bbee284e42d4a/autoload/lsp/omni.vim#L286
