### ISSUE TITLE
Debugging java language server

### ISSUE THREAD

**Issue by albfan** [prabirshrestha/vim-lsp#362]
When debug is enable in java

    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044

there's a message that do not conform with vim-lsp message parsing:

> a:data = ["Listening for transport dt_socket at address: 1044",""]

I fixed adding:

```
diff --git i/autoload/lsp/client.vim w/autoload/lsp/client.vim
index a10a2ef..acabf1b 100644
--- i/autoload/lsp/client.vim
+++ w/autoload/lsp/client.vim
@@ -37,26 +37,41 @@ function! s:on_stdout(id, data, event) abort
         return
     endif
 
+    call lsp#log('data: ', a:data)
+
+    let l:buffer = join(a:data, "\n")
+    if l:buffer =~? '^Listening'
+       "ignore
+       return
+    endif
+
     if empty(l:ctx['buffer'])
         let l:ctx['buffer'] = join(a:data, "\n")
     else
         let l:ctx['buffer'] .= join(a:data, "\n")
     endif
```

But is there any other way to ignore some messages? 

I'm thinking on process a:data to always ensure lines end with  `\r\n\r\n` (here it ends with only \n and is not parsed correctly, but as it has Content-length after joining other messages, parsing  communication fails)

**Comment by prabirshrestha** [comment]
To me seems to be more of a bug on the language server. I would suggest filing an issue where. Feel free to add me there and I can help as needed.

**Comment by albfan** [comment]
Yeah, not sure, vim-lsc works out of the box. Maybe is lsp v3 protocol.

Thanks anyway.

**Comment by natebosch** [comment]
It does seem strange that the client is only checking for `\n` and not `\r\n\r\n`. The `Listening for` line is odd, but I _think_ it could be still technically spec compliant and treated as a header...
