### ISSUE TITLE
`s:apply_text_edit()` was not called if only one a complete match item in omni complete.

### ISSUE THREAD

**Issue by mikoto2000** [prabirshrestha/vim-lsp#365]
# Issue

Complete item menu is not displayed, if call omnifunc when only one a complete match item.

In this case, `s:appry_text_edit()` was not called, because was not fired `CompleteDone`. 

![vim-lsp_omnifunc_Pattern_not_found gif](https://user-images.githubusercontent.com/345832/56426394-2ba02000-62f3-11e9-8447-4848a1ecc219.gif)

# Cause

1. complete_item was not provided `'empty': 1`.
   https://github.com/prabirshrestha/vim-lsp/blob/357a074c851ec04d9d21640a77bd9aaa25f1140a/autoload/lsp/omni.vim#L189-L196
2. `s:apply_text_edit()` is nothing to do if `completed_item['word']` is empty.
   https://github.com/prabirshrestha/vim-lsp/blob/357a074c851ec04d9d21640a77bd9aaa25f1140a/autoload/lsp/omni.vim#L256-L259

# Propose solution

- Add `'empty': 1` in complete_item
- Delete `completed_item['word'] ==# ''` check

Do you think will get degrade, when applying these fixes?
If no problem then I will fix it.

# Used files for verification

<details>
    <summary>test.xsd</summary>

```xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="books">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="book">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="title" type="xsd:string" />
              <xsd:element name="price" type="xsd:decimal" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>
```

</details>

<details>
    <summary>test.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./test.xsd">
    <!--
        1. type bo<C-x><C-o> after <C-y> -> complete `<book></book>`
        2. type book<C-x><C-o> -> `Pattern not found`
    -->
</books>
```

</details>

<details>
    <summary>.vimrc</summary>

```vim
""" for xml development
command! Xmld call StartXmlDevelopment()
function! StartXmlDevelopment()
    packadd async.vim
    packadd vim-lsp

    let g:lsp_log_verbose = 1
    let g:lsp_log_file = expand('~/vim-lsp.log')

    " for asyncomplete.vim log
    " let g:asyncomplete_log_file = expand('~/asyncomplete.log')

    autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'lsp4xml',
        \ 'cmd': {server_info->[
        \     'java',
        \     '-noverify',
        \     '-Xmx1G',
        \     '-XX:+UseStringDeduplication',
        \     '-Dfile.encoding=UTF-8',
        \     '-jar',
        \     fnamemodify("~", ":p") . '/.vim/lsp/lsp4xml/org.eclipse.lsp4xml-0.3.0-uber.jar'
        \ ]},
        \ 'whitelist': ['xml'],
        \ })

    call lsp#enable()
    autocmd FileType xml setlocal omnifunc=lsp#complete
endfunction
```

</details>

**Comment by prabirshrestha** [comment]
Should be ok.

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/378 merged.
