### ISSUE TITLE
Document that language server version 3.0 is supported

### ISSUE THREAD

**Issue by niklaas** [prabirshrestha/vim-lsp#367]
In #311 it says that version 3.0 is supported. But there is no information about the supported version in neither the readme nor the docs.

I stumbled upon the following sentence in georgewfraser/java-language-server:

> Note: This tool is not compatible with vim-lsp as it only supports LSPv2.0.

I had to search in the issues to find out that this statement is wrong. This should be stated more clearly.

If you want to, assign this issue to me and I will send a pull request

1. adding a note in the docs
2. adding a note in the readme

Further, I can send a pull request to georgewfraser/java-language-server removing the statement.

**Comment by prabirshrestha** [comment]
java-language-server now works with vim-lsp. please try latest master.
