### ISSUE TITLE
Support Texlab language server

### ISSUE THREAD

**Issue by krishnakumarg1984** [prabirshrestha/vim-lsp#370]
The officially supported language server for LaTeX is [TexLab](https://texlab.netlify.com/) which also supports BibTeX.  I have had a positive experience using it in VSCode for which the same author provides a client plugin bearing the same name. 

Can you please provide support for the `TexLab` language server?

**Comment by prabirshrestha** [comment]
Please ask the question in the server repo on how to start the language server. I couldn’t find anything about it in the docs. Feel free to include me in the issue if you need assistance from my side.

**Comment by thestr4ng3r** [comment]
This works for me:
```vim
if executable('texlab')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'texlab',
      \ 'cmd': {server_info->['texlab']},
      \ 'whitelist': ['tex', 'bib', 'sty'],
      \ })
endif
```
