### ISSUE TITLE
Updated vim-lsp and see a lot of W> in the gutter

### ISSUE THREAD

**Issue by huy-springlabs** [prabirshrestha/vim-lsp#374]
Updated vim-lsp recently and started seeing a lot of W> in the gutter. Do you guys know if this is related or what it means?

![Screen Shot 2019-05-01 at 9 23 29 PM](https://user-images.githubusercontent.com/46936438/57056963-9d189080-6c5a-11e9-95f4-d9ff5cd2e785.png)

**Comment by tsufeki** [comment]
These are [signs](https://github.com/prabirshrestha/vim-lsp#signs). `W>` means 'warning', in your case probably formatting is not pep8 enough. If you stop the cursor on one of these lines you should see a message at the bottom. Ofc, you can turn them off.

**Comment by huy-springlabs** [comment]
Thank you, I was able to resolve this last night when running LspDocumentDiagnostics. For some reason my AleLinter started working and these warnings popped up.
