### ISSUE TITLE
Got invalid completions with typescript-language-server

### ISSUE THREAD

**Issue by sivakov512** [prabirshrestha/vim-lsp#377]
Hello!

I've started using vim-lsp for typescript with configuration like this
```vim
if executable('typescript-language-server')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
        \ 'whitelist': ['javascript', 'javascript.jsx', 'typescript', 'typescript.jsx'],
        \ })
    autocmd FileType typescript,typescript.jsx,javascript,javascript.jsx setlocal omnifunc=lsp#complete
    autocmd FileType typescript,typescript.jsx,javascript,javascript.jsx nnoremap <buffer> <silent> <c-]> :LspDefinition<cr>
    autocmd FileType typescript,typescript.jsx,javascript,javascript.jsx nnoremap <buffer> <silent> <leader>r :LspReferences<cr>
    autocmd FileType typescript,typescript.jsx,javascript,javascript.jsx nnoremap <buffer> <silent> K :LspHover<cr>
endif
```

But, when I triggering completion for partialy typed word I'm getting unexpected results like on the screenshot screenshot below. Completion triggered manually after class App extends Com.
![image](https://user-images.githubusercontent.com/10251687/57198987-496fb500-6f82-11e9-8be5-af3e2b4f35d9.png)

```bash
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 21 2019 17:50:56)
Included patches: 1-1027
Compiled by void-buildslave@a-hel-fi
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
+clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       +xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              -mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: cc -c -I. -Iproto -DHAVE_CONFIG_H     -fstack-clash-protection -mtune=generic -O2 -pipe   -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: cc   -L. -Wl,-z,relro -Wl,-z,now     -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now     -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf -lnsl   -lncursesw -lacl -lattr -ldl  -L/usr/lib -llua -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -pthread  -L/usr/lib/perl5/core_perl/CORE -lperl -lm -lcrypt -lpthread -ldl  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -lruby -lm
```

My vim configuration https://github.com/sivakov512/.vim/blob/master/vimrc#L106

**Comment by zbinlin** [comment]
I use this patch to fix it:

```diff
diff --git a/autoload/lsp/omni.vim b/autoload/lsp/omni.vim
index a1e4fe5..75df0a6 100644
--- a/autoload/lsp/omni.vim
+++ b/autoload/lsp/omni.vim
@@ -47,7 +47,17 @@ function! lsp#omni#complete(findstart, base) abort
     endif
 
     if a:findstart
-        return col('.')
+        let line = getline('.')
+        let start = col('.') - 1
+        while start > 0
+            let char = line[start - 1]
+            if char =~ '\k'
+                let start -= 1
+            else
+                break
+            endif
+        endwhile
+        return start
     else
         if !g:lsp_async_completion
             let s:completion['status'] = s:completion_status_pending
```

**Comment by mattn** [comment]
Related to https://github.com/prabirshrestha/vim-lsp/issues/291

**Comment by thomasfaingnaert** [comment]
It seems that `typescript-language-server` sends `AbortController` etc. even though it knows you have already typed `Com`.
It is possible to let Vim start completion from the first character not in `'iskeyword'`, like @zbinlin suggests, however this would reintroduce #291.

If we do want to fix this in `vim-lsp`, we will have to filter the completion results received from the language server: all results not starting with the already typed part should be discarded.
Though, it is unclear how to best define "already typed part": looking only at characters in `'iskeyword'` may not work for all language servers.
It seems to me like this is something that the language server itself should fix, i.e. when it knows you have typed `Com`, it shouldn't send completions for `AbortController`.

**Comment by tsufeki** [comment]
@thomasfaingnaert 

> It seems to me like this is something that the language server itself should fix

Filtering and sorting falls into client's responsibility in LSP, that way it can decide whether to match by prefix or fuzzily (by subsequence) for example. I think most servers don't filter completions (unless list gets big enough to cause performance problems).

**Comment by thomasfaingnaert** [comment]
@tsufeki Ah indeed I did not think of fuzzy matching. For `clangd` (or C++ servers in general, I guess) though, filtering is required in the server, due to the sheer amount of results that otherwise would be returned. The best way to solve this would then indeed be filtering the results based on the already typed part.

**Comment by thomasfaingnaert** [comment]
@sivakov512 Can you check if #391 solves your issue?

**Comment by sivakov512** [comment]
Sorry, I stopped using this plugin :(

**Comment by zbinlin** [comment]
@thomasfaingnaert 
I try patch #391 , but it seems does not resolve the issue.

It have three problems.

1. Popup window does not align the completing word.

2. Sometime can't complete methods likes `{WORD}.<CURSOR_HERE>` .

3. In the current situation, the completion is case insensitive, it will causes like `al<CURSOR_HERE>`, if completion list has  `ALPN_ENABLE` item, it will complete to `alALPN_ENABLE` not `ALPN_ENABLE`.

Apply #391 :

![Peek 2019-05-25 16-23](https://user-images.githubusercontent.com/880513/58377234-64947a00-7fae-11e9-9a8f-18a607ee6994.gif)

Expected:

![Peek 2019-05-25 16-32](https://user-images.githubusercontent.com/880513/58377239-70803c00-7fae-11e9-8c28-e7c2f17b2baf.gif)

**Comment by thomasfaingnaert** [comment]
@zbinlin 
This patch (applied to `master`) seems to fix most of these issues:
```diff
diff --git a/autoload/lsp/omni.vim b/autoload/lsp/omni.vim
index c94d69a..bb8b85c 100644
--- a/autoload/lsp/omni.vim
+++ b/autoload/lsp/omni.vim
@@ -63,14 +63,27 @@ function! lsp#omni#complete(findstart, base) abort
             while s:completion['status'] is# s:completion_status_pending && !complete_check()
                 sleep 10m
             endwhile
-            let l:base = tolower(a:base)
-            let s:completion['matches'] = filter(s:completion['matches'], {_, match -> stridx(tolower(match['word']), l:base) == 0})
+
+            let l:current_line = strpart(getline('.'), 0, col('.') - 1)
+            let l:start_pos = match(l:current_line, '\k*$')
+            let l:last_typed_word = strpart(l:current_line, l:start_pos)
+
+            let s:completion['matches'] = filter(s:completion['matches'], {_, item -> s:filter_match(item, l:last_typed_word)})
             let s:completion['status'] = ''
-            return s:completion['matches']
+
+            call complete(l:start_pos + 1, s:completion['matches'])
+            return v:none
         endif
     endif
 endfunction
 
+function! s:filter_match(item, last_typed_word) abort
+    let l:label = trim(a:item['word'])
+    let l:match_pattern = '^' . a:last_typed_word
+
+    return l:label =~? l:match_pattern
+endfunction
+
 function! s:handle_omnicompletion(server_name, complete_counter, data) abort
     if s:completion['counter'] != a:complete_counter
         " ignore old completion results
@@ -147,6 +160,7 @@ endfunction
 
 
 function! s:remove_typed_part(word) abort
+    return a:word
     let l:current_line = strpart(getline('.'), 0, col('.') - 1)
 
     let l:overlap_length = 0

```

However, I still have a weird issue where the completed item is inserted twice. I even have this when applying:
```diff
diff --git a/autoload/lsp/omni.vim b/autoload/lsp/omni.vim
index c94d69a..fad66b7 100644
--- a/autoload/lsp/omni.vim
+++ b/autoload/lsp/omni.vim
@@ -66,7 +66,8 @@ function! lsp#omni#complete(findstart, base) abort
             let l:base = tolower(a:base)
             let s:completion['matches'] = filter(s:completion['matches'], {_, match -> stridx(tolower(match['word']), l:base) == 0})
             let s:completion['status'] = ''
-            return s:completion['matches']
+            call complete(col('.'), s:completion['matches'])
+            return v:none
         endif
     endif
 endfunction
```

I'm not entirely sure what the problem is: `complete` is only called once as far as I can tell.
Perhaps you have an idea what's happening?

**Comment by zbinlin** [comment]
@thomasfaingnaert It seems cannot call `complete` in `completefunc/omnifunc`?

**Comment by Andilutten** [comment]
Any status on this ? I'm experiencing this to. Works fine with gopls for golang tho

**Comment by thomasfaingnaert** [comment]
@Andilutten I've updated #391. Can you check if that PR fixes the issue for you as well?

**Comment by prabirshrestha** [comment]
@Andilutten Can you try the latest PR and let us know if you still have issues.

**Comment by sivakov512** [comment]
Hello!
I tried to use https://github.com/thomasfaingnaert/vim-lsp/tree/filter-completions, but nothing changed ( Issue reproduced as in first comment.

**Comment by sivakov512** [comment]
I can create a repository with code example and vimrc if it helps solve the problem.

**Comment by thomasfaingnaert** [comment]
@sivakov512 Did you use the "prefix" filter by adding this to the server registration?
```vim
'config': { 'filter': { 'name': 'prefix' } }
```

**Comment by sivakov512** [comment]
No. Wait a moment, I will try

**Comment by sivakov512** [comment]
Nothing changed, I tried with this setup:
```vim
if executable('typescript-language-server')
  au User lsp_setup call lsp#register_server({
        \ 'name': 'typescript-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'typescript-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'tsconfig.json'))},
        \ 'whitelist': ['typescript', 'typescript.jsx'],
        \ 'config': { 'filter': { 'name': 'prefix' } },
        \ })
endif
```

**Comment by sivakov512** [comment]
Looks good, but completion is case insensitive, So, if i start typing `com` it may complete with `Component`

**Comment by sivakov512** [comment]
More weird example - if I start with `ex` it completed with `EXDEV` instead `exec`, for example. But the first problem is solved.

**Comment by sivakov512** [comment]
Problem with case insensitive completion also reproduces with python:
```python
import sqlalchemy as sa

sa.meta<|>
```
If I trigger completion at `<|>` it completes with `metaData`, but only `MetaData` exists.

But it works file with Rust.

**Comment by thomasfaingnaert** [comment]
@sivakov512 I'm using `'ignorecase'` to determine if completions should be filtered case (in)sensitive. `set noignorecase` should only provide completions of the correct case. Would you prefer to have a different setting for this?

**Comment by sivakov512** [comment]
It would be cool to have possibility to override this behaviour - for example, I want to search case-insensitive but case-sensitive for completion.
As for me, I use `smartcase`. Afaik, `smartcase` behaviour does not depends on `ignorecase` (or not?)

**Comment by thomasfaingnaert** [comment]
I believe `smartcase` has no effect if `ignorecase` is not set. Anyway, I'll add a configuration option for this evening.
As for the Python example, do you mean that the already typed part (`meta`) is not overwritten when completing, leading to an incorrect case for `metaData`?
That's weird, because I believe I start completion at the start of the word, so the entire completion should get overwritten. I'll try to reproduce that, too.

**Comment by sivakov512** [comment]
> As for the Python example, do you mean that the already typed part (meta) is not overwritten when completing, leading to an incorrect case for metaData?

Yes. It was a reason why some times so I stopped using this plugin.

**Comment by sivakov512** [comment]
Can we merge 'filter' prefix into master now? :)

**Comment by thomasfaingnaert** [comment]
@prabirshrestha

**Comment by thomasfaingnaert** [comment]
Shouldn't we wait for the ignorecase setting, though :)

**Comment by sivakov512** [comment]
> Problem with case insensitive completion also reproduces with python:
> 
> ```python
> import sqlalchemy as sa
> 
> sa.meta<|>
> ```
> 
> If I trigger completion at `<|>` it completes with `metaData`, but only `MetaData` exists.
> 
> But it works fine with Rust.

Oh, if i set `noignorecase` I got `sa.meMetaData` in this case

**Comment by thomasfaingnaert** [comment]
@sivakov512 I added a `g:lsp_ignorecase` option to #391. For the issue with Python, I can't seem to reproduce it:

![Peek 2019-07-22 20-36](https://user-images.githubusercontent.com/10748726/61656227-9bda8b00-acc0-11e9-9771-241e8b7833e0.gif)

**Comment by sivakov512** [comment]
Hm... Can problem be a configuration specific? Can you share you vimrc? Or, maybe my vimrc can help repro this issue?

**Comment by thomasfaingnaert** [comment]
Could you first try a minimal vimrc and see if you can still reproduce the issue?

**Comment by sivakov512** [comment]
Yes, I can reproduce this problem without any special settings in vimrc.

**Comment by thomasfaingnaert** [comment]
Hmm, what branch did you try the Python example on?
With `filter-completions`, I get `MetaData`, as expected.
I only get the incorrect case `metaData` on master.

**Comment by sivakov512** [comment]
Ah, sorry, I tried it with master, yep.
I will try again tomorrow and report that all is well :)

**Comment by sivakov512** [comment]
Does this that if everything is fine, then tomorrow PR can be merged into master? :)

**Comment by thomasfaingnaert** [comment]
It's a rather big change, so I'd like @prabirshrestha to take a look at it first :smiley:

**Comment by sivakov512** [comment]
It works well, but `g:lsp_ignorecase` and `ignorecase` works as expected with TypeScript, not in Python. In Python I get `sa.me` -> `sa.MetaData` always with any settings.

**Comment by thomasfaingnaert** [comment]
Are you using the prefix filter with Python?

**Comment by sivakov512** [comment]
Oh, it works well with prefix filter.

But it does not look obvious - in addition to configure lsp server user should also add "prefix filter".
It would be cool to be able not to do it or it should be mentioned in page with lsp setup (like https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Python)

**Comment by thomasfaingnaert** [comment]
I think not filtering the completion items by default would be better: having more completion results than expected is better than having fewer I would think?

In some cases, the language server already takes the typed prefix into account, so prefix filtering in vim-lsp would do nothing extra.
Other language servers also allow substring matching (e.g. returning `some_function` if you type `func`), or camelcase matching (e.g. returning `SomeClassName` if you type `scn`). These would be broken with the `prefix` filter.

Maybe we could add a reference in the readme to the vim doc, and mention the best filter to use for each language server to the wiki?

@prabirshrestha What are your thoughts on this?

**Comment by sivakov512** [comment]
> Maybe we could add a reference in the readme to the vim doc, and mention the best filter to use for each language server to the wiki?

Sound good

**Comment by sivakov512** [comment]
Any news here?
@prabirshrestha

**Comment by sivakov512** [comment]
@prabirshrestha @thomasfaingnaert ping

**Comment by mattn** [comment]
@sivakov512 Could you please try https://github.com/prabirshrestha/vim-lsp/pull/391 ?

**Comment by sivakov512** [comment]
A few days ago I noticed that completion in python work very slow.
Completion in python files do not work now. I type `import py`, trigger completion and should see `pytest` or many choices, but nothing happens.

Completion in Rust works bad, for example in this screenshot cursor is placed after `Response, `
![image](https://user-images.githubusercontent.com/10251687/64479882-56b5de00-d1c6-11e9-9dd3-d71411486354.png)
I type `h` and trigger completion. I got something like this:
![image](https://user-images.githubusercontent.com/10251687/64479889-6af9db00-d1c6-11e9-9ff4-5fc0b3e783e5.png)

**Comment by sivakov512** [comment]
Completion works on 374955ff160d9492cbd19b63bde374cf3271ecb5.

> A few days ago I noticed that completion in python work very slow.

Python completions works slow in master branch too. Looks like an unrelated issue.

**Comment by sivakov512** [comment]
Any news here?

**Comment by sivakov512** [comment]
Any news here?

**Comment by prabirshrestha** [comment]
@sivakov512 Does this work https://github.com/prabirshrestha/vim-lsp/pull/391?

**Comment by sivakov512** [comment]
@prabirshrestha, yes, works good.

**Comment by sivakov512** [comment]
🎉🎉🎉
