### ISSUE TITLE
`lsp#utils#text_edit#apply_text_edits` is delete one character when textEdit command kind is insert.

### ISSUE THREAD

**Issue by mikoto2000** [prabirshrestha/vim-lsp#383]
`lsp#utils#text_edit#apply_text_edits` is delete one character when textEdit command kind is insert(textEdit['range']['start'] equals textEdit['range']['end']).

![vim-lsp_apply_text_edit](https://user-images.githubusercontent.com/345832/57867539-4a36ff80-783c-11e9-90a9-bd2b21c28f19.gif)

# Cause

execute normal command 'x' when textEdit['range']['start'] equals textEdit['range']['end'] and `len(newText) == 0`.

https://github.com/prabirshrestha/vim-lsp/blob/feba6d6d5370d7547cc27798653506112e089f2d/autoload/lsp/utils/text_edit.vim#L160-L162

So was deleted one character.

# Propose solution

Not execute normal command if `textEdit['range']['start'] equals textEdit['range']['end']`  and `len(newText) == 0`.

**Comment by prabirshrestha** [comment]
Are you planning to send a PR for this?

Also would be good to see if we can actually write these tests since text edits are pretty complex.

**Comment by mikoto2000** [comment]
> Are you planning to send a PR for this?

Yes. Sorry, I forgot to write this.
I will fix the code by proposed solution and implement tests if you think no problem.

**Comment by mikoto2000** [comment]
> Not execute normal command if `textEdit['range']['start'] equals textEdit['range']['end']`  and `len(newText) == 0`.

This approach is needed large modify in apply_text_edit flow.
I will change the approach, execute `l:sub_cmd` `x` to `i`.

**Comment by prabirshrestha** [comment]
This should be fixed by https://github.com/prabirshrestha/vim-lsp/pull/384
