### ISSUE TITLE
A new empty line is inserted whenever code gets formatted with gopls (Go language server)

### ISSUE THREAD

**Issue by maticz** [prabirshrestha/vim-lsp#386]
When the Go code gets formatted by gopls, an empty new line is inserted just above the line that gets formatted.

Example (before formatting, notice the 2 tabs before "fmt"):

```Go
package main

import (
		"fmt"
)

func main() {
	fmt.Println("Test")
}
```

Example (after formatting, an empty line above "fmt"):

```Go
package main

import (

	"fmt"
)

func main() {
	fmt.Println("Test")
}
```

I didn't see the same behaviour in other LSP clients which leads me to believe the problem is in vim-lsp.

**Comment by mattn** [comment]
Could you please provide small vimrc reproducible.

**Comment by maticz** [comment]
Sure, here it is:

```
call plug#begin()
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
call plug#end()

if executable('gopls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls']},
        \ 'whitelist': ['go'],
        \ })
endif
```

With this .vimrc I was still able to reproduce the issues by running :LspDocumentFormat or :LspDocumentFormatSync on the example above. I should also probably mention that I use vim and not neovim.

**Comment by mattn** [comment]
This is response from gopls

```json
{
  "response": {
    "id": 2,
    "jsonrpc": "2.0",
    "result": [
      {
        "range": {
          "end": {
            "character": 0,
            "line": 4
          },
          "start": {
            "character": 0,
            "line": 3
          }
        },
        "newText": ""
      },
      {
        "range": {
          "end": {
            "character": 0,
            "line": 4
          },
          "start": {
            "character": 0,
            "line": 4
          }
        },
        "newText": "\t\"fmt\"\n"
      }
    ]
  },
  "request": {
    "id": 2,
    "jsonrpc": "2.0",
    "method": "textDocument/formatting",
    "params": {
      "options": {
        "insertSpaces": false,
        "tabSize": 8
      },
      "textDocument": {
        "uri": "file:///C:/Users/mattn/go/src/github.com/mattn/misc/format/main.go"
      }
    }
  }
}
```
Applying this command into:

```
0:package main
1:
2:import (
3:
4:	"fmt"
5:)
6:
7:func main() {
8:	fmt.Println("Test")
9:}

```

1. from line 3, column 0 to line4, column 0 become `""`. i.e. joining two lines.
2. from line 4, column 0 to line4, column 0 but newText contains \n. i.e. replace line with newText.

@prabirshrestha If my understanding is right, joininig line (1) is broken.

**Comment by mikoto2000** [comment]
This issue's cause is #384.

I missed test pattern the multi line editing.

I will add test and fix this.

**Comment by mikoto2000** [comment]
> This issue's cause is #384.

Sorry, It was wrong...
It was reproduced before # 384.

**Comment by mikoto2000** [comment]
I seem the issue cause is `selection` condition.
https://github.com/prabirshrestha/vim-lsp/blob/900e8619be7b6dce5605076a7dadb4e17babfc7e/autoload/lsp/utils/text_edit.vim#L60

Needs `selection=inclusive` when end of range was newline character.

![vim-lsp](https://user-images.githubusercontent.com/345832/58176878-3c6ef780-7cde-11e9-8906-6c1f57662b00.gif)

I will fix it, add tests and create PR.

<details>
<summary>buffer content and execute command</summary>

buffer content:

```
foo
bar
baz
```

execute command:

```
execute 'keepjumps keepalt b 1 | execute ''keepjumps normal! 2G0v2G$x'''
```

</detail>

**Comment by prabirshrestha** [comment]
Please try the latest version of vim-lsp. Should had been fixed by https://github.com/prabirshrestha/vim-lsp/pull/388
