### ISSUE TITLE
Maxed CPU after opening C++ files using ccls

### ISSUE THREAD

**Issue by n00bmind** [prabirshrestha/vim-lsp#390]
Hi,
I've recently started testing this plugin, but I'm having a couple issues so far..
Installation seemed to go mostly fine, and I'm using ccls as my server (on Windows).
I'm on a pretty big codebase (about 100K files, although maybe 'only' 50% of that must be C++).
Now, everytime I open Vim with a .cpp file, the process will quickly start maxing out my CPU, and stay like that for a good few minutes.

- What could be causing this? Is ccls maybe reindexing the whole codebase everytime? Has anyone seen this happen before?
- Also, is vim-lsp launching the server in the same process as Vim? (that's what Windows is reporting as the process eating up all the CPU) I've tried things like Omnisharp in the past and I seem to recall this would launch the server as an external process the first time, and it would remain open even if I closed Vim, leading to much faster startup the next time I opened it (and it would 'solve' the previous issue too).. why does vim-lsp not do this?

**Comment by mattn** [comment]
What version of vim do you use? AFAIK, vim-lsp use heavy loop if running on older vim.

**Comment by tsufeki** [comment]
* ccls indeed indexes whole project, but full scan should happen only the first time you open a file in given project. Are you providing the same [root_uri](https://github.com/prabirshrestha/vim-lsp#registering-servers) every time you start vim? If not, ccls may treat every subfolder as a different project.
* Server is started as a child process of vim, so maybe that's why Windows reports 100% CPU @ vim (i.e. sum of vim and its children)?

**Comment by prabirshrestha** [comment]
Make sure root_uri is set correctly https://github.com/prabirshrestha/vim-lsp/wiki/Servers-ccls

**Comment by n00bmind** [comment]
Forgot to say I'm on (g)vim 8.1, so not old at all.
I'm using that exact root_uri expression and I've placed my compile_commands.json at the root of the project, although I'm actually using a symbolic link so I don't have to copy over from the build dir if I ever want to update it. I assume it's fine since that path is showing correctly on the status bar and it's also created cache files, etc. (although I cannot check their content until I get back to my work computer)

Before this I've also tried languageclient-neovim and it did something pretty similar (although it made Vim entirely unusable, here I can at least keep typing somewhat decently). Any posibility of adding an option to launch ccls as a separate process entirely?
Any other ideas?

**Comment by n00bmind** [comment]
I seems to remember reading somewhere that it is possible to connect to the language server through a TCP socket? If that's the case I could launch manually external to vim and connect through localhost..
Anyone knows how to do that?

**Comment by prabirshrestha** [comment]
Can you get the latest master and try `let g:lsp_highlight_references_enabled = 0` and see if the perf improves. Also if you can provide logs that would be good.

**Comment by aravind2612krishna** [comment]
Try capping the threads to ccls in the initializationOptions and seeing if the CPU% is reduced.
"initializationOptions": {
         "index": { "threads": 4 },
}

**Comment by prabirshrestha** [comment]
please use the latest vim/vim-lsp and the language server. `g:lsp_highlight_references_enabled ` is now disabled by default.
