### ISSUE TITLE
vim-lsp sends "textDocument/documentHighlight" request even if "lsp_highlight_references_enabled" disabled

### ISSUE THREAD

**Issue by edganiukov** [prabirshrestha/vim-lsp#393]
For each cursor move vim-lsp sends "textDocument/documentHighlight" request which slows down neovim. 
I disabled this with `let g:lsp_highlight_references_enabled=0` but it still sends those requests. 

Setup: neovim and gopls

**Comment by edganiukov** [comment]
Tested vim-lsc - it also sends such requests, but it doesn't slow down neovim.

**Comment by prabirshrestha** [comment]
This is fixed in master.
