### ISSUE TITLE
Range format does not work as expected

### ISSUE THREAD

**Issue by xulongwu4** [prabirshrestha/vim-lsp#394]
I tried to use the range formatting functionality for both python and cpp files and the behaviour of vim-lsp is a bit unexpected.

I have the following lines in my `.vimrc` file:
```
autocmd FileType python nmap gd <plug>(lsp-document-format)
autocmd FileType python vmap gd <plug>(lsp-document-format)
autocmd FileType cpp nmap gd <plug>(lsp-document-format)
autocmd FileType cpp vmap gd <plug>(lsp-document-format)
```

If I select a block of code in the visual mode and type `gd` to autoformat it, the code does not get formatted immediately. Instead, the following message pops up below my status line:
```
Formatting document range ...
Document formatted
```
The code I selected earlier is still selected and in their unformatted form. I need to manually press the `enter` key to complete the formatting and dismiss the log message. If I select a single line and press `gd`, it gets formatted immediately and the above message pops up but immediately disappears.

There is one other strange behaviour when I try to format python code. If I select a range of code to be formatted, and if there is another non-blank line immediately below my selection, `vim-lsp` actually formats not only my selected block but also the line immediately below. This does not happen when I format cpp code.

**Comment by mattn** [comment]
Did you try lsp-document-format-sync ?

**Comment by xulongwu4** [comment]
@mattn Just tried it. The same behavior as what I described above.

**Comment by prabirshrestha** [comment]
@xulongwu4 Can you try with latest master again. Also do provide logs.

**Comment by xulongwu4** [comment]
@prabirshrestha The same behavior persists with the latest master branch. Can you tell me how I can check logs on vim-lsp?

**Comment by thomasfaingnaert** [comment]
@xulongwu4 Instructions on how to enable logging are available in the README (https://github.com/prabirshrestha/vim-lsp#debugging).
I can reproduce the issue locally. I've provided a fix in #410. Could you check if your issue is resolved using that PR?

**Comment by prabirshrestha** [comment]
@xulongwu4  Can you this PR and let us know if it is fixed. https://github.com/prabirshrestha/vim-lsp/pull/410

**Comment by xulongwu4** [comment]
@thomasfaingnaert @prabirshrestha I tried the PR and the formatted text does not have redundent newlines any more.

However, I don't know if we should mark this issue as resolved. I am still seeing exactly the same issues as I described when I initially opened this issue. Basically code does not get formatted in visual mode until I manually press enter. Also the range of code being formatted is not quite the same as what I selected in python.

**Comment by thomasfaingnaert** [comment]
@xulongwu4 I've fixed the pressing enter issue in visual mode. As for the range not being the same, I can't seem to reproduce it locally. Could you provide us with an example .py file, indicating which commands you ran and the corresponding vim-lsp.log?

**Comment by xulongwu4** [comment]
@thomasfaingnaert I can confirm that your new commit fixes the issue that I had to press the enter key when formatting in the visual mode.

To reproduce the issue about the range of formatting, the following code should be enough:

```python
import numpy as np

a=1
b=2
c=3
d=4
```

If I select the `a=1` and `b=2` lines and press `gd` (see my `.vimrc` file in the description of the issue), I expect that only these two lines get formatted. However, the result I got is as follows:

```python
import numpy as np

a = 1
b = 2
c = 3
d=4
``` 

You can see that the line immediately follow my selection also get formatted.

**Comment by xulongwu4** [comment]
@thomasfaingnaert Just filed an issue with pyls: https://github.com/palantir/python-language-server/issues/610.

I think you can close this issue now. Thanks for your great work.
