### ISSUE TITLE
Disable/Enable diagnostics

### ISSUE THREAD

**Issue by SirJls** [prabirshrestha/vim-lsp#401]
I don't know if this is already available, so pardon me if it is, but I would love a feature which suppresses the warnings/errors about code formatting while still showing the actual errors.

I don't know if this is already possible, but from what I've seen the only option is to either enable diagnostics or disable it via: `let g:lsp_diagnostics_enabled = 0` or `let g:lsp_diagnostics_enabled = 1` respectively.

**Comment by prabirshrestha** [comment]
This is already supported should be document in help.
