### ISSUE TITLE
colorscheme and syntax highlight must enable beforehand for Highlight to take effect

### ISSUE THREAD

**Issue by ApolloTang** [prabirshrestha/vim-lsp#405]
colorscheme and syntax highlight must enable beforehand, otherwise, Lsp Highlight won't take effect.  
I don't think this is a bug, but I think this should be **added** to documentation.  

here is a working example:
https://github.com/ApolloTang/vim-sandbox/blob/master/0100-installing-lsp/02-lsp-minimum-w-config/dot-vimrc

**Comment by prabirshrestha** [comment]
Feel free to send a PR to add in docs on known issues.
