### ISSUE TITLE
Signs no longer work for me after feba6d6

### ISSUE THREAD

**Issue by papertigers** [prabirshrestha/vim-lsp#406]
Swapping my submodlue checkout between feba6d6d5370d7547cc27798653506112e089f2d (working) and c1be74277471f68f31d2995bb7054676e71aa65b (not working) causes signs to no longer be displayed in the gutter.  If I hover over the line with the cursor I do get LSP error messages, it just lacks the accompanying symbol in the gutter.

**Comment by ApolloTang** [comment]
could be related to #399

**Comment by maloneymr** [comment]
I had this issue. As per the recommendation on #399, I upgraded to the latest vim, and the signs work again, even on `vim-lsp/master`. Details:

    $ vim --version
    VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 17 2019 19:05:53)
    ...

and

    commit e0f832443b81184536588767716f2ae93ebe2346 (HEAD -> master, origin/master, origin/HEAD)
    Merge: e781beb 19090fe
    Author: mattn <mattn.jp@gmail.com>
    Date:   Tue Jun 18 02:55:30 2019 +0900
    
        Merge pull request #387 from dhakimian/fix-ref-jump
        
            Fix cursor positioning when jumping to next/prev reference

**Comment by prabirshrestha** [comment]
Please try latest version.
