### ISSUE TITLE
more easy config for php

### ISSUE THREAD

**Issue by zhoupro** [prabirshrestha/vim-lsp#409]
'php': ['intelephense', '--stdio']  rather than ['node', '/usr/local/lib/node_modules/intelephense/lib/intelephense.js', '--stdio']

**Comment by prabirshrestha** [comment]
Can you try something similar to typescript language server? https://github.com/prabirshrestha/vim-lsp/wiki/Servers-TypeScript

If that works feel free to update the wiki for php.

**Comment by prabirshrestha** [comment]
Please refer to existing samples for other servers.
