### ISSUE TITLE
Add "peek definition"

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#411]
I'd be nice to add a `LspPeekDefinition` (insert bike-shedding here, name taken from VS Code that offers this) that works like `LspDefinition`, but instead of jumping to the location in a new buffer, only shows the location in a preview window (like `LspHover` uses; bonus points for floating window when that is implemented).

**Comment by thomasfaingnaert** [comment]
@clason Does #412 fulfill your needs?

**Comment by clason** [comment]
Yes, that's exactly what I had in mind, thank you!
