### ISSUE TITLE
completion does not work when typing some characters after deleting

### ISSUE THREAD

**Issue by mattn** [prabirshrestha/vim-lsp#421]
![terminal7](https://user-images.githubusercontent.com/10111/60251163-fb808900-9902-11e9-9426-a724f8023fd0.gif)

Repro steps:
1. type some characters that can be match something type name or module name
2. type backspace to delete input
3. type another characters

Probably, it seems to behave with remaining prefix characters.

**Comment by casr** [comment]
Perhaps you are using [`asyncomplete.vim`](https://github.com/prabirshrestha/asyncomplete.vim)? Could the issue be related to that?

As a workaround for this problem, I have:
```vim
" prabirshrestha/asyncomplete.vim {{{
imap <C-g> <Plug>(asyncomplete_force_refresh)
" }}}
```
in my `.vimrc`. When I backspace, I then hit <kbd>Ctrl</kbd>+<kbd>g</kbd> if I notice the menu failing me.

Would be great to have this automatic where ever the issue may lie.

**Comment by prabirshrestha** [comment]
I can't seem to reproduce this now. Can you try with latest vim-lsp and asyncomplete and check if works?

**Comment by mattn** [comment]
Yes, me too.
