### ISSUE TITLE
References to vim positions can't handle non-ASCII chars

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#425]
The issue is that the encoding of non-English characters (cue UTF-16 rant) breaks position information in vim-lsp, leading to all sorts of issues. Consider the following minimal example using the `pyls` language server for Python (I use neovim HEAD for this):

1. Edit a fresh Python file, e.g., with `nvim test.py`
2. Type the following:
```python
var1 = 1.0
var2 = var1**2
```
3. Move the cursor to `var1` on the first line, which should correctly highlight `var1` on the second line as well (cursor is on character after `|`, highlight indicated by `[...]`):
```python
|var1 = 1.0
var2 = [var1]**2
```
4. Change `var2` to `vär2`, move cursor back to first line:
```python
v|ar1 = 1.0
vär2 =[ var]1**2
```
Note how the highlight is shifted left by one character. This is not just a cosmetic problem; the location of the symbol `var1` on the second line is calculated incorrectly, which means that, e.g., `hover`  (which triggers on the same -- incorrect -- characters as are highlighted) and identification of completion triggers for candidate selection and replacement do not work.

**EDIT** It seems that the issue is with the `range_to_position` function in `references.vim`; it's not clear to me how to change it to account for non-ASCII chars _outside_ the given range.

5. (Bonus **EDIT**: this is fixed by #447, but I'm leaving it here since the error message might contain useful information to someone.) Now change `vär2` to `vör2`, go back to `var1`, and get the error message
```
Error detected while processing function lsp#ui#vim#references#highlight[31]..lsp#send_requ
est[4]..lsp#utils#step#start[1]..<SNR>75_next[9]..<lambda>121[1]..<SNR>70_ensure_flush[1]..
lsp#utils#step#start[1]..<SNR>75_next[9]..<lambda>123[1]..<SNR>70_ensure_start[15]..<SNR>75
_callback[1]..<SNR>75_next[9]..<lambda>124[1]..<SNR>70_ensure_init[6]..<SNR>75_callback[1].
.<SNR>75_next[9]..<lambda>125[1]..<SNR>70_ensure_conf[14]..<SNR>75_callback[1]..<SNR>75_nex
t[9]..<lambda>126[1]..<SNR>70_ensure_open[16]..<SNR>75_callback[1]..<SNR>75_next[9]..<lambd
a>127[1]..<SNR>70_ensure_changed[19]..<SNR>70_send_notification[6]..lsp#log_verbose[2]..lsp
#log:
line    2:
E474: String "<b6>" contains byte that does not start any UTF-8 character
```

**Comment by clason** [comment]
Closed by #467

**Comment by clason** [comment]
Sorry, wrote too soon. Something is different between the merged version and the one I tested.

**Comment by clason** [comment]
@machakann It seems that you're still working on that branch -- do you plan on merging it soon, or should I cherry-pick your fix that didn't make it into the PR?

**Comment by machakann** [comment]
Hi @clason, yes I'm working on it. I inserted character-byte index interconversion at the places necessary (maybe). Currently, I'm searching for a language server for testing some features; my language server won't work with rename command... At least, it seems `textDocument/completion` is working.

I will open a new PR soon, I would be glad if you could help to test the branch.

**Comment by clason** [comment]
@machakann Great, thank you! I tested your branch, and `hover` and `Goto`/`PeekDefinition` seems to be working as well. I have a language server (texlab) that does support renaming, and I'll be happy to test it. (Have to find an example that doesn't work on master first.)

**Comment by clason** [comment]
@machakann If you wish, I can make a PR on top of master based on your branch now so we can get the fixes in, and you can continue on top of that?

**Comment by machakann** [comment]
@clason Sorry for being late. I submitted! #490

**Comment by clason** [comment]
@machakann No need to apologize! I really appreciate your kind help!

I can confirm that #490 fixes my issues (including `hover`, `Definition`, `References`, `completion`, and `rename`).

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/490 has been merged. please try again.

**Comment by clason** [comment]
Yep, still works! Thank you!
