### ISSUE TITLE
Support workspace/configuration request

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#426]
Vim-lsp supports configuration of servers via the `initializationOptions` field of the `InitializeParams`interface, but not via the [workspace/configuration](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration) request that some servers use: it responds with a "method not found error if texlab sends this request:

```
Thu 27 Jun 2019 02:40:55 PM CEST:["--->", 5, "texlab", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize": 8}, "textDocument": {"uri": "file:///home/clason/Dropbox/tex/NonsmoothBook/nonsmooth.bib"}}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["<---", 5, {"method": "workspace/configuration", "jsonrpc": "2.0", "id": 1, "params": {"items": [{"section": "bibtex.formatting"}]}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["--->", 5, "texlab", {"id": 1, "error": {"code": -32601, "message": "Method not found"}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["<---(stderr)", 5, "texlab", ["TRACE - Received message:", "{\"id\": 2, \"jsonrpc\": \"2.0\", \"method\": \"textDocument/formatting\", \"params\": {\"options\": {\"insertSpaces\": true, \"tabSize\": 8}, \"textDocument\": {\"uri\": \"file:///home/clason/Dropbox/tex/NonsmoothBook/nonsmooth.bib\"}}}", "TRACE - Sent message:", "Content-Length: 112\r", "\r", "{\"jsonrpc\":\"2.0\",\"method\":\"workspace/configuration\",\"params\":{\"items\":[{\"section\":\"bibtex.formatting\"}]},\"id\":1}", ""]]
Thu 27 Jun 2019 02:40:55 PM CEST:["invalid response id. ignoring message", {"id": null, "jsonrpc": "2.0", "error": {"code": -32700, "message": "Could not parse the input"}}]
Thu 27 Jun 2019 02:40:55 PM CEST:["<---(stderr)", 5, "texlab", ["TRACE - Received message:", "{\"id\": 1, \"jsonrpc\": \"2.0\", \"error\": {\"code\": -32601, \"message\": \"Method not found\"}}", "TRACE - Sent message:", "Content-Length: 89\r", "\r", "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32700,\"message\":\"Could not parse the input\"},\"id\":null}", ""]]
```

**Comment by edganiukov** [comment]
I guess vim-lsp already supports it, see - https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Rust
```
\ 'workspace_config': {'rust': {'clippy_preference': 'on'}},
```

**Comment by clason** [comment]
But it doesn't (correctly) advertise it, it seems? And if the server decides the client doesn't support a feature, it may ignore it.

**Comment by thomasfaingnaert** [comment]
`'workspace_config'` is used for the params of [`workspace/didChangeConfiguration`](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration), which I believe is different from `workspace/configuration`?
From the spec it appears `workspace/didChangeConfiguration` is a notification from client to server to signal changes in configuration, whereas `workspace/configuration` is a request sent from server to client to fetch configuration settings.

Do these two messages use the same "configuration database"? If so, it shouldn't be too hard I guess to implement the response to `workspace/configuration`.

**Comment by thomasfaingnaert** [comment]
@clason 
Could you try #427?

**Comment by clason** [comment]
That seems to be working so far, although vim-lsp's answers still lack the apparently mandatory `'json': '2.0'` fields. I'm also seeing an error in the log:
```
Fri Jul  5 23:16:09 2019:["s:on_stdout on_notification() error", "Vim(call):E5555: API call: Wrong  type for argument 1, expecting Buffer"]
```
but that may be unrelated.

**Comment by thomasfaingnaert** [comment]
Are you checking the `'jsonrpc'` field in the vim-lsp log? If so, I believe the `jsonrpc` header is only added after logging. It should be visible in the log of texlab's `-vvvv`.
At first sight, the error seems to be unrelated. It appears an exception is thrown when the server sends a notification to the client, although without knowing which notification, it's difficult to say what the problem could be.

**Comment by clason** [comment]
Yes, I'm looking at the log. (I would never have guessed that the log doesn't actually contain what's being sent -- doesn't that kinda defeat the purpose?)

I agree that the error looks unrelated; it comes after the lint results for the included bibtex file, which is not opened in a buffer. So I would ignore it for now.

**Comment by thomasfaingnaert** [comment]
I did not write the source, though I suppose it doesn't really matter that the `'jsonrpc'` field is not explicitly written to the log, because it is always present. I guess it's just an oversight, or intentional to clean up the log a bit.

It seems that the call to lsp#log is before the call to send, https://github.com/prabirshrestha/vim-lsp/blob/d542bbc5a3b0b2d78552a11f4edfee1c55fc3796/autoload/lsp.vim#L562-L563

and jsonrpc is only set in `s:lsp_send`, which is called from `lsp#client#send_request`:
https://github.com/prabirshrestha/vim-lsp/blob/d542bbc5a3b0b2d78552a11f4edfee1c55fc3796/autoload/lsp/client.vim#L209-L215

Similarly, the `Content-Length: ...` header is also omitted from the log, but that appears to be it.

**Comment by clason** [comment]
@thomasfaingnaert I know you didn't; I also wasn't complaining; just surprised. (Although it would have saved some discussions on earlier texlab issues to have this in the log as well.)
