### ISSUE TITLE
Completion mess with existing code

### ISSUE THREAD

**Issue by pengux** [prabirshrestha/vim-lsp#431]
Referring to issue https://github.com/prabirshrestha/asyncomplete.vim/issues/127, upon completion it deletes existing code. Setting `let g:lsp_text_edit_enabled = 0` fixes this behavior.

**Comment by 0xBADDCAFE** [comment]
This issue targets like the behavior?

1. <kbd>ce</kbd> on normal mode to go to insert mode with erase part of word
2. `<C-n>` to select completion that longer than original word. 
3. `<Esc>` and wait to dismiss popup
3. Completion deletes trailing code ( `(` before `resp.Body` is deleted in below gif)

![rec_20191028_100458](https://user-images.githubusercontent.com/599164/67645298-26d7bb00-f96b-11e9-8d4d-703c1daaddc7.gif)

VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 29 2019 22:27:49)
Included patches: 1-2102
OS: Arch Linux (on WSL)
LSP Engine: golang.org/x/tools/gopls v0.1.7 (go version go1.13.3 linux/amd64)

**Comment by mnishz** [comment]
I think I got the same behavior. I'll also change `g:lsp_text_edit_enabled` for tentative fix.

**Comment by mattn** [comment]
did you solve this issue?

**Comment by 0xBADDCAFE** [comment]
Setting `let g:lsp_text_edit_enabled = 0` prevent this, but  still causes when `let g:lsp_text_edit_enabled = 1`  .
#597 explains further, so I think that can close this issue and continue discussion in #597 .

**Comment by mattn** [comment]
Updated textEdit behavior in recent changes. Could you please try this again?

**Comment by mnishz** [comment]
The same issue was recreated with the latest one (ed1c26342b29681cbc06faaaaad675ebbbe2d1a3) and `let g:lsp_text_edit_enabled = 1`.

**Comment by 0xBADDCAFE** [comment]
Still causes with ed1c263 and `let g:lsp_text_edit_enabled = 1` (on above environment) too.

**Comment by prabirshrestha** [comment]
Can you try the latest master again. else please provide a hello world repository with repo.

**Comment by prabirshrestha** [comment]
Also if anyone has a minimal repository with the repo that would be good.

**Comment by 0xBADDCAFE** [comment]
>  hello world repository with repo.

I'll try it so please just a time (few day).

**Comment by hrsh7th** [comment]
@0xBADDCAFE
Could you try #637?
I re-implement CompleteDone behavior.

**Comment by 0xBADDCAFE** [comment]
I tried #637 and it seems to be fixed.

**Comment by mnishz** [comment]
#637 worked on my machine as well.

**Comment by prabirshrestha** [comment]
PR has been merged. Please try latest master. Thanks to those who tired and bit shoutout to @hrsh7th for the actual fix.
