### ISSUE TITLE
How should I get back after a go-to-definition action?

### ISSUE THREAD

**Issue by kailin4u** [prabirshrestha/vim-lsp#434]
Hi every one , I'm wondering if there is a command to let me get back to the original file position after I jump to a symbol definition.

should there be something like position stack to let me jump front and jump back between files?

**Comment by thomasfaingnaert** [comment]
CTRL-O and CTRL-I in normal mode should work.
(see `:h CTRL-O` and `:h CTRL-I`)

**Comment by kailin4u** [comment]
> CTRL-O and CTRL-I in normal mode should work.
> (see `:h CTRL-O` and `:h CTRL-I`)

works for me. thanks a lot ^_^

**Comment by gokayburuc** [comment]
<kbd> CTRL + O </kbd>  default key works pretty well in NeoVim.

System : 
Linux 5.15.0-67-generic
20.04.1-Ubuntu
