### ISSUE TITLE
Battery included?

### ISSUE THREAD

**Issue by VMatrix1900** [prabirshrestha/vim-lsp#44]
Can we include the configuration of supported language server in the plugin? Just like the [ALE](https://github.com/w0rp/ale) does. This will lower the barrier to use the plugin. In this way the registering server API is hiding from the end user, giving you the freedom to change it in the future.

**Comment by prabirshrestha** [comment]
No plans to add batteries. But if anyone wants to tackle this on their own vim plugin I would be happy to include the reference and even promote it in this repo and README.md.

If I include batteries it means I need to keep maintaining it forever. ALE has over 80+ issues mostly asking to include those batteries. I have too many OSS projects and that wouldn't scale for me. I want all issues to be actionable by me by at most 1 week. I wouldn't be the right person to make the decisions on languages I don't work on. I would then become the bottleneck for others.

Ideally I would prefer special plugins based on `vim-lsp`. For example: For typescript/typescript that plugin should support `:NpmInstall`, `:NpmSearch`, `:NpmStart`. For python, c, c++ it could be some other things. I would rather have those experiences.

Closing the issue now. But feel free to continue the dicsussions.

**Comment by ryanolsonx** [comment]
Can you please include references to two of my repositories?

https://github.com/ryanolsonx/vim-lsp-typescript
https://github.com/ryanolsonx/vim-lsp-python

I had a hard time getting setting up when I started using this plugin and simply installing these other plugins should allow for an easier setup experience.

I might create other repositories for _some_ other languages but I mainly use these two.

**Comment by prabirshrestha** [comment]
@ryanolsonx Feel free to update the wiki. You can refer to cquery as an example - https://github.com/prabirshrestha/vim-lsp/wiki/Servers-cquery

**Comment by ryanolsonx** [comment]
Awesome! Will do. Thanks.
