### ISSUE TITLE
Float positioning

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#444]
There seems to be an issue with the float positioning that could be improved (at least with neovim):

1. If `PeekDefinition` is triggered on a symbol in the top half of the window, the float is opened under the current line and extends to the bottom of the window. 
2. If it's triggered in the bottom half, the float is opened above the current line but the height is the same as would fit to the bottom (up to a minimum height of ten lines) -- which, needless to say, may be too small.

~Bonus:~

~3. It would be nice if the peek target was always a fixed distance from the *top* of the float (either the first line or -- with padding -- the second or third line) rather than the middle of the float; currently it takes me quite a bit each time a float opens to locate the line(s) I'm interested in (since the size and hence the offset is different each time).~

**Comment by thomasfaingnaert** [comment]
For 3. `:h g:lsp_peek_alignment` is what you're looking for, unless I'm misunderstanding something?

**Comment by clason** [comment]
No, I just fail basic reading comprehension 🤦‍♂

**Comment by thomasfaingnaert** [comment]
It happens to the best of us :smiley: 
You could probably even add padding by setting `scrolloff` in the float opened autocmd, but I haven't tested it.

**Comment by thomasfaingnaert** [comment]
@clason 
Sorry for the delay. Can you check if #468 fixes your issue?

**Comment by clason** [comment]
Hey, no worries, you're doing this in your spare time! 

Yes, that fixes the issue nicely. The only (cosmetic) issue I noticed is that if the location is at the end of the buffer, the float still extends from the top of the page to the position, padded with end of buffer marks (default `~`). Doesn't interfere with functionality, though (meaning the relevant line is still shown, unlike without this PR).

**Comment by thomasfaingnaert** [comment]
I guess that's because the "requested height" of the floating window is the total number of lines in the buffer. It doesn't take into account that you will later scroll the buffer.

I don't think it makes much sense to fix this, since it only happens for things like `LspPeekDefinition`. Adding code just for this specific case may make the codebase more unreadable? Besides, if you focus the popup window and scroll around, you may want the height to extend to the top of the screen. What do you think?

**Comment by clason** [comment]
In principle, I agree -- this is a minor cosmetic issue. Long-term, I hope that texlab supports the `LocationLink` field in `GotoDefinition` that contains a range for the target of interest (which could be the labelled environment) that could be used for a more tailored peek (using `nvim_win_config` to resize the float).

But that's in the future and not relevant here. The only thing I can think of now in this context is maybe adding a `g:lsp_preview_max_height` option?

**Comment by thomasfaingnaert** [comment]
Added `g:lsp_preview_max_height` to #468.
