### ISSUE TITLE
vim8.1 has no diagnostics highlight

### ISSUE THREAD

**Issue by LinkShen** [prabirshrestha/vim-lsp#453]
Hi, I follow the readme on github to get vim-lsp works well except diagnositc highlight.

### vim version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 16 2019 12:45:04)
Included patches: 1-1008
Compiled by slxn4090@onlinegame-52-103
Huge version without GUI.  Features included (+) or not (-):
+acl               +conceal           +folding           +menu              +packages          -sun_workshop      +virtualedit
+arabic            +cryptv            -footer            +mksession         +path_extra        +syntax            +visual
+autocmd           +cscope            +fork()            +modify_fname      -perl              +tag_binary        +visualextra
+autochdir         +cursorbind        -gettext           +mouse             +persistent_undo   +tag_old_static    +viminfo
-autoservername    +cursorshape       -hangul_input      -mouseshape        +postscript        -tag_any_white     +vreplace
-balloon_eval      +dialog_con        +iconv             +mouse_dec         +printer           -tcl               +wildignore
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +wildmenu
-browse            +digraphs          +job               -mouse_jsbterm     +python            +terminal          +windows
++builtin_terms    -dnd               +jumplist          +mouse_netterm     -python3           +terminfo          +writebackup
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      -X11
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       -xfontset
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +textprop          -xim
-clientserver      +ex_extra          +libcall           +mouse_xterm       -ruby              +timers            -xpm
-clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        +title             -xsmp
+cmdline_compl     -farsi             +lispindent        +multi_lang        +signs             -toolbar           -xterm_clipboard
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +user_commands     -xterm_save
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +vartabs
+comments          +float             -lua               +num64             +statusline        +vertsplit

### lsp related vimrc config
syntax on
colorscheme desert

" lsp
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-background-index']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp']})
endif

let g:lsp_highlights_enabled = 1
let g:lsp_textprop_enabled = 1
highlight link lspReference CursorLine

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')

### vim-lsp log with "highligh" keyword
Sun 28 Jul 2019 05:23:27 PM HKT:["lsp#register_server","server registered","clangd"]
Sun 28 Jul 2019 05:23:27 PM HKT:["vim-lsp signs enabled"]
Sun 28 Jul 2019 05:23:27 PM HKT:["vim-lsp highlighting requires neovim"]
Sun 28 Jul 2019 05:23:27 PM HKT:["vim-lsp highlighting enabled (textprop)"]
Sun 28 Jul 2019 05:23:27 PM HKT:["s:on_text_document_did_open()",1,"cpp","/home/slxn4090/test","file:///home/slxn4090/test/main.cpp"]
Sun 28 Jul 2019 05:23:27 PM HKT:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"clangd"},"message":"started lsp server successfully"}}]
Sun 28 Jul 2019 05:23:27 PM HKT:["--->",1,"clangd",{"method":"initialize","params":{"rootUri":"file:///home/slxn4090/test","capabilities":{"workspace":{"configuration":true,"applyEdit":true}},"rootPath":"/home/slxn4090/test","processId":1268,"trace":"off"}}]
Sun 28 Jul 2019 05:23:27 PM HKT:["<---",1,"clangd",{"response":{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["clangd.applyFix"]},"documentHighlightProvider":true,"hoverProvider":true,"definitionProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"codeActionProvider":true,"textDocumentSync":2,"documentOnTypeFormattingProvider":{"moreTriggerCharacter":[],"firstTriggerCharacter":"}"},"workspaceSymbolProvider":true,"documentRangeFormattingProvider":true,"documentFormattingProvider":true,"documentSymbolProvider":true,"renameProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",">",":"]}}}},"request":{"id":1,"jsonrpc":"2.0","method":"initialize","params":{"rootUri":"file:///home/slxn4090/test","capabilities":{"workspace":{"configuration":true,"applyEdit":true}},"rootPath":"/home/slxn4090/test","processId":1268,"trace":"off"}}}]

### my question
As to the log post upon, it seems like i need neovim to enable diagnostic highlight. But the document on github says : Highlighting diagnostics requires either NeoVim 0.3+ or Vim with patch 8.1.0579.
By the way, reference highlight works well for me.
Do I mess up anything? (config or something else)

**Comment by drewolson** [comment]
I'm seeing the same issue with the vim that ships with debian buster. Here's my version info:

```VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401                                                                   
Modified by team+vim@tracker.debian.org                          
Compiled by team+vim@tracker.debian.org                        ```

**Comment by thomasfaingnaert** [comment]
`g:lsp_highlights_enabled` and `g:lsp_textprop_enabled` are actually unrelated. The former is used for Neovim highlights, whereas the latter is used for Vim textprops.
Normally, you shouldn't even need explicitly set either of these variables: they are set to 1 automatically, depending on if you are using Vim or Neovim.
You can ignore the `vim-lsp highlighting requires neovim` warning, it refers to `g:lsp_highlights_enabled` being set to `1`. Setting it to `0` should solve it, though it won't influence much.

Is this the only issue you are having with diagnostics textprops, or does the feature not work?

**Comment by drewolson** [comment]
Here's what I'm seeing:

On my mac, when there are diagnostics, I see the line highlighted and the gutter opens with the icon showing an error.

On my debian machine (version above), I see the diagonostic information in the echo line but the gutter does not open and there is no highlighting of the error.

**Comment by LinkShen** [comment]
thx for response. @thomasfaingnaert 
the error or warning diagnostics not work at all.

my host is debian 8. maybe we share the same problem @drewolson

**Comment by thomasfaingnaert** [comment]
@LinkShen @drewolson Tested this with a live USB of Debian, and I can indeed reproduce this. Do you also have an error "Not enough arguments for function prop_remove" in the log?
It seems that `prop_remove` requires 3 arguments, even though the help clearly indicates that one is sufficient.

@prabirshrestha 
To fix this, we should change the `prop_remove`s in `textprop.vim` to specifiy the start and end line. `line('$')` will only work for the current buffer, though. I don't really know a way to get the number of lines of a buffer, apart from using something like `len(getbufline(buf, 1, '$'))`, but that may be slow for large files.

**Comment by dc25** [comment]
I'm seeing the same problems ( "diagonostic information in the echo line but the gutter does not open and there is no highlighting of the error" ) with the vim version that is installed by default ( 8.1.1401 ) on Ubuntu 19.10 .   However, if I build and install the _same version of vim_ from source, then the the line is highlighted and the gutter opens with the icon showing an error.   Also the "prop_remove" error goes away.

Building and installing the latest version of vim (8.1.2301) from source also seems to work fine.

If I use neovim (installed using apt-get) the highlighting works fine and the gutter opens.     The message on the echo line is also appended to the line that it applies to - I'm not sure whether this is a bug or a feature but I'm only seeing it in neovim.

**Comment by thomasfaingnaert** [comment]
@dc25 Is it also because `prop_remove` expects 3 arguments? (i.e. `:call prop_remove({'id':'test'})` errors with "Not enough arguments?"

The reason you see different behaviour with the system Vim and Vim compiled from source, is that package maintainers (at least on Debian and Ubuntu) do not include all upstream patches in the version they distribute. You can check the "Included patches" line from `:version` to verify this.

**Comment by dc25** [comment]
That makes sense @thomasfaingnaert .   

In any case, my main reason for posting was to give a work around for people who want to use the functionality being discussed.   ( work around: build vim from scratch ) .   

FWIW, here's a simple but (hopefully) self contained script  for building and installing the latest vim in ubuntu : https://raw.githubusercontent.com/dc25/docker_sshd/master/build_scripts/build_latest_vim.sh

**Comment by thomasfaingnaert** [comment]
@LinkShen @drewolson @dc25 Could you give #574 a try? That seems to fix it on my end.

**Comment by dc25** [comment]
@thomasfaingnaert ,  this problem seems to be fixed in the latest vim-lsp running either under the vim that comes with ubuntu 19.10 or under a vim built from scratch from the latest sources.

Thanks!

**Comment by LinkShen** [comment]
It works when i update vim-lsp with VundleUpdate. Great THX.
I feel really good that vim-lsp team response to this issue. @thomasfaingnaert
