### ISSUE TITLE
Support DocumentSymbol in Location list

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#458]
The `texlab` language server (on HEAD) provides a list of `DocumentSymbols` that `vim-lsp` does not show (with `neovim` HEAD). Here's the relevant log snippet (slightly redacted):
```
Sat Aug  3 16:28:44 2019:["--->", 5, "texlab", {"method": "textDocument/documentSymbol", "on_notification": "---funcref---", "params": {"textDocument": {"uri": "file://XXX"}}}]
Sat Aug  3 16:28:44 2019:["<---", 5, "texlab", {"response": {"id": 2, "jsonrpc": "2.0", "result": [{"range": {"end": {"character": 22, "line": 101}, "start": {"character": 0, "line": 101}}, "children": [], "selectionRange": {"end": {"character": 22, "line": 101}, "start": {"character": 0, "line": 101}}, "kind": 2, "name": "1 Introduction", "deprecated": false},...]}, "request": {"id": 2, "jsonrpc": "2.0", "method": "textDocument/documentSymbol", "params": {"textDocument": {"uri": "file://XXX"}}}}]
Sat Aug  3 16:28:44 2019:["s:on_stdout client request on_notification() error", "Vim(let):E716: Key not present in Dictionary: location", "function <SNR>137_on_stdout[4]..<SNR>136_on_stdout[79]..<lambda>9[1]..<SNR>151_handle_symbol[10]..lsp#ui#vim#utils#symbols_to_loc_list, line 11"]
```
Looking at the `symbols_to_loc_list` function, it seems that it's looking for `location`, which is not a required field for `DocumentSymbol`, only for `SymbolInformation` -- by [specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol), a server may return an array of either (or `null`). It seems that `vim-lsp` only supports the latter?

**EDIT** The advantage of `DocumentSymbol` is that it is hierarchical, so you can distinguish, e.g., global and local variables in different functions. This can be used to make the location list into a sort of table of contents (which can be quite useful).

**Comment by clason** [comment]
looks indeed like an invalid response; following up with the server.

**Comment by kadrach** [comment]
This happens with the golang `gopls` language server as well.

**Comment by clason** [comment]
@kadrach What texlab now does is check for the `documentSymbol` capability and otherwise return flat `symbolInformation`s -- that's arguably the correct thing to do. (Doesn't mean `documentSymbol` support wouldn't be nice, of course.)

**Comment by prabirshrestha** [comment]
`vim-lsp` now supports both `DocumentSymbols` and `SymbolInformation`. Please try the latest master.
