### ISSUE TITLE
Signs debounce

### ISSUE THREAD

**Issue by cosminadrianpopescu** [prabirshrestha/vim-lsp#459]
Would you be interested in a PR which would debounce for 500 ms (by default, with possibility to change) the handling of the signs?

I am asking because handling signs is a little heavy on a cygwin environment and it would be nice to be handled only when the user finished typing. I don't want to see all the intermediate signs. For example, if I type `this._pro`, I don't want to see a sign that `_pro` is not defined. But if I finished typing, then my complete typing would be `this._property`, which would generate no sign.

**Comment by prabirshrestha** [comment]
Anything to improve performance is great. Ideally it would be good if we can come up with a more generic queuing/debouncing apis so anyone can use it. Something similar to `s:add_didchange_queue` we currently have but public api that anyone can use. Basically sort of event loop for vim-lsp that others can hook into with knowledge on flushing.
