### ISSUE TITLE
Support servers using different transports than stdio

### ISSUE THREAD

**Issue by hauleth** [prabirshrestha/vim-lsp#469]
Not all servers are supporting stdio as transport. It would be worth adding support for Unix sockets and TCP transports

**Comment by thomasfaingnaert** [comment]
This should be possible, because `ch_open` allows TCP connections.
My guess is that this will require some refactoring, as everything is done with jobs at the moment.

The simplest solution is to start the server outside of Vim, and then use `ncat` as server command.
This allows both TCP/IP and UDS connections.

If you want to add support for TCP, you may want to check `autoload/lsp/client.vim` and start from there.

**Comment by prabirshrestha** [comment]
I'm usually not a fan of TCP due to security issues. vim does support opening TCP connections so should be possible. Good thing about moving to socket or TCP is that it would be faster than stdio specially on windows.

**Comment by prabirshrestha** [comment]
@hauleth Can you provide language servers that doesn't support `stdio`?

For now closing to keep the issues to minimum but feel free to comment so we can revisit this if necessary. For now it might be easier to create a separate binary that just proxies stdout to some other protocol and vice versa.

**Comment by hauleth** [comment]
[Erlang's Sourcer](https://github.com/erlang/sourcer)

**Comment by habamax** [comment]
> Can you provide language servers that doesn't support `stdio`?

godot game engine https://github.com/godotengine/godot/issues/34523

**Comment by mattn** [comment]
Erlang's Sourcer seems support stdio (transport flag?)


https://github.com/erlang/sourcer/blob/e598ec52ed2c62eb50e4556dc9cd5adb664de610/apps/erlang_ls/src/erlang_ls.erl#L24

**Comment by hauleth** [comment]
The additional case is remote development (within Docker or VMs).

**Comment by hauleth** [comment]
@mattn my bad, I meant [ErlangLS which gained the support for stdio quite recently](https://github.com/erlang-ls/erlang_ls/pull/201)

**Comment by mattn** [comment]
@prabirshrestha What about to add ch_open to async.vim ?

```diff
diff --git a/autoload/async/job.vim b/autoload/async/job.vim
index a96a5f1..827329b 100644
--- a/autoload/async/job.vim
+++ b/autoload/async/job.vim
@@ -285,6 +285,21 @@ function! s:job_pid(jobid) abort
     return 0
 endfunction
 
+function! s:callback_cb(jobid, opts, ch, data) abort
+    if has_key(a:opts, 'on_stdout')
+        call a:opts.on_stdout(a:jobid, split(a:data, "\n", 1), 'stdout')
+    endif
+endfunction
+
+function! s:close_cb(jobid, opts, ch) abort
+    if has_key(a:opts, 'on_exit')
+        call a:opts.on_exit(a:jobid, 'closed', 'exit')
+    endif
+    if has_key(s:jobs, a:jobid)
+        call remove(s:jobs, a:jobid)
+    endif
+endfunction
+
 " public apis {{{
 function! async#job#start(cmd, opts) abort
     return s:job_start(a:cmd, a:opts)
@@ -306,4 +321,20 @@ endfunction
 function! async#job#pid(jobid) abort
     return s:job_pid(a:jobid)
 endfunction
+
+function! async#job#connect(addr, opts) abort
+	let l:ch = ch_open(a:addr, {})
+    call ch_setoptions(l:ch, {
+		\ 'callback': function('s:callback_cb', [l:ch, a:opts]),
+		\ 'close_cb': function('s:close_cb', [l:ch, a:opts]),
+		\ 'mode': 'raw',
+	\})
+	return {
+	    \ 'type': s:job_type_vimjob,
+	    \ 'opts': a:opts,
+	    \ 'job': l:ch,
+	    \ 'channel': l:ch,
+        \ 'buffer': ''
+	\}
+endfunction
 " }}}
```
As far as I played little, it might work well.
```
let s:ch = async#job#connect('localhost:8888', {
\ 'on_stdout': {jobid, data, code -> execute('echo data', 1)},
\ 'on_exit': {jobid, status, code -> execute('echo status', 1)},
\})
echo s:ch
```

**Comment by habamax** [comment]
> As far as I played little, it might work well.

I can test if there is anything could be tested :)

**Comment by prabirshrestha** [comment]
If it is using TCP/HTTP one could try using netcat as a proxy.

**Comment by habamax** [comment]
> 
> 
> If it is using TCP/HTTP one could try using netcat as a proxy.

Fair enough. I guess there is netcat for windows.

**Comment by prabirshrestha** [comment]
For now please refer to docs on how to use netcat. https://github.com/prabirshrestha/vim-lsp/pull/928

@mattn might be good to do this by default in vim-lsp-settings that only supports tcp.

**Comment by prabirshrestha** [comment]
@mattn fell free to open an issue in Async.vim about channel. We do need to also think about neocon so the api is consistent.
