### ISSUE TITLE
Better diagnostics UI

### ISSUE THREAD

**Issue by hauleth** [prabirshrestha/vim-lsp#471]
There should be options for:

- cropping virtual text
- use popup/floats

Currently the diagnostics messages can get a little bit messy:

![Zrzut ekranu 2019-08-21 14 39 09](https://user-images.githubusercontent.com/291639/63432440-722c9500-c421-11e9-8b08-e21d820b7e1d.png)

It would be better to allow cropping virtual text displayed inline as well as allowing to show extended informations in popup/float.

**Comment by chao-mu** [comment]
Are you on NeoVim? I just installed vim-lsp and had similar problems. I switched to Vim (current master in Git) and the experience was much better with the text not clogging up my workflow by default. I had no way of shutting this off when using NeoVim. Now vim-lsp just highlights it red and I opt in to the messaging, which is much better.

**Comment by prabirshrestha** [comment]
You can disable it using `let g:lsp_virtual_text_enabled = 1`.
