### ISSUE TITLE
Output from modules is hindering workflow

### ISSUE THREAD

**Issue by pengux** [prabirshrestha/vim-lsp#476]
For example, every time I save a document, there's an output which says `Document formatted`, which is annoying in a few ways:

1. It always shows even though no changes were made to the buffer
2. It requires a key press to hide

Looking through the code, the output is coming from:

```
plugged/vim-lsp/autoload/lsp/ui/vim.vim
551:    echo 'Document formatted'
```

Perhaps adding an option to show/hide these echo lines would be the first step, the second step would be to only echo the output when there are changes made.

**Comment by prabirshrestha** [comment]
For now use this in vimrc to avoid enter key.`set cmdheight=2`
