### ISSUE TITLE
Finding references not working until files are opened

### ISSUE THREAD

**Issue by sbenedetto** [prabirshrestha/vim-lsp#480]
[CMakeLists.txt](https://github.com/prabirshrestha/vim-lsp/files/3551314/CMakeLists.txt)
[vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/3551315/vim-lsp.log)
[f1.txt](https://github.com/prabirshrestha/vim-lsp/files/3551316/f1.txt)
[f2.txt](https://github.com/prabirshrestha/vim-lsp/files/3551317/f2.txt)
[f3.txt](https://github.com/prabirshrestha/vim-lsp/files/3551318/f3.txt)
[main.txt](https://github.com/prabirshrestha/vim-lsp/files/3551319/main.txt)

1. vim my_definition.h , LspReferences on 'first'
Expected: all references are found
Result: None of the references in the other files are shown.
2. now open any of the other cpp file and afterwards go back to my_definition and LpsReferences on 'first' again. Now a new reference is found.

Hope this helps.

**Comment by thomasfaingnaert** [comment]
This is because clangd by default only finds references for open files (see https://clang.llvm.org/extra/clangd/Features.html#cross-references).

You can make references work without opening files by using a project-wide index, see https://clang.llvm.org/extra/clangd/Installation.html#project-wide-index.

**Comment by prabirshrestha** [comment]
Not a vim-lap bug.

**Comment by ramfattah** [comment]
Thank you @thomasfaingnaert, Those links were really helpful.

I added this in my CMakeLists.txt:
```cmake
# Generate the compile_commands.json file to help clangd
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```

then built the project again and go to reference works like a charm.

**Comment by jdeepaa** [comment]
> This is because clangd by default only finds references for open files (see https://clang.llvm.org/extra/clangd/Features.html#cross-references).
> 
> You can make references work without opening files by using a project-wide index, see https://clang.llvm.org/extra/clangd/Installation.html#project-wide-index.

@thomasfaingnaert  can you share the correct link for project-wide index? I have compile_commands.json, but still project-wide reference is not working

**Comment by thomasfaingnaert** [comment]
The index is discussed at https://clangd.llvm.org/design/indexing now. You probably want a BackgroundIndex. IIRC, there is a boolean flag --background-index to control that, but it should be enabled by default. If cross-file references are not working, it might be that your project is quite large, and you need to wait a bit for the index to be completely built.



________________________________

**Comment by jdeepaa** [comment]
@thomasfaingnaert my project is not big. only 4 src files and are 3KB size each. I did use --background-index, but still project wide references are not working.
