### ISSUE TITLE
Completion with clangd overwrites following characters

### ISSUE THREAD

**Issue by E1k3** [prabirshrestha/vim-lsp#482]
Whenever I accept a completion item (selected using C-n and then ESC) from the clangd lsp source, some of the following characters will be overwritten.
Usually between 1 and 3 characters are overwritten. The amount of characters does not seem to depend on the number of characters already typed or being completed.

1. Example ('|' is the cursor position):
`void transfer(std::a|<std::byte, Size>& buffer);`
Selecting std::array from the list of completions results in:
`void transfer(std::array|std::byte, Size>& buffer);`

2. Example ('|' is the cursor position):
`void transfer(std::ar|<std::byte, Size>& buffer);`
Selecting std::array from the list of completions results in:
`void transfer(std::array|d::byte, Size>& buffer);`

Clangd version:
```
clangd version 8.0.1 (tags/RELEASE_801/final)
```
Neovim version:
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -We
xtra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdi
agnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_
HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/sr
c/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
```

init.vim:
```
" Vim-Plug plugin directory
call plug#begin('~/.config/nvim/plugins')

" Completion
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
" LSP client
Plug 'prabirshrestha/vim-lsp'

call plug#end()

set nocompatible
filetype plugin indent on

set background=dark 
set termguicolors

syntax on

" Asyncomplete config
let g:asyncomplete_smart_completion = 1
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_remove_duplicates = 1

" LSP config
let g:lsp_highlights_enabled = 0
let g:lsp_textprop_enabled = 0
" let g:lsp_virtual_text_enabled = 0
" C/C++ LSP
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
		\ 'priority' : 10
        \ })
endif
" Python LSP
if executable('pyls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
		\ 'priority' : 10
        \ })
endif
```
[asyncomplete.log](https://github.com/prabirshrestha/vim-lsp/files/3564001/asyncomplete.log)
[vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/3564002/vim-lsp.log)

**Comment by E1k3** [comment]
No idea?

**Comment by thenewvu** [comment]
Related to: https://github.com/prabirshrestha/asyncomplete.vim/issues/156

It happens to me too. Seems supporting for textEdit is unstable: prabirshrestha/vim-lsp#142

I set let g:lsp_text_edit_enabled = 0 in my rc to workaround this.

**Comment by thomasfaingnaert** [comment]
Does this happen without asyncomplete as well?

**Comment by thenewvu** [comment]
Just tested it, doesn't happens without asyncomplete.

**Comment by thenewvu** [comment]
@thomasfaingnaert  done with logs, thank you.
