### ISSUE TITLE
`clangd` format issues

### ISSUE THREAD

**Issue by xulongwu4** [prabirshrestha/vim-lsp#483]
I found that the formatting function with `clangd` is sometimes a hit or miss. I have the following example to reproduce the issue that I have seen.

Create the following file with the given content:
```cpp
class ABC {
    private:
int a;};
```
Then running `LspDocumentFormat` gives me the following result:
```cpp
class ABC {private:

int a;};
```

The expected formatted document should be as follows:
```cpp
class ABC {
private:
  int a;
};
```

This is when no `.clang-format` file is used.

The log file is attached here: 
[vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/3563740/vim-lsp.log)

**Comment by E1k3** [comment]
I would expect clangd to use cpang-format internally. Have you compared this behaviour with a manual clang-format call?

**Comment by mattn** [comment]
Could you please try https://github.com/prabirshrestha/vim-lsp/pull/488 fix this?

**Comment by xulongwu4** [comment]
@mattn With patch #488 applied, the formatted text for the above example becomes as follows:
```cpp
class ABC {
private:
  
int a;};
```

So it is slightly better than before, but it still does not resolve the issue.

**Comment by thomasfaingnaert** [comment]
@xulongwu4 Could you retry with 4ee0799b4d61cb33f0e5ce5b39c36ff477ccdf58? On my machine, I get the expected result now:

```cpp
class ABC {
private:
  int a;
};
```

**Comment by xulongwu4** [comment]
@thomasfaingnaert Pathc $488 with commit 4ee0799 gives me correct result as well.
