### ISSUE TITLE
Allow per-server customization of symbol and completion kinds

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#486]
The standard enum from the [LSP specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) is a poor fit for some languages (such as LaTeX, for which there is https://github.com/latex-lsp/texlab).

It would be nice to be able to override the `s:symbol_kinds` and `s:kind_text_mappings` with a custom enum in the `lsp_setup` server configuration.

**Comment by thomasfaingnaert** [comment]
Do you think you'll be able to make a PR for this?

**Comment by clason** [comment]
With help, maybe 😉

**Comment by thomasfaingnaert** [comment]
@clason Oops, missed the sneaky edit :smile: 

1. I would keep it script-local, so something like `s:get_kind_text_mappings(server)` that returns the correct mappings will work. We may indeed want to cache this so we don't have to look it up every completion request (though I image the overhead wouldn't be _that_ high). Anyways, to do that you can cache it in a Dict with key the language server and value the cached list, if any. When calling `s:get_kind_text_mappings` you check if it's cached, and if so return the cached value. (This may not be worth it, though)

2. I would just use another entry in the `config` dict, whose value is another dict that looks like `s:symbol_kinds`. I.e. `'config': {'symbol_kinds': {'27': '...', '28': '...'}`. You might want to include logic to "merge" this custom list with the defaults, so you don't have to specify items 1-26 every time.

3. That's a bit more complicated, indeed. You need to propagate the server name up the entire call hierarchy. I suggest leaving this for last.

**Comment by clason** [comment]
@thomasfaingnaert Sorry for the sneaky edit :) 

To be honest, this does sound a bit above my pay grade, complication-wise -- I think I'd rather work on the `LocationLink` issue first (where pointers on where to start would also be appreciated), and come back to this when and if I feel more comfortable with the code base (and vimL).

**Comment by clason** [comment]
@thomasfaingnaert Getting per-server `symbolKinds` was surprisingly easy, but I'm having difficulties with `completionItemKinds`. Specifically, I can't seem to pass the server name to the `lsp#omni#default_get_vim_completion_item` function -- mostly because I don't understand this line:    https://github.com/prabirshrestha/vim-lsp/blob/e23a00e12d3dded5590e7f4c37ea897071c5be2c/autoload/lsp/omni.vim#L157

**Comment by thomasfaingnaert** [comment]
@clason 
That line replaces each item in `l:items` by the return value of `lsp#omni#get_vim_completion_item` (by default, this redirects to `lsp#omni#default_get_vim_completion_item`).
Did you change the signature of `default_get_vim_completion_item` as well?

**Comment by clason** [comment]
@thomasfaingnaert Yes, I did. Maybe the indirection via `lsp#omni#get_vim_completion_item` is somehow eating it?

**Comment by thomasfaingnaert** [comment]
It should just forward all arguments to `default_...`. Could you push the changes you made? Might make it easier to debug what the problem could be.

**Comment by clason** [comment]
@thomasfaingnaert Done.
