### ISSUE TITLE
Signature help closes too soon

### ISSUE THREAD

**Issue by thomasfaingnaert** [prabirshrestha/vim-lsp#493]
At the moment, signature help closes immediately after typing the trigger character. It would be more useful to keep the signature open, like VSCode does.

The LSP spec doesn't seem to have a list of "commit chars" that close the signature help, so maybe we can allow this to be configurable instead?

**Comment by thomasfaingnaert** [comment]
Seeing that `textDocument/signatureHelp` is only used for function calls, it might make sense to just show it until the user types `)` or leaves insert mode.

**Comment by hrsh7th** [comment]
Hi, I try to improve signature-help too.

IMO, We should use `getline()` to search trigger character and `preview` feature should support insert-mode well, I think.

I implemented those changes, but it has become bit complex.
(And pum and signature-help are overlapping..., I don't know solution)

My patch are [here](https://github.com/hrsh7th/vim-lsp/commit/bcbf48f3a80f178328742ce3a16b2ef83b502ca6).

If it looks good, I'll send PR.

**Comment by thomasfaingnaert** [comment]
@hrsh7th 
It still autocloses after typing `(` on my machine. Do I need additional configuration?
Feel free to send PR. Could you separate the autoclosing fix and highlighting parameters in different PRs?

**Comment by hrsh7th** [comment]
Thanks for your response and advice.

I think, It must not need to additional configuration.
I'll check more deeply.

First I try to create PR to highlights.

**Comment by hrsh7th** [comment]
I've created improved version of my before patch.
https://github.com/hrsh7th/vim-lsp/commit/694f1c03d66ba5c1b3bcc13721af32b43ab2f97c

I found the reason of the before patch is not work, that caused by `lexima.vim`.

My new patch are the supports lexima.vim maybe.

I will organize code then send PR.

**Comment by hrsh7th** [comment]
I checked my patch in nvim, it works well. but it not work vim.
I found the reason. I trying solve it now.

**Comment by prabirshrestha** [comment]
This now works by https://github.com/prabirshrestha/vim-lsp/pull/638. Thanks to @hrsh7th for the fix.

It works with text edit (such as auto imports in typescript) as well as lexima.

**Comment by Hezkore** [comment]
This still happens to me every single time I try to use the signature help in Go using gopls.
