### ISSUE TITLE
Configuration for Ember Language Server

### ISSUE THREAD

**Issue by lowski** [prabirshrestha/vim-lsp#50]
Hi,
I'm sorry but I'm not very familiar with language server protocol yet.

Could you help me with configuring it to work with [ember-language-server](https://github.com/emberwatch/ember-language-server)?

Thank you in advance!

**Comment by prabirshrestha** [comment]
Seems like this is quite different than other lang servers.

I would suggest to file a bug on their github issue and request them to add `bin` in `package.json` so it can be executed as a normal binary. https://github.com/emberwatch/vscode-ember/blob/ba2d653556a54c8383c669f4062353dfc8d7e96f/src/extension.ts#L15. While it possible to do without this it seems better to have bin and would simplify the code in vim.

**Comment by lowski** [comment]
@prabirshrestha thanks for your reply!

I will file an issue on their GitHub but before that, I would like to understand it :).

I came up with the following (temporary) solution so far:

1. I've installed `ember-language-server` globally (`npm install -g ...`)
2. I've wrapped it inside simple bash script which I've added to the path with `chmod +x` permission:

```
#!/usr/bin/env bash

npm_path=$(npm config get prefix)
node ${npm_path}/lib/node_modules/@emberwatch/ember-language-server/lib/start-server.js
```

Unfortunately, the last line does not do anything (no error, no output, etc.). Even if I run it directly (`node start-server.js`) inside the `ember-language-server/lib` directory nothing happens.

Am I doing something wrong? How should I start the server?

**Comment by prabirshrestha** [comment]
You are most likely missing `--stdio` flag.

```
node ${npm_path}/lib/node_modules/@emberwatch/ember-language-server/lib/start-server.js --stdio
```

Also another feature request would be to add support for `--help`.

```
$ typescript-language-server --help

  Usage: typescript-language-server [options]


  Options:

    -V, --version                         output the version number
    --stdio                               use stdio
    --node-ipc                            use node-ipc
    --socket <port>                       use socket. example: --socket=5000
    --tsserver-logFile <tsServerLogFile>  Specify a tsserver log file. example: --tsServerLogFile=ts-logs.txt
    --tsserver-path <path>                Specifiy path to tsserver. example: --tsserver-path=tsserver.cmd
    -h, --help                            output usage information
```

**Comment by lowski** [comment]
@prabirshrestha adding `--stdio` flag didn't help. I guess it must be something wrong with the library.

Thank you for your help.
