### ISSUE TITLE
neovim multiprocessing

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#501]
https://github.com/neovim/neovim/pull/9943

Wondering if we can do heavy computation such as computing diff or fuzzy omni func filtering using this. asyncomplete does support custom pre-processor https://github.com/prabirshrestha/asyncomplete.vim/blob/797394b1c1180ff6d9a60c25e2fbac47bb2f721c/doc/asyncomplete.txt#L57-L89

@justinmk Would this be possible? Also it is using threads or new process?

**Comment by justinmk** [comment]
Depends on what you're looking for. It starts subprocesses, so you can do anything in the subprocesses and return/collect results.

**Comment by abdelhakeem** [comment]
@prabirshrestha Yes, that would be a very good chance to assess the current implementation and discover pain points. https://github.com/neovim/neovim/pull/10843 is the up-to-date PR for this feature.
