### ISSUE TITLE
highlight on incorrect texts

### ISSUE THREAD

**Issue by thenewvu** [prabirshrestha/vim-lsp#503]
This issue hasn't happened before, only with recent commits, I'm not sure which one causes this.

In my case, I set:

```
hi link LspErrorHighlight Underlined
hi link LspWarningHighlight Underlined
hi link LspInformationHighlight Underlined
hi link LspHintHighlight Underlined
```

Notice these underline highlights are on incorrect texts, which that should be on the ones above.

![Screen Shot 2019-09-11 at 14 57 58](https://user-images.githubusercontent.com/6092585/64679028-04660d00-d4a5-11e9-8846-01431657b1b7.png)

**Comment by thomasfaingnaert** [comment]
Could you do a bisect to see which commit introduces this?

**Comment by thenewvu** [comment]
Okay, it may take some minutes.

**Comment by thenewvu** [comment]
The commit 3121f0a causes this.

**Comment by clason** [comment]
It's line 98 in `highlights.vim`, I think -- the commit added a `+1` here. (Probably copy&paste, don't see what that should have been needed.)

**Comment by thenewvu** [comment]
No, removing `+1` doesn't fix the issue, the author did `-1` here https://github.com/prabirshrestha/vim-lsp/commit/3121f0a91610ec8c70d5d69f6f2bc66a28e8122d#diff-d894fdd20596308dd9b1c8ac8a9197c8R752 in `lsp#get_position`. Looks like the `l:item['range']['start']['character']` is incorrect, so it leads to all below variables are incorrect. Honestly, I don't understand what I just said :(

**Comment by clason** [comment]
@thenewvu Are you sure? `lsp#get_position` doesn't seem called in the `highlight` code path (and most other functions work correctly -- I tested this). I assume you've tested just removing the `+1` here, right?

**Comment by thenewvu** [comment]
This patch may work:

```diff
diff --git a/autoload/lsp/ui/vim/highlights.vim b/autoload/lsp/ui/vim/highlights.vim
index 8c7b5d5..674e380 100644
--- a/autoload/lsp/ui/vim/highlights.vim
+++ b/autoload/lsp/ui/vim/highlights.vim
@@ -95,11 +95,11 @@ function! s:place_highlights(server_name, path, diagnostics) abort
 
     if !empty(a:diagnostics) && l:bufnr >= 0
         for l:item in a:diagnostics
-            let l:line = l:item['range']['start']['line'] + 1
+            let l:line = l:item['range']['start']['line']
             let l:start_char = l:item['range']['start']['character']
-            let l:start_col = lsp#utils#to_col(l:bufnr, l:line, l:start_char)
+            let l:start_col = lsp#utils#to_col(l:bufnr, l:line, l:start_char) - 1
             let l:end_char = l:item['range']['end']['character']
-            let l:end_col = lsp#utils#to_col(l:bufnr, l:line, l:end_char)
+            let l:end_col = lsp#utils#to_col(l:bufnr, l:line, l:end_char) - 1
 
             let l:name = get(s:severity_sign_names_mapping, l:item['severity'], 'LspError')
             let l:hl_name = l:name . 'Highlight'
```

After applied the patch, I found another bug and I don't think it was from the patch, the highlight won't be applied if the above line is empty, take a look closely on this gif:

![vim-lsp-503](https://user-images.githubusercontent.com/6092585/64688375-7135d300-d4b6-11e9-8ffa-4daf7dcc786d.gif)

**Comment by hrsh7th** [comment]
The `nvim_buf_add_highlights` based on {zero,bytes}-indexed.
Is this related to the problem?

<img width="407" src="https://user-images.githubusercontent.com/629908/64694780-7bb39500-d4d5-11e9-9561-4395a0cce10f.png">

**Comment by clason** [comment]
@hrsh7th Yes, `to_col` converts to 1-based byte index, so the `-1` in this patch is needed.

**Comment by clason** [comment]
@thenewvu The issue with the blank line is specific to the underline highlight: I get the correct highlight after an empty line with the default; it also works correctly in vim (8.1). So this looks like an independent issue with neovim's handling of terminal codes (these are notoriously tricky), and should be reported there. (Try to get a minimal example without vim-lsp for that.)

**Comment by thenewvu** [comment]
Okay, so I will make the PR for the above patch.

**Comment by clason** [comment]
@thenewvu I meant the error in your sample that the server is complaining about (`Expected expression` -- note that the message changes, too, so it might be something to do with the server rather than the client or neovim).

**Comment by thenewvu** [comment]
@clason Oh .. it's just a clangd thing I believe, after removing `/` from `//`, clangd thinks it is an operator , so it expects an expression, nothing wrong here I believe, I just make a quick gif to express the issue here only.

**Comment by clason** [comment]
Yes, but *what's* the issue you're illustrating? Is it that the highlights disappear if you delete the top line? (You already pointed that out earlier, so I was looking for a different issue.)

This seems to be a neovim issue; the highlights are correct in vim.

**Comment by thenewvu** [comment]
It's the underlining, the diagnostic highlight from vim-lsp, you can see that altering the above line effects the highlight, it should be an issue right? But you said it's an {neo}vim issue, so I didn't go futher.

**Comment by thenewvu** [comment]
Okay ... after made some tests to make sure, the issue in the below gif actually a vim-lsp issue and it causes by 3121f0a too, because it doesn't happen before the commit.

https://user-images.githubusercontent.com/6092585/64705680-8886b780-d4da-11e9-84fb-56288380995b.gif

**Comment by clason** [comment]
OK, then I understand, thank you for confirming. Yes, the issue with highlights seems to be a different one -- I only get highlights up to the end of the previous line as well. It would be good to try to reproduce this without vim-lsp in neovim; as far as I can see, vim and neovim use totally different code paths here (textprop.vim vs. highlight.vim).

**Comment by clason** [comment]
Yes, I think I see the problem, let me test briefly.

**Comment by thenewvu** [comment]
> > @clason I don't think it solves the whole issue, after working on the patch for some hours, there's still another problem:
> > ![vim-lsp-503-2 x0 2](https://user-images.githubusercontent.com/6092585/64705680-8886b780-d4da-11e9-84fb-56288380995b.gif)
> 
> Okay ... after making some tests to make sure, the issue in the above gif actually a vim-
> lsp issue and it causes by [3121f0a](https://github.com/prabirshrestha/vim-lsp/commit/3121f0a91610ec8c70d5d69f6f2bc66a28e8122d) too, because it doesn't happen before the commit.

> Yes, I think I see the problem, let me test briefly. **EDIT** Yes, that was it -- I commented on your PR #504.

The new patch fixed the above problem is confirmed.
