### ISSUE TITLE
Request for yaml-language-server support

### ISSUE THREAD

**Issue by fourjay** [prabirshrestha/vim-lsp#511]
This looks doable, as here https://github.com/autozimu/LanguageClient-neovim/wiki/yaml-language-server and in this issue thread on the yaml-language-server github repo https://github.com/redhat-developer/yaml-language-server/issues/56

I've poked it a bit, but I'm unsure about how to pass configuration in, in particular my (uninfomed) guess is that the server needs to have an event generated to load the config. I'm not sure how the various config options in vim-lsp correspond, config{} workspace_config{} initialization_options. The neovim client seems to have an explicit #notify() command for the purpose of speaking with the server, and (so far) it's not clear to me what the equivalent lsp-vim command might be.
I confess to being a total newbie here. Not a node person, no experience with typescript nor vscode so I'm not much help.

**Comment by thomasfaingnaert** [comment]
Do you know how the language server expects the settings (i.e. `workspace/didChangeConfiguration`, init options to `initialize`, etc.)?

**Comment by kadrach** [comment]
vim-lsp works with the redhat yaml language server. I do find it a bit slow at times, not something I've looked into too much.

Example config (I use it primarily with AWS CloudFormation templates):

```viml
if executable('yaml-language-server')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'yaml-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'yaml-language-server --stdio']},
        \ 'whitelist': ['yml', 'yaml'],
        \ 'workspace_config': {
        \   "yaml": {
        \     "format.enable": "true",
        \     "completion": "true",
        \     "customTags": [
        \       "!And",
        \       "!If",
        \       "!Not",
        \       "!Equals",
        \       "!Or",
        \       "!FindInMap",
        \       "!Base64",
        \       "!Cidr",
        \       "!Ref",
        \       "!Sub",
        \       "!GetAtt",
        \       "!GetAZs",
        \       "!ImportValue",
        \       "!Select",
        \       "!Split",
        \       "!Join"
        \     ],
        \     "schemas": {
        \       "/Users/neckerskorn/.cache/all-spec.json": "*.yaml"
        \     }
        \   }
        \  }
        \ })
endif
```

**Comment by kadrach** [comment]
Apologies, I forgot that I had to muck with the yaml-language-server itself to get this to work!

I removed these in the `connection.onInitialize` function of the language server (because it was throwing exceptions about undefined values).
```
    // hierarchicalDocumentSymbolSupport = !!capabilities.textDocument.documentSymbol.hierarchicalDocumentSymbolSupport;
    // clientDynamicRegisterSupport = !!capabilities.workspace.symbol.dynamicRegistration;
```

**Comment by fourjay** [comment]
Thanks Niko, that got things working for me enough to go farther. Particularly helpful to know about the ``onInitialize`` issue.
My use case is ansible, and I get completion (with a schema). I enabled hover, with odd results (a blank box).

**Comment by prabirshrestha** [comment]
Please try again by updating both vim-lsp and yaml-language-server.
