### ISSUE TITLE
Control when diagnostics is run

### ISSUE THREAD

**Issue by williamboman** [prabirshrestha/vim-lsp#515]
Hey! I'd like to control when diagnostics are updated/re-run. For example, I want to be able to suspend diagnostics while in insert mode.
[It looks like](https://github.com/prabirshrestha/vim-lsp/blob/906bd2eafea3c305a0b921215c1696436d57e232/autoload/lsp.vim#L154-L171) this is somewhat hard-coded right now.

Also, I'd like to be able to clear diagnostics on a per-line basis. When entering insert mode I want to clear any diagnostic messages on that line (really what I want to do is to clear diagnostics on any lines that I make changes to, but I'd imagine that's pretty difficult to facilitate).

**Comment by caksoylar** [comment]
I would also like to second the request on modifying when diagnostics are run. I really liked [the defaults change in ALE](https://www.reddit.com/r/vim/comments/bs95ud/announcement_changing_default_linting_options_for/), so that linting doesn't happen in insert mode but always happens when you leave it.

**Comment by caksoylar** [comment]
Still valid issue, so leaving this comment.

**Comment by prabirshrestha** [comment]
This is now supported by https://github.com/prabirshrestha/vim-lsp/pull/990. Please give the branch a try.

You can use `let g:lsp_diagnostics_virtual_text_insert_mode_enabled  = 0` to disable the virtual text in insert mode. This is currently only for neovim's virtual text. other highlights and signs will come in future PRs.

**Comment by prabirshrestha** [comment]
[Signs](https://github.com/prabirshrestha/vim-lsp/pull/994), [Virtual Text](https://github.com/prabirshrestha/vim-lsp/pull/994) and [Highlights](https://github.com/prabirshrestha/vim-lsp/pull/995) can now be delayed or disabled in insert mode.

I will also add support for disabling and enabling diagnostics per buffer but this will come few day later. Infrastructure is already there just need to make the apis public.
