### ISSUE TITLE
:LspDocumentFormat doesn't change anything despite the language server returning the formatted text

### ISSUE THREAD

**Issue by opennota** [prabirshrestha/vim-lsp#516]
windows 10
gvim 8.1
When I want to format a file containing `Var    x;` (with extra spaces in between) and use `:LspDocumentFormat`, vim just switches to the visual mode without changing anything. The logs show that the language server returns the formatted text:

```
19.09.2019 11:16:56:["--->",1,"bsl-language-server",{"method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C:/Users/xxx/Documents/2.bsl","version":1,"languageId":"bsl","text":"Var   x;\n\n"}}}]
...
19.09.2019 11:17:06:["--->",1,"bsl-language-server",{"method":"textDocument/formatting","on_notification":"---funcref---","sync":0,"params":{"options":{"insertSpaces":false,"tabSize":8},"textDocument":{"uri":"file:///C:/Users/xxx/Documents/2.bsl"}}}]
19.09.2019 11:17:06:["<---",1,"bsl-language-server",{"response":{"id":3,"jsonrpc":"2.0","result":[{"range":{"end":{"character":1,"line":1},"start":{"character":0,"line":0}},"newText":"Var x;\n"}]},"request":{"id":3,"jsonrpc":"2.0","method":"textDocument/formatting","params":{"options":{"insertSpaces":false,"tabSize":8},"textDocument":{"uri":"file:///C:/Users/xxx/Documents/2.bsl"}}}}]
19.09.2019 11:17:06:["s:build_cmd","keepjumps keepalt b 1 | execute 'keepjumps normal! 1G0v2G01l\"=l:merged_text_edit[''merged''][''newText''].''?''\rgph\"_x'"]
```

**Comment by opennota** [comment]
Vim stops executing the command when it tries an impossible movement. If I add `silent!' to the command here:

https://github.com/prabirshrestha/vim-lsp/blob/60a1d58b77b7f62d3d701652bd8cdd1188027703/autoload/lsp/utils/text_edit.vim#L147

the file is formatted.

```
    let l:cmd = l:cmd . " | execute 'keepjumps silent! normal! " . l:escaped_sub_cmd . "'"
```

**Comment by mattn** [comment]
please provide repro steps.

**Comment by opennota** [comment]
```
echo -e "Var   x;\n\n" > xxx
vim xxx
```

In vim (`^M` is `Ctrl-V Enter`):

```
:let @a="Var x;\n"
:execute 'keepjumps normal! 1G0v2G01l"=@a.''?''^Mgph"_x'
```
This is the command vim-lsp is trying to execute. It fails.

This works:

```
:execute 'keepjumps silent! normal! 1G0v2G01l"=@a.''?''^Mgph"_x'
```

This too (without the `1l`):

```
:execute 'keepjumps normal! 1G0v2G0"=@a.''?''^Mgph"_x'
```

Adding `silent! is not a solution, though: vim-lsp should generate commands correctly.

**Comment by mattn** [comment]
I mean that we want to how to reproduce with your language server. What is the language server? and what is the language?

**Comment by mattn** [comment]
Could you please try this patch?

```diff
diff --git a/autoload/lsp/utils/text_edit.vim b/autoload/lsp/utils/text_edit.vim
index 88f7f0c..12b40a8 100644
--- a/autoload/lsp/utils/text_edit.vim
+++ b/autoload/lsp/utils/text_edit.vim
@@ -209,7 +209,7 @@ endfunction
 
 function! s:generate_move_start_cmd(line_pos, character_pos) abort
     let l:result = printf('%dG0', a:line_pos) " move the line and set to the cursor at the beginning
-    if a:character_pos > 0
+    if a:character_pos > 1
         let l:result .= printf('%dl', a:character_pos) " move right until the character
     endif
     return l:result
```

**Comment by opennota** [comment]
The patch doesn't work, but I made the same change to the `s:generate_move_end_cmd` and this fixed the problem.

The language server is https://github.com/1c-syntax/bsl-language-server/releases

**Comment by mattn** [comment]
Could you please try this PR?

https://github.com/prabirshrestha/vim-lsp/pull/518

**Comment by opennota** [comment]
Works for me.

**Comment by clason** [comment]
Breaks formatting for me, see https://github.com/prabirshrestha/vim-lsp/pull/518#issuecomment-534037815.
