### ISSUE TITLE
Manual requests to server by name

### ISSUE THREAD

**Issue by clason** [prabirshrestha/vim-lsp#520]
Is there a way to manually send a (custom) request or notification to a registered language server by name? I've been trying something like 
```vimL
call lsp#client#send_request('pyls', {'method': 'exit'})
```
but this doesn't work. If I use the `lsp_id` instead of the language server name, it seems to work (if I happen to know it, e.g., by snooping on the log). If that's how it has to be, how can I find out the id from the server name at runtime?

**Comment by clason** [comment]
Nevermind, I confused `lsp#send_request` and `lsp#client#send_request` (the former takes the name, the latter the id).

**Comment by prabirshrestha** [comment]
There is get_server_info too.

**Comment by clason** [comment]
> There is get_server_info too.

Thanks! But how would I get the `lsp_id` for `client#send_request` from that? (I already know the name, or can get it from `lsp#get_whitelisted_servers()`.)
