### ISSUE TITLE
Should use `only` parameter for CodeAction request?

### ISSUE THREAD

**Issue by hrsh7th** [prabirshrestha/vim-lsp#522]
I tried adding a `only` parameter to the code action request.

```VimL
        call lsp#send_request(l:server, {
            \ 'method': 'textDocument/codeAction',
            \ 'params': {
            \   'textDocument': lsp#get_text_document_identifier(),
            \   'range': l:range,
            \   'context': {
            \       'diagnostics' : l:diagnostics,
            \       'only': ['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports']
            \   },
            \ },
            \ 'on_notification': function('s:handle_code_action', [l:server, s:last_req_id, 'codeAction']),
            \ })
```

Then the server returned `Organize Imports` as code action.

I think the `only` parameter is prepared for the toolbar.
I don't know how should handle `only` parameter in vim (because vim has not Toolbar).

IMO, probably if vim-lsp always add the all of `only` parameter, it will be useful.

(I checked in `typescript-language-server`)

**Comment by mattn** [comment]
Can you make pull-request?

**Comment by hrsh7th** [comment]
I will create PR. thanks for your response.

**Comment by prabirshrestha** [comment]
Thanks for the PR. Fixed by https://github.com/prabirshrestha/vim-lsp/pull/607
