### ISSUE TITLE
LspTypeDefinition Not enough arguments for function lsp#ui#vim#type_definition

### ISSUE THREAD

**Issue by gbishop** [prabirshrestha/vim-lsp#530]
I get E119 when I try to use LspTypeDefinition in Typescript code. This is a recent development. 

I've tried updating the various pieces to no avail.

Any ideas on what is going wrong?

**Comment by thomasfaingnaert** [comment]
Can you provide logs?

**Comment by gbishop** [comment]
More info. I see LspTypeDefinition is defined twice.

https://github.com/prabirshrestha/vim-lsp/blob/master/plugin/lsp.vim#L63

and

https://github.com/prabirshrestha/vim-lsp/blob/master/plugin/lsp.vim#L72

Can the 2nd one be the problem?

**Comment by thomasfaingnaert** [comment]
Huh, that's weird. That's indeed the problem: the signature of `type_definition` was changed (it now takes 1 parameter), but apparently the change was only done to the first `LspTypeDefinition`.
Not sure why it occurs twice though...

**Comment by gbishop** [comment]
Deleting the 2nd line in my copy appears to fix things.

**Comment by thomasfaingnaert** [comment]
Seems it's my fault: https://github.com/prabirshrestha/vim-lsp/commit/813ea77b91f9c0a7429d61bb87598beeaddd978b. I'll delete the second occurrence. Thanks for reporting!
