### ISSUE TITLE
Completely disable popup

### ISSUE THREAD

**Issue by GoldsteinE** [prabirshrestha/vim-lsp#533]
vim-lsp is opening popup/preview window every time after opening parenthesis in Python code. I failed to find any option to disable this behaviour.

**Comment by thomasfaingnaert** [comment]
Please see g:lsp_signature_help_enabled.

**Comment by GoldsteinE** [comment]
Thanks!

**Comment by matsp** [comment]
@thomasfaingnaert I think it's a good idea to make this more clear in the documentation. Needed a few hours to find the reason and just found this issue by accident.
