### ISSUE TITLE
pyls output doesn't change after first run

### ISSUE THREAD

**Issue by furrycatherder** [prabirshrestha/vim-lsp#536]
The warnings and errors displayed from pyls don't change after changing my code to correct them.

**Comment by Kraust** [comment]
I've been seeing this issue as well, My workaround currently is to do:
```
:call lsp#stop_server("pyls")
:e!
:w 
```
Every time I want to resfresh pyls. This doesn't always need to be done, but seems more common in files with many errors/warnings.

**Comment by mattn** [comment]
did you solve this issue?

**Comment by Kraust** [comment]
I believe it's a pyls bug. Had the same issue with coc.nvim and coc-python.
