### ISSUE TITLE
Opening LspHover in a split instad of a popup

### ISSUE THREAD

**Issue by JPFrancoia** [prabirshrestha/vim-lsp#539]
Hi,

At the moment, when I run `:LspHover` on a word, it opens a popup (see screen). I can't see the entire popup because it goes out of the screen (or maybe I don't know which key to press?). Anyway, if possible, I would like to see the content of the popup in a split. Is there a way to do that?

Cheers

![screen-2019-10-18-21-17-04](https://user-images.githubusercontent.com/2399090/67121925-ecdd1b00-f1ec-11e9-9f63-3bb888d6bdcb.png)

**Comment by thomasfaingnaert** [comment]
You can fallback to using the preview window using `let g:lsp_preview_float = 0`.

**Comment by JPFrancoia** [comment]
Perfect ! that's exactly what I needed, thanks.
