### ISSUE TITLE
Error: Not enough arguments for function: prop_remove

### ISSUE THREAD

**Issue by studiome** [prabirshrestha/vim-lsp#542]
I use Debian Buster and vim8.1 , Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
.
When vim-lsp starts, error: Not enough arguments for function: prop_remove occurs.
Although newer vim patch solved this problem, Debian (also latest Ubuntu) have a little old version.
I submitted PR #540 .
Dose this change work?

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/540
