### ISSUE TITLE
Wrong TextEdit when inserting into empty line and newText ends with "\n"

### ISSUE THREAD

**Issue by tsufeki** [prabirshrestha/vim-lsp#543]
Text edit inserts wrongly when new text ends with "\n". 

For example:

Original buffer:
```
foo

bar
```

Text edit (insert string ending with a new line at the beginning of the empty line above):
```json
{
  "range": {
    "end": {
      "character": 0,
      "line": 1
    },
    "start": {
      "character": 0,
      "line": 1
    }
  },
  "newText": "quux\n"
}
```

Wrong result:
```
foo

quux
bar
```

Should be:
```
foo
quux

bar
```

I think it's because `"=...p` regards contents as linewise when string ends with `\n` ( see `:h "=`).
Indeed, when I remove `if` at [text_edit.vim:169](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/utils/text_edit.vim#L169) and always use `gPh"_x` branch, it works correctly (but I'm not sure this doesn't break some other cases).

Thanks

**Comment by mattn** [comment]
I added small test into text_edit.vimspec

```
        It adds small line
            call s:set_text(['foo', '', 'bar'])

            call lsp#utils#text_edit#apply_text_edits(
                \ expand('%'),
                \ [{
                \     "range": {
                \       "start": {
                \         "character": 0,
                \         "line": 1
                \       },
                \       "end": {
                \         "character": 0,
                \         "line": 1
                \       }
                \     },
                \     "newText": "quux\n"
                \   }
                \ ])

            let l:buffer_text = s:get_text()
            Assert Equals(l:buffer_text, ['foo', 'quux', '', 'bar', ''])
        End
```
This works well.

**Comment by prabirshrestha** [comment]
@tsufeki @mattn Did anyone of you send a PR? Also is this issue only on windows and when the fileformat is unix? What OS and fileformat were you using?

I had seen similar issue when testing this PR which supports `completion/resolve` with text edits i.e. for langservers like typescript-langauge-server when `CompleteDone` is fired it can auto import the modules.

https://github.com/prabirshrestha/vim-lsp/pull/637#issuecomment-570143730

**Comment by mattn** [comment]
A weeks ago, I tried it on Windows.

**Comment by prabirshrestha** [comment]
@tsufeki Could you send a PR?

**Comment by prabirshrestha** [comment]
Will let @thomasfaingnaert have a look at it since he had written most of the `apply_text_edit`. Not sure if there was a particular reason behind this or the current change is ok.

**Comment by tsufeki** [comment]
e566dcd160497f9903bfa1c822f3c89dd8242f1a seems to fix at least my original problem.

**Comment by mattn** [comment]
Closable?

**Comment by tsufeki** [comment]
yup.
