### ISSUE TITLE
Strange cursor behavior

### ISSUE THREAD

**Issue by dradtke** [prabirshrestha/vim-lsp#548]
I've been using `vim-lsp` a fair amount on a project with the [Java language server](https://github.com/georgewfraser/java-language-server), and for the most part it's been working pretty well, but I've been running into one problem that I can't seem to pin down. After a little while, the cursor starts moving around in ways that interrupt what I'm doing:

1. In earlier Neovim versions (before overlapping pop-up support), the cursor would often jump up to the preview window automatically after typing a comma.
2. When typing something quickly, the cursor sometimes jumps around seemingly randomly. This appears to occur when linting or diagnostic results are returned from the server, but I wouldn't expect that to actually move my cursor.
3. Sometimes, insert mode outright breaks, with typing `i` resulting in the error `E523: Not allowed here`.

Any tips on how to track down the causes of these issues?

**Comment by casr** [comment]
I think I'm having a similar problem to you but with Python and pyls. When typing out the name of the method's arguments the cursor jumps to the preview window when typing an equals, comma or opening bracket sign.

e.g. typing out the following should trigger the problem:
```python
print("hello", sep=",")
```

(if it doesn't happen try hitting backspace back to `(` and type it out again)

My guess is that the code that switches up the documentation for the preview window from method description to argument description is where to take a look first as those appear to be it triggers for me.

**Comment by laixintao** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/9675939/68275755-7de63a00-00a7-11ea-8098-65262cfae59c.png)

**Comment by hrsh7th** [comment]
I think it occurs by double tap feature in `signature_help` maybe.
Please re-check after adding `g:lsp_signature_help_enabled = v:false` to your vimrc.

If it guessing is right, I'll try to solve it.

**Comment by laixintao** [comment]
Hi  I run `:let g:lsp_signature_help_enabled = v:false` in Vim, it still
has the problem.

hrsh7th <notifications@github.com> 于2019年11月14日周四 下午4:23写道：

**Comment by hrsh7th** [comment]
Thanks for your information.
If you didn't add the flags to vimrc, please add to vimrc.

signature help initialization is automatically invoke when server starting.
So the flag should set before the server starting.

**Comment by laixintao** [comment]
Hi I set it in my `.vimrc`, it disabled the document prompt.

[image: image.png]

My vimrc here:

https://github.com/laixintao/myrc/blob/e8c3c1b59f815890e93accc9886ee8fc57fe2780/.vimrc#L137

**Comment by hrsh7th** [comment]
But didn't you get the right results?
Hmm... I can only think @casr's case is related the signature help...
Sorry, Probably my guessing was fault in @laixintao's case.

**Comment by laixintao** [comment]
Sorry, the image was missing.

When I added `:let g:lsp_signature_help_enabled = v:false`, the function signature works fine.

<img width="731" alt="Screen Shot 2019-11-15 at 2 53 18 PM" src="https://user-images.githubusercontent.com/9675939/68922887-cee8e300-07b7-11ea-8874-e18f920de10a.png">

But the nice document prompt was missing.

<img width="453" alt="Screen Shot 2019-11-15 at 2 53 27 PM" src="https://user-images.githubusercontent.com/9675939/68922902-dad4a500-07b7-11ea-9d70-ad3ce5af5490.png">

Without `:let g:lsp_signature_help_enabled = v:false`, I will have:

![image](https://user-images.githubusercontent.com/9675939/68922946-f63fb000-07b7-11ea-8b46-c18e7b92ca0f.png)

**Comment by hrsh7th** [comment]
> But the nice document prompt was missing.
Yes. The flag will disable document popup aka signature-help.

Is your problem `strange cursor behavior`?
My understanding is that problem is related to highlights not cursor behavior, this is right?

(And sorry, I don't have the solution to solve highlight problem now...)

**Comment by laixintao** [comment]
@hrsh7th yes, I think my problem is same with @casr

**Comment by casr** [comment]
> I think it occurs by double tap feature in `signature_help` maybe.
> Please re-check after adding `g:lsp_signature_help_enabled = v:false` to your vimrc.
> 
> If it guessing is right, I'll try to solve it.

@hrsh7th Thanks for taking a look; I've just had a chance to test this.

I added the above to my `.vimrc` and, whilst it does mean the cursor remains where it should be, the preview window no longer shows.

Does that help with your investigation? Would you like us to try anything else?

**Comment by hrsh7th** [comment]
Thanks for your reporting.
I sent PR, Please check this.

**Comment by prabirshrestha** [comment]
PR is merged. https://github.com/prabirshrestha/vim-lsp/pull/558
