### ISSUE TITLE
Jump to the top when retrieving defintion

### ISSUE THREAD

**Issue by mcepl** [prabirshrestha/vim-lsp#55]
Hi,

when I do ``Ctrl-]`` to get to the definition of the symbol under the cursor, it looks like the found definition is put just to the middle of the screen, so it looks I would press ``zz`` after the command. However, I would prefer if the found symbol was shown on the top of the screen. I have to literally run ``zt`` after every jump to the definition. Would it be possible to add some option switching vertical location of the jump target, please?

Thank you

**Comment by prabirshrestha** [comment]
It should be simple. Feel free to send a PR to add a hook here.

https://github.com/prabirshrestha/vim-lsp/blob/812d89070743e3a8fd594d8e8a7d3233a2d7cec5/autoload/lsp/ui/vim.vim#L313-L317

**Comment by mcepl** [comment]
Hmm, I cannot reproduce even the original problem with the current master and vim 8.0.1520.
