### ISSUE TITLE
Strange leading dot for external functions

### ISSUE THREAD

**Issue by adam900710** [prabirshrestha/vim-lsp#554]
When using vim-lsp with clangd to complete kernel module (btrfs), if completing external functions (functions not implemented in current .C file), the functions will start with a leading dot like this:

![Screenshot_20191106_152113](https://user-images.githubusercontent.com/460269/68276952-192bdf00-00a9-11ea-9a63-668908d250c8.png)

That leading dot is screwing up the completion.

Any idea where this leading dot comes from?

**Comment by prabirshrestha** [comment]
Can you try updating to latest master and see if you still have the issue. If you have a minimal vimrc and a repository that we can repro that would be easier for us to debug.

**Comment by adam900710** [comment]
Updated to commit b2f3f086bcf3c2bdb1b378e86c79173c34d41ffa. Still the same bug.

My vimrc looks like this:
```
" project vimrc
set exrc

" Complete use LSP
autocmd FileType c,h set omnifunc=lsp#complete
autocmd FileType c,h set completefunc=lsp#complete
```

And my linux project .vimrc looks like:
```
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-compile-commands-dir=/home/adam/compile_commands.d/kernel/']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif
```

The project is upstream linux kernel.
The compilied command is generated by:
```
$ make modules_prepare
$ bear make M=fs/btrfs -j12
```

I triggered the completion mamualy by `C-x C-o` in `fs/btrfs/disk-io.c`.
You could try to complete `list_ad` in any function.

**Comment by adam900710** [comment]
BTW it can also be reproduced using smaller project, like btrfs-progs.

You could try to complete "list_ad" under disk-io.c.

Not sure where the dot comes from, maybe it's from clangd?

**Comment by thomasfaingnaert** [comment]
@adam900710 Log files will also be useful to debug this.

**Comment by adam900710** [comment]
@thomasfaingnaert Did you mean clangd log? Or vim log?

For vim log, here is the verbose=15 log.
The operation is editing disk-io.c of btrfs-progs project, try to complete `list_ad`.

https://gist.github.com/adam900710/520f533bf08b9514034839dd1011c4e1

The log may be a little too big though.

**Comment by thomasfaingnaert** [comment]
Either the vim-lsp or the clangd log, so we can check what the language server returns.
My guess is that the issue lies with clangd, i.e. it adds the dot for some reason.

**Comment by adam900710** [comment]
Any way to extract the lsp log? The full verbose=15 log is really too large just for one single completion attempt.

**Comment by thomasfaingnaert** [comment]
You can add a couple lines to your vimrc, as described in https://github.com/prabirshrestha/vim-lsp#debugging

**Comment by adam900710** [comment]
Here is the log.

It looks like it's returned by clangd.
https://gist.github.com/adam900710/77fcd0bc5545fc51147fd8d3385f8419

**Comment by thomasfaingnaert** [comment]
That's really weird behaviour IMO, it might be worth reporting this upstream.
I did notice that the filterText is OK, so it may work if you use the prefix filter for clangd (`:h vim-lsp-completion-filter`).

**Comment by adam900710** [comment]
However using prefix filter makes it unable to complete at all.
Since the extra dot makes the typed data differ from the label.

I'll report it to clangd upstream, but any idea about a workaround?

**Comment by thomasfaingnaert** [comment]
The extra dot is not present in the filterText, which is what I use for filtering, so not sure why it's not working.
As for a workaround, can you upload a log with the following patch applied, so we can inspect the items in the Vim completion menu?

```diff
diff --git a/autoload/lsp/omni.vim b/autoload/lsp/omni.vim
index 593dbc1..8f713f6 100644
--- a/autoload/lsp/omni.vim
+++ b/autoload/lsp/omni.vim
@@ -229,6 +229,8 @@ function! s:get_completion_result(server_name, data) abort
 
     let l:matches = type(l:items) == type([]) ? map(l:items, {_, item -> lsp#omni#get_vim_completion_item(item, a:server_name) }) : []
 
+    call lsp#log('Matches:', l:matches)
+
     return {'matches': l:matches, 'incomplete': l:incomplete}
 endfunction
```

**Comment by adam900710** [comment]
> The extra dot is not present in the filterText, which is what I use for filtering, so not sure why it's not working.

I guess I'm also using other plugins, especially snippet related to use `Label` field to do snippet completion.
Or I'm using wrong filter?

The filter I added:
```
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-compile-commands-dir=/home/adam/compile_commands.d/btrfs-progs/']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ 'config': { 'filter': { 'name': 'prefix' } },
        \ })
endif
```
Or should the `name` be replace with certain field name?

And with that log line added, the lsp.log
https://gist.github.com/adam900710/4541d28ec6f910c679bb96931cb183a7

**Comment by thomasfaingnaert** [comment]
I suppose what could work is if we use `'filterText'` as `'word'` instead of `'label'`:

```diff
diff --git a/autoload/lsp/omni.vim b/autoload/lsp/omni.vim
index 593dbc1..a5c2701 100644
--- a/autoload/lsp/omni.vim
+++ b/autoload/lsp/omni.vim
@@ -249,6 +249,8 @@ function! lsp#omni#default_get_vim_completion_item(item, ...) abort
 
     let l:kind = lsp#omni#get_kind_text(a:item, l:server_name)
 
+    let l:word = get(a:item, 'filterText', l:word)
+
     let l:completion = {
                 \ 'word': l:word,
                 \ 'abbr': l:abbr,
```
Does this patch remove the dots from the completion menu?
This does still seem like weird usage of the LSP protocol by clangd, though

**Comment by thomasfaingnaert** [comment]
Which version of clangd are you using, by the way? I may be able to reproduce this locally.

**Comment by adam900710** [comment]
With that `filterText` snippet, now I can at least do regular completion.
Thank you very much!

Although that leading character is still pretty annoying even in the completion menu.

For clangd version, it's `clangd version 9.0.0 (tags/RELEASE_900/final)`.

BTW, have to wait for an account to report bug to upstream clang. :(

**Comment by thomasfaingnaert** [comment]
You can change `l:abbr` as well to change what is displayed in the menu as a temporary workaround.
Apparently, the dot indicates that includes will be added to the current file (https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/clients/clangd-vscode/README.md#include-management).
If I have a bit more time, I'll look into how VSCode handles it, so we don't have to do ugly workarounds just for clangd.

**Comment by thomasfaingnaert** [comment]
@prabirshrestha I don't think it makes much sense to use `filterText` for `abbr` and `word` for all servers by default. Is there a better solution than allowing this to be configured per-server?

**Comment by adam900710** [comment]
Since that special character is just a special one, can we just truncate such character as a more generic workaround?
Or just truncate any non-ASCII leading characters?

**Comment by thomasfaingnaert** [comment]
That still seems like a per-server hacky workaround. Plus, in some languages, non-ASCII characters are allowed in function names, so completion would be broken there :(

**Comment by prabirshrestha** [comment]
@thomasfaingnaert wondering if this is the same issue as this. https://github.com/prabirshrestha/vim-lsp/issues/328#issuecomment-492646814 and https://github.com/prabirshrestha/vim-lsp/issues/328#issuecomment-493732930.

Also what happens if you disable textedit feature?

**Comment by adam900710** [comment]
No difference disabling `lsp_text_edit_enabled`.

**Comment by prabirshrestha** [comment]
Can you paste the log file with `lsp_text_edit_enabled` disabled?

**Comment by adam900710** [comment]
Here it is.
https://gist.github.com/adam900710/ad06eef27e37764cfe8f90eae41019e5

Please note that, I still have the `log matches` and `l:word` snippet applied.

**Comment by prabirshrestha** [comment]
It is still responding with `textEdits` because we are telling that `"capabilities":{"workspace":{"configuration":true,"applyEdit":true}` we support it.

Can you set `g:lsp_get_supported_capabilities` and make sure to not pass `applyEdit`. This will make changes to all language servers. If you only want to change for clang pass `capabilities` when registering the language server. https://github.com/prabirshrestha/vim-lsp/blob/6db5bd6c3bbf2139b94b5f23df234f3fab5993d3/autoload/lsp.vim#L454-L458

**Comment by adam900710** [comment]
Not familiar enough with vim script, but I changed `function! lsp:default_get_supported_capabilities` to make `applyEdit` to `v:false`.

And lsp log indeed shows `"applyEdit":false`. But still the same result.

And here goes the LSP log:
https://gist.github.com/adam900710/dbbc5b6cc5379121d5b8896a8e278389

**Comment by prabirshrestha** [comment]
Can you also disable snippet support. `{"completion":{"completionItem":{"snippetSupport":true}}}` That requires textEdits.

**Comment by adam900710** [comment]
Disabled, still get the dot in completion menu.

BTW, the cost of no snippet support is too big to me. I can afford the dot in completion menu, as long as it doesn't pollute the completion.

The lsp log:
https://gist.github.com/adam900710/85b851d55463c06d705ad1ca409eaed2

**Comment by bfrg** [comment]
@adam900710 Which snippet plugin do you use and what have you set up exactly?

I use the same `clangd` version as above, with the same `vim-lsp` settings. The dot appears in the completion menu but is not inserted. But I don't use any snippets.

Try starting `clangd` with the `--header-insertion-decorators=false` option. This will remove the dots. See `clangd --help` for more details.

**Comment by prabirshrestha** [comment]
Can you try the latest master? There was a bunch of fixes to the autocomplete engine. 

For snippets you can use https://github.com/hrsh7th/vim-vsnip

**Comment by adam900710** [comment]
From previous comment, it's something caused by clangd, so I just added clangd option to not show that dot.

No matter if it's latest master, it solves the problem for me. So close the case.
