### ISSUE TITLE
Unexpectedly canceling visual mode when enable folding feature.

### ISSUE THREAD

**Issue by hrsh7th** [prabirshrestha/vim-lsp#556]
I found the reason.
The reason is below code.
https://github.com/prabirshrestha/vim-lsp/blob/efff12608f334edcc6878ce9a790b136c7fa92c6/autoload/lsp/ui/vim/folding.vim#L189.

It looks like the `windo` canceling visual-mode.

I tried to solve it, but I can't understood the code meanings.
https://github.com/prabirshrestha/vim-lsp/blob/efff12608f334edcc6878ce9a790b136c7fa92c6/autoload/lsp/ui/vim/folding.vim#L190
This line says `foldmethod is 'expr' so assign 'expr' to it`.
Should this fix too?

**Comment by hrsh7th** [comment]
@thomasfaingnaert Please tell me the code means.
If it is just mistake, I'll fix both.

**Comment by thomasfaingnaert** [comment]
@hrsh7th It's explained in the comment above: setting `'foldmethod'` back to `'expr'` forces Vim to reevaluate the `foldexpr`. This is needed to update the folds when a new response comes in.
It's probably best to change https://github.com/prabirshrestha/vim-lsp/blob/efff12608f334edcc6878ce9a790b136c7fa92c6/autoload/lsp/ui/vim/folding.vim#L181-L184 to make sure the folding is only updated in normal mode.

What would also be nice is, if the user is in some mode other than normal mode, the folding is updated immediately after he goes back to normal mode.

**Comment by hrsh7th** [comment]
Thanks to explain and sorry I missed the comment.

We can't detect leaving visual mode.
So probably we should use timer, I think.

I will put out PR for the time being.
