### ISSUE TITLE
Lack of docs about how to use this. With samples for C++

### ISSUE THREAD

**Issue by effolkronium** [prabirshrestha/vim-lsp#561]
Can't understand nothing. Autocomplete do not work for c++ files. Can't find any dock about how to enable it and how to use it

**Comment by prabirshrestha** [comment]
Please refer to the wiki on setting up language servers for c++. https://github.com/prabirshrestha/vim-lsp/wiki

You can use clangd or ccls.

As for autocomplete it depends on your use case. You can use omnifunc, asyncomplete-lsp.
