### ISSUE TITLE
Optionally disable realtime running of diagnotics

### ISSUE THREAD

**Issue by rcr** [prabirshrestha/vim-lsp#566]
Running diagnostics in realtime doesn't make sense. For example, running the compiler while typing code generates compilation errors for missing semicolons before I'm finished typing the line out. I'd like to control when diagnostics are run, on BufWrite, or after a timeout period.

**Comment by mattn** [comment]
Diagnostics are notification messages from server. Unfortunately, Language Server Specification does not have spec for customize to disable diagnotic.

See TextDocumentClientCapabilities in https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/

**Comment by rrcmd** [comment]
How does the server running the diagnostics know that the content has changed if it's just in nvim's internal buffer and hasn't been saved to disk? Clearly there has to be some mechanism alerting the server of changes in realtime...

**Comment by rcr** [comment]
How does the server running the diagnostics know that the content has changed if it's just in nvim's internal buffer and hasn't been saved to disk? Clearly there has to be some mechanism alerting the server of changes in realtime...

**Comment by prabirshrestha** [comment]
you can use `g:lsp_diagnostics_enabled` to hide the signs error if that is what you are looking for.

**Comment by rcr** [comment]
Not quite. I want the diagnostics, I just don't want them to be recalculated on every keystroke, that doesn't make sense. You wouldn't run your compiler after every keystroke. I'm wondering if there's an option to have diagnostics refreshed, for example, on BufWrite.

**Comment by mattn** [comment]
To not send the text until saving mean to not support hover, completion, or most of features of language server.

**Comment by rcr** [comment]
Ahh, hadn't considered that, good point. However I've been looking at the protocol and it looks like after any given `"textDocument/didChange"` event you could feasibly ignore the `"diagnostics"` json struct returned from the server unless it was expected? I might try to hack something out myself for this, it really does seem to me like the behavior the average user might expect.

**Comment by acomagu** [comment]
@rcr Setting `g:lsp_diagnostics_enabled` stops the updating diagnostics message, because vim-lsp seems to check the variable every time on receiving publishDiagnostics event([autoload/lsp.vim#L703](https://github.com/prabirshrestha/vim-lsp/blob/70234f/autoload/lsp.vim#L703)).

I guess `g:lsp_diagnostics_enabled` should be `1` on startup(when `lsp#enable()` is called) so this trick is a little hacky, but works.
