### ISSUE TITLE
Non LSP buffer is analyzed

### ISSUE THREAD

**Issue by habamax** [prabirshrestha/vim-lsp#568]
OS: windows 19
vim: 8.1.2318

## vim-lsp setup
```
"" vim-lsp {{{1
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '‼'}
let g:lsp_signs_hint = {'text': '~'}

augroup lsp_preview | au!
	autocmd CompleteDone * silent! pclose
augroup end

if executable('pyls')
	" pip install 'python-language-server[all]'
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
endif

if executable('solargraph')
    " gem install solargraph
    au User lsp_setup call lsp#register_server({
        \ 'name': 'solargraph',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
        \ 'initialization_options': {"diagnostics": "true"},
        \ 'whitelist': ['ruby'],
        \ })
endif
```

## Steps to reproduce

1. Open vim and `:e ` some ruby file
2. Split and open vim file

Now vim file is analyzed against ruby lsp

![image](https://user-images.githubusercontent.com/234774/69123449-7022b280-0ab2-11ea-918e-541692c4ebde.png)

**Comment by hrsh7th** [comment]
I think https://github.com/prabirshrestha/vim-lsp/pulls is related to this issue.

Please check with adding `let g:lsp_fold_enabled = v:false` to vimrc or #502.

**Comment by habamax** [comment]
> I think https://github.com/prabirshrestha/vim-lsp/pulls is related to this issue.

Yes, indeed. Couldn't find it.

> 
> Please check with adding `let g:lsp_fold_enabled = v:false` to vimrc or #502.
Yes, this helps!

**Comment by hrsh7th** [comment]
Thanks for your reporting.
OK, I will tackle the #502 again.

**Comment by hrsh7th** [comment]
@habamax I've updated the PR (#502 ).
Please check with this.

**Comment by habamax** [comment]
fixed
