### ISSUE TITLE
JDK classes seen only 

### ISSUE THREAD

**Issue by slawtul** [prabirshrestha/vim-lsp#570]
Hi guys,

yesterday I installed vim-lsp plugin with java launguage server (https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Java) and I opened simple maven project with few classes. I found that only jdk classes and their methods are seen  - no autocomplete for project classes and classes from pom dependencies.
Do I need to add extra configuration?

Thanks
Slawek

_Edit_
Only one difference. I installed jdt-language-server-0.47 version - not jdt-language-server-0.35 as in above wiki link

**Comment by mattn** [comment]
What you get with `:LspStatus` ? Could you try to get log?

https://github.com/prabirshrestha/vim-lsp#debugging

**Comment by slawtul** [comment]
Hi mattn

:LspStatus returns: eclipse.jdt.ls: running

and I checked logs and found one error message: **Classpath is incomplete.**

`20.11.2019 21:39:03:["<---",1,"eclipse.jdt.ls",{"response":{"method":"window/logMessage","jsonrpc":"2.0","params":{"message":"2019-11-20 21:39:03 Classpath is incomplete. Only syntax errors will be reported for file:///C:/Users/slawtul/Workspace/Wicket_reusables/src/main/java/org/javablues/wicket_reusables/behaviors/popover/PopoverBehavior.java","type":3}}}]`

**Comment by jaredculp** [comment]
Try adding this to your config:

```
\ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'pom.xml'))},
```

**Comment by slawtul** [comment]
Hi jaredculp
unfortunately it did not help.
