### ISSUE TITLE
text edit breaks while completion

### ISSUE THREAD

**Issue by mattn** [prabirshrestha/vim-lsp#571]
`let g:lsp_text_edit_enabled = 1` and select candidate on the popup. and type `(`.

![terminal7](https://user-images.githubusercontent.com/10111/69231892-4611e300-0bcd-11ea-9072-c13ded499180.gif)

<details>
2019年11月20日 19時24分43秒:["<---",1,"intelephense",{"response":{"id":12,"jsonrpc":"2.0","result":{"isIncomplete":false,"items":[{"label":"getSection","data":6400570719995496,"textEdit":{"range":{"end":{"character":21,"line":32},"start":{"character":11,"line":32}},"newText":"getSection($0)"},"sortText":"getSection","kind":2,"insertTextFormat":2,"command":{"title":"Trigger Parameter Hints","command":"editor.action.triggerParameterHints"},"detail":"getSection($section)"}]}},"request":{"id":12,"jsonrpc":"2.0","method":"textDocument/completion","params":{"textDocument":{"uri":"file:///home/mattn/dev/gitlist/src/Application.php"},"position":{"character":21,"line":32}}}}]
2
</details>

**Comment by prabirshrestha** [comment]
Is this a bug in the lang server instead? Only if we say `snippetSupport: v:true` it should add those `$0`.

**Comment by mattn** [comment]
vim-lsp does not send client capability so server probably choise default enabled.

**Comment by mattn** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/572 fix this.

**Comment by prabirshrestha** [comment]
@mattn can this be closed now?

**Comment by mattn** [comment]
Yes. closing.
