### ISSUE TITLE
go server vimrc example change in the wiki

### ISSUE THREAD

**Issue by gyorb** [prabirshrestha/vim-lsp#580]
Using `autocmd BufWritePre *.go "LspDocumentFormatSync<CR>"`
instead of `autocmd BufWritePre *.go LspDocumentFormatSync` in the
example will automatically format and save the file and no extra key needs to be pressed.
The `Press ENTER or type command to continue` message will not be shown.

What do you think about this change?
Should I modify the wiki? (there is no support to create a PR for a wiki change)

**Comment by prabirshrestha** [comment]
Sounds good. Thanks.

**Comment by mattn** [comment]
Thank you.

**Comment by gyorb** [comment]
I've updated the wiki page. Thanks!

**Comment by mattn** [comment]
Thank you, too.
