### ISSUE TITLE
Document lazy-load vim-lsp configuration

### ISSUE THREAD

**Issue by casr** [prabirshrestha/vim-lsp#584]
To keep my editing snappy, I load heavier features when I request them via the command `:IDE`

<details>
<summary>Briefly this amounts to this but you can expand to see the full command including other plugins

```vim
command! IDE
	\   packadd async.vim
	\ | packadd vim-lsp
	\ | source $MYVIMRC
	\ | call lsp#enable()
```

</summary>

```vim
command! IDE
	\   packadd vim-signify
	\ | packadd vim-fugitive
	\ | packadd vim-rhubarb
	\ | packadd async.vim
	\ | packadd vim-lsp
	\ | packadd asyncomplete.vim
	\ | packadd asyncomplete-lsp.vim
	\ | packadd asyncomplete-omni.vim
	\ | let g:__ide_mode_enabled = 1
	\ | source $MYVIMRC
	\ | call lsp#enable()
	\ | call asyncomplete#enable_for_buffer()
	\ | call FugitiveDetect(expand('<amatch>:p'))
```

</details>

I got this from reading the initialisation sequence for vim-lsp but I may have missed something. Would this be something worth documenting on the wiki pages?

**Comment by prabirshrestha** [comment]
A wiki would be good. There are lot of vim plugin manager and I would like the users to maintain them similar to how we have maintained servers. 

Feel free to start it similar to servers wiki page.

**Comment by casr** [comment]
I tried to kick this page off over at https://github.com/prabirshrestha/vim-lsp/wiki/Lazy-load-vim-lsp . I went with describing the general approach and then putting package manager specific stuff at the end of the article.

Feel free to arrange it better in the wiki hierarchy as I was not quite sure how to do that.
