### ISSUE TITLE
Jump to warnings

### ISSUE THREAD

**Issue by s417-lama** [prabirshrestha/vim-lsp#586]
It is better for me if we can jump to warnings as well as errors (like `LspNextError`).
The followings are possible solutions I considered.

1. define `LspNextWarning` as well as `LspNextError`.
2. jump to warnings in `LspNextError` by setting some flags like `g:lsp_warnings_as_errors`.
3. define `LspNextDiagnostics` to jump to errors, warnings and so on.

(Personally, I prefer the 3rd option.)

**Comment by prabirshrestha** [comment]
We should add support for `LspNextWarning` and `LspNextDiagnostics`. Feel free to send a PR.
