### ISSUE TITLE
Scala: How to import build

### ISSUE THREAD

**Issue by davidpdrsn** [prabirshrestha/vim-lsp#593]
I'm trying to switch from coc to vim-lsp for scala development, but I'm running into an issue. I'm still new to scala so I'm hoping someone could maybe help.

I'm using [metals](https://scalameta.org/metals) which afaik runs some kind of build server in the background (or maybe that is [bloop](https://scalacenter.github.io/bloop)).

As part of getting all that working you have to ["import your build"](https://scalameta.org/metals/docs/editors/vim.html#importing-a-build). I'm not quite sure what that means but the first time I would save a scala file coc would automatically ask me to import the build. Example [here](https://i.imgur.com/EAyt0xP.png). Afterwards things would work fine.

I cannot find a way to get vim-lsp to do that, however if I "import the build" with coc and then disable coc, vim-lsp works fine. It doesn't work before importing the build.

There is a [section in the metals readme](https://scalameta.org/metals/docs/editors/vim.html#manually-start-build-import) which says you can trigger a manual import with

```
:call CocRequestAsync('metals', 'workspace/executeCommand', { 'command': 'build-import' })
```

How would I run this with vim-lsp?

If none of this doesn't make any sense or is beyond the scope of this project feel free to close this.

**Comment by prabirshrestha** [comment]
You can use lsp#send_request to send custom requests to language server.

**Comment by davidpdrsn** [comment]
Works! Thanks 🙌
