### ISSUE TITLE
Completion after "->" or "." always selects the first candidate

### ISSUE THREAD

**Issue by adam900710** [prabirshrestha/vim-lsp#595]
Hi,

It looks like between commit d542bbc and current master 7ebf071, there is some change which caused completion to always select the first candidate after launching completion.

It can be pretty annoying, especially when a structure has a lot of members, this forces user to cancel current completion using `C-e`, then re-input leading characters, and re-launch the completion.

Any clue about how to change the default behavior?

**Comment by adam900710** [comment]
BTW, the default behavior for selecting the first candidate is kinda OK out of structure context, but still, it would be better to let user to choose the default behavior.

**Comment by mattn** [comment]
Hmm, I can't find any commits breaking this between commit d542bbc and current master 7ebf071.

**Comment by adam900710** [comment]
Strange, my older vim-lsp package using d542bbc doesn't had that behavior at all.
And that's the only package get upgraded, then the behavior breaks.

I'll try to do a proper bisection to pin down the problem.

BTW, I'm using clangd lsp-sever, completing pure C projects (btrfs-progs and kernel btrfs module), all the same problem.

**Comment by prabirshrestha** [comment]
What is your completeopt settings?

**Comment by adam900710** [comment]
> What is your completeopt settings?
menuone,longest,preview

> I'll try to do a proper bisection to pin down the problem.
And bisect leads to this commit 0e811a287422786741849aa52614c11942227292.
After that, the behavior is broken, and before it everything is OK.

**Comment by prabirshrestha** [comment]
Can you try latest master. There were multiple fixes that went for autocomplete.

**Comment by adam900710** [comment]
Tried, and nope, it doesn't work.

Completion after `.` or `->` still selects the first candidate.

**Comment by adam900710** [comment]
Tried latest branch, just vim-lsp, no async.

Still the same.

The full config is here (just copied from the README)
```
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '--compile-commands-dir=/home/adam/compile_commands.d/kernel/', '--header-insertion-decorators=false']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif

function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> <c-]> <plug>(lsp-definition)
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <Plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <Plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)

    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
```

The testing code is pretty simple:
```
#include <stdio.h>
#include <stdlib.h>

struct test_struct {
        int x;
        int y;
};

int main (void) {
        struct test_struct my_struct;
        my_struct.x = 0;
        return 0;
}
```

If I just trigger omnifunc by 'C-x C-o' at `my_strcut.`, then x just pop up and get selected.

**Comment by adam900710** [comment]
And even set `completeopt` to `menu`, it still selects the first entry.
