### ISSUE TITLE
How could I restart LSP servers?

### ISSUE THREAD

**Issue by tyru** [prabirshrestha/vim-lsp#596]
Hi @prabirshrestha and its contributors,
Thanks for creating great product!

I want to restart LSP servers to refresh state,
because sometimes the server does not respond.

I could add `:LspStopServer`, but after executing `:LspStopServer`, `:LspStatus` continuously returns `exited` status (even if executing `:e`).
https://github.com/prabirshrestha/vim-lsp/compare/master...tyru:add-excmd-stop-server?expand=1

**Comment by tyru** [comment]
I heard that vim-lsp does autostart when "completion", "jump to definition" from @mattn .
would you autostart also when `:edit` ?

**Comment by hoopchen** [comment]
That will be quite useful if `vim-lsp` has an command to restart backend LSP server. 

Sometimes the LSP server crashed ( or some buggy behavior) , I don't want to restart whole vim to get the server up and running again, because of all the tabs and buffers and working state...

**Comment by tyru** [comment]
@prabirshrestha Would you include this patches?
If so, I'll send pull requests.

> https://github.com/prabirshrestha/vim-lsp/compare/master...tyru:add-excmd-stop-server?expand=1

> would you autostart also when `:edit` ?

**Comment by prabirshrestha** [comment]
Feel free to send a PR. If paean is set might be good to restart only that server.

**Comment by tyru** [comment]
Thanks for merge #604.

https://github.com/prabirshrestha/vim-lsp/pull/604#issuecomment-566874235

> But I found the problem that `:LspStatus` shows `exited` for stopped server...
> `gopls` process seems to be running, though.

Here is the gif.
After executing `:e` and gopls process was invoked, `:LspStatus` should display `running` again.

![画面収録 2019-12-18 14 18 24](https://user-images.githubusercontent.com/48169/71060824-e8f85580-21a9-11ea-98a0-e36820a2f1ad.gif)

**Comment by tyru** [comment]
However, now restarting LSP servers work with `:LspStopServer` (because vim-lsp automatically starts again).
The problem is only `:LspStatus`, it is little off-topic from this issue.

**Comment by tyru** [comment]
> The problem is only `:LspStatus`

Now #605 fixed that.
Thanks @prabirshrestha, @mattn !
