### ISSUE TITLE
Commit "Added textEdit support on omni complete." breaks autocomplete

### ISSUE THREAD

**Issue by aktau** [prabirshrestha/vim-lsp#597]
First of: I have no idea why I've only observed this behaviour recently [1]. The culprit commit (determined by git bisect) is 315d73c0bd9b38c6d1d1f5604cd9e42467eacda2.

What happens is:

  1. Open a file on which LSP-based autocompletions are suppored (I use a Go file).
  2. Try to autocomplete a method call (e.g.: `err.<TAB>`)
  3. Select a method call (note: not a `type` autocompletion, the kind seems to be significant).
  4. The chosen text will be inserted, but the first word in the file will also be erased. For Go files, that would be the `package` statement.

cc @mikoto2000 

I can reproduce with Neovim v0.5.0-240-gbc879dd1f  and Vim 8.1.2269.

Possibly related: #431, #543

Minimal `.vimrc`:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp' 
call plug#end()

au User lsp_setup call lsp#register_server({
    \ 'name': 'MyLSP',
    \ 'cmd': ['/some/custom/lsp'],
    \ 'whitelist': ['c', 'cpp', 'go'],
    \})
```

[1]: Maybe the custom LSP I'm using (supplied by the company I work) suddenly got a new capability and it now triggers this behaviour.

**Comment by aktau** [comment]
I can also confirm that setting `g:lsp_text_edit_enabled = 0` fixes it at HEAD.

**Comment by prabirshrestha** [comment]
Can you try the latest master. Else please provide a sample hello world repo

**Comment by prabirshrestha** [comment]
Please try latest master.
