### ISSUE TITLE
Cannot LspRename

### ISSUE THREAD

**Issue by mcepl** [prabirshrestha/vim-lsp#61]
I have opened [this script](https://gist.github.com/mcepl/e4a6f7aea55f9cca0f603873dc5a7d1b), went to the line [26](https://gist.github.com/mcepl/e4a6f7aea55f9cca0f603873dc5a7d1b#file-t_kinit-py-L26) and with cursor on ``provider_type``, I run ``LspRename`` (manually, as I have no mapping for it). vim started do something, but actually with no result. Why ``LspRename`` doesn’t?

[vim-lsp.log.txt](https://github.com/prabirshrestha/vim-lsp/files/1479284/vim-lsp.log.txt) is the log collected via ``g:lsp_verbose`` and ``g:lsp_log_file``.

**Comment by prabirshrestha** [comment]
Seems like there is a bum script bug based on your log. Will look into more details.

**Comment by prabirshrestha** [comment]
I didn't get the error you had so I hard coded the response in vim-lsp and could reproduce it.

`Vim(call):E716: Key not present in Dictionary: result"` error should now be handled by https://github.com/prabirshrestha/vim-lsp/pull/86.

But the rename still doesn't work so I think the language server doesn't support it.
