### ISSUE TITLE
rls can't complete correctly

### ISSUE THREAD

**Issue by heavenshell** [prabirshrestha/vim-lsp#614]
Hello.
After https://github.com/prabirshrestha/vim-lsp/commit/0e811a287422786741849aa52614c11942227292 this commit, rls can't complete correctly.

```rust
let app_matches = cli::build_cli().get_matches();
// cursor is here
```

When I type `app_<C-x><C-o>` and choose `app_matches` candidate, I expected `app_matches` but currentlry vim-lsp inserted like `app_app_matches`.

```viml
if executable('rls')
  augroup RLS
    autocmd User lsp_setup call lsp#register_server({
      \ 'name': 'rls',
      \ 'cmd': {server_info -> ['rustup', 'run', 'stable', 'rls']},
      \ 'workspace_config': {'rust': {'clippy_preference': 'on'}},
      \ 'root_uri':{server_info -> lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'Cargo.toml'))},
      \ 'whitelist': ['rust'],
      \ })
  augroup END
  autocmd FileType rust setlocal omnifunc=lsp#complete
endif
```
note: I don't use any auto completion library, just Vim's omni complete.

### Expected
Before https://github.com/prabirshrestha/vim-lsp/commit/0e811a287422786741849aa52614c11942227292 works fine.
![Kapture 2019-12-25 at 1 27 22](https://user-images.githubusercontent.com/56591/71420104-adccb980-26b6-11ea-878e-1f70f6892a04.gif)

### Actual(master branch)
![Kapture 2019-12-25 at 1 28 48](https://user-images.githubusercontent.com/56591/71420112-b7562180-26b6-11ea-9443-48ff04db27b1.gif)

### env
macOS 10.14.6
Vim 8.2.000
rls 1.40.0 (5db91c7 2019-10-30)

**Comment by hrsh7th** [comment]
I sent PR to solve the problem.
Please check with #615.

The problem's reason is that `let g:lsp_async_completion = 1`, I think.
@heavenshell Does your .vimrc has `let g:lsp_async_completion = 1?

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/615 is merged. Please try the latest master.

**Comment by heavenshell** [comment]
Thank you!! works fine for me!
