### ISSUE TITLE
use vim8 listener api to track changes for perf instead of using the diff function

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#616]
Refences:

https://github.com/vim/vim/commit/6d2399bd1053b367e13cc2b8991d3ff0bf724c7c
https://github.com/vim/vim/issues/4490
https://groups.google.com/forum/#!msg/vim_dev/L8jg6u47Dro/CbH3LNXdAQAJ

This will most likely improve perf and need to see how this works for utf-16.

**Comment by hrsh7th** [comment]
I have a repo that contains polyfill of `listener_add/nvim_buf_attach/simple-diff`.
But it is not stable maybe.
I share it, for now, https://github.com/hrsh7th/vim-diffkit.

**Comment by prabirshrestha** [comment]
@hrsh7th That is awesome. I think using the native diff listeners will definitely make vim-lsp lot faster. for vim-lsp we do need to support utf-16 for multibyte chars.

**Comment by hrsh7th** [comment]
My polyfill behaves below.

- Use `listener_add` or `nvim_buf_attach` when it is enabled.
- Get the line changes and store `old buf line changes` and `new buf line changes` to the dict.
- Call `lsp#utils#diff#compute` with changed lines when suitable timing (e.g. debounced after)

So we can control diagnostic timing and textDocument/didChange timing as ever.
It is not maximum performance maybe, But It can be avoid slow down on worst case.

**Comment by hrsh7th** [comment]
I will tackle it.
But it is a bit difficult so probably likely take time.

**Comment by hrsh7th** [comment]
My currently planning...

- Use listener_add/nvim_buf_attach to compute buffer diff.
- Improve diagnostic handling.
    - diagnostics count was decreased -> immediately update signs/highlights/etc...
    - diagnostics count was increased -> Use debounce, and check changedtick.

If vim-lsp retrieved diagnostics and target buffer's changedtick is advanced.
In this case, we can skip updating the diagnostics (because the server will serve new diagnostics later).

**Comment by prabirshrestha** [comment]
Out of curiosity @hrsh7th have you done profiling in current code? Is diff the biggest bottleneck?
Have you had a chance to work on the listener diff?

**Comment by hrsh7th** [comment]
The below results is profiled in my machine.

```
let old = readfile(expand('~/Develop/Repos/nicovideo-web/web/lib/niwavide_db.php'))
let new = readfile(expand('~/Develop/Repos/nicovideo-web/web/lib/niwavide_db.php'))

let new[1100] = 'aiueo'

let start = reltime()
call lsp#utils#diff#compute(old, new)
echomsg string(reltimefloat(reltime(start)) * 1000) " => almost returns 30ms
```

Sorry. listener_add/nvim_buf_attach needs buffer modification.
So pure profiling is hard (But I will try it).

My sandbox lsp client uses listener diff and it is better performance than pure diff logic for me.
(I tried it with patch that remove vim-lsp's debounce, and my sandbox client's debounce both)

**Comment by hrsh7th** [comment]
The listener_add/nvim_buf_attach is event style interfae.
But currently diff implementation is not.

I had been solved this mismatch in https://github.com/hrsh7th/vim-diffkit.
I organizing vim-diffkit codes and trying port to vim-lsp. (But it take a time).

**Comment by prabirshrestha** [comment]
@hrsh7th I started porting the current diff to also use pure lua. WIP but hopefully once ported will have better perf improvements. https://github.com/prabirshrestha/vim-lsp/blob/use-lua/autoload/lsp/utils/diff.vim. Also might be better to use pure lua in neovim and only expose the vim wrapper function for diffkit.

**Comment by prabirshrestha** [comment]
Improvements in diff perf has improved a lot. More details at https://github.com/prabirshrestha/vim-lsp/pull/821

There are now 3 algorithms for this.
Old one: which is in vimscript that uses whileloop
New vimscript: which is in vimscript that uses for loop with range
Lua: which is in lua

Lua is ~6.5x faster than old algorithm in vimscript. Lua is still 3x faster than new vimscript algorithm.

**Comment by hrsh7th** [comment]
@prabirshrestha Thank you for your advice.
I tried to improve diff performance by `listener_add` or `nvim_buf_attach` but it will be complex.
I think using lua is good for now.
Thank you for work that enhance lua support on vim.

**Comment by prabirshrestha** [comment]
I'm closing this for now since I do agree it is going to increase complexity. Also the real bottleneck seems to be here and not diff. https://github.com/prabirshrestha/vim-lsp/issues/823
