### ISSUE TITLE
LspDocmentSymbol: Key not present in Dictionary: location

### ISSUE THREAD

**Issue by lkebin** [prabirshrestha/vim-lsp#625]
```
Thu Dec 26 11:05:23 2019:[{"response":{"data":{"__data__":"vim-lsp","server_name":"gopls"},"message":"server already started"}}]
Thu Dec 26 11:05:23 2019:[{"response":{"data":{"__data__":"vim-lsp","init_result":{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["tidy"]},"documentHighlightProvider":true,"hoverProvider":true,"typeDefinitionProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"foldingRangeProvider":true,"codeActionProvider":true,"textDocumentSync":{"save":{},"change":2,"openClose":true},"workspace":{"workspaceFolders":{"changeNotifications":"workspace/didChangeWorkspaceFolders","supported":true}},"documentLinkProvider":{},"implementationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentSymbolProvider":true,"renameProvider":true,"completionProvider":{"triggerCharacters":["."]}},"custom":null}},"server_name":"gopls"},"message":"lsp server already initialized"}}]
Thu Dec 26 11:05:23 2019:[{"response":{"data":{"__data__":"vim-lsp","server_name":"gopls"},"message":"configuration sent"}}]
Thu Dec 26 11:05:23 2019:[{"response":{"data":{"path":"file:///Users/kb/Workspace/project/code/main.go","__data__":"vim-lsp","server_name":"gopls"},"message":"already opened"}}]
Thu Dec 26 11:05:23 2019:[{"response":{"data":{"path":"file:///Users/kb/Workspace/project/code/main.go","__data__":"vim-lsp","server_name":"gopls"},"message":"not dirty"}}]
Thu Dec 26 11:05:23 2019:["--->",1,"gopls",{"method":"textDocument/documentSymbol","on_notification":"---funcref---","params":{"textDocument":{"uri":"file:///Users/kb/Workspace/project/code/main.go"}}}]
Thu Dec 26 11:05:23 2019:["<---",1,"gopls",{"response":{"id":6,"jsonrpc":"2.0","result":[{"range":{"end":{"character":1,"line":10},"start":{"character":0,"line":8}},"name":"main","selectionRange":{"end":{"character":9,"line":8},"start":{"character":5,"line":8}},"kind":12,"detail":"()"}]},"request":{"id":6,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/kb/Workspace/project/code/main.go"}}}}]
Thu Dec 26 11:05:23 2019:["s:on_stdout client request on_notification() error","Vim(let):E716: Key not present in Dictionary: location","function <SNR>119_out_cb[2]..<SNR>118_on_stdout[79]..<lambda>47[1]..<SNR>132_handle_symbol[10]..lsp#ui#vim#utils#symbols_to_loc_list, line 11"]
```

**Comment by lkebin** [comment]
Seems the problem from [gopls](https://github.com/golang/tools/tree/master/gopls) implementation. [go-langserver](https://github.com/sourcegraph/go-langserver) works

**Comment by prabirshrestha** [comment]
Does the spec say location is optional?

**Comment by lkebin** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_documentSymbol

SymbolInformation[]
DocumentSymbol[]

Seems gopls returned `DocumentSymbol`, but go-langserver returned `SymbolInformation`

**Comment by prabirshrestha** [comment]
@lkebin could you send a PR?

These changes were most likely added in newer version of lang server.

**Comment by lkebin** [comment]
I can try to do that, cannot guarantee the result. :-)

Should we compatible `SymbolInformation` and `DocumentSymbol` or just replace to `DocumentSymbol` ?

**Comment by prabirshrestha** [comment]
@lkebin Actually seems like a bug in the `gopls`. Based on the spec it should return hierarchical symbols only if `hierarchicalDocumentSymbolSupport` is set. Could you file a bug there instead?

Can you try setting that value to false here and see if the langserver respects?

https://github.com/prabirshrestha/vim-lsp/blob/a38c46d59184e932c6394a65bb2b31b8b22ad00d/autoload/lsp.vim#L439-L442

I also don't see gopls using `HierarchicalDocumentSymbolSupport` in the codebase.

**Comment by lkebin** [comment]
I just review gopls source code, its protocol generated from `vscode-languageserver-node`. The vscode-languageserver-node client side set `hierarchicalDocumentSymbolSupport` default true, the server side use DocumentSymbol directly. 😂

https://github.com/microsoft/vscode-languageserver-node/blob/a293b0be6c366427c8fe75ffcc79e334606f751d/client/src/client.ts#L1769-L1776

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/vim-lsp/pull/630 now sets `hierarchicalDocumentSymbolSupport` to false. `vscode-languageserver-node` is not used in `vim-lsp` so shouldn't be an issue. The issue is with `gopls` not respecting the spec. Another option is for vim-lsp to support it.

**Comment by prabirshrestha** [comment]
This is now fixed even if we don't expose hierarchy support. https://github.com/prabirshrestha/vim-lsp/pull/631

Please try latest master.

![image](https://user-images.githubusercontent.com/287744/71491712-19ae3f80-27e7-11ea-9184-4a774b2cdfe6.png)


Ideally we need to support tree view to default it to true.
