### ISSUE TITLE
use observables to manage async flows

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#636]
@mattn @thomasfaingnaert let me know what your thoughts are on this.

Currently trying to organize async flows is very difficult in flow. While callbacks are ok as code grows it becomes very difficult to synchronize them.

Current code uses [step.vim](https://github.com/prabirshrestha/vim-lsp/commit/d9d8fe1c3ec00047edcee405b12ee5852edca81c0) which I wrote on my own based of the [step from javascript](https://github.com/creationix/step) which existed before Promise was popular and was very easy to reason about. It is also very lightweight compared to promises even though there were already existing vim promise libraries out there.

While promises are better then callback, I never preferred it and went to write low level step.vim primarily because promise isn't powerful as [rx](https://www.learnrxjs.io/) where one can easily debounce, cancel and so on. 

I had proposed in vital.vim to add Rx with callback supports as it is easier to write operators. https://github.com/vim-jp/vital.vim/issues/622

RxJS 7 is also getting written using callbags. https://twitter.com/ladyleet/status/1058035320611057670

[Callbag spec](https://github.com/callbag/callbag) is pretty interesting.

And here is how easy it is write one. https://github.com/staltz/callbag-pseudo-rxjs
All we need is `pipe` operator and `Observable` class and then add custom operators such as `map`, `filter`, `debounce` as we need it.

And here is why I think it is awesome:

```vim
function! lsp#enable() abort
    lsp#rx#pipe(
        lsp#rx#merge(
            lsp#rx#fromEvent('InsertLeave'),
            lsp#rx#fromEvent('TextChanged'),
            lsp#rx#fromEvent('TextChangedP'),
            lsp#rx#fromEvent('CursorHold'),
        ),
        lsp#rx#debounceTime(250),
        lsp#rx#distinctUntilChanged(previous, current -> getbufvar(previous['buffer'], 'changedtick') != getbufvar(current['buffer'], 'changedtick')),
        lsp#rx#swtichMap(x -> lsp#flush(x['buffer']))
    )
endfunction
```

Because rx always returns stream, it now makes it very easy to change the internal implementation.

```vim
function! lsp#diff(buffer) abort
    if has('patch-1320')
        return lsp#rx#create(s:vim_listener_diff)
    elseif has('python')
        return lsp#rx#create(s:python_thread_diff)
    else
        return lsp#rx#create(s:vim_diff)
    endif
endfunction

lsp#rx#pipe(
    lsp#diff(bufnr('%')),
    lsp#rx#forEach(changes -> lsp#send_changes(changes))
)
```

I have used rx in the past and found it very easy to write express and optimize the code. The best part about this is that you internally change the implementation of your custom rx operator and it just magically works because end of the day everything is just a stream of something. It also means I can start writing in sync and change to async with python threads or vim change listeners and the callers don't even need to worry about it as all it cares is that when it is done it will return a stream of results.

**Comment by prabirshrestha** [comment]
Very much work in progress but you can try it here: https://github.com/prabirshrestha/rx.vim

```viml
let s:i = 0
function! s:next(cb) abort
    echom s:i
    let s:i = s:i + 1
endfunction

function! rx#callbag#demo() abort
    let l:res = rx#callbag#pipe(
        \ rx#callbag#interval(1000),
        \ rx#callbag#take(3),
        \ rx#callbag#forEach(function('s:next')),
        \ )
    return l:res
endfunction
```

**Comment by prabirshrestha** [comment]
Need to implement more operators so we can do something like this:

```viml
function! lsp#enable_for_buffer() abort
    call rx#callbag#pipe(
      \ rx#callbag#merge(
      \     rx#callbag#fromEvent('InsertLeave'),
      \     rx#callbag#fromEvent('TextChanged'),
      \     rx#callbag#fromEvent('TextChangedP'),
      \     rx#callbag#fromEvent('CursorMoved'),
      \     rx#callbag#fromEvent('CursorHold'),
      \ ),
      \ rx#callbag#takeUntil(
      \     rx#merge(
      \         rx#callbag#fromEvent('BufWinLeave'),
      \         rx#callbag#fromUserEvent('LspDisable'),
      \     )
      \ ),
      \ rx#callbag#map({x-> getbufvar(x['bufnr'], 'changedtick')})
      \ rx#callbag#debounce(250),
      \ rx#callbag#debounceUntilChanged(),
      \ rx#switchMap({x->s:send_did_change_requests(x['bufnr'])}),
      \ forEach({x-> echom 'change request sent'})
      \ )
endfunction
```

Basically the above code is saying this:
Listen to `InsertLeave`, `TextChanged`, `TextChangedP`, `CursorMoved` and `CursorHold` event but stop listening when we get `BufWinLeave` or `LspDisable` event, then look at the `changedtick` for the every `250ms` and if has changed from previous `changedtick` then only send the change_requests.
`switchMap` is basically like `.then` or `await` which waits for async call to comple before it echos `change request sent`.

**Comment by prabirshrestha** [comment]
Renamed the project to callbag.vim since seems like it is quite powerful and lightweight that we don't actually need to have rx equivalent of it.

Implemented more operators (8 in total as of now).

In few lines we can easily implement debounce now. 😃 

```vim
call callbag#pipe(
  \ callbag#fromEvent(['TextChangedI', 'TextChangedP']),
  \ callbag#debounceTime(250),
  \ callbag#forEach({x -> s:log('text changed') }),
  \ )
```

**Comment by thomasfaingnaert** [comment]
This sounds great. I haven't used rx myself, but I suppose this would be really useful to improve the performance of highlight references and semantic highlight?

**Comment by prabirshrestha** [comment]
More then perf it is to easily help in writing async code. The good part about this is it doesn't matter whether it is sync or async code we can continue to to use the same map/filter operators. Certain parts of vimscript are quite hard to express and I'm hoping callbag/rx will help us express those very easily. I'm hopping this will make entire vim-lsp codebase smaller and lot easier to add new apis and change. 

I have been migrating some of the operators from callbag wiki. https://github.com/callbag/callbag/wiki Once we migrate more it will will be easier. Feel free to send PR there if you write operators.

I have been thinking of having the lsp as a stream so might look something like this. Notice how the code looks synchronous as in flows down.

```viml
function! s:setup()  abort
    call s:setup_diagnostics() 
    call s:setup_completion()
endfunction

function! s:setup_diagnostics() abort
    call callbag#pipe(
        \   lsp#stream(),
        \   lsp#takeUntil(
        \       callbag#pipe(
        \           lsp#stream(),
        \           callbag#filter({x->lsp#utils#isLspDisabledEvent(x) || lsp#utils#isLspDiagnosticsDisabledEvent(x) })
        \       ),
        \   ),
        \   callbag#filter({x->lsp#utils#response#isDiagnosticResponse(x)}),
        \   callbag#debounceTime(250),
        \   callbag#map({x->lsp#diagnostics#update_signs(x)}),
        \   callbag#forEach({x->lsp#diagnostics#update_virtual_text(x)}),
        \ )

    call callbag#pipe(
        \   callbag#fromEvent('CursorMoved'),
        \   callbag#takeUntil(....),
        \   lsp#debounceTime(250),
        \   lsp#map({x-> lsp#diagnostics#getDiagnosticsUnderCursor() }),
        \   lsp#filter({ x-> x != v:null }),
        \   lsp#map({x -> lsp#diagnostics#getTrimmedMessage(x) }),
        \   lsp#forEach({x -> lsp#diagnostic#printMessage(x) })
        \ )
endfunction

function! s:setup_completion() abort
    call callbag#pipe(
        \ lsp#stream(),
        \ lsp#takeUntil(....),
        \ callbag#filter({x -> lsp#utils#isCompleteDoneEvent(x)}),
        \ callbag#map({x -> v:completed_item }),
        \ callbag#filter({ x -> lsp#utils#isVimLspCompletdItem(x) }),
        \ callbag#forEach({ x-> s:apply_edits(x) }),
        \ )
endfunction
```

Write now we spend too much time adding deboucing and make the code complicated when all we need to do is just add one function call `.debouncetime(250)`. Not we can incrementally use callbags instead of changing for everything.

We need to build the right operators and should be fairly simple to add features as well as refactor. http://reactivex.io/documentation/operators.html#categorized

also be the best part about this is via the virtue of it being small functions makes it very easy to have unit tests.

**Comment by prabirshrestha** [comment]
This is now possible using callbag. Will slowly migrate to the new api.
