### ISSUE TITLE
optimal .vimrc configuration for php autocompletion

### ISSUE THREAD

**Issue by mnsami** [prabirshrestha/vim-lsp#66]
I started using your packages for `php` for autocompletion .. etc

this is my `.vimrc` configuraiton

```

" PHP Language server
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'felixfbecker/php-language-server', {'do': 'composer install && composer run-script parse-stubs'}

" Autocomplete
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'


" PLUGIN: vim-lsp
" Register server
au User lsp_setup call lsp#register_server({
     \ 'name': 'php-language-server',
     \ 'cmd': {server_info->['php', expand('~/.vim/plugged/php-language-server/bin/php-language-server.php')]},
     \ 'whitelist': ['php'],
     \ })

nnoremap <buffer><silent> <c-]>  :LspDefinition<cr>
nnoremap <buffer><silent> K :LspHover<cr>

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')

" for asyncomplete.vim log
let g:asyncomplete_auto_popup=1
let g:asyncomplete_remove_duplicates=1
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
autocmd FileType php setlocal omnifunc=lsp#complete
let g:asyncomplete_log_file = expand('~/asyncomplete.log')
```

checking the logs, no errors reported, but I have the following issues / difficulties:
1. Autocomplete doesn't work with omni `CTRL+x,CTRL+o`, doesn't autocomplete everything.
2. Every time i open a file from the project folder, indexing starts from the beginning again, and it does not help in autocompletion as well.

Any help?

thanks.

**Comment by mnsami** [comment]
any help @marcdeop or @tsufeki ?

**Comment by tsufeki** [comment]
@mnsami Hi

1. It depends on how you usually start vim, but explicitly setting root_uri may help. See https://github.com/prabirshrestha/vim-lsp#registering-servers (swap tsconfig.json with composer.json).

2. Indexing on every startup is how the server works: https://github.com/felixfbecker/php-language-server#performance

3. I don't think setting _both_ omnifunc _and_ asyncomplete is right (not really sure though). I use asyncomplete only and map `<C-Space>` like this:

```viml
imap <C-Space> <Plug>(asyncomplete_force_refresh)
imap <Nul> <Plug>(asyncomplete_force_refresh)
```

Hope that helps.

**Comment by mnsami** [comment]
@tsufeki can you share your `.vimrc` if you are using `vim-lsp` for `php`?

I'm following setting up the `php` server as mentioned in the wiki
https://github.com/prabirshrestha/vim-lsp/wiki/Servers-PHP.

as you see I have logging enabled, so all the logs see the root folder correctly.

**Comment by tsufeki** [comment]
I don't use Plug and detect root_uri by .git folder presence:

```viml
      let g:lsp_log_verbose = 1
      let g:lsp_log_file = expand('~/00-vim-lsp.log')
      let g:asyncomplete_log_file = expand('~/00-asyncomplete.log')

      imap <C-Space> <Plug>(asyncomplete_force_refresh)
      imap <Nul> <Plug>(asyncomplete_force_refresh)
      autocmd FileType php,javascript,typescript,python nmap <buffer> <C-]> :LspDefinition<CR>

      " ... other completors ...

      function FindProjectRoot(server_info)
        let l:relative_path = finddir('.git', lsp#utils#get_buffer_path() . ';')

        if !empty(l:relative_path)
          return lsp#utils#path_to_uri(fnamemodify(l:relative_path, ':p:h:h'))
        else
          return ''
        endif
      endfunction

      autocmd User lsp_setup call lsp#register_server({
        \ 'name': 'php-language-server',
        \ 'cmd': {server_info->['php', $DOTVIM . '/language-server/php/vendor/bin/php-language-server.php']},
        \ 'root_uri':{server_info->FindProjectRoot(server_info)},
        \ 'whitelist': ['php'],
        \ })

      " ... other servers ...
```

Did you try removing `autocmd FileType php setlocal omnifunc=lsp#complete`?

**Comment by jludwig** [comment]
@mnsami I had your .vimrc entries and had the same problem.

Installing php71 fixed the problem for me. Before, I had 7.2 and 7.0 installed and I'm not 100% sure what happened, but replacing both with 7.1 made my asyncomplete php lsp.

**Comment by prabirshrestha** [comment]
closing to clean up old issues and seems to have been fixed. let me know if it is still now working.
