### ISSUE TITLE
No expand textEdit in omnifunc

### ISSUE THREAD

**Issue by mikoto2000** [prabirshrestha/vim-lsp#668]
# Problem

I set `omnifunc=lsp#complete` and call omnifunc, but no expand textEdit.

![vim-lsp](https://user-images.githubusercontent.com/345832/72269076-5216a000-3666-11ea-9ddd-63cb1cac58cf.gif)

# Cause

Fire `CompleteDone` and got not empty `v:complete_item`, when execute `complete` function in omnifunc.

I add debug log. See [this commit](https://github.com/mikoto2000/vim-lsp/commit/d44f22b1030a1dcb37bed30e1938d554bc07cf44) and next image.

![image](https://user-images.githubusercontent.com/345832/72268667-9190bc80-3665-11ea-9abb-9a64a2669812.png)

- red block: when `Ctrl-X, Ctrl-O` (start omni completion), fire `CompleteDone` and clear `s:managed_user_data_map`.
- blue block: when `Ctrl-Y` (selected completion item). already cleard `s:managed_user_data_map`.

# Propose workaround

`s:on_complete_done` is do nothing, when `v:completed_item` all keys empty.
(has key but all value is empty.)

https://github.com/prabirshrestha/vim-lsp/blob/64d514d14f339f2e516af6f7b4417e441f7f62fa/autoload/lsp/ui/vim/completion.vim#L26

**Comment by hrsh7th** [comment]
Thanks for your reporting.
It reproduced in my environment too.

It occurs by `complete` function calling in omnifunc, I think.

I think we should add the proposed workaround is better.
I will create the PR.

**Comment by hrsh7th** [comment]
Could you test with #669?
The PR has solved the problem in my environment.

**Comment by mikoto2000** [comment]
I tried #669, it solved the problem!
