### ISSUE TITLE
lsp_float_opened not activated because win_execute fails?

### ISSUE THREAD

**Issue by gbishop** [prabirshrestha/vim-lsp#670]
When I use LspHover to see the hover text it appears in a float window. I'd like to close the float with escape as suggested in the doc. But the User lsp_float_opened autocommand doesn't get activated. 

Attempting to trace through the code in lsp/ui/vim/output.vim, it doesn't get beyond
`call s:setcontent(l:lines, l:ft)`

In setcontent it seems to quit at
`call win_execute(s:winid, 'setlocal filetype=' . a:ft . '.lsp-hover')`
silently never returning. 

If I comment out that line, it works as expected.

I'm using vim 8.2 on Ubuntu 18.04.

**Comment by cuviper** [comment]
#911 stopped using `win_execute`, so maybe it's worth another try.
