### ISSUE TITLE
vim-lsp completion is broken (at least for go, possibly other languages too)

### ISSUE THREAD

**Issue by acornejo** [prabirshrestha/vim-lsp#68]
Ran using the following:

`vim -u example.vimrc  go/src/golang.org/x/net/context/ctxhttp/ctxhttp.go`

LspDocumentDiagnostics:
No diagnostics results

LspDefinition works fine
LspReferences works fine
LspSymbol works fine

Completion however does not work, omnicompletion or automatic (neither work).

If I open a flow document completion works fine there, so the brokeness seems specific to go; I did not try python because I did not want to pollute my system with python-language-server which requires tons of dependencies.

This is the example.vimrc file I am using (slightly modified from the suggested minimal example in one of the issues):
```vim
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim

call plug#begin('/tmp/plugged')
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

imap <c-space> <Plug>(asyncomplete_force_refresh)
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

if executable('pyls')
    " pip install python-language-server
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
    autocmd FileType python setlocal omnifunc=lsp#complete
endif

if executable('flow-language-server')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'flow-language-server',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'flow-language-server --stdio']},
        \ 'root_uri':{server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), '.flowconfig'))},
        \ 'whitelist': ['javascript'],
        \})
    autocmd FileType javascript setlocal omnifunc=lsp#complete
endif

if executable('go-langserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'go-langserver',
        \ 'cmd': {server_info->['go-langserver', '-mode', 'stdio']},
        \ 'whitelist': ['go'],
        \})

    autocmd FileType go setlocal omnifunc=lsp#complete
endif

" autocmd VimEnter * PlugClean! | PlugUpdate --sync
```

I initially ran without the autocmd commented, but I also tried commenting that out (so that Plug doesn't reinstall everything everytime).

**Comment by acornejo** [comment]
Closing this issue give that I realized the issue is not this plugin.

For posterity go-langserver doesn't support completion.

https://github.com/sourcegraph/go-langserver/issues/201

**Comment by prabirshrestha** [comment]
In the mean time you could try this https://github.com/prabirshrestha/asyncomplete-gocode.vim

**Comment by acornejo** [comment]
Thanks for the suggestion @prabirshrestha I tried that but I did not find it to be a significant improvement over the fatih/vim-go plugin which also relies on gocode.

**Comment by prabirshrestha** [comment]
If that is async it may not have much difference. Using lsp will allow you to use just one plugin for other languages and improvments can happen in the lang server and vim lsp plugin independently. 
It is your choice.

**Comment by acornejo** [comment]
go-langserver now provides completion support, but it still doesn't seem to work (same vimrc file provided above doesnt work).

This now seems like an issue for this plugin.

**Comment by acornejo** [comment]
This was simple enough, the recommended way to run go-langserver is missing the -gocodecompletion flag.

I'll keep this issue open to track fixes on the documentation and wiki to reflect this.

**Comment by jsfaint** [comment]
It works for me with this setting (see [lsp] line in picture)
```viml
  if executable('go-langserver')
    au User lsp_setup call lsp#register_server({
          \ 'name': 'go-langserver',
          \ 'cmd': {server_info->['go-langserver', '-gocodecompletion']},
          \ 'whitelist': ['go'],
          \ })
  endif
```

But the weird thing is there is no function parameter in the completion
![image](https://user-images.githubusercontent.com/571829/44625366-e9783780-a939-11e8-803b-50e61fe656d5.png)

But vim-lsp do support function parameter with clangd
![image](https://user-images.githubusercontent.com/571829/44625378-35c37780-a93a-11e8-9d73-7dbaf6ad0ebd.png)

**Comment by prabirshrestha** [comment]
Key not present in dictionary should be fixed by this. https://github.com/prabirshrestha/vim-lsp/pull/137

It is actually bugs in language servers, but since other language servers also has this issue, we have fixed it in vim-lsp instead.
