### ISSUE TITLE
Fold is closed while typing

### ISSUE THREAD

**Issue by mkoura** [prabirshrestha/vim-lsp#684]
When using `vim:foldmethod=marker` the fold gets closed while I'm typing inside the fold.

![vim_folding](https://user-images.githubusercontent.com/2352619/72916530-7c411f80-3d42-11ea-95b8-354c8d334685.gif)

Minimal vimrc I can reproduce the behavior with:
```vim
set nocompatible

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  au VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/vim-lsp' | Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete.vim'
call plug#end()

augroup AsynComplete
  autocmd!
  au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
    \ 'name': 'buffer',
    \ 'whitelist': ['*'],
    \ 'completor': function('asyncomplete#sources#buffer#completor'),
    \ }))
augroup END
```

When the line with `Plug 'prabirshrestha/vim-lsp'` is commented out the folding and completion behaves correctly.

Minimal file I use to reproduce the issue:

```
vim:foldmethod=marker:foldlevel=0

Fold {{{
# folding fol
}}}
```
Open the file in vim, open the fold, go to the end of the line with comment, start typing "ding". At that point completion menu appears and the fold is closed.

**Comment by hrsh7th** [comment]
Could you yest with #692?

**Comment by mkoura** [comment]
Still happening even with https://github.com/prabirshrestha/vim-lsp/pull/692

**Comment by hrsh7th** [comment]
thanks for your time.
Hm... i will tackle this issue.

**Comment by incoggnito** [comment]
Same for me.

**Comment by mkoura** [comment]
I can no longer reproduce the issue.

**Comment by mattn** [comment]
This issue is resolved by https://github.com/prabirshrestha/vim-lsp/pull/904

**Comment by mattn** [comment]
G
