### ISSUE TITLE
fzf backend for LspReferences and LspDocumentSymbols

### ISSUE THREAD

**Issue by acornejo** [prabirshrestha/vim-lsp#69]
Currently these both display in the quickfix list.

It would be nice to provide backends or hooks to display this data differently. In particular displaying these inside fzf would be nice.

One easy way to do this would be to provide a function that prints the output as a list of strings. This would allow the user to easily write their own fzf hooks.

**Comment by prabirshrestha** [comment]
I do plan to support this but not anytime soon.

**Comment by matfranczyk** [comment]
Hi, maybe some generic mechanism would be better here.? 
unite/denite/fzf/... could benefit from that kind of solution

**Comment by prabirshrestha** [comment]
Ya it would be good to have hooks into. But here is how I do with `CtrlP` now. Not the best but works.

I run `:LspReferences` command first and then have a mapping to convert quickfix to `CtrlP`.

```
nnoremap <leader>qf :cclose <CR>:CtrlPQuickfix<CR>
```

**Comment by natebosch** [comment]
Here's something I hacked up to search the quickfix or location list with fzf
https://github.com/natebosch/dotfiles/commit/4eb2f5eb12e8b71221959d57edbc8ca9834f8e61

I'd imagine this is about the equivalent to `:CtrlPQuickfix`

**Comment by prabirshrestha** [comment]
Currently no plans to support it yet. I prefer [vim-fz](https://github.com/mattn/vim-fz) over fzf.vim so won't be able to maintain fzf support even if I built it. In order to make search experience seamless we need a way to notify that the search text has changed. You can read more on my vision at https://github.com/mattn/vim-fz/issues/4

**Comment by gbrlsnchs** [comment]
For people coming from search engines, there is https://github.com/liuchengxu/vista.vim, which can use `vim-lsp` as its source.

**Comment by jiz4oh** [comment]
Hi everyone, I have created a plugin [vim-lspfuzzy](https://github.com/jiz4oh/vim-lspfuzzy) that can show etc. documentsymbol and references in fzf window, any suggestion is appreciated and pr welcome
