### ISSUE TITLE
Eclipse.JDT custom configuration

### ISSUE THREAD

**Issue by husainaloos** [prabirshrestha/vim-lsp#690]
This is more of a question than an issue.

eclipse.jdt support custom configurations. For example, it support the configuration of what formatter to use: https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

How can I pass these configurations? in particular, how can I pass `java.format.settings.url` configuration to the server in vim-lsp?

**Comment by lgranie** [comment]
I created a plugin : https://github.com/lgranie/vim-lsp-java but you can not do it from vim.
Following the instructions from the link you gave, you had to edit the file "org.eclipse.jdt.core.prefs" in [eclipse.jdt.ls install directory]/.setttings/ for global settings or [project directory]/.settings/ for project specific settings.
