### ISSUE TITLE
`LspDocumentDiagnostics` runs before file is fully saved

### ISSUE THREAD

**Issue by jhod0** [prabirshrestha/vim-lsp#695]
To automatically show diagnostics when I save a file, I added the following to my `.vimrc`:

```vimscript
autocmd BufWritePost * LspDocumentDiagnostics
```

However, using `pyls`, if I add something like the following to a file, and then write with `:w`:

```python
dummy_string = 'Hello there!'
```

I get the diagnostic message `EOL while scanning string literal`. When I write again a second later, it gives the correct diagnostics. It seems like lsp is using diagnostics from a partially-updated file?

I may just be using `vim-lsp` wrong, in which case a suggestion how to do this properly would be appreciated. Thanks!

**Comment by Daniel-viberg** [comment]
My work around for this issue:
`  7 function! FormatAndWrite()                                                                          
  6   LspDocumentFormatSync                                                                              
  5   :w                                                                                                 
  4 endfunction                                                                                                                   
autocmd BufWritePost * silent! call FormatAndWrite() `
