### ISSUE TITLE
Flow doesn't work with Hover

### ISSUE THREAD

**Issue by TrySound** [prabirshrestha/vim-lsp#70]
I use [vim-lsp with flow-language-server](https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Flow) and have autocompletion, document symbols and go to definition commands. But hover doesn't work (I saw it in the code). When I call lspHover command I got `Retrieving hover...`

Here is vim-lsp log
```js
Thu Dec 14 12:24:02 2017:["s:on_text_document_did_save()", 4]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "flow-language-server"}, "message": "server already started"}}]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"hoverProvider": true, "documentSymbolProvider": true, "definitionProvider": true, "textDocumentSync": 2, "completionProvider": {"resolveProvider": true, "triggerCharacters": ["."]}}}}, "server_name": "flow-language-server"}, "message": "lsp server already initialized"}}]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"path": ".../src/example.js", "__data__": "vim-lsp", "server_name": "flow-language-server"}, "message": "already opened"}}]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"path": ".../src/example.js", "__data__": "vim-lsp", "server_name": "flow-language-server"}, "message": "not dirty"}}]
Thu Dec 14 12:24:11 2017:["--->", 2, "flow-language-server", {"method": "textDocument/hover", "on_notification": "---funcref---", "params": {"textDocument": {"uri": ".../src/example.js"}, "position": {"character": 11, "line": 205}}}]
Thu Dec 14 12:24:11 2017:["<---", 2, "flow-language-server", {"response": {"id": 16, "jsonrpc": "2.0", "result": {"range": {"end": {"character": 14, "line": 205}, "start": {"character": 4, "line": 205}}, "contents": {"language": "javascript", "value": "...code..."}}}, "request": {"method": "textDocument/hover", "jsonrpc": "2.0", "id": 16, "params": {"textDocument": {"uri": ".../src/example.js"}, "position": {"character": 11, "line": 205}}}}]
Thu Dec 14 12:24:11 2017:["s:on_stdout client request on_notification() error", "Vim(call):E714: List required"]
```

**Comment by entropitor** [comment]
I've got the same issue. It works with Neovim LanguageClient

**Comment by prabirshrestha** [comment]
@TrySound @entropitor do you have a sample repository that I can try to reproduce this on? I wasn't able to reproduce it on my hello world sample.

**Comment by TrySound** [comment]
Same hello world example
https://github.com/TrySound/vim-lsp-hover-bug
I use NVIM v0.2.0, node8.9.1, mac os high sierra

**Comment by prabirshrestha** [comment]
Tried in Vim8-1427 and Neovim 0.2.2 on Windows 10 and I couldn't reproduce.

Can you tell me the exact line number/col where you are running `:LspHover`?
Can you also add `.gitattributes` in your repository?
I will try in Mac soon.

**Comment by prabirshrestha** [comment]
I couldn't repro in Mac. Can you upgrade your neovim?

Neovim 0.2.2
Node: v9.3.0
flow-language-server: 0.2.0

@TrySound can you provide a minimal vimrc? Which version of lang server are you using?
Here is an minimal vimrc example. Make sure to have the flow lang server registered as mentioned [here](https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Flow) once you download it the vimrc. 

```sh
curl https://raw.githubusercontent.com/prabirshrestha/vim-lsp/master/minimal.vimrc -o /tmp/minimal.vimrc
vim -u minimal.vimrc
:PlugInstall
:e index.js
6g
:LspHover
```

**Comment by TrySound** [comment]
Neovim 0.2.2
flow-language-server 0.2.5
Running at 6,1
Here's my minimal [init.vim](https://gist.github.com/TrySound/869e20838936f1d6cd12ddf2c4e7fe4e)
I opened just minimal version with neovim and got the same problem

Your script with vim8 works fine.

**Comment by TrySound** [comment]
Works fine after upgrade to the latest version of vim-lsp.
