### ISSUE TITLE
Is there a way to set vim-lsp for specific project?

### ISSUE THREAD

**Issue by hujianxin** [prabirshrestha/vim-lsp#706]
Hi, I love vim-lsp, it's clean simple and robust, Thanks for your work.
Now, I'm finding a feature to set vim-lsp for specific project(git project and so on), by looking around docs, I found nothing about it. So is there a way to set vim-lsp for specific project?

**Comment by prabirshrestha** [comment]
I'm not sure what you meant by specific project. It is mostly done by filetype so it should automatically pick up the right root once you specify the root_uri. Most language servers should pick the right config value. I would suggest you to try using https://github.com/mattn/vim-lsp-settings which makes installing and configuring language server very easy with vim-lsp
