### ISSUE TITLE
lsp_highlight_references_enabled conflicts with lsp_semantic_enabled

### ISSUE THREAD

**Issue by Barricade** [prabirshrestha/vim-lsp#707]
I can't use at the same time ctermbg from highlight_references and ctermfg from highlight_semantic. Highlight references override all highlights including set to none. Moreover when I open another file and return back, semantic highlight stops working.

**Comment by thomasfaingnaert** [comment]
> I can't use at the same time ctermbg from highlight_references and ctermfg from highlight_semantic. Highlight references override all highlights including set to none.

Does #679 solve this particular issue?

>Moreover when I open another file and return back, semantic highlight stops working.

Is that also the case when highlight ref is disabled?
I'll have a look at this, it may have been introduced by #635

**Comment by Barricade** [comment]
> Is that also the case when highlight ref is disabled?
Same problem with highlight ref disabled

**Comment by thomasfaingnaert** [comment]
I cannot reproduce the file switching:
![Peek 2020-02-08 18-53](https://user-images.githubusercontent.com/10748726/74089722-62267180-4aa4-11ea-99f1-f8202520842a.gif)


Could you provide the log so we can check for errors?

**Comment by Barricade** [comment]
[vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/4174919/vim-lsp.log)
