### ISSUE TITLE
Show inferred type

### ISSUE THREAD

**Issue by Vanuan** [prabirshrestha/vim-lsp#715]
Is there a way to show an inferred type of the symbol under the cursor?

Like this one in VSCode?

![Screenshot from 2020-02-13 16-51-56](https://user-images.githubusercontent.com/361985/74446918-3bd84b80-4e81-11ea-8738-dba16b0f1dc3.png)

**Comment by thomasfaingnaert** [comment]
Is this information provided by hover? If so, `:LspHover` should do what you want.

**Comment by Vanuan** [comment]
Awesome! Thanks!
