### ISSUE TITLE
rust-analyzer helper completions broken since #718

### ISSUE THREAD

**Issue by Friz64** [prabirshrestha/vim-lsp#725]
Completion
![image](https://user-images.githubusercontent.com/20155479/74989838-dd433c80-5441-11ea-97ce-6b0a6efa24ad.png)

Expected
![image](https://user-images.githubusercontent.com/20155479/74989880-f6e48400-5441-11ea-99f6-9f21a461ffae.png)

Observed
![image](https://user-images.githubusercontent.com/20155479/74989889-fc41ce80-5441-11ea-98c1-e8f686775f81.png)

I have been experiencing this issue since PR #718. Method completions continue to work as expected. I use asyncomplete.vim for autocompletion.

**Comment by hrsh7th** [comment]
Thanks you for your reporting.
I will investigate it.

**Comment by hrsh7th** [comment]
It was reproduced in my machine.
It try to solve it.

**Comment by hrsh7th** [comment]
Sorry. It's my bad.

Could you try to use https://github.com/prabirshrestha/vim-lsp/pull/726/files?

**Comment by Friz64** [comment]
Thank you for fixing this so quickly! I will test your fix after i get home from school.

**Comment by Friz64** [comment]
I can confirm #726 fixes my issue. Thank you again!

**Comment by hrsh7th** [comment]
Thank you for comfirmation!
