### ISSUE TITLE
Missing autocommand when diagnostics are updated

### ISSUE THREAD

**Issue by ipkiss42** [prabirshrestha/vim-lsp#733]
Hi,

I tried using `lsp#get_buffer_diagnostics_counts()` to update my statusline (via the [lightline plugin](https://github.com/itchyny/lightline.vim)). Unfortunately, I can't find a way to know when diagnostic counts are updated in order to refresh the status line, so the status line is never updated. Everything works fine if I refresh it manually (in this case via a `lightline#update()` call).

Other LSP plugins provide autocommands for that:
* [coc.nvim](https://github.com/neoclide/coc.nvim) has the `CocDiagnosticChange` event ([source](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L2425)).
* [Ale](https://github.com/dense-analysis/ale) has the `ALELintPost` event ([source](https://github.com/dense-analysis/ale/blob/master/doc/ale.txt#L3663)).

It seems that none of the [existing autocommands](https://github.com/prabirshrestha/vim-lsp/blob/master/doc/vim-lsp.txt#L1136) can work for this use case. What about adding one for this?

I might give it a try myself if you agree with the approach and point me in the right direction.

Thanks!

**Comment by prabirshrestha** [comment]
Feel free to send a PR.

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/783#issuecomment-612314764
