### ISSUE TITLE
auto complete can't popup snippets' list menu

### ISSUE THREAD

**Issue by chenjie199234** [prabirshrestha/vim-lsp#746]
can't popup snippets list menu
start with this,there is no popup menu
![2020-03-09-00:08:28](https://user-images.githubusercontent.com/29348971/76166654-2530c600-619b-11ea-9b17-a70704d339c0.png)
input expand key:
![2020-03-09-00:08:38](https://user-images.githubusercontent.com/29348971/76166603-a9cf1480-619a-11ea-973e-7271405ce378.png)
plugins:
![2020-03-09-00:12:55](https://user-images.githubusercontent.com/29348971/76166661-337ee200-619b-11ea-802e-929aa4c49f40.png)

**Comment by hrsh7th** [comment]
It seems not LSP's snippet but neosnippet's snippet.

Could you try this plugin?
https://github.com/prabirshrestha/asyncomplete-neosnippet.vim

**Comment by chenjie199234** [comment]
@hrsh7th 
wow~it works fine
thx very much
