### ISSUE TITLE
Suggested headers with clangd contains extra '>' symbol

### ISSUE THREAD

**Issue by Shatur95** [prabirshrestha/vim-lsp#747]
I have a small issue with `clangd`.
It suggest snippet `#include <header>`, but when I using this snippet it suggests headers with `>`.
I using `vim-vsnip` for snippets.

Here is the video that describes issue a bit more:
[![asciicast](https://asciinema.org/a/FV70Y94r9Gh2DgaRDX8B7NuWC.svg)](https://asciinema.org/a/FV70Y94r9Gh2DgaRDX8B7NuWC)

**Comment by okwellok** [comment]
Hello,I also have this issue with clangd.Have you solved it now？
