### ISSUE TITLE
PHP Intelephense and files.associations

### ISSUE THREAD

**Issue by puresyntax71** [prabirshrestha/vim-lsp#749]
For some reason, I can't seem to get Intelephense to index files ending in other extensions (*.inc and *.module). I'm using `vim-lsp-settings` and have this configuration:

```
{
  "intelephense": {
    "workspace_config": {
      "intelephense.files.associations": ["*.inc", "*.module", "*.php"]
    }
  }
}
```

I also tried with this:

```
{
  "intelephense": {
    "workspace_config": {
      "intelephense": {
        "files.associations": ["*.inc", "*.module", "*.php"]
      }
    }
  }
}
```

Not working as well. Definitions from *.php files seem to work but the ones at *.inc and *.module just can't seem to be found.

Any help appreciated. Thanks!

**Comment by mattn** [comment]
AFAIK, `file.associations` is not configuration for vim-lsp or language server. it is configuration for Visual Studio Code to assign pattern of filenames to be recognized as php files.

**Comment by puresyntax71** [comment]
Oh okay, yeah I just noticed it at https://github.com/prabirshrestha/vim-lsp/wiki/Servers-PHP#registering-in-vimrc and thought maybe it works the same.

Upon further testing, I noticed that I was able to find the definition if say I've opened the file first e.g. I open index.php and helper.inc, if I do `LspDefinition` on a function defined in helper.inc but called in index.php, then it goes to the definition.

**Comment by puresyntax71** [comment]
Not entirely sure if I am looking at this correctly but https://github.com/bmewburn/intelephense-docs/blob/master/README.md#configuration-options says that it has support for the `intelephense.files.associations` configuration. But anyway, just to verify, yeah it does seem it doesn't index the other file extensions are than *.php (or perhaps including *.phtml).

**Comment by puresyntax71** [comment]
Yeah, just to update, I was able to get this working with https://github.com/neoclide/coc.nvim and https://github.com/marlonfan/coc-phpls using the `intelephense.files.associations`:

```
{
  "intelephense.files.associations": [
    "*.inc",
    "*.php",
    "*.module"
  ]
}
```

I guess I can test further if necessary; otherwise feel free to close.

**Comment by mattn** [comment]
Probably, you need make nests with keys `"intelephense": { "files": { "associations": ... } } }`

**Comment by puresyntax71** [comment]
That is correct. Dang, I never thought of this. Thank you so much!
