### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by RoGryza** [prabirshrestha/vim-lsp#762]
The only tagged release is v0.1.0 from three years ago, would you be willing to tag new versions?
I want to maintain a versioned alternative to [vim-lsp-git](https://aur.archlinux.org/packages/vim-lsp-git/) ou AUR, but without version numbers I'd have to pin arbitrary commit hashes.

**Comment by prabirshrestha** [comment]
v0.1.1 released.

**Comment by gobwas** [comment]
Hey @prabirshrestha I wonder are there any significant changes after v0.1.1?

**Comment by prabirshrestha** [comment]
added new `v0.1.1` tag. 

There has been a bunch of new bug fixes as well as some new features after v0.1.1.

Since I use master branch for the plugin for my day to day, feel free to ping again if you would like to see new tags.
