### ISSUE TITLE
Can't figure out vim-lsp-server_info config or workspace_config

### ISSUE THREAD

**Issue by dbarnett** [prabirshrestha/vim-lsp#765]
I cannot for the life of me figure out how to pass configuration to an LSP server when it starts, whether through `lsp#register_server`'s `config` or `workspace_config` or through ~/.local/share/vim-lsp-settings/settings.json. In every case, when I enable vim-lsp logging and look in the logs, I see
```
Tue 24 Mar 2020 08:33:05 AM PDT:["--->",1,"pyls",{"method":"initialized","params":{}}]
Tue 24 Mar 2020 08:33:05 AM PDT:["--->",1,"pyls",{"method":"workspace/didChangeConfiguration","params":{"settings":{}}}]
```
and can't find anything about the `pyls.plugins.pycodestyle.enabled: false` option I'm so desperately trying to configure.

How do I troubleshoot this?

**Comment by mattn** [comment]
If you use vim-lsp-settings, do `:LspSettingsLocalEdit` and type:

```
{
    "pyls": {
        "config": {
            "pyls": {
                "plugins": {
                    "pycodestyle": {
                        "enabled": false
                    }
                }
            }
        }
    }
}
```

**Comment by dbarnett** [comment]
It works! I had to use `workspace_config` instead of `config` for this but then I got the results I was hoping for. I was missing a few layers of nesting so instead of having `pyls.config.pyls.plugins.pycodestyle` I had just `pyls.plugins.pycodestyle`.

As far as conveniently troubleshooting situations like this, I found that `:LspSettingsStatus` tells me more directly whether the config was picked up. Any other tricks to discover if it encounters invalid config like `{ "pyls": { "plugins": … } }`, or track down where particular parts of my json config are going if they're not reaching the LSP server I'm expecting them to?

**Comment by prabirshrestha** [comment]
Refer to read me to enable logs.

**Comment by dbarnett** [comment]
K, but I didn't see anything about the invalid "plugins" section I added anywhere in the verbose logs I enabled and checked.

**Comment by dbarnett** [comment]
Would still be helpful if something would log or print a message for unrecognized sections in the config.
