### ISSUE TITLE
Any way to explicitly select JSON Schema for current file?

### ISSUE THREAD

**Issue by dbarnett** [prabirshrestha/vim-lsp#775]
Using vim-lsp with vscode-json-languageserver, I can define some `fileMatch` config rules to select an appropriate schema when I open a file whose filename matches a particular pattern. Is there any after-the-fact way as I'm editing a JSON file to explicitly pass a choice of schema to use to the JSON language server?

**Comment by mattn** [comment]
vim-lsp-settings works with catelogue file popularly.

If you want to use own JSON schema, you can use workspace_config:

https://github.com/mattn/vim-lsp-settings/blob/34a22e56db7f4d8baea7ae042c483df17bc37271/settings/json-languageserver.vim#L11

**Comment by dbarnett** [comment]
I'm talking about manually selecting a schema, similar to how filetypes work in vim that you can either have ftdetect rules upfront or use `:setfiletype somefiletype` interactively.

**Comment by dbarnett** [comment]
How about this: Is there a way to *get* the JSON Schema for the JSON file I'm currently editing (as in the `$id` for it)?

**Comment by dbarnett** [comment]
Looks like the answer for that last question is "no", jsonls provides no way to get the current schema right now (there's a PR for it microsoft/vscode-json-languageservice#47 that the maintainers have ignored).

I also filed microsoft/vscode-json-languageservice#58 in jsonls since the operations I found implemented in the lang server were for filename matching and nothing to help with on-the-fly selection.

**Comment by dbarnett** [comment]
From discussion on the issue in jsonls/vscode I learned that temporarily adding a `$schema` key in the file I'm editing works pretty well to switch schema on the fly.
