### ISSUE TITLE
How to configure different schemas for yaml-language-server

### ISSUE THREAD

**Issue by korney4eg** [prabirshrestha/vim-lsp#779]
Hey guys,

Thank you for great plugin!
I have pretty short experience with configuring LSP, but I managed to configure with docker, terraform, bash. What I would like currently to configure is LSP for yaml for docker-compose and kubernetes.

Right now it looks like this and doesn't work:
```yaml
if executable('yaml-language-server')
  augroup LspYaml
   autocmd!
   autocmd User lsp_setup call lsp#register_server({
       \ 'name': 'yaml-language-server',
       \ 'cmd': {server_info->['yaml-language-server', '--stdio']},
       \ 'whitelist': ['yaml', 'yaml.ansible','yaml.kubernetes'],
       \ 'workspace_config': {
       \   'yaml': {
       \     'validate': v:true,
       \     'hover': v:true,
       \     'completion': v:true,
       \     'customTags': [],
       \     'schemas': {
     \           'https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/v1.17.0-standalone-strict/all.json': '*.yaml',
     \           'https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/v1.17.0-standalone-strict/all.json': '*.yaml',
     \},
       \     'schemaStore': { 'enable': v:true },
       \   }
       \ }
       \})
  augroup END
endif
```

I have seen how it could be configured via `coc-yaml` https://octetz.com/docs/2020/2020-01-06-vim-k8s-yaml-support/ , but I would like to configure it using vim-lsp.

*P.S.* I have installed `yaml-language-server`

**Comment by yaegassy** [comment]
@korney4eg Hi!

This is an example `schemas` settings for kubernetes and docker-compose.
Please try it.

```vim
       \     'schemas': {
       \        'kubernetes': ['/kubernetes.yml'],
       \        'https://raw.githubusercontent.com/docker/cli/master/cli/compose/schema/data/config_schema_v3.9.json': ['/docker-compose.yml'],
       \      },
```

**Comment by korney4eg** [comment]
Thank you @yaegassy ,

will try it out on my work laptop tomorrow.

BTW, in this schemas, `/kubernetes.yml` - is the file name where those schemas should be applied or is it filetype?

**Comment by yaegassy** [comment]
> is the file name where those schemas should be applied or is it filetype?

This is a file name, but can also be globPattern.

Check the documentation at yaml-language-server.

https://github.com/redhat-developer/yaml-language-server/blob/master/README.md#more-examples-of-schema-association

**Comment by dbarnett** [comment]
Hi, FWIW I'm trying similar and cannot figure out how to get vim-lsp to pass through settings to yaml-language-server at all. I tried lsp_setup like yours above and also tried using vim-lsp-settings and a settings.json like:
```json
{
  "yaml-language-server": {
    "workspace_config": {
      "yaml": {
        "schemas": {
          "kubernetes": ["/home/myusername/.kube/config"]
        }
      }
    }
  }
}
```
However I tried, if I opened a YAML file in vim and then searched through my log file for yaml-language-server `workspace/didChangeConfiguration` entries, they'd have a big `params.settings.yaml` blob with a whole bunch of schemas but none of the settings I'd tried to provide.

**Comment by rene-descartes2021** [comment]
I wanted to be able to configure the schemas after server initialization rather than at initialization like [here](https://github.com/prabirshrestha/vim-lsp/issues/511#issuecomment-531607293).

You can see the current schemas configured in the server here:
```vim
echo lsp#get_server_info('yaml-language-server').workspace_config
```
And update the workspace_config (contains the schemas) using:
```vim
call lsp#update_workspace_config('yaml-language-server', workspace_config)
```
