### ISSUE TITLE
Omnisharp Language Server doesn't work

### ISSUE THREAD

**Issue by VeeDeltaVee** [prabirshrestha/vim-lsp#780]
I'm using the following configuration for vim-lsp:

```
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'lighttiger2505/deoplete-vim-lsp'
Plug 'mattn/vim-lsp-settings'


" Make LSP diagnostics signs high priority
let g:lsp_signs_priority = 20

" No virtual text that looks awful
let g:lsp_virtual_text_enabled = 0

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/Desktop/vim-lsp.log')
```

No part of the omnisharp language server is working, but I'm able to get every other language server I've tried to work. I'm installing and using it using the vim-lsp-settings plugin.

Here's a link to the [log file](https://gist.github.com/VeeDeltaVee/f67b5660e1952cb5aac26b6fbb840ec3) where I just open a Program.cs file, and type in some random stuff, then exit when I don't get any diagnostics info or completion info popping up like it does for other languages.

Does anyone have any idea why this is happening?

**Comment by prabirshrestha** [comment]
I don't see any errors on our side. Please follow with omnisharp. Wondering if they have some unhandled exceptions and it is crashing.
