### ISSUE TITLE
redrawtime exceeded syntax highlighting disabled

### ISSUE THREAD

**Issue by guildem** [prabirshrestha/vim-lsp#786]
Tried with the smallest .vimrc file I could have :

```
syntax on

if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

call plug#end()
```

Tested with a big Angular project and typescript server installed.
Start with a few seconds with a clean syntax coloration, then a few seconds locked without any move possible, and finally `redrawtime exceeded syntax highlighting disabled` message displayed at the bottom and coloration deactivated.
All my next moves are sometimes laggy, unable to see in realtime my updates, like if all the searches with the typescript server were synchronized.

This bug is only on the bigger buffer of the project (.ts file of 1000 lines) and all is working fine in other buffers.

### Partial fix : 

`set redrawtime=10000`
Fix only the coloration, the lags stay there : 
- a few seconds the buffer is shown, I have a lag of a few seconds,
- each call to typescript server (completion) seems to be synchronized so small lag.

### Other infos : 

ALE test seems to be fine, no lag but errors are shown and completion is working.

**Comment by danielbair** [comment]
I'm seeing this problem too.

**Comment by chris-gillatt** [comment]
I've had this problem intermittently on Mac (via brew) since I upgraded to Big Sur.  Seems to only affect some files.

Somehow I ended up missing a dependency for `source-highlight` (https://www.gnu.org/software/src-highlite/): which was `boost` (https://www.boost.org/)
Managed to resolve by doing;

`brew reinstall source-highlight`

**Comment by tristantao** [comment]
Setting re=0 in vimrc actually solved this problem for me as well:

```
syntax on
set re=0
```
If this doesn't work, I think it's also worth trying setting re to 1 and 2.


Commenting as this is currently the top answer on Google :)

**Comment by sagsango** [comment]
I'm seeing this problem on macOS Monterey.

**Comment by ckyoog** [comment]
Instead of setting re=0, I solved the problem by the following
```
set rdt=0
syntax on
```

**Comment by subeenregmi** [comment]
Using `set re=0` made editting a `.tsx` file possible, thanks! 👍
