### ISSUE TITLE
CMake language server support

### ISSUE THREAD

**Issue by Rubonnek** [prabirshrestha/vim-lsp#791]
I'm attempting to use https://github.com/regen100/cmake-language-server

There's nothing in the wiki about it.

I'm trying to set it up with:

```
if executable('cmake-language-server')
    augroup lsp_cmake
        autocmd!
        autocmd User lsp_setup call lsp#register_server({
                    \ 'name': 'cmake',
                    \ 'cmd': {server_info->['cmake-language-server']},
                    \ 'whitelist': [ 'CMakeLists.txt', 'cmake' ],
					\ 'initialization_options': {
					\   'buildDirectory': 'build',
					\ }})
        autocmd FileType CMakeLists.txt setlocal omnifunc=lsp#complete
        autocmd FileType cmake setlocal omnifunc=lsp#complete
    augroup end
endif
```

But in the log I'm getting:

```
Mon 13 Apr 2020 01:33:37 PM EDT:[{"response":{"error":{"data":{"lsp_id":1,"__error__":"vim-lsp","server_name":"cmake"},"code":0,"message":"ignore initialization lsp server due to empty root_uri"}}}]
```

I'm not quite sure what root_uri should be..

**Comment by prabirshrestha** [comment]
refer to samples here. https://github.com/prabirshrestha/vim-lsp/wiki/Servers or refer to docs. `root_uri` by default is the current `cwd` if not provide. Else you can create a function that uses your own or use other markers such as `.git/`, `Cargo.toml` and so on.

Another option would be to request feature at https://github.com/mattn/vim-lsp-settings
