### ISSUE TITLE
Why highlight references and echo diagnostics only in normal mode?

### ISSUE THREAD

**Issue by mitinarseny** [prabirshrestha/vim-lsp#792]
* Why not to implement `g:lsp_highlight_references` and `g:lsp_highlight_references_insert` boolean variables and add autocommands for insert mode as well? 
https://github.com/prabirshrestha/vim-lsp/blob/5dd94c66f7195cf4605fe02c86a27d6d24d8fc88/autoload/lsp.vim#L208
* And why clean reference highlighting on `InsertEnter`?
https://github.com/prabirshrestha/vim-lsp/blob/5dd94c66f7195cf4605fe02c86a27d6d24d8fc88/autoload/lsp.vim#L210
* With `g:lsp_diagnostics_float_cursor` enabled unmapping from #787 causing error: `no such mapping`:
```vim
autocmd User lsp_float_closed call lsp#ui#vim#references#highlight(v:false)
      \ | nunmap <buffer> <Esc>
```

I'm just asking before submitting PR as it can be done for some reason...

P.S.: Why `augroup` is empty here?)
https://github.com/prabirshrestha/vim-lsp/blob/9fa593aed479fdf884f643a4711dfdfe32fc0424/autoload/lsp/ui/vim/output.vim#L27-L29

**Comment by prabirshrestha** [comment]
Feel free to send a PR to support it in non normal mode.

**Comment by mitinarseny** [comment]
I am just wondering if these lines have any particular reasons to exist? Were there any hidden reasons why not to support it in non-normal mode as these lines prevent it?

**Comment by prabirshrestha** [comment]
There is no particular reason for it. 

We just need to make sure it is debounce properly so every cursor move doesn't cause flushing which causes diff computation which is heavy. Some users may not like to see errors as they type while some would prefer it but if debounce is handled it shouldn't be an issue.
