### ISSUE TITLE
After the last update go to definition opens a split instead of jumping to the definition

### ISSUE THREAD

**Issue by NikosEfthias** [prabirshrestha/vim-lsp#796]
After the last update LspDefinition behaviour changed and no longer jumps to the definition instead it opens a split which is really annoying when you already have a ton of splits is there a way to override this default behaviour ?

**Comment by NikosEfthias** [comment]
```
	nnoremap <buffer> <c-]> :LspDefinition<cr>
```
this is the binding I use and according to the documentation it should replace the current buffer but it does not do that instead opens a split similar to LspPeakDefinition which is wrong and extremely annoying

**Comment by prabirshrestha** [comment]
Could you try reverting https://github.com/prabirshrestha/vim-lsp/commit/9a4f8de6bee608407a341e188adc9c5f49e90811

**Comment by sivakov512** [comment]
I have the same problem.
I rolled back plugin to 5f8f3fbeb7349fba53cb69fb60b9068de396a2f6, works well.

**Comment by fredrik-jansson-se** [comment]
Same problem for me

**Comment by prabirshrestha** [comment]
Please try https://github.com/prabirshrestha/vim-lsp/pull/774 and https://github.com/prabirshrestha/vim-lsp/pull/798

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/774 please try latest master.

Sorry for the inconvenience.

**Comment by NikosEfthias** [comment]
thank you and sorry for the really late reply I was on my holiday didnt have much screen time
