### ISSUE TITLE
[Question] How do I register a language server that's already running?

### ISSUE THREAD

**Issue by Rybadour** [prabirshrestha/vim-lsp#799]
Perhaps I'm confused at how this plugin works but I'm hoping to using this plugin to connect to an already running language server. It's running locally on a known port. It seems like all examples that use vim-lsp do so by telling it which command to run, which I assume is how it sets up the communication between vim and the language server.

Does this plugin not support my use-case or am I just being dense and missing something?

Any clarification would be appreciated!

**Comment by prabirshrestha** [comment]
Currently not possible and no plans to support it. 

[vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) is the preferred way to register servers.

You can create a proxy LSP server that talks to existing already running server.
