### ISSUE TITLE
Write Vim documentation

### ISSUE THREAD

**Issue by hauleth** [prabirshrestha/vim-lsp#80]

**Comment by prabirshrestha** [comment]
This has been long over due. I added an empty doc file. https://github.com/prabirshrestha/vim-lsp/pull/82

Let me know what particular docs you are looking for or think would be useful to others and we can prioritize based on it.

**Comment by hauleth** [comment]
This was rather not to myself to handle it soon.

**Comment by mkwork** [comment]
Doc file no more empty. Looks like this issue can be closed? While in other case it would be endless :)

**Comment by prabirshrestha** [comment]
Yes. Can close it. We can file separate bugs for  other docs if needed.
