### ISSUE TITLE
Using netcat or socat to connect to a TCP LSP server

### ISSUE THREAD

**Issue by Rubonnek** [prabirshrestha/vim-lsp#801]
Hello,

I'm trying to connect to the LSP server of the [Godot Game Engine](https://github.com/godotengine/godot) which only communicates over TCP, so I figured I could use netcat or socat to get around that.

I tried this, but I don't see any packets going through the loopback device:

Here's what I tried:
```
if executable('godot_server')
	augroup lsp_godot
		autocmd!
		autocmd User lsp_setup call lsp#register_server({
					\ 'name': 'godot_server',
					\ 'cmd': {server_info->['nc', '127.0.0.1', '6008']},
					\ 'whitelist': ['gd'],
					\ 'initialization_options': {
					\   'vimruntime': $VIMRUNTIME,
					\   'runtimepath': &rtp,
					\ }})
	augroup end
	autocmd FileType gd setlocal omnifunc=lsp#complete
endif
```

The godot_server exists and I see it getting registered:

```
Fri 24 Apr 2020 08:53:30 PM EDT:["lsp#register_server","server registered","godot_server"]
```

I just don't see packets passing through the loopback device.

**Comment by Rubonnek** [comment]
Welp, nevermind. I got it to work:

```
if executable('godot_server')
	augroup lsp_godot
		autocmd!
		autocmd User lsp_setup call lsp#register_server({
					\ 'name': 'godot_server',
					\ 'cmd': {server_info->['nc', '127.0.0.1', '6008']},
					\ 'whitelist': ['gd', 'gdscript3'],
					\ })
	augroup end
endif
```

**Comment by mattn** [comment]
Now vim-lsp support tcp feature. https://github.com/prabirshrestha/vim-lsp/pull/985
