### ISSUE TITLE
LspDefinition not working after the first time

### ISSUE THREAD

**Issue by HiPhish** [prabirshrestha/vim-lsp#805]
After updating to cf43b59127907bff442626acb1ca354a0675f0f0 I have the following issue: executing `:LspDefinition` in a buffer on a symbol defined in another file works fine, but if I execute it again on a symbol in another file nothing happens. I see the `Retrieving definition...` message in the message area, but that is it. Other LSP functionality like displaying documentation or peeking into the definition work fine. Executing `:LspDocumentation` on a symbol defined in the same buffer also works.

The last commit which worked fine for me was 5f8f3fbeb7349fba53cb69fb60b9068de396a2f6, afterwards I experienced the issue #796. Updating to cf43b59127907bff442626acb1ca354a0675f0f0 fixed that issue, but caused this one instead.

I am using Neovim version 0.4.3 on Kubuntu 19.10 and the [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) language server for Java.

**Comment by prabirshrestha** [comment]
can you try latest master. https://github.com/prabirshrestha/vim-lsp/pull/806 was checked in.

**Comment by HiPhish** [comment]
Seems to be working, closing the issue. Thank you.
