### ISSUE TITLE
signature help opens up even when g:lsp_signature_help_enabled is 0

### ISSUE THREAD

**Issue by NikosEfthias** [prabirshrestha/vim-lsp#820]

**Comment by mattn** [comment]
g:lsp_signature_help_enabled does not change the behavior even if it is switched during running.

**Comment by NikosEfthias** [comment]
so this is a bug right ? @mattn

**Comment by mattn** [comment]
What is your expected behavior?

**Comment by NikosEfthias** [comment]
when g:lsp_signature_help is 0 on stepping in a function call the signature help windows should not pop up is the expected behaviour otherwise there is no use of having an option which does not do anything

**Comment by mattn** [comment]
What the way to set g:lsp_signature_help=0 ? vimrc? or something lazy events?

**Comment by NikosEfthias** [comment]
in my inside User event 
```
function! s:on_lsp_buffer_enabled() abort
	...
	let g:lsp_signature_help_enabled=0
	...
endfunction
augroup lsp_install
	au!
	autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

```

**Comment by prabirshrestha** [comment]
This is now fixed. Please try the latest master.
