### ISSUE TITLE
Css3 nested classes and 'composes' property 

### ISSUE THREAD

**Issue by zorgick** [prabirshrestha/vim-lsp#825]
Hi! Thank you for your amazing plugin. It is really what I've been looking  for my neovim for a long time.
Could you please help to fix this annoying problem that happens in .css files?
The vim-lsp doesn't know how to handle nested classes by default. Maybe there is an option that can switch the diagnostics off for this feature, at least?
![image](https://user-images.githubusercontent.com/32340377/82821206-56708680-9eac-11ea-8b3f-74047eb7e93d.png)
The same goes for `composes:` property
![image](https://user-images.githubusercontent.com/32340377/82821410-bd8e3b00-9eac-11ea-9c0d-46257da6a189.png)

**Comment by NikosEfthias** [comment]
I think this is a problem with the serevr you are using rather than this plugin

**Comment by prabirshrestha** [comment]
Yups the problem with server and not vim-lsp. You will need to file a bug there instead.
