### ISSUE TITLE
Completion no longer working since last commit

### ISSUE THREAD

**Issue by HiPhish** [prabirshrestha/vim-lsp#837]
Hello,

I am using [ncm2](https://github.com/ncm2/ncm2) for auto-completion, and since the last commit (e0cacffe54c9335a101bc44d9b601601e679d9fc) nothing from LSP is displayed any longer. Other completion sources work fine though. Reverting to the previous commit (33dcddfbe663b5b38ef8e5ec0f1201afe801687a) got completion working again.

Using Neovim 0.4.3 on GNU/Linux Kubuntu 20.04

**Comment by prabirshrestha** [comment]
Ncm2 needs to be updated.

https://github.com/ncm2/ncm2-vim-lsp/issues/12

**Comment by HiPhish** [comment]
Thanks for pointing it out, I have sent them a PR. But for crying out loud, this was much harder than it should have been. You really should provide proper documentation for code which is exposed to the outside; I spent way too much time randomly poking at things until I got something up and running.
