### ISSUE TITLE
Add possibility to open uris with other protocol than file for location request

### ISSUE THREAD

**Issue by patrickpichler** [prabirshrestha/vim-lsp#839]
[clojure-lsp](https://github.com/snoe/clojure-lsp/) will return an URI with `zipfile` as protocol when issuing a definition command for any symbol comming from a library. 

As of right now vim-lsp cannot handle those case, as it always assumes the resulting URI to be in file protocol.

It would be nice to be able to register some custom handlers for protocols so that other protocols such as http could be handled as well.

**Comment by gpontesss** [comment]
was it solved?
