### ISSUE TITLE
Disable Autocomplete Function

### ISSUE THREAD

**Issue by jasontcole** [prabirshrestha/vim-lsp#848]
I have been using coc.nvim for autocomplete but have found that vim-lsp has better goto definition support.  I would like to use vim-lsp for that function.  How would I disable autocomplete/omni complete?

**Comment by jmdevin** [comment]
Vim-lsp does not autocomplete or set omnifunc out of the box. Are you asking how to disable CoC.nvim's autocompletion?

**Comment by jasontcole** [comment]
Hmm.  I am using vim-lsp with the Kythe LSP.  Would it be Kythe that I may have to disable the autocomplete function on then?

**Comment by jmdevin** [comment]
I can't speak for Kythe specifically, but I don't believe it can be a function of the language server. Check whether you have asyncomplete.vim installed, as that is vim-lsp's normal autocompletion integration.
