### ISSUE TITLE
Doesn't working show preview due to window size.

### ISSUE THREAD

**Issue by Ttayu** [prabirshrestha/vim-lsp#850]
Hi. I get this error on completion.
This error can be seen in Rust, C++ and python.

![image](https://user-images.githubusercontent.com/32290119/85917439-00b94080-b895-11ea-8418-4bb126282f1c.png)

This is an error due to the window size, and the `l:width` is 0.
https://github.com/prabirshrestha/vim-lsp/blob/32fae1f0e9c0c2c21361d0bb94f119f9ae65a118/autoload/lsp/ui/vim/documentation.vim#L43

I have responded foolishly(`if l:width==0; let l:width +=1`), but is there any better idea?

Related
#507

**Comment by prabirshrestha** [comment]
Instead of =0 can you send a PR with <= 0

**Comment by Ttayu** [comment]
I sent it. please check it.

**Comment by bcspragu** [comment]
I'm seeing a similar issue, but for height, when working with Go code + golsp

![height](https://user-images.githubusercontent.com/2402010/86538696-6ec0c180-beac-11ea-8907-394151aef02a.png)

**Comment by Ttayu** [comment]
thanks for reporting.
I sent pull request.
