### ISSUE TITLE
rust LspDefinition not working

### ISSUE THREAD

**Issue by yarikbratashchuk** [prabirshrestha/vim-lsp#855]
It just doesn't work for me.
I see how it works in vscode (`rls`), and it doesn't work in vim.
If I `Plug 'racer-rust/vim-racer'`, I'm able to find some definitions, but `rls` always return `No definition found.`
Any suggestions?

I set it up using the wiki page.

**Comment by prabirshrestha** [comment]
I would using https://github.com/mattn/vim-lsp-settings with rust analyzer. I use it every day and it works.

Are you using workspace?

**Comment by yarikbratashchuk** [comment]
Works for me as well.
Much thanks for the help :)
