### ISSUE TITLE
wrong type of argument 1 expecting window

### ISSUE THREAD

**Issue by NikosEfthias** [prabirshrestha/vim-lsp#860]
![image](https://user-images.githubusercontent.com/9097437/86117476-28e8af80-bae0-11ea-8db2-bc08978152d3.png)
this error occurs often when I am writing a rust project.
basically I start typing someting then hit <c-x><c-o> and when autocomplete starts errors start popping up making the thing unusable.
When I remove vim-lsp from vim everything works as expected

**Comment by prabirshrestha** [comment]
Most likely using old version of vim. What is your vim version?

**Comment by prabirshrestha** [comment]
In the mean time you could try to set `let g:lsp_documentation_float=0`

**Comment by NikosEfthias** [comment]
@prabirshrestha  `g:lsp_documentation_float` seems to be the issue so far. With that setting of I didnt get any errors whole day today
