### ISSUE TITLE
Should markdown render inside preview on hover?

### ISSUE THREAD

**Issue by jbizzle** [prabirshrestha/vim-lsp#865]
Not sure if this is related to #576 or not, but wonder if there is some configuration I'm overlooking to allow markdown in hover previews to be rendered more stylistically? Currently I see raw markdown, with markdown-highlighting, but wonder if there is some way to have it actually rendered (to the degree possible in an editor).

An example: 
![Screen Shot 2020-07-08 at 8 59 47 AM](https://user-images.githubusercontent.com/1414162/86942096-9789c680-c0f9-11ea-9135-1da72aef647b.png)

I'm using the version at 11b13507002e42adf77b35ed63b4164ecc5d5b8a and vim:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 24 2020 23:42:24)
macOS version
Included patches: 1-1050
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cursorshape       +job               +mouse_urxvt       +signs             +vartabs
+arabic            +dialog_con        +jumplist          +mouse_xterm       +smartindent       +vertsplit
+autocmd           +diff              +keymap            +multi_byte        -sound             +virtualedit
+autochdir         +digraphs          +lambda            +multi_lang        +spell             +visual
-autoservername    -dnd               +langmap           -mzscheme          +startuptime       +visualextra
-balloon_eval      -ebcdic            +libcall           +netbeans_intg     +statusline        +viminfo
+balloon_eval_term +emacs_tags        +linebreak         +num64             -sun_workshop      +vreplace
-browse            +eval              +lispindent        +packages          +syntax            +wildignore
++builtin_terms    +ex_extra          +listcmds          +path_extra        +tag_binary        +wildmenu
+byte_offset       +extra_search      +localmap          +perl              -tag_old_static    +windows
+channel           -farsi             +lua               +persistent_undo   -tag_any_white     +writebackup
+cindent           +file_in_path      +menu              +popupwin          -tcl               -X11
-clientserver      +find_in_path      +mksession         +postscript        +termguicolors     -xfontset
+clipboard         +float             +modify_fname      +printer           +terminal          -xim
+cmdline_compl     +folding           +mouse             +profile           +terminfo          -xpm
+cmdline_hist      -footer            -mouseshape        -python            +termresponse      -xsmp
+cmdline_info      +fork()            +mouse_dec         +python3           +textobjects       -xterm_clipboard
+comments          +gettext           -mouse_gpm         +quickfix          +textprop          -xterm_save
+conceal           -hangul_input      -mouse_jsbterm     +reltime           +timers
+cryptv            +iconv             +mouse_netterm     +rightleft         +title
+cscope            +insert_expand     +mouse_sgr         +ruby              -toolbar
+cursorbind        +ipv6              -mouse_sysmouse    +scrollbind        +user_commands
```

**Comment by cuviper** [comment]
FWIW, with the builtin markdown syntax, you can at least enable syntax highlighting on code snippets like so:

```vim
let g:markdown_fenced_languages = ['go', 'rust']
```

There's also `g:markdown_syntax_conceal=1`, but I can't see any effect from setting that, even with `g:lsp_hover_conceal=1`.

**Comment by rafi** [comment]
@jbizzle if you use [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown) you can set:
```viml
let g:vim_markdown_conceal = 1
let g:vim_markdown_conceal_code_blocks = 1
```
By default, `conceallevel` is disabled, otherwise, you can disable it for regular markdown:
```viml
autocmd FileType markdown setlocal conceallevel=0
```
https://github.com/prabirshrestha/vim-lsp/blob/master/ftplugin/lsp-hover.vim#L11 will automatically enable `conceallevel`.

You can customize the lsp-hover window with an event:
```viml
autocmd FileType markdown.lsp-hover
	\ nmap <silent><buffer>q :pclose<CR>| doautocmd <nomodeline> BufWinEnter
```
For some reason I need to trigger `BufWinEnter` for the markdown code syntax to apply.

Unfortunately, the code fences are empty-lines. I wonder if Neovim's `:h vim.lsp.util.try_trim_markdown_code_blocks` can be imitated here to make preview cleaner.

**Comment by jbizzle** [comment]
Thanks @rafi . That does get some syntax highlighting at least. The conceal still doesn't seem to kick in inside the hover, but still better than before.

**Comment by ElArtista** [comment]
Any updates on this?

**Comment by prabirshrestha** [comment]
Currently working on other asks but if someone can port neovim's trim function to vimscript that would be great. https://github.com/neovim/neovim/blob/a1ec36ff31ff1fd545dd135faa47dc782b41a687/runtime/lua/vim/lsp/util.lua#L1272-L1291

Another short term fix would also be to support only plain text for hovers via customization.

https://github.com/prabirshrestha/vim-lsp/blob/4f4fdf4aa1782dcba6c68f82d93da25ff6229399/autoload/lsp.vim#L506-L509

**Comment by prabirshrestha** [comment]
I have fixed this temporarily while we are looking into revamping the hover menu.

neovim:
![image](https://user-images.githubusercontent.com/287744/112764740-db419a80-8fbe-11eb-8809-83d856e2b63c.png)

vim:
![image](https://user-images.githubusercontent.com/287744/112764747-e4326c00-8fbe-11eb-94ec-e0f25b7a3d07.png)

**Comment by nkaretnikov** [comment]
@prabirshrestha hi, is this supposed to work with a C++ codebase? here's how it looks for me with solarized in iterm2. lmk if i need to provide more info to troubleshoot. thx!

<img width="900" alt="Screen Shot 2021-08-23 at 06 19 53" src="https://user-images.githubusercontent.com/10469885/130385674-03972ab5-85c5-4fe7-b4a2-d7c1a2a6ae43.png">

**Comment by nkaretnikov** [comment]
UPD: the hover output looks the same with Rust code as well (using rust-analyzer).

**Comment by ElArtista** [comment]
Same:
![image](https://user-images.githubusercontent.com/4622346/130792516-c988444e-39ec-4eb0-8ee3-9bedac5750ae.png)

**Comment by georgeharker** [comment]
the conceal issue seems to relate to the lsp_do_conceal var and the order the ftplugin runs.  If you do a 

```
win_execute(s:winid, 'set concellevel=2')
```

from inside lsp#ui#vim#output#preview it works fine.
