### ISSUE TITLE
RFE: emit some kind of message for "window/showMessage" notifications

### ISSUE THREAD

**Issue by jclulow** [prabirshrestha/vim-lsp#871]
Some LSPs will occasionally send a message that should be shown to the client using the [ShowMessage Notification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showMessage).  It'd be cool if `vim-lsp` were able to display those to the user somehow.

This is an extremely basic prototype (I do not know a great deal of Vimscript!) that does something at least vaguely useful when I drop it in my `.vimrc`:

```vimrc
function WindowShowMessage(id, data)
        if !has_key(a:data, 'response')
                return
        endif
        let l:response = a:data['response']

        if !has_key(l:response, 'method') || !has_key(l:response, 'params')
                return
        endif
        let l:method = l:response['method']
        let l:params = l:response['params']

        if l:method == "window/showMessage"
                let l:type = l:params['type']
                let l:msg = l:params['message']

                if l:type == 1
                        echohl ErrorMsg
                elseif l:type == 2
                        echohl WarningMsg
                elseif l:type == 3
                        echohl ModeMsg
                else
                        return
                endif
        else
                return
        endif

        echom "LSP: " . l:msg
        echohl NONE
endfunction

call lsp#register_notifications('window/showMessage', function('WindowShowMessage'))
```

**Comment by prabirshrestha** [comment]
Did you mean something down this line https://github.com/prabirshrestha/vim-lsp/pull/661?

**Comment by ckipp01** [comment]
I'd love to piggy back on this and say that having this would be really helpful for servers like [Metals, the Scala language server](https://scalameta.org/metals/docs/editors/new-editor.html#windowshowmessage) where we rely on this being there to show important status messages to the users such as the status of their build import, when indexing is complete, etc. We also have the ability to send these messages via logMessage, which I think is why #661 started to add the `window/logMessage` in that the `window/showMessageRequest` functionality. We actually allow for an `initializationOption` to fine tune how you get your messages, but without having neither supported by vim-lsp, it's quite difficult for Metals users to have any clue what's going on with server.

**Comment by prabirshrestha** [comment]
This is not possible in master via using the stream apis.

```vim
call lsp#callbag#pipe(
    \ lsp#stream(),
    \ lsp#callbag#filter({x->has_key(x, 'response') && has_key(x['response'], 'method') && x['response']['method'] ==# 'window/logMessage'}),
    \ lsp#callbag#forEach({x->lsp#utils#echo_with_truncation(x['response']['params']['message'])})
    \ )
```

**Comment by ckipp01** [comment]
Hi @prabirshrestha, I'm a bit confused with closing this issue. Could you explain a bit more about what you mean by:

> This is not possible in master via using the stream apis.

Thanks for the workaround, that's helpful, but I also feel like this is a valid feature request. Both [`window/logMessage`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_logMessage) and [`window/showMessage`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showMessage) are part of the base protocol. So I think there is a pretty realistic expectation from servers that at least one of these exists. This seems like a valid feature request.

**Comment by prabirshrestha** [comment]
It should had been this is possible in master.
