### ISSUE TITLE
[Omni] 'kind' should be a single letter

### ISSUE THREAD

**Issue by jsit** [prabirshrestha/vim-lsp#872]
`:h complete-items` says:

> **kind**            single letter indicating the type of completion

In vim-lsp's Omni completion, `kind` is often a full word, like "method" or "variable." This should be a single character.

**Comment by natebosch** [comment]
I'm curious - do you have a preference for the single letter, and if so can you expand on why?

I recently made a change in the opposite direction with `vim-lsc` - it used to use a single letter because of the docs you reference, and I changed it to full words because that seemed to be what users preferred.

**Comment by jsit** [comment]
My preference is only because the Vim docs dictate that it be a single letter. It will save room, too.

**Comment by yaegassy** [comment]
@jsit @natebosch 

vim-lsp has a `completion_item_kinds` setting.

You can use this to change it to a string of your choice. `:help lsp#register_server()`

```
	* completion_item_kinds
	    Type: |Dict|
	    Default: |{}|

	    This allows overriding the default text mappings for completion
	    item kinds (e.g., "module", "method") per server. Useful for
	    abbreviating or removing the kind text.

	    Example: >
		'config': { 'completion_item_kinds': {'26': 'type' } }
```

Unfortunately, I don't know what to change in this document alone...

You can check the `s:default_completion_item_kinds` in the source code itself. https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/omni.vim#L5-L31

For example, if you want to change `function` to `F` and `keyword` to `K`, you can do the following

**Example lsp#register_server: **

```

if executable('gopls')
  augroup LspGopls
    au!
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls']},
        \ 'allowlist': ['go'],
        \ 'config': {
        \   'completion_item_kinds': {
        \     '3': 'F',
        \     '14': 'k',
        \   },
        \ })
  augroup END
endif

```

**Misc:** 

As you can see by checking out `s:default_completion_item_kinds`, there are many different types, and it may not be desirable to set only one letter, including convenience.

**Comment by prabirshrestha** [comment]
I prefer word but you can override. No plans to fix for now.
