### ISSUE TITLE
Cannot read property 'ocamlmerlin' of undefined

### ISSUE THREAD

**Issue by benmp** [prabirshrestha/vim-lsp#88]
Hello,

First off, thank you for your work on this awesome plugin.  I am able to use the javascript server implementation with no issues.

However, my ocaml server is having issues that I would like to diagnose with you.

Setup:
WSL on Windows 10, running Ubuntu 17.04
Vim in Tmux

Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
let g:lsp_async_completion = 1
`
Fri 05 Jan 2018 08:45:01 AM STD:["lsp#register_server","server registered","ocaml-language-server"]
Fri 05 Jan 2018 08:45:01 AM STD:["s:on_text_document_did_open()",1,"","/Documents/z/dashboard_frontend",null]
Fri 05 Jan 2018 08:45:07 AM STD:["s:on_text_document_did_open()",1,"reason","/Documents/z/dashboard_frontend","file:///Documents/z/dashboard_frontend/src/app.re"]
Fri 05 Jan 2018 08:45:07 AM STD:[{"response":{"data":{"__data__":"vim-lsp","lsp_id":1,"server_name":"ocaml-language-server"},"message":"started lsp server successfully"}}]
Fri 05 Jan 2018 08:45:07 AM STD:["--->",1,"ocaml-language-server",{"method":"initialize","params":{"rootUri":"file:///Documents/z/dashboard_frontend","initializationOptions":{},"capabilities":{},"rootPath":"/Documents/z/dashboard_frontend","trace":"off"}}]
Fri 05 Jan 2018 08:45:07 AM STD:["<---",1,"ocaml-language-server",{"response":{"id":1,"jsonrpc":"2.0","error":{"code":-32603,"message":"Request initialize failed with message: Cannot read property 'ocamlmerlin' of undefined"}},"request":{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///Documents/z/dashboard_frontend","initializationOptions":{},"capabilities":{},"rootPath":"/Documents/z/dashboard_frontend","trace":"off"}}}]
Fri 05 Jan 2018 08:45:15 AM STD:["s:on_text_document_did_close()",1]
`

As you can see, it appears that the ocaml server is being found and booted up, however any request put through the server fails.  Above is a hover request.

Thanks!

**Comment by prabirshrestha** [comment]
Semma like you need to install Merlin. https://github.com/freebroccolo/ocaml-language-server#installation

**Comment by benmp** [comment]
which ocamlmerlin refmt ocamlmerlin-reason

`/home/ben/.npm-global/bin/ocamlmerlin
/home/ben/.npm-global/bin/refmt 
/home/ben/.npm-global/bin/ocamlmerlin-reason 
`

ocamlmerlin -version

`
The Merlin toolkit version 2.5.4, for Ocaml 4.02.3
`

**Comment by prabirshrestha** [comment]
This is most likely not a vim-lsp plug-in. Please ask help from the Lang server
