### ISSUE TITLE
Support custom commands to open QuickFix windows

### ISSUE THREAD

**Issue by 123subhadeep** [prabirshrestha/vim-lsp#883]
Currently, this plugin uses "copen" to open vim's quickfix window to show results (such as references, definitions when there are multiple matches).
But not everyone would like to see the result in vim's quickfix window. I personally use FZF to see quickfix result, as it's more sophisticated, supports filtering on the results as well as shows context in a preview section.

So it will be great if we can support custom command to open the quick fix window. This should be a pretty easy fix (I have already made that change locally, I can send a pull request if you want me to): expose a global variable (eg: g:lsp_quickfix_window_cmd) using which users can supply their custom quickfix command, if it's non-empty run that otherwise run the copen command.

**Comment by prabirshrestha** [comment]
Refer to my thoughts on:

https://github.com/prabirshrestha/vim-lsp/issues/69
https://github.com/prabirshrestha/vim-lsp/pull/211
https://github.com/prabirshrestha/vim-lsp/pull/195

Need to come up more generic api.

**Comment by rafi** [comment]
@prabirshrestha would it be possible to allow user to disable `botright [lc]open`?

**Comment by 123subhadeep** [comment]
@prabirshrestha  I went through your comments on those 3 bugs you mentioned, I have some feedbacks on two of your comments on https://github.com/prabirshrestha/vim-lsp/issues/69 : 

> Ya it would be good to have hooks into. But here is how I do with CtrlP now. Not the best but works. I run :LspReferences command first and then have a mapping to convert quickfix to CtrlP.

With that approach it just doubles the amount of work (need to wait for the quickfix list to come up and then press that additional key stroke). Which isn't great if you one uses LSP navigation often.



> Currently no plans to support it yet. I prefer vim-fz over fzf.vim so won't be able to maintain fzf support even if I built it. In order to make search experience seamless we need a way to notify that the search text has changed. You can read more on my vision at mattn/vim-fz#4

I think there's no single interface that everyone would like, so instead of focusing on developing a builtin fuzzy UI, I feel it would be better to focus on extensibility. That way users can use whatever interface they want, and you won't have to maintain them.
A couple of ideas I can think of are:

1. Supporting  commands that will be used to open the quickfix window (like what I originally mentioned in this bug)
2. Support autocmd callback functions that receives the result in the argument. Users can then use that to open the interface of their choice.

Seems like it shouldn't be a lot of work to add extensibility. But there doesn't seem to be a timeline for it, so I went ahead and edited your plugin locally to unblock myself. Thanks.

**Comment by prabirshrestha** [comment]
I recently added `lsp#stream()` api via https://github.com/prabirshrestha/vim-lsp/pull/884. This should now lay the foundation for extensibility and custom api. It internally uses [callbag.vim](https://github.com/prabirshrestha/callbag.vim) so you do need to understand the callbag spec.

`lsp#stream()` api returns a subject, which means you can either listen or push values to it.

Currently vim-lsp does this.

```vim
command! LspDocumentSymbol call lsp#ui#vim#document_symbol()
```

This could be changed to 

```vim
function! s:notify_command('LspDocumentSymbol') abort
  let l:Subject = lsp#stream()
  call l:Subject(1, { 'command': 'LspDocumentSymbol' })
endfunction

command! LspDocumentSymbol call s:notify_command('LspDocumentSymbol')
```

Then anyone can listen to `LspDocumentSymbol` event and intercept it. Might need to add a flag that says vim-lsp not to bother about this command by `let:lsp_custom_commands = ['LspDocumentSymbol']`.

```vim
function! s:on_LspDocumentSymbolCommand(x) abort
  " custom code when :LspDocumentSymbol is called
endfunction

au User lsp_setup call lsp#callbag#pipe(
    \ lsp#stream(),
    \ lsp#callbag#filter({x-> has_key(x, 'command') && x['command'] ==# 'LspDocumentSymbol' }),
    \ lsp#callbag#subscribe({ 'next':{x->s:on_LspDocumentSymbolCommand(x)} }),
    \ )
```

**Comment by 123subhadeep** [comment]
@prabirshrestha  Sorry about the delay, autocmd sounds good to me.

Do you plan to implement it soon ? 

Current implementation of showing references/definition is causing two problems:
1. Doesn't let me use FZF as it internally calls copen
2. Uses quickfix list, since there's only one quickfix list in vim, it often conflicts with other plugins. For example, I use an async plugin to run builds/test which writes to quickfix window, if I use vim-lsp in the meantime, the output is messed up.

Looking forward to hearing, and thanks for this plugin !

**Comment by prabirshrestha** [comment]
it will be stream api but not any time soon.

by the way you can create your custom command in the mean time. refer to these on how others are extending vim-lsp.

https://github.com/prabirshrestha/quickpick-lsp.vim
https://github.com/liuchengxu/vista.vim

**Comment by 123subhadeep** [comment]
Awesome, thanks for your prompt response, will look into them.

**Comment by jiz4oh** [comment]
Hi everyone, I have created a plugin [vim-lspfuzzy](https://github.com/jiz4oh/vim-lspfuzzy) that can show etc. documentsymbol and references in fzf window, any suggestion is appreciated and pr welcome

**Comment by prabirshrestha** [comment]
If you would like feel free to update readme/docs to link that can point to vim-lspfuzzy.

**Comment by jiz4oh** [comment]
yeah, I'd like to do that, but have no idea how to do it, where is the right place in readme/doc to update? I haven't seen any existing plugin refer link, could you give me any advice?
