### ISSUE TITLE
E685 Vim errors when removing code with errors

### ISSUE THREAD

**Issue by Pobega** [prabirshrestha/vim-lsp#888]
This is using the Rust Language Server.

Given the following incorrect code:
```rust
async fn http_reqwest(url: &str) {
    let body = reqwest::get("https://www.rust-lang.org")
        .await?
        .text()
        .await?;
     println!("body = {:?}", "test");
}
  
fn main() {
    http_reqwest("https://www.rust-lang.org");
}
```
I get expected errors
![Screenshot from 2020-08-21 16-03-13](https://user-images.githubusercontent.com/474525/90930108-fcf2f780-e3c7-11ea-9b2e-998aba51f9ef.png)
But when I try to delete any of the code that is highlighted red, I get a bunch of Vim errors
![Screenshot from 2020-08-21 16-04-53](https://user-images.githubusercontent.com/474525/90930170-13994e80-e3c8-11ea-9baa-a64a0eab2871.png)
(this output is from using visual mode to highlight all 4 lines and deleting them at once. Deleting any single line of this produces an error as well, except for the `.text()` line interestingly)

Here's an attached log where I open the file and delete the 4 lines: [vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/5111036/vim-lsp.log)

**Comment by prabirshrestha** [comment]
Can you try changing this to `silent! call prop_type_delete(l:prop_type)` instead?

https://github.com/prabirshrestha/vim-lsp/blob/a8dd16f59a1f56ee40d0d403a722b6d556fa04e9/autoload/lsp/ui/vim/diagnostics/textprop.vim#L94

**Comment by Pobega** [comment]
It looks like that fixes the issue on the other lines but trying to delete the first line with an error results in `E685: Internal error: text property below deleted line not found`.

Messing around with it a little more it seems the others lines are _fine_, the issue seems only related to deleting the first line (or the line below it, since it'll complain with the same message just saying `text property above delete line not found`)

**Comment by Pobega** [comment]
I'm confused, the issue isn't stale, it still exists

**Comment by prabirshrestha** [comment]
Seems like we need to check if range is valid before adding text props. More details here. https://github.com/prabirshrestha/vim-lsp/pull/721#issuecomment-753279052

Feel free to send PRs.
