### ISSUE TITLE
Vim crashes with SIGSEGV when using tagfunc=lsp#tagfunc

### ISSUE THREAD

**Issue by vogre** [prabirshrestha/vim-lsp#895]
Hello!

I've encountered infrequent and hard-to-reproduce crashes when using tagfunc and completing words with i_CTRL-N.

Vim version 8.1.2269
OS: Linux (Ubuntu 20.04)
Language Server: pyls

Removing tags from `complete` (`complete-=t`) got rid of the crashes.

Stack trace:
```
 __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
 vim_strsave ()
 dict_add_string_len ()
 find_tags ()
 ?? ()
```

This might be issue in core VIM instead and only triggered by vim-lsp

**Comment by prabirshrestha** [comment]
@vogre can you file an issue at https://github.com/vim/vim. vim should never crash.

**Comment by prabirshrestha** [comment]
Bug in vim.
