### ISSUE TITLE
Fix max-line-length formatting

### ISSUE THREAD

**Issue by kraxli** [prabirshrestha/vim-lsp#900]
Hi

is there a way to fix also `max-line-length` formatting errors? `LspDocumentFormat` does not do anything on the length of the line. My lsp-settings:

    let g:lsp_settings = {
    \   'filetype': {'python': 'pyls-all'},
    \   'pyls': {
    \     'workspace_config': {
    \         'pyls': {
    \             'configurationSources': ['pycodestyle'],
    \             'plugins': {
    \                 'pydocstyle': {'enabled': v:true},
    \                 'pycodestyle': {
    \                     'enabled': v:true,
    \                 },
    \                 'black': {'enable': v:true},
    \                 'autopep8': {'enable': v:true},
    \             },
    \         },
    \     },
    \   },
    \ }

setup.cfg in my project folder:
```
[pycodestyle]
count = False
ignore = E226,E302,E41
max-line-length = 120
statistics = True
```

My environment:

- OS: Linux Mint 20 Ulyana
- Vim: NVIM v0.4.4
- Python: 3.8.2
- Lsp: pyls-all

**Comment by prabirshrestha** [comment]
please paste logs for both vim-lsp and pyls. most likely a question for pyls.

**Comment by kraxli** [comment]
thanks for coming back and sorry for not providing it first hand:

- [vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/5161612/vim-lsp.log)
- pyls.log is emtpy (I have set it with `pyls --log-file ~/pyls.log`)
