### ISSUE TITLE
lsp with pyls breaks normal mode `go` command

### ISSUE THREAD

**Issue by idbrii** [prabirshrestha/vim-lsp#901]
Update: I've removed sideways from the equation! See updated min vimrc [comment below](https://github.com/prabirshrestha/vim-lsp/issues/901#issuecomment-728260888). 

----

vim-lsp with pyls prevents AndrewRadev/sideways.vim from visual selecting arguments to functions in python files. Instead of selecting the argument, the cursor moves to the start of the line and visual selects the first character. This problem does not occur when using vim-lsp with emmylua-ls to edit lua files. I don't understand the difference.

# Repro

Setup vim-lsp to use pyls and open broken.py containing this code:

```python
def commit():
    print("hi", "there")
```
Then try to select "hi" with sideway's SidewaysArgumentTextobjI:
`/hi<CR>vi,`

Calling `lsp#disable()` or `:LspStopServer` doesn't fix the behaviour, but disabling lsp or lsp-settings in vimrc does fix it.

# Minimal vimrc

I save the following as ~/.vim/reprovimrc.vim and run

`gvim -Nu ~/.vim/reprovimrc.vim -U NONE broken.py`

```vim
" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']

" Plugins to test here ------------------------------------------
let s:plugins += ['sideways']
let s:plugins += ['lsp']
" Use lsp-settings to get pyls setup.
let s:plugins += ['lsp-settings']
" /end ----------------------------------------------------------

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE

" Setups mappings we'll test with
omap a, <Plug>SidewaysArgumentTextobjA
xmap a, <Plug>SidewaysArgumentTextobjA
omap i, <Plug>SidewaysArgumentTextobjI
xmap i, <Plug>SidewaysArgumentTextobjI

" Alternatively, use these pyls settings from the wiki.
let g:pyls = $USERPROFILE . '\AppData\Local\vim-lsp-settings\servers\pyls\pyls.cmd'
if 0 && executable(g:pyls)
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->[g:pyls]},
        \ 'whitelist': ['python'],
        \ })
endif

```

# Versions
I updated my plugins to see if latest versions fix it, but no luck:

prabirshrestha/vim-lsp@ a8dd16f59a1f56ee40d0d403a722b6d556fa04e9
mattn/vim-lsp-settings@c6552ddaf099fb7c2e66d3b487261f3a6fc0bda2
AndrewRadev/sideways.vim@403accb75e7659dfa9caa9a43e43db9840ea140a
tpope/vim-sensible@7aa7dba2a2594c209d8063c4c1c56de130c362d3

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 27 2020 22:26:20)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1076

**Comment by idbrii** [comment]
I'd love to dig more into how to fix this, but I'm not sure where to start looking.

**Comment by idbrii** [comment]
I tried turning off a lot of options in that minimal vimrc, but no dice:

```vim
let g:lsp_diagnostics_echo_cursor = 0
let g:lsp_diagnostics_enabled = 0
let g:lsp_diagnostics_float_cursor = 0
let g:lsp_documentation_float = 0
let g:lsp_highlight_references_enabled = 0
let g:lsp_highlights_enabled = 0
let g:lsp_insert_text_enabled = 0
let g:lsp_preview_autoclose = 0
let g:lsp_preview_doubletap = 0
let g:lsp_preview_float = 0
let g:lsp_preview_keep_focus = 0
let g:lsp_show_workspace_edits = 0
let g:lsp_signature_help_enabled = 0
let g:lsp_signs_enabled = 0
let g:lsp_signs_priority = 0
let g:lsp_text_edit_enabled = 0
let g:lsp_textprop_enabled = 0
let g:lsp_use_event_queue = 0
let g:lsp_virtual_text_enabled = 0
```

Both with default settings and with above disabled, still occurs on 594751093da71a662c0ef371ee60c05c1c96b63b AndrewRadev/sideways.vim@19c5a21206b6c9f999004256a10e7381450ea83f.

**Comment by idbrii** [comment]
I can reproduce without sideways: Using `go` to jump to a byte is broken. Here's a further reduced min vimrc:

```vim
" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']

" Plugins to test here ------------------------------------------
let s:plugins += ['lsp']
let s:plugins += ['lsp-settings']
" /end ----------------------------------------------------------

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE

" This command should select "hi", but it only jumps to the correct line when
" lsp is enabled.
nnoremap \\ :<C-u>normal! 25gov28go<CR>
```

Using
`vim -Nu ~/.vim/reprovimrc.vim -U NONE broken.py` on the original broken.py example:

```python
def commit():
    print("hi", "there")
```

And then `\\` selects "hi" when lsp is disabled but only the first character of the line when lsp is enabled.

**Comment by subnut** [comment]
Just FYI, I can't reproduce in neovim v0.4.4
I don't have vim installed.

### Demo

![gifcast_210105111824](https://user-images.githubusercontent.com/56714626/103611280-f2d13000-4f47-11eb-8c04-4712f1aa147a.gif)

**Comment by idbrii** [comment]
@subnut What does `:LspStatus` output for that reduced case?

**Comment by subnut** [comment]
![gifcast_210109024626](https://user-images.githubusercontent.com/56714626/104064997-fbb25200-5224-11eb-9cf1-769b3f1735a4.gif)

**Comment by idbrii** [comment]
Testing my reprovimrc and reduced case with eb237a2cedf2c69a44543d2ffaee25470c53e29b, the issue is resolved!
