### ISSUE TITLE
g:lsp_highlight_references_delay appears to have no effect

### ISSUE THREAD

**Issue by idbrii** [prabirshrestha/vim-lsp#902]
I tried using both of these values and they seem to cause the same delay:
```
let g:lsp_highlight_references_delay = 50
let g:lsp_highlight_references_delay = 50000
```

# Repro

Open a file that has lsp support setup (I used a python file with pyls) and put the cursor on a symbol, wait for 2 seconds, highlight changes. Change delay:

`:let g:lsp_highlight_references_delay = 50`

Repeat. Change delay:

`:let g:lsp_highlight_references_delay = 50000`

Repeat.

Regardless of delay setting, it takes about 2 seconds.

Edit `~\.vim\bundle\lsp\autoload\lsp\internal\highlight_references.vim` and echo the `lsp#callbag#debounceTime(g:lsp_highlight_references_delay)` line to verify that you've correctly spelled the variable. (echo'd output should contain 'duration' with your delay value.)

I tried to debug further, but I was totally lost at what s:Dispose and callbag were doing.

`let g:lsp_highlight_references_enabled = 0` successfully disables the highlighting.

# Minimal vimrc

```vim
" Invoke with:
" vim -Nu ~/.vim/reprovimrc.vim -U NONE

" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']

" Plugins to test here ------------------------------------------
let s:plugins += ['lsp']
let s:plugins += ['lsp-settings']
" /end ----------------------------------------------------------

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE


let g:lsp_highlight_references_delay = 50000
```

# Versions

prabirshrestha/vim-lsp@ a8dd16f59a1f56ee40d0d403a722b6d556fa04e9
mattn/vim-lsp-settings@c6552ddaf099fb7c2e66d3b487261f3a6fc0bda2
tpope/vim-sensible@7aa7dba2a2594c209d8063c4c1c56de130c362d3

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 27 2020 22:26:20)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1076

**Comment by prabirshrestha** [comment]
You need to set it in vimrc. Once vim-lsp runs we don’t watch for the changes in value.

Did setting in vimrc not work?

**Comment by idbrii** [comment]
Ah. Yeah, changing the value in vimrc and restarting each time does make different delays work.

Thanks!
