### ISSUE TITLE
Not loading retriggerCharacters for signature_help prevents signature help when filling in function call parameters.

### ISSUE THREAD

**Issue by ElPiloto** [prabirshrestha/vim-lsp#903]
The LSP (v3.15) specification dictates both `triggerCharacters` and `retriggerCharacters` in SignatureHelpOptions to trigger [Signature Help](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp). 

**vim-lsp only looks at `triggerCharacters`.** This prevents vim-lsp from triggering when there is a character in `retriggerCharacters` that is not in `triggerCharacters`. 

The issue manifests itself when certain LSPs set `triggerCharacters` to `( )` and `retriggerCharacters` to `(,)`.  By ignoring `retriggerCharacters`, vim-lsp does not trigger signature help while filling in a function call (which should be triggered by the `,` character).

I have implemented a quick (but potentially controversial) fix for this issue locally, which I am happy to submit a pull request for if desired.  The idea is to change `lsp#capabilities#get_signature_help_trigger_characters` [here](https://github.com/prabirshrestha/vim-lsp/blob/18f2e922f7ba75448c18ec7dc98e4574481e364f/autoload/lsp/capabilities.vim#L164) to also check if the server returned a list of `retriggerCharacters`.  If it exists, return the concatenation of `triggerCharacters` and `retriggerCharacters`.

This is just a superficial way of dealing with `retriggerCharacters`  Ideally, there would be logic in vim-lsp that tracks whether this is a trigger or a retrigger and uses the appropriate char lists based on that state.  That would be preferable to the above fix which has the downside that it always sends a call to signature help when it encountered a `,`  (even outside of a function call).

**Comment by prabirshrestha** [comment]
if we pass this as false server should handle it.

```
	/**
	 * The client supports to send additional context information for a
	 * `textDocument/signatureHelp` request. A client that opts into
	 * contextSupport will also support the `retriggerCharacters` on
	 * `SignatureHelpOptions`.
	 *
	 * @since 3.15.0
	 */
	contextSupport?: boolean;
```

Feel free to send a PR and mention draft.

**Comment by ElPiloto** [comment]
Okay, PR sent. I'm not sure what you mean by "server should handle it."  My PR is working fine (presumably because vim-lsp doesn't set `contextSupport=True` (doesn't send it at all which must default to False?)). I was just worried that treating retriggerChars like triggerChars would result in too many unnecessary calls to the server (even though the server handles those calls gracefully).  But honestly, I have no sense if too many calls would even have a noticeable impact on performance or is a serious concern at all.

**Comment by prabirshrestha** [comment]
Merged. What you have should be good for now.
