### ISSUE TITLE
Compatibility issue with  easymotion / vim-easymotion

### ISSUE THREAD

**Issue by jbaek7023** [prabirshrestha/vim-lsp#915]
While I'm using `easymotion/vim-easymotion`, the linter gets confused... :( 

Is there any way to fix it? 
![Screen Shot 2020-10-09 at 11 57 35 PM](https://user-images.githubusercontent.com/23069682/95648426-ce220500-0a8b-11eb-84f5-ea247d8dd999.png)

**Comment by jbaek7023** [comment]
The error goes away after the motion but it kindda hurts my eyes :(

**Comment by prabirshrestha** [comment]
I use easy motion and it never happens to me.

![image](https://user-images.githubusercontent.com/287744/96373686-fd3b1500-1122-11eb-8836-8e45bea66652.png)
![image](https://user-images.githubusercontent.com/287744/96373754-691d7d80-1123-11eb-91a3-4a23ea692e96.png)

Few things to try:
1. Make sure you have the latest version of vim or neovim.
2. Try with minimal repo that is just easy motion and vim-lsp.

**Comment by prabirshrestha** [comment]
easymotion now has autocmd commands u can listen to. There is also `EasyMotion#is_active()` function if you want to check that.

```vim
autocmd User EasyMotionPromptBegin call lsp#disable()<CR>
autocmd User EasyMotionPromptEnd call lsp#enable()<CR>
```

Ideally I should have `lsp#enable_for_buffer(bufnr)` and `lsp#disable_for_buffer(bufnr)`. I will track this as part of [Revamp Diagnostics](https://github.com/prabirshrestha/vim-lsp/discussions/977)

**Comment by prabirshrestha** [comment]
This is now fixed. You can temporarily enable/disable diagnostics per buffer and the ui will automatically reflect the new state. Refer to https://github.com/prabirshrestha/vim-lsp/pull/1005 for docs.
