### ISSUE TITLE
Option to add delay to diagnostic highlights/virtual text

### ISSUE THREAD

**Issue by reedts** [prabirshrestha/vim-lsp#923]
Currently while in insert mode and writing, `vim-lsp` (e.g. with `clangd`) will instantly mark the current line as an error because one is not finished writing.

Adding a delay in milliseconds or for example only check for errors when leaving the insert mode etc, would IMO improve usability.

**Comment by E1k3** [comment]
I agree that constant highlights and virtual text are quite distracting when I am writing a line that I know *will be* valid, when I finish.

I would prefer a `g:lsp_diagnostics_highlight_delay` and `g:lsp_diagnostics_virtual_text_delay` as it is consistent with the `g:lsp_diagnostics_echo_delay` and `g:lsp_diagnostics_float_delay` options that already exist.

If such a feature is possible, I would welcome the addition.

**Comment by prabirshrestha** [comment]
[Signs](https://github.com/prabirshrestha/vim-lsp/pull/994) and [Virtual Text](https://github.com/prabirshrestha/vim-lsp/pull/994) can now be delayed or disabled in insert mode. Will work on highlights later.

**Comment by prabirshrestha** [comment]
[Highlights](https://github.com/prabirshrestha/vim-lsp/pull/995) can now be delayed or disabled in insert mode for both vim and neovim.

Thanks everyone for your feedback.
