### ISSUE TITLE
Unknown function: lsp#ui#vim#type_hierarchy from <plug>(lsp-type-hierarchy)

### ISSUE THREAD

**Issue by flwyd** [prabirshrestha/vim-lsp#933]
It looks like the function that `<plug>(lsp-type-hierarchy)` is mapped to does not exist.  Running a mapping to this plug, I get the error
`E117: Unknown function: lsp#ui#vim#type_hierarchy`
Perhaps it should be `lsp#internal#type_hierarchy#show()` instead?

Also, there's a typo in the error message for `:LspTypeHierarchy`: "Retrieing type hierarchy not supported for $language" should be "Retrieving" (missing 'v').

**Comment by prabirshrestha** [comment]
yes. feel free to send a PR.
