### ISSUE TITLE
Preview floating window not getting focus

### ISSUE THREAD

**Issue by vkrajacic89** [prabirshrestha/vim-lsp#935]
This is my config:
```
set completeopt-=preview
let g:lsp_preview_keep_focus = 0
let g:lsp_preview_autoclose = 0
```
If I use Hover or Peek command on symbol, floating window is closed the moment I move cursor. Maybe I misread the docs, but floating window should get focus and I should be able to move inside it and exit with ESC key.
I tried without my other plugins and my custom vimrc, I still get the same behaviour. 
I'm using latest stable build on Windows 10 (32-bit 8.2)

**Comment by prabirshrestha** [comment]
Focus only works on neovim.

Please comment in vim mailing list instead so it can be prioritized there.

https://groups.google.com/g/vim_dev/c/42DjcXhuVAE/m/JoRi8sirCwAJ
https://github.com/vim/vim/issues/5639

Feel free to send a PR to update docs to mention the limitations.
