### ISSUE TITLE
Question: How to suppress error messages?

### ISSUE THREAD

**Issue by MrChenWithCapsule** [prabirshrestha/vim-lsp#942]
I want to use autocmd to display hover information automatically. However, every time I move the cursor to a symbol which doesn't have that available, vim-lsp will complain, and this is quite annoying.

Is there a way I can suppress error messages? I looked through the docs but didn't find anything useful.

**Comment by hrsh7th** [comment]
vim-lsp doesn't provide this feature and it's an advanced usage, so I think you'll have to do it yourself.

Fortunately, `autoload/lsp/ui/hover.vim` is very simple.

Here is the example.
```viml
autocmd CursorMoved * call <SID>auto_hover()

let s:auto_hover_timer_id = 0
function! s:auto_hover()
  call timer_stop(s:auto_hover_timer_id)
  let s:auto_hover_timer_id = timer_start(500, { -> s:do_auto_hover() })
endfunction

function! s:do_auto_hover()
  let l:servers = filter(lsp#get_allowed_servers(), 'lsp#capabilities#has_hover_provider(v:val)')
  for l:server in l:servers
    call lsp#send_request(l:server, {
    \   'method': 'textDocument/hover',
    \   'params': {
    \     'textDocument': lsp#get_text_document_identifier(),
    \     'position': lsp#get_position(),
    \   },
    \   'on_notification': function('s:handle_auto_hover', [l:server]),
    \ })
  endfor
endfunction

function! s:handle_auto_hover(server, data)
  if lsp#client#is_error(a:data['response'])
    call lsp#utils#error('Failed to retrieve hover information for ' . a:server)
    return
  endif

  if has_key(a:data['response'], 'result') && !empty(a:data['response']['result']) && !empty(a:data['response']['result']['contents'])
    call lsp#ui#vim#output#preview(a:server, a:data['response']['result']['contents'], {'statusline': ' LSP Hover'})
  endif
endfunction
```

**Comment by MrChenWithCapsule** [comment]
> vim-lsp doesn't provide this feature and it's an advanced usage, so I think you'll have to do it yourself.
> 
> Fortunately, `autoload/lsp/ui/hover.vim` is very simple.
> 
> Here is the example.
> 
> ```viml
> autocmd CursorMoved * call <SID>auto_hover()
> 
> let s:auto_hover_timer_id = 0
> function! s:auto_hover()
>   call timer_stop(s:auto_hover_timer_id)
>   let s:auto_hover_timer_id = timer_start(500, { -> s:do_auto_hover() })
> endfunction
> 
> function! s:do_auto_hover()
>   let l:servers = filter(lsp#get_allowed_servers(), 'lsp#capabilities#has_hover_provider(v:val)')
>   for l:server in l:servers
>     call lsp#send_request(l:server, {
>     \   'method': 'textDocument/hover',
>     \   'params': {
>     \     'textDocument': lsp#get_text_document_identifier(),
>     \     'position': lsp#get_position(),
>     \   },
>     \   'on_notification': function('s:handle_auto_hover', [l:server]),
>     \ })
>   endfor
> endfunction
> 
> function! s:handle_auto_hover(server, data)
>   if has_key(a:data['response'], 'result') && !empty(a:data['response']['result']) && !empty(a:data['response']['result']['contents'])
>     call lsp#ui#vim#output#preview(a:server, a:data['response']['result']['contents'], {'statusline': ' LSP Hover'})
>   endif
> endfunction
> ```

This works for me. Thanks.
