### ISSUE TITLE
Strange behavior with clangd and omnifunc

### ISSUE THREAD

**Issue by mind-rot** [prabirshrestha/vim-lsp#945]
Having strange behavior with clangd autocompletion.
When writing `myVariableToC|` then hit \<C-x\>\<C-o\> i've got `myVariableToC myVariableToComplete` instead of `myVariableToComplete`.
 
This behavior is not reproducible with golang lsp. But i'm not sure if this is specific to clangd

**Comment by hrsh7th** [comment]
@mind-rot Sorry for annoying.
I think this issue is fixed now on latest master.
Could you test it?
If this problem is gone, feel free to close issue.
