### ISSUE TITLE
javascript function signatures

### ISSUE THREAD

**Issue by bryansammon** [prabirshrestha/vim-lsp#95]
Is it possible to display function signatures for built in javascript (typescript) functions? Maybe after selecting, and typeing the '(' and show while inside of '( <> )'

**Comment by lowski** [comment]
I'm using `vim-lsp` with `asyncomplete.vim` and have preview window enabled (`set completeopt+=preview`) but function signatures for TypeScript are not displayed in the preview window - they are displayed only when I call `:LspHover`.

@prabirshrestha Is there any extra step required to open preview window to see function signature?

**Comment by tmerse** [comment]
Would be awesome if it could work like [this](https://raw.githubusercontent.com/runoshun/readme-images/master/tscompletejob/signature_help.gif)

source: https://github.com/runoshun/tscompletejob

**Comment by prabirshrestha** [comment]
This has been implemented. https://github.com/prabirshrestha/vim-lsp/pull/479
