### ISSUE TITLE
unknown function: nvim_buf_set_lines on lsp#ui#vim#output#setcontent

### ISSUE THREAD

**Issue by dkjii-g** [prabirshrestha/vim-lsp#952]
On omnifunc, when selecting entries (ctrl+o x, ctrl+n to select entries), I get the error:

"Error detected while processing function <lambda>49[1]..<SNR>69_show_documentation[113]..lsp#ui#vim#output#setcontent:
line    9: E117: Unknown function: nvim_buf_set_lines"

I am using vim-8.2

minimal vimrc (with https://github.com/mattn/vim-lsp-settings) and vim-plug:

```
set nocompatible

call plug#begin("~/.vim/plugged")
	Plug 'prabirshrestha/vim-lsp'
	let g:lsp_preview_float = 0
	set omnifunc=lsp#complete
	Plug 'mattn/vim-lsp-settings'
call plug#end()
```

I checked the code and the error seems to be that the function assumes you are using nvim if lsp_preview_float is off, the expected behaviour would be to have the fn signature in the preview window

Thanks for the plugin & the help!

**Comment by prabirshrestha** [comment]
nvim_buf_set_lines only runs on neovim. Are you sure you are on the right version of vim and have latest vim-lsp?

**Comment by dkjii-g** [comment]
I am using vim-8.2 and vim-lsp 9dce8c50ed845b1f68d03875007c0a8a47b5490a

I'm not too familiar with this plugin but this snippet is basically what is going on in output.vim:
```
let s:use_vim_popup = has('patch-8.1.1517') && g:lsp_preview_float && !has('nvim')

function! lsp#ui#vim#output#setcontent(winid, lines, ft) abort
    if s:use_vim_popup
        " vim popup
        call setbufline(winbufnr(a:winid), 1, a:lines)
        call setbufvar(winbufnr(a:winid), '&filetype', a:ft . '.lsp-hover')

    else
        " nvim floating or preview

        call nvim_buf_set_lines(winbufnr(a:winid), 0, -1, v:false, a:lines)
        call nvim_buf_set_option(winbufnr(a:winid), 'readonly', v:true)
        call nvim_buf_set_option(winbufnr(a:winid), 'modifiable', v:false)
        call nvim_buf_set_option(winbufnr(a:winid), 'filetype', a:ft.'.lsp-hover')
        call nvim_win_set_cursor(a:winid, [1, 0])
    endif
endfunction
```

here s:use_vim_popup will always be false if g:lsp_preview_float is off, so the code will always branch off to neovim commands

**Comment by dkjii-g** [comment]
Seems to be a regression from 45babeb9474e007935f279fcdb3fa95bcf63673e, but I tried on the commit previous to that one (594751093da71a662c0ef371ee60c05c1c96b63b) and it still didn't work, this time with a different error:
```
Error detected while processing function <lambda>37[1]..<SNR>125_show_documentation[43]..lsp#ui#vim#output#setcontent:
line    7:
E21: Cannot make changes, 'modifiable' is off
```

**Comment by prabirshrestha** [comment]
we need to guard it to with `else s:use_nvim_float`. 

this condition is most likely evaluating to false hence executing the neovim codepath.

```
let s:use_vim_popup = has('patch-8.1.1517') && g:lsp_preview_float && !has('nvim')
```

**Comment by dkjii-g** [comment]
When I add elseif s:use_nvim_float, the error goes away but I see no documentation on omnicomplete (just an empty popup window with "(no documentation available)". I think the documentation.vim is lacking preview window support

**Comment by prabirshrestha** [comment]
@dkjii-g can you try this PR. https://github.com/prabirshrestha/vim-lsp/pull/955. It will temporarily disable the doc.

**Comment by fedorenchik** [comment]
I also have the same issue. vim 8.2.2022.

**Comment by prabirshrestha** [comment]
@ fedorenchik did you try the above PR?

**Comment by fedorenchik** [comment]
@prabirshrestha Yes. Also happens with #955 merged.

**Comment by fedorenchik** [comment]
My vim-lsp config is:
```
let g:lsp_preview_keep_focus = 1
let g:lsp_preview_float = 0
let g:lsp_preview_autoclose = 0
let g:lsp_documentation_float_docked = 0
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_float_cursor = 0
let g:lsp_signs_enabled = 1
let g:lsp_signs_priority = 10
let g:lsp_highlights_enabled = 1
let g:lsp_textprop_enabled = 1
let g:lsp_peek_alignment = "top"
let g:lsp_show_workspace_edits = 1
let g:lsp_fold_enabled = 1
let g:lsp_hover_conceal = 1
let g:lsp_ignorecase = 1
let g:lsp_log_file = ''
let g:lsp_semantic_enabled = 0
let g:lsp_async_completion = 1
```

**Comment by prabirshrestha** [comment]
Seems like I wasn't setting up the right config.

This should now be fixed by https://github.com/prabirshrestha/vim-lsp/pull/986 which is in master. Please let me know if you still have issues with it.

**Comment by fedorenchik** [comment]
Yes. Fixed. Thank you.
