### ISSUE TITLE
How to enable auto-import for pyright-language-server?

### ISSUE THREAD

**Issue by tamuhey** [prabirshrestha/vim-lsp#954]
Pyright shows `Auto-import` option in completion menu, but merely selecting this doesn't import anything:

![image](https://user-images.githubusercontent.com/24998666/102770261-2d26c300-43c7-11eb-8976-de62b37d8c52.png)

**Comment by tamuhey** [comment]
I misunderstood something. It works

**Comment by roblevy** [comment]
How did you get it to work?

**Comment by khadegd** [comment]
```vimscript
if executable('pyright-langserver')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyright-langserver',
        \ 'cmd': {server_info->[&shell, &shellcmdflag, 'pyright-langserver --stdio']},
        \ 'allowlist': ['python'],
        \ 'workspace_config': {
        \   'python': {
        \     'analysis': {
        \       'useLibraryCodeForTypes': v:true
        \      },
        \   },
        \ }
        \ })
endif
```

**Comment by prabirshrestha** [comment]
You might want to try vim-lsp-settings since it makes install lang servers easy as well as most of the appropriate configurations set. https://github.com/mattn/vim-lsp-settings/blob/master/settings/pyright-langserver.vim
