### ISSUE TITLE
Rename not working properly

### ISSUE THREAD

**Issue by AgentCosmic** [prabirshrestha/vim-lsp#96]
I'm not sure if this belongs here or the language server. I'm using vim8 with the javascript. I followed the examples and most things work fine except for the rename. When I perform a rename, the word seems to get mixed with the previous word.

**Comment by siegelaaron94** [comment]
Yes, this belongs here it has to do with this TODO. https://github.com/prabirshrestha/vim-lsp/blob/10d45996ff3eefbdc45b82ccedf1f006da7e1c94/autoload/lsp/ui/vim.vim#L370 I have started working on this but I am still a vimscript noob so it might take some time.

**Comment by prabirshrestha** [comment]
vim-lsp now supports `documentChanges` in master.

**Comment by doriath** [comment]
It will probably get fixed with #162, which adds proper sorting to text edits.

**Comment by prabirshrestha** [comment]
There has been a bunch of changes to applying edits. Please try again.
